### ISSUE TITLE
How can i make the discord emojis work

### ISSUE THREAD

**Issue by Tuncion** [javascript-obfuscator/javascript-obfuscator#1000]
I tried to obfuscate my discord Bot. Almost everything works perfectly except one thing and that is I save the emojis in a variable to use them in a message (string). unfortunately this does not work and in the message is then only the emoji id and not the emoji as wanted. Code is below :)

`
        const emoji = client.emojis.cache.get("XXX")
  
        const embed_menu = new Discord.MessageEmbed()
        .setDescription(`
        This is the Test Emoji ${emoji}
        `)

        message.reply({embed: embed_menu})

`

**Comment by relative** [comment]
`<:emoji_name:id>`

**Comment by 3kh0** [comment]
Why even tho?
