### ISSUE TITLE
Nosources Source Maps option

### ISSUE THREAD

**Issue by lamuertepeluda** [javascript-obfuscator/javascript-obfuscator#1002]
I'd like to obtain full error stack traces with meaningful code lines for bug reporting from obfuscated production code without having to put the source maps on a separate server not accessible by the users.

I'd like something similar to what [webpack devTools `nosources-source-map`](https://webpack.js.org/configuration/devtool/#production) option does.

> nosources-source-map - A SourceMap is created without the sourcesContent in it. It can be used to map stack traces on the client without exposing all of the source code. You can deploy the Source Map file to the webserver.
> 
> Warning
> It still exposes filenames and structure for decompiling, but it doesn't expose the original code.

Would it even be feasible with this library also for server-side (node) applications?

**Comment by sanex3339** [comment]
Closed as resolved
