### ISSUE TITLE
Transformation is applied even if all options are set to false

### ISSUE THREAD

**Issue by psabharwal123** [javascript-obfuscator/javascript-obfuscator#101]
with following options with 0.11.1 -

	compact: false,
	controlFlowFlattening: false,
	deadCodeInjection: false,
	debugProtection: false,
	debugProtectionInterval: false,
	disableConsoleOutput: false,
	log: false,
	mangle: false,
	renameGlobals: false,
	rotateStringArray: false,
	selfDefending: false,
	stringArray: false,
	unicodeEscapeSequence: false

my game is still changed and gets stuck at asset loading. Game is made using cocos creator 1.6.1

**Comment by sanex3339** [comment]
```
Transformation is applied even if all options are set to false
```

This is correct behaviour. Many base transformations always will applied.

**Comment by psabharwal123** [comment]
ok what are the base transformations? i am trying to figure out what is causing issue in the game

**Comment by sanex3339** [comment]
This transformers:
https://github.com/javascript-obfuscator/javascript-obfuscator/tree/master/src/node-transformers/obfuscating-transformers

and this:
https://github.com/javascript-obfuscator/javascript-obfuscator/tree/master/src/node-transformers/converting-transformers

**Comment by sanex3339** [comment]
What error you got?

**Comment by psabharwal123** [comment]
thats the issue, there is no error in console, however game gets stuck while loading game scene. Seems to be due to some base transform.

**Comment by sanex3339** [comment]
This is very strange. Debug it.

**Comment by psabharwal123** [comment]
sure, will keep you updated

**Comment by psabharwal123** [comment]
now we do see an error

project.dev.js:2620 TypeError: this._super is not a function
    at CCClass.initialize (project.dev.js:1062)
    at CCClass._initTriggers (project.dev.js:8811)
    at CCClass.initialize (project.dev.js:8806)
    at CCClass.initializeEpisode (project.dev.js:8872)
    at CCClass.<anonymous> (project.dev.js:2616)
    at _0x3371e1 (project.dev.js:11098)
    at project.dev.js:11178
    at _0x31350f (project.dev.js:11269)
    at _0x3b72da (project.dev.js:11303)

**Comment by sanex3339** [comment]
Can you reproduce this error with more smaller amount of code? Or upload your unobfuscated and obfuscated code and i'll try to inspect code.

**Comment by psabharwal123** [comment]
sure i ll try to narrow down the code which causes this

**Comment by sanex3339** [comment]
Ping

**Comment by psabharwal123** [comment]
sorry but i dint get time to do that, this will most likely happen in a few months.

**Comment by sanex3339** [comment]
Ok, i close this issue, please make another one when you will ready.
