### ISSUE TITLE
class-validator vulnerability, is this a problem?

### ISSUE THREAD

**Issue by namleasia** [javascript-obfuscator/javascript-obfuscator#1019]
I use javascript-obfuscator pakage, and run **npm audit** to check.
The result:
```
Moderate        SQL Injection and Cross-site Scripting in class-validator
  Package         class-validator                                 

  Patched in      No patch available                              

  Dependency of   javascript-obfuscator [dev]                     

  Path            javascript-obfuscator > class-validator         

  More info       https://github.com/advisories/GHSA-fj58-h2fr-3pp2
                                                                  
.. found 1 moderate severity vulnerability.
```

Is this a problem? How to fix it?

**Comment by zaytsev-mxm** [comment]
Hello, all! I am not sure who can I ask directly — but maybe @sanex3339
I see that the vulnerable package "class-validator" got a patch in a version of "13.0.2" — I also see that the current version of "javascript-obfuscator" requires for "class-validator@13.0.1" — so the difference is only 1 patch-version.
What do you see — would it be worth it to update the list of dependencies of "javascript-obfuscator"?

**Comment by leopucci** [comment]
![image](https://user-images.githubusercontent.com/38509299/146684078-2327c6ec-cab5-496b-863b-f24b8bb09460.png)

**Comment by leopucci** [comment]
Hey @zaytsev-mxm @sanex3339 @namleasia, I am also having this warning. 
As there is a fix on the library already I think that would be good for everybody to update this.

**Comment by leopucci** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/1032

**Comment by sanex3339** [comment]
Released
