### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by ImKill6r** [javascript-obfuscator/javascript-obfuscator#1020]
Hello this I obfusque a code for a client and I obfusca for something then I forgot to save the src https://pastebin.com/JDysh3Fn

**Comment by ImKill6r** [comment]
I need yes or yes to recover that code I can even pay if you can call me at md

**Comment by slig** [comment]
There's no way to recover the original code.

**Comment by ImKill6r** [comment]
FUCK +3K THE CODE

**Comment by ImKill6r** [comment]
UFFF....

**Comment by ImKill6r** [comment]
Okey.

**Comment by ImKill6r** [comment]
I'm going to shoot myself I swear

**Comment by sanex3339** [comment]
Closed. Sadly you can't revert obfuscated code
