### ISSUE TITLE
你好，我该如何解密呢

### ISSUE THREAD

**Issue by swarm413** [javascript-obfuscator/javascript-obfuscator#1030]
是这样子的
我的javascript在https://obfuscator.io上面进行了加密和混淆
问题是，我把源码搞丢了
现在想要修改这些js代码都做不到
请问我该怎么办
我应该把这些js文件上传到哪里进行解密呢

**Comment by swarm413** [comment]
似乎你们是十六进制混淆的......

**Comment by da411d** [comment]
You cannot decode obfuscated code to original

**Comment by swarm413** [comment]
天哪，那我该怎么办呢

**Comment by AngelShadow2017** [comment]
> 天哪，那我该怎么办呢

看起来不太好，但是你可以试试https://jsdec.js.org/

**Comment by AngelShadow2017** [comment]
> 天哪，那我该怎么办呢

或者你有耐心的话用chrome自带格式化来试试自主复原（前提是你得记得大概写了啥）

**Comment by sanex3339** [comment]
Closed. Please use English

**Comment by swarm413** [comment]
> > 天哪，那我该怎么办呢
> 
> 或者你有耐心的话用chrome自带格式化来试试自主复原（前提是你得记得大概写了啥）

谢了伙计，那个网站我试了，但是并没有效果，chrome确实自带美化输出功能，但是js代码太多了，算了能跑就行

**Comment by AngelShadow2017** [comment]
> > > 天哪，那我该怎么办呢
> > 
> > 
> > 或者你有耐心的话用chrome自带格式化来试试自主复原（前提是你得记得大概写了啥）
> 
> 谢了伙计，那个网站我试了，但是并没有效果，chrome确实自带美化输出功能，但是js代码太多了，算了能跑就行

所以说，在github上做个备份挺重要的。

**Comment by swarm413** [comment]
> > > > 天哪，那我该怎么办呢
> > > 
> > > 
> > > 或者你有耐心的话用chrome自带格式化来试试自主复原（前提是你得记得大概写了啥）
> > 
> > 
> > 谢了伙计，那个网站我试了，但是并没有效果，chrome确实自带美化输出功能，但是js代码太多了，算了能跑就行
> 
> 所以说，在github上做个备份挺重要的。

留下了没有版本控制的眼泪
