### ISSUE TITLE
Please add a interval setting option of Debug Protection Interval

### ISSUE THREAD

**Issue by partyspy** [javascript-obfuscator/javascript-obfuscator#1031]
It appears the default debug protection interval of this is 4000ms. As long as someone acts quick (add breakpoints in source code with 4 seconds), one can overpass the debug protection afterwards.

And it wouldn't be a great idea to change the js code manually after the obfuscation I suppose.

**Comment by sanex3339** [comment]
Released as `4.0.0`
Check updated description of `debugProtectionInterval` option
