### ISSUE TITLE
Webpack + obfuscator inserts `require()`, which doesn't work in browser

### ISSUE THREAD

**Issue by codemacabre** [javascript-obfuscator/javascript-obfuscator#1038]
## Expected Behavior
I've recently upgraded `"javascript-obfuscator": "~3.0.0"` and `"webpack-obfuscator": "^3.5.0"` and I'm having essentially the same issue as #382 - it appears to be inserting a `require()` statement unnecessarily. I'm using the following options:

```
identifierNamesGenerator: 'mangled',
identifiersPrefix: 'test_',
stringArrayEncoding: ['rc4'],
transformObjectKeys: true,
```

I'm relying on the following defaults, but I've also tried adding explicitly the following:

```
compact: true,
ignoreRequireImports: false,
target: 'browser',
```

## Current Behavior
The obfuscated code contains numerous require() statements, sometimes from existing node_modules packages, such as:
```
require('core-js/modules/es.regexp.exec.js'),require('core-js/modules/es.string.split.js'),require('core-js/modules/es.array.concat.js')
```
 Sometimes generated from my own code, as in the example in the example below.

## Steps to Reproduce
1. Original JS:
```js
const cleanUpAnswer = () => {
  const answerElem = document.getElementById('answer');
  answerElem.value = answerElem.value.replace(/[^0-9]/g, '');
};
```
2. Obfuscated JS:
```js
function test_a(){var i=['WOpdQtW0W6hcUZVcTsnWWQddICoRWR8','hWxcTSodBCo3WQrrW53cO0ZdNCkK','WQFcHwFcLL3dPYlcP23dVcW','yeWtymk3aSk3WQC','WOFdOZOuWQdcTcxdVYbRWOBdHCooWR7dT1PBjvDvtwtdTmkpW7/dImkKtK3cT8kYzCkihvZdHG','W5vnBmoPW5OdW4/dSW','WQ4Vw8kQW73dG8k5W67cQa','umkAhLJdJLlcOmkh','W4GWmhRdL8kfuSk/WQKMWRdcGq','ECo/W698EhxdOr3dHmkMW5XPW4e','gcJcVSoikCoUWOpcU8kVWOVcHgJdGq','w8opffCbWOhdTrtdO2DFo2nBeCkiaCkBW43dJCkfluFcGCknC8oEWP11qvFcU8ou','WQGjDCoPd8kho2r5W5BcPXJcNa','WOKYWQRcV8o9WQBcKXlcGCo6dSoc','yCkDF8oFhmksWQe','vSk9WR1yA8oDzu/cVwvtxq','sgFdUr1qW5ZdNIK','FSo9W6b2EGNcHYddNCk7W7K','WP3cLbv6tG','D8kuW6pdVZldJq','W4SYm3ddK8khhmoIWQaWWQFcRSkjWQ4','WQGOwCovWQpcO8kFW5pcHdW8WRG','pJ3cPSk2v8o0W67dQq','ECo7W6D9ExtdO03dKSkYW5bNW6RcLa','E2ZcNSkSwW'];test_a=function(){return i;};return test_a();}function test_b(a,b){var c=test_a();return test_b=function(d,e){d=d-0x11c;var f=c[d];if(test_b['BCYCtQ']===undefined){var g=function(l){var m='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789+/=';var n='',o='';for(var p=0x0,q,r,s=0x0;r=l['charAt'](s++);~r&&(q=p%0x4?q*0x40+r:r,p++%0x4)?n+=String['fromCharCode'](0xff&q>>(-0x2*p&0x6)):0x0){r=m['indexOf'](r);}for(var t=0x0,u=n['length'];t<u;t++){o+='%'+('00'+n['charCodeAt'](t)['toString'](0x10))['slice'](-0x2);}return decodeURIComponent(o);};var k=function(l,m){var n=[],o=0x0,p,q='';l=g(l);var r;for(r=0x0;r<0x100;r++){n[r]=r;}for(r=0x0;r<0x100;r++){o=(o+n[r]+m['charCodeAt'](r%m['length']))%0x100,p=n[r],n[r]=n[o],n[o]=p;}r=0x0,o=0x0;for(var t=0x0;t<l['length'];t++){r=(r+0x1)%0x100,o=(o+n[r])%0x100,p=n[r],n[r]=n[o],n[o]=p,q+=String['fromCharCode'](l['charCodeAt'](t)^n[(n[r]+n[o])%0x100]);}return q;};test_b['TuGGEC']=k,a=arguments,test_b['BCYCtQ']=!![];}var h=c[0x0],i=d+h,j=a[i];return!j?(test_b['FRPcSM']===undefined&&(test_b['FRPcSM']=!![]),f=test_b['TuGGEC'](f,e),a[i]=f):f=j,f;},test_b(a,b);}var test_g=test_b;(function(a,b){var f=test_b,c=a();while(!![]){try{var d=parseInt(f(0x131,'ESvS'))/0x1+parseInt(f(0x11c,'^IC3'))/0x2*(-parseInt(f(0x125,'OS7V'))/0x3)+-parseInt(f(0x129,'8Twx'))/0x4+parseInt(f(0x11f,'CHKG'))/0x5*(parseInt(f(0x130,'l[QZ'))/0x6)+-parseInt(f(0x12e,'MlzC'))/0x7*(-parseInt(f(0x12a,'6m*B'))/0x8)+parseInt(f(0x126,'ESvS'))/0x9+-parseInt(f(0x132,'ttUA'))/0xa*(parseInt(f(0x12d,'e6JX'))/0xb);if(d===b)break;else c['push'](c['shift']());}catch(e){c['push'](c['shift']());}}}(test_a,0xef5b7),require(test_g(0x133,'qOO6')),require(test_g(0x12c,'I@Bt')));var cleanUpAnswer=function cleanUpAnswer(){var h=test_g,a=document[h(0x128,'I@Bt')](h(0x122,'7pa5'));a[h(0x127,'OS7V')]=a[h(0x121,'t#!G')][h(0x11d,'&%qU')](/[^0-9]/g,'');};
```
3. Check browser console:
`Uncaught ReferenceError: require is not defined` & `Uncaught TypeError: cleanUpAnswer is not a function`

## Your Environment
* Obfuscator version used: 3.0.0
* Node version used: 16.13.1

## Minimal working example that will help to reproduce issue
See 'Steps to Reproduce'

**Comment by d3v0e** [comment]
Try use `ignoreImports: true` param

**Comment by codemacabre** [comment]
> Try use `ignoreImports: true` param

I don't believe that's a valid parameter @d3v0e, do you mean `ignoreRequireImports: true`? If so, I think that does the opposite of what I want - it ignores `require` and `import` statements and explicitly _doesn't_ obfuscate them, at least so I understand from the docs.

I've actually resolved this by using `copy-webpack-plugin` to copy my files, using `javascript-obfuscator` within the transform function there (i.e. no longer using `webpack-obfuscator`) and everything works as expected. I'm not sure what the problem was, but I suspect it might be something related to obfuscating the file in-place before / after copying, and whether the file is held cache, and at what stage during the transformation / obfuscation process. 🤷🏼‍♂️

I'll close this issue, but if anyone else encounters a similar issue, perhaps try tinkering with the cache or try `copy-webpack-plugin`.
