### ISSUE TITLE
Switch/continue pattern is not supported by javascript

### ISSUE THREAD

**Issue by jnpatrick99** [javascript-obfuscator/javascript-obfuscator#104]
You're using this pattern, which is not defined by javascript language standard. Continue cannot be used in switch statement.

```
switch (A)
{
case "B":
    continue;
}
```

It indeed does work in most cases, but it's a very hacky way that is not supported by language documentation. In some cases it doesn't work. I'm using various embedded javascript frameworks which either throw an error that this statement is not supported or just perform switch statements one by one ignoring the loop thus resulting in invalid obfuscated code. There's a way to avoid this problem by using the label or if statements.

**Comment by sanex3339** [comment]
`continue` related to parent `while` loop. I don't see any problems here.

**Comment by jnpatrick99** [comment]
`break` and `continue` statements are treated as belonging to the `switch` by interpreter (that's the problem that I face as I mentioned above). I'm not alone, you can read more about the problem here:
https://stackoverflow.com/questions/18076238/continue-allways-illegal-in-switch-in-js-but-break-works-fine

**Comment by sanex3339** [comment]
What interpreter?

**Comment by jnpatrick99** [comment]
All I'm saying is that you're using this pattern which is not defined by javascript language standard. It indeed does work in most cases, but generally it is not supported by language. In some cases it doesn't work. Here's the example.

```
var A = 1;
while (true)
{ 
 switch (A)
 {
 case 1:
   continue; // statement is treated as belonging to the switch or ignored
 case 2:
   continue; // statement is treated as belonging to the switch or ignored
 case 3:
   break; // statement is treated as belonging to the switch
 }
 alert("we're here!");
}

```
 I'm using various embedded javascript frameworks which either throw an error that this statement is not supported or just perform switch statements one by one ignoring the loop and going straight to alert. There's a way to avoid this problem by using the label or if statements. 

Here's more details why it may not work and how to avoid it:
https://stackoverflow.com/questions/18076238/continue-allways-illegal-in-switch-in-js-but-break-works-fine

**Comment by sanex3339** [comment]
In what browser you test your example? In Chrome it enters in infinity loop as expected.

**Comment by jnpatrick99** [comment]
I'm not using the browser it's rather various versions of embedded Javascript. Due to the security reasons I cannot describe here where it is embedded. But I did give you a public example of what's happening and why.

**Comment by sanex3339** [comment]
`javascript-obfuscator` designed for browser and `node.js`, it won't support rare JS interpreters with unexpected behaviour.
