### ISSUE TITLE
Custom function in stringArrayEncoding

### ISSUE THREAD

**Issue by trycontrolmymind** [javascript-obfuscator/javascript-obfuscator#1040]
**Is your feature request related to a problem? Please describe.**
I have some strings in my script that always needs to be random, for example string with "$$$" should be transformed to sha256(string).

**Describe the solution you'd like**
I wanna pass function to stringArrayEncoding like
```
const options = {
  ...other options,
  stringArrayEncoding: [function(originalString) { 
     /// my encoding function
     return newString;
  }],
}
```

**Comment by BlackYuzia** [comment]
@trycontrolmymind but, how string would be decoded?
By some key or we should also add stringArrayDecoding function? 

🤔

**Comment by trycontrolmymind** [comment]
@BlackYuzia hmm, I mean we don't want to decode them.
But it looks good as other part of this enhancement.

**Comment by sanex3339** [comment]
This is not planned atm.
