### ISSUE TITLE
Obfuscator transforms class names

### ISSUE THREAD

**Issue by d3lm** [javascript-obfuscator/javascript-obfuscator#1045]
The obfuscator seems to rename classes when they are defined inside IIFEs. For example:

```js
(()=>{class Foo{}console.log(new Foo),console.log(new Foo)})();
```

The above is some output from Webpack.

## Expected Behavior

I'd like an option to disable this behavior, at least for classes.

## Current Behavior

Currently, it renames classes.

## Steps to Reproduce
1. Take the code and paste it into the online playground at https://obfuscator.io/
2. Use the default options
3. Click on "Obfuscate"
4. Inspect the output and notice how classes are renamed

## Minimal working example that will help to reproduce issue

Reproducable with the online playground.

**Comment by sanex3339** [comment]
Why do you need to keep class names?

**Comment by sanex3339** [comment]
Closed. I do not plan to add such specific things

**Comment by pilaoda** [comment]
Sorry to talk this closed issue again. 
I need to use the class name in runtime for network data deserialization, the obfuscation of class name break this feature.

Pseudocode:
```
(() => {
  class Foo{}

  RegisterSerializableClass(Foo.constructor.name, Foo);
  // Foo.constructor.name is expected to be 'Foo' but obfucated to some random hex string.

})()
```
Is there any option to preserve class name?
