### ISSUE TITLE
[Feature Request] Auto Split Chunks Function

### ISSUE THREAD

**Issue by BlackYuzia** [javascript-obfuscator/javascript-obfuscator#1047]
### Description 

I test some settings with string chunks.
I test it with 1 - 5 chars per word.
I found next:
1. Minimum chars for encrypt strings is 3 or more.
2. 1 and 2 chars do not be encrypted.
3. you can also disable chunks but that means what if anyone check strings array, he can saw full of string

### Request & Examples

So, if we really can't protect 1-2 symbols per string then:
- Add option for auto set size of chunk for every string. `AutoChunks = true`
- Add safe option for auto chunks `SafeChunks = true`

```js
"hello" () => encrypt<"hello"> // if AutoChunks && SafeChunks. Why only one string? we can chunk it like 3 and 2 (hell and lo), but, we have safeChunks, save chunks do not allow not encrypted strings.
"Hello World!" () => encrypt("hel"), encrypt("llo"), encrypt(" Wo"), encrypt("Rld!")  // AutoChunks && SafeChunks, in example I use min. length = 3
"hello" () => encrypt("hel"), "lo" // if AutoChunks only
```

So, that means what `AutoChunks ` would use min. symbols for encrypt (also we can get a few modes like low, mid, high)
So, that means what `SafeChunks `, if true, prevent not encrypted words (strings) 2 or less symbols (require encryption string option)
So, after that we get 100% of encrypted strings. Without a ...., "d!" on the end.

Also, we can set `AutoChunksLength` for set min/max length of string.

PS: Sorry my eng lang. I test it on some bot, he say "intermediate".

### Source code

![image](https://user-images.githubusercontent.com/25010528/152654273-e44dbbe0-5ee6-4d86-91ad-40f2ad0e6333.png)

### Obfuscated code

![image](https://user-images.githubusercontent.com/25010528/152654257-5944728d-ca3c-4f6e-bc7e-4704869acbae.png)
![image](https://user-images.githubusercontent.com/25010528/152654563-32db7ffd-4d24-496c-91a5-6950fc6368fe.png)
![image](https://user-images.githubusercontent.com/25010528/152654566-ff2a6098-4a7e-4e6a-bff4-c9cadf30a8ee.png)
![image](https://user-images.githubusercontent.com/25010528/152654568-80c6163a-55fd-42ff-b56f-83cd010d9de9.png)
![image](https://user-images.githubusercontent.com/25010528/152654572-a8a49993-619f-4b10-b883-c61bf0815081.png)

### Obfuscate Settings
![image](https://user-images.githubusercontent.com/25010528/152654266-778226bf-274e-4b06-8c56-93968ca57a4c.png)
![image](https://user-images.githubusercontent.com/25010528/152654599-a76aacd8-12b9-4404-84ad-e4a60c6eb7b1.png)

**Comment by sanex3339** [comment]
The reason for >3 characters is that `stringArray` ignores all strings with 1-2 characters (for runtime performance reasons).
Right now i don't see any reason to add such options, it complicates things.
