### ISSUE TITLE
TypeError: [].values is not a function

### ISSUE THREAD

**Issue by SimonB2011** [javascript-obfuscator/javascript-obfuscator#1051]
When running script via NPM the error TypeError: [].values is not a function is thrown, preventing the obfuscation 

## Expected Behavior
For the code to be obfuscated and the error to not be thrown or give context as to why it was thrown

## Current Behavior
Error is thrown with no explanation why

## Steps to Reproduce
Code string is passed to server and processed then returned. Processing always fails. Code string has no obvious issues.
`try{
				var obfuscationResult = JavaScriptObfuscator.obfuscate(
					objs.code,
					{
						compact: true,
						simplify: true,
						stringArray: false,
						
						
					}
				);
				responseBody = { 
					status:"success",
					result:obfuscationResult.getObfuscatedCode()
				};
			} catch(e){
				responseBody = { 
					status:"error",
					result:"Could not obsfuctae the given string\n\n"+e.toString()
				};
			}`

## Your Environment
package json 
`{
  "name": "jsobs",
  "version": "1.0.0",
  "description": "jsob for packager",
  "main": "index.js",
  "dependencies": {
    "clean-css": "^4.2.4",
    "css-minifiers": "^3.0.0",
    "css-minify": "^1.1.0",
    "html-minifier": "^3.5.21",
    "http": "0.0.0",
    "javascript-obfuscator": "^3.2.2"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
`

**Comment by sanex3339** [comment]
Do you have this problem with `3.1.0` version?

**Comment by SimonB2011** [comment]
Hi, 

I've changed the package.json to require version 3.1.0 and ran npm update to roll it back.  Ran the code to protect the script and got back the same error.  I also logged out the content of the target file and ran that through the https://obfuscator.io/ site which was able to protect the string with no issue. 

Here's an example script that I have used and fails to be protected.

`import { Behaviour } from "./Core/Behaviour.js";

export class MainMenu extends Behaviour {
    static Topics = [];
	constructor( parameters ) {
        super( parameters );
		
		if(window._mainMenu != null){
            delete this;
            return;
        }
        window._mainMenu = this;
		
		const PrivateFunction = ()=>{
			return true;
		}
		
		this.PublicFunction = ()=>{
			return true;
		}
	}
}`

**Comment by sanex3339** [comment]
Try to use 3.2.4 version. If it won't help, please provide a repository with a reproducible example.
Using your code i can't reproduce it

**Comment by SimonB2011** [comment]
Thanks  @sanex3339, I've tried with 3.2.4 and still have had no luck. I've uploaded the project with a simplified execution. The index.js script attempts to protect a snippet of test code, for me it always throws the error. 

https://github.com/SimonB2011/jsobstest

![image](https://user-images.githubusercontent.com/28984829/153001859-7b92f114-e127-4774-9d34-d06c675b6d7b.png)

**Comment by sanex3339** [comment]
![image](https://user-images.githubusercontent.com/9210534/153003505-1ec4664a-7777-46f5-aa56-345370f92db6.png)

**Comment by sanex3339** [comment]
What `node` version are you using?

**Comment by BlackYuzia** [comment]
Hmm, I test it on latest version with webpack.
![image](https://user-images.githubusercontent.com/25010528/153004675-590e27e7-4e4d-4b56-8521-ca91947afe90.png)
`[].values` work's fine

But, I get the error with `"developer"` mode.
![image](https://user-images.githubusercontent.com/25010528/153004760-2310da14-6bbe-40ab-ae95-d4b47675e98e.png)

On mode `"none"` all work's fine.

@sanex3339 could you test production and development modes with webpack 5 and webpack obfuscator plugin?

**Comment by SimonB2011** [comment]
Node version installed on this machine is v10.6.0. I will try updating it and see what happens

**Comment by SimonB2011** [comment]
Thanks both, it looks like it was down to an older version of node being used. The script executes fine now using v16.13.2
