### ISSUE TITLE
Npm install failed if opencollective is not installed

### ISSUE THREAD

**Issue by frontenddeveloping** [javascript-obfuscator/javascript-obfuscator#1052]
## Expected Behavior
npm install works as usual

## Current Behavior
npm install failed

## Steps to Reproduce
1) Add javascript-obfuscator to package.json
2) Run `npm i` 

## Your Environment
* Obfuscator version used: any, from 2.10 to latest
* Node version used: 11.15

# Stack trace
npm verb stack Error: javascript-obfuscator@2.19.1 postinstall: `opencollective`
npm verb stack spawn ENOENT

# Fix
`npm install -g opencollective` fix the problem

**Comment by sanex3339** [comment]
Will try to use https://github.com/opencollective/opencollective-postinstall

**Comment by sanex3339** [comment]
Try 3.2.4 version
