### ISSUE TITLE
[BUG] Webpack 5 Development Mode

### ISSUE THREAD

**Issue by BlackYuzia** [javascript-obfuscator/javascript-obfuscator#1053]
## Expected Behavior

Webpack `development` mode do not break any obfuscated code.

## Current Behavior

Currently, webpack destroy obfuscated code by webpack obfuscator plugin if you set mode to `development`.

## Steps to Reproduce

1. Use webpack obfuscator plugin with high presset (I set 90% obfuscated functions to true and 1.0 of 1.0)
2. Set mode to `development` inside `webpack.config.js`
3. Build bundle
4. Try run it and get error

## Your Environment

* Obfuscator version used: latest (3.4.1 or something)
* Node version used: 14.16.1

# Stack trace

![image](https://user-images.githubusercontent.com/25010528/153034251-d7050bcc-056d-4b39-9530-8b1897d595d1.png)

## Minimal working example that will help to reproduce issue

```js
function hi() {
    console.log("hi!");
}

hi();
```

**Comment by sanex3339** [comment]
Can't reproduce. Can you provide a repo with example?

**Comment by BlackYuzia** [comment]
@sanex3339 try this one - https://github.com/BlackYuzia/bug-report-1053

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/1060

**Comment by sanex3339** [comment]
Hi. Please try `3.2.6` version

**Comment by BlackYuzia** [comment]
@sanex3339 
![image](https://user-images.githubusercontent.com/25010528/153731275-b5159ef2-d667-44cb-ab03-91b9be347169.png)

**Comment by sanex3339** [comment]
Nice catch!
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/1062

**Comment by sanex3339** [comment]
Should be fixed in `3.2.7`

**Comment by BlackYuzia** [comment]
@sanex3339 could that be a one more bug?
![image](https://user-images.githubusercontent.com/25010528/154134581-531c9f89-8366-47ff-b576-d141839b36e0.png)

I suppose what global `exports` was broken in some case also with webpack and development mode.
I can't share with source code, currently, but I try find a small codeexample for reproduce bug.
