### ISSUE TITLE
"Illegal return statement" in Chrome extension

### ISSUE THREAD

**Issue by HerrimanCoder** [javascript-obfuscator/javascript-obfuscator#107]
I have a Chrome extension that runs obfuscated js (obfuscated by this lib), and after the most recent cmd-line obfuscation, and running it in the browser, I am getting this error:

**Illegal return statement**

The block of code triggering this is here:

```
if (_0xcbe1('0x11') !== _0xcbe1('0x11')) {
      if (_0x529317) {
               var _0x169e9b = fn[_0xcbe1('0x12')](_0x428b52, _0x229593);
                _0x3ad9e8 = null;
                return _0x183a90;
        }
 } else {
        zingLog(_0xcbe1('0x13'));
}
```

It is the  **return _0x183a90** statement throwing the exception. I had a similar problem a few months ago and that was fixed with a newer release. I am on the latest version: 0.11.2

Can this be fixed?

**Comment by sanex3339** [comment]
Hi, can you show source code of this part of obfuscated code and some amount of source code before this part of obfuscated code.

**Comment by sanex3339** [comment]
Also, this code in the root block scope, as i can see.  This is `deadCodeInjection` error

**Comment by sanex3339** [comment]
ping

**Comment by sanex3339** [comment]
Can't reproduce. Waiting for response.

**Comment by HerrimanCoder** [comment]
I ended up changing some code around and the problem went away after obfuscating. Next time this happens (it's happened twice now), what is the best way for me to help you repro?

**Comment by sanex3339** [comment]
Best way - show me source code and more larger piece of obfuscated code.

**Comment by HerrimanCoder** [comment]
I will next time it happens. Thank you.
