### ISSUE TITLE
Blank output when input code size = 900kb

### ISSUE THREAD

**Issue by digdug82** [javascript-obfuscator/javascript-obfuscator#109]
I tried to obfuscate a 900kb code and in the output was blank in the test website, Is there is any fix to this problem?

**Comment by sanex3339** [comment]
You mean javascriptobfuscator.herokuapp.com?

**Comment by slig** [comment]
There's a maximum request timeout on the site. If your code is big, you should download and install the npm package.

**Comment by digdug82** [comment]
sanex3339, yes 
slig, yes but there are many options aren't available in the npm like self defending, domain lock, debug protection.

**Comment by sanex3339** [comment]
All options described above available within `javascript-obfuscator` npm package.

**Comment by digdug82** [comment]
Can you please provide an example about how to use the domain/multidomain lock in the cli option?

**Comment by sanex3339** [comment]
--domainLock www.example.com,www.foo.net

**Comment by digdug82** [comment]
Many thanks
