### ISSUE TITLE
Obfuscate Error

### ISSUE THREAD

**Issue by Krex38** [javascript-obfuscator/javascript-obfuscator#1114]
Obfuscate Error

## Expected Behavior

I'm trying to obfuscate my codes using cmd like : javascript-obfuscator .... but I'm getting error

## Current Behavior

>I exptexted It would work withour any errors

## Steps to Reproduce

1. https://i.imgur.com/JfIWJzo.png
2.
3.
4.

## Your Environment

* Obfuscator version used: 4.0.0
* Node version used: 16x

# Stack trace

## Minimal working example that will help to reproduce issue

is big

**Comment by slig** [comment]
It's not possible to help you without more details. What's the translation of the error message? Can you try to obfuscate a simple "hello world" instead of your whole project and reproduce the error?

**Comment by Krex38** [comment]
> It's not possible to help you without more details. What's the translation of the error message? Can you try to obfuscate a simple "hello world" instead of your whole project and reproduce the error?

```
E:\Exotic\exotic\exotic\commands\build.js:58
          if (error) throw error;
                     ^

Error: Command failed: javascript-obfuscator ./build/8247406453812101431.js --config ./build/obf-config.json --output ./build/824740645381210143s.js
Der Befehl "javascript-obfuscator" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'javascript-obfuscator ./build/8247406453812101431.js --config ./build/obf-config.json --output ./build/824740645381210143s.js'
```

error what im getting

**Comment by Krex38** [comment]
"javascript-obfuscator" couldn't find or doesn't exist

**Comment by Krex38** [comment]
The Problem is I can't obfuscate using cmd 
![image](https://user-images.githubusercontent.com/102794636/186661999-ff2a8fd2-c955-4ec3-b1ee-24c6ad562813.png)
 like theese but i get this error

![image](https://user-images.githubusercontent.com/102794636/186662065-84844247-94bd-4c21-a352-6b5e5c73570e.png)

**Comment by slig** [comment]
The obfuscator isn't on your `path`. Try something like `node_modules/javascript-obfuscator/bin/javascript-obfuscator ...`

**Comment by Krex38** [comment]
![image](https://user-images.githubusercontent.com/102794636/186662820-3f0b994f-c5a9-45fa-a8e7-dc2c66babcab.png)


how isn't in my path?

**Comment by slig** [comment]
This one https://en.wikipedia.org/wiki/PATH_(variable)

**Comment by Krex38** [comment]
I didn't understand it i need to put to the Path

**Comment by Krex38** [comment]
am I right?

![image](https://user-images.githubusercontent.com/102794636/186663800-9a1d5f67-b257-47e4-adbc-c0b8af5e6d79.png)

**Comment by slig** [comment]
Changing the Path variable in the settings for a specific folder for a project is not the right way to do it. I'm not sure how to do it on Windows, but this is how I'd try (it works on mac/linux):

    ./node_modules/javascript-obfuscator/bin/javascript-obfuscator

Instead of just:

    javascript-obfuscator

**Comment by Krex38** [comment]
> Changing the Path variable in the settings for a specific folder for a project is not the right way to do it. I'm not sure how to do it on Windows, but this is how I'd try (it works on mac/linux):
> 
> ```
> ./node_modules/javascript-obfuscator/bin/javascript-obfuscator
> ```
> 
> Instead of just:
> 
> ```
> javascript-obfuscator
> ```

worked but other issue 

![image](https://user-images.githubusercontent.com/102794636/186666332-4edce172-b5b4-491d-98f5-987a0ac96a6e.png)

**Comment by Krex38** [comment]
Thanks it worked im working on another issue

**Comment by Krex38** [comment]
What Can I do?

**Comment by Krex38** [comment]
Didn't worked any other selection

**Comment by Krex38** [comment]
Can somebody help me please?

**Comment by HanHuiOnLine** [comment]
Maybe you can get a different computer to solve your problem, I use Windows11 and it works fine.

**Comment by Krex38** [comment]
lol worked thx

> Maybe you can get a different computer to solve your problem, I use Windows11 and it works fine. or you can try it: `npm install javascript-obfuscator -g`

**Comment by Krex38** [comment]
Fixed thx @HanHuiOnLine
