### ISSUE TITLE
Fails to run on AWS Linux

### ISSUE THREAD

**Issue by pkasson** [javascript-obfuscator/javascript-obfuscator#1119]
Runs just fine on OSX (Mac) ... but running this on an AWS Linux instance:

Linux ip-172-30-1-5.ec2.internal 4.14.209-160.339.amzn2.aarch64 #1 SMP Wed Dec 16 22:44:17 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

Invocation:

`/home/ec2-user/server/obfuscate/bin/javascript-obfuscator $FILE --output $newFN >> obfuscate.log`

Nothing works ... every time, get an Unexpected token ... error:

`/home/ec2-user/server/obfuscate/dist/index.cli.js:2
require("source-map-support").install(),(()=>{var e={7568:(e,t,r)=>{"use strict";Object.defineProperty(t,"__esModule",{value:!0});const o=r(8206);e.exports=o.JavaScriptObfuscatorCLI},425:function(e,t,r){"use strict";var o=this&&this.__createBinding||(Object.create?function(e,t,r,o){void 0===o&&(o=r),Object.defineProperty(e,o,{enumerable:!0,get:function(){return t[r]}})}:function(e,t,r,o){void 0===o&&(o=r),e[o]=t[r]}),n=this&&this.__setModuleDefault||(Object.create?function(e,t){Object.defineProperty(e,"default",{enumerable:!0,value:t})}:function(e,t){e.default=t}),i=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(null!=e)for(var r in e)"default"!==r&&Object.prototype.hasOwnProperty.call(e,r)&&o(t,e,r);return n(t,e),t},a=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:!0}),t.ASTParserFacade=void 0;const s=i(r(9631)),c=a(r(5022));class l{static parse(e,t){c
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec2-user/server/obfuscate/bin/javascript-obfuscator:3:1)`

Version is latest - 4.0

**Comment by relative** [comment]
What version of node is your VM running? It appears you need Node v12.22.x or later but your VM has node <=10

**Comment by pkasson** [comment]
Version 7.x

**Comment by pkasson** [comment]
That was the issue ... thank you ... thank you.
