### ISSUE TITLE
Help me install

### ISSUE THREAD

**Issue by AhsanE** [javascript-obfuscator/javascript-obfuscator#113]
I ran : `npm install --save-dev javascript-obfuscator
`

After that I did:
 `javascript-obfuscator samples/sample.js --output output/output.js --compact true --selfDefending false`

But than I get an Error:
```
javascript-obfuscator' is not recognized as an internal or external command,
operable program or batch file.
```

Why is this happening?

I checked everything, and verified if it is installed. It is installed, why do I get this error?

**Comment by sanex3339** [comment]
Try `npm link`

**Comment by AhsanE** [comment]
Tried, 
![untitled](https://user-images.githubusercontent.com/28547327/31585450-81d2a5be-b1ca-11e7-9dea-c980b96cab94.png)

**Comment by AhsanE** [comment]
:(
![untitled](https://user-images.githubusercontent.com/28547327/31585866-9d72a9a2-b1d1-11e7-94bc-eab195702a3b.png)

**Comment by sanex3339** [comment]
There is no file under `ahsan/samples/samole.js` path.

**Comment by thrwat** [comment]
uhm.. I've verified. A file exists, but this error still pops up. Is it due to some dependencies?

**Comment by sanex3339** [comment]
No. Maybe it not works under windows, but in general all file paths should be relative to current working directory, so if this file exist - command should work.

**Comment by AhsanE** [comment]
Okay it works. The issue was that the file samples/sample.js was there but, that will was like "sample.js.js".
double extensions were the culprit.

**Comment by sanex3339** [comment]
Nice!
