### ISSUE TITLE
Is the default example good enough?

### ISSUE THREAD

**Issue by lincdh** [javascript-obfuscator/javascript-obfuscator#1135]
The default example is:

> var JavaScriptObfuscator = require('javascript-obfuscator');
> 
> var obfuscationResult = JavaScriptObfuscator.obfuscate(
>     `
>         (function(){
>             var variable1 = '5' - 3;
>             var variable2 = '5' + 3;
>             var variable3 = '5' + - '2';
>             var variable4 = ['10','10','10','10','10'].map(parseInt);
>             var variable5 = 'foo ' + 1 + 1;
>             console.log(variable1);
>             console.log(variable2);
>             console.log(variable3);
>             console.log(variable4);
>             console.log(variable5);
>         })();
>     `,
>     {
>         compact: false,
>         controlFlowFlattening: true,
>         controlFlowFlatteningThreshold: 1,
>         numbersToExpressions: true,
>         simplify: true,
>         stringArrayShuffle: true,
>         splitStrings: true,
>         stringArrayThreshold: 1
>     }
> );
> console.log(obfuscationResult.getObfuscatedCode());`

Is there any more properties of the the options parameter should I add or update?

**Comment by slig** [comment]
You have to try for yourself whatever fits your needs. Also check the presets https://github.com/javascript-obfuscator/javascript-obfuscator#preset-options and the online version at obfuscator.io.
