### ISSUE TITLE
Date Lock

### ISSUE THREAD

**Issue by gwinterhalter** [javascript-obfuscator/javascript-obfuscator#116]
What would it take to have Date Lock added to this project?

Thanks

**Comment by sanex3339** [comment]
Closed. Right now i don't see any reason to add date lock feature.

**Comment by gwinterhalter** [comment]
Would you add it for a consulting engagement? If so, let me know costs.

**Comment by gwinterhalter** [comment]
Hi Timofey

I have a need to date lock my code through your obfuscator.

Would you add it as a consulting engagement? Or inform my staff how to modify?

Greg Winterhalter
VP, Professional Services, PMP
d:925.804.6757 | f: 926.804.6155 | gwinterhalter@epmsolutions.com
2603 Camino Ramon | Suite 200 | San Ramon | CA 94583
People | Project | Performance
Microsoft Gold Partner | PMI Global Education Provider | ISO 9001:2008 Certified
Inc 500 America's Fastest Growing Private Company | Fast 50 Asian American Business

**Comment by sanex3339** [comment]
Main problem of all features of this type - all code that will added with this feature can be tracked and removed by "third party" user, this is why i want to focus on transformations of AST tree - they can't be reverted.
