### ISSUE TITLE
Whether I can produce the different content of bundle.js by configuration?

### ISSUE THREAD

**Issue by XLearner** [javascript-obfuscator/javascript-obfuscator#1180]
In order to improve the safety of the front-end code, I want to fulfill the product of the obfuscated file is different, that is, I hope that all the variable names and code sequences will change in every packaging. I tried to change some parameters, like `stringArrayThreshold` and `splitStringChunkLength`, but it seemed that the result did not change a lot. Whether I ignore some options? Or what can I do to achieve my requirement?

**Comment by BlackYuzia** [comment]
@XLearner did you set seed?
You should ignore seed, then it would be random.
If I don't mistake.

**Comment by XLearner** [comment]
> @XLearner did you set seed? You should ignore seed, then it would be random. If I don't mistake.

When I set `seed: 1`, the result was random. So, according to your said, is that random result a default configuration if I ignore `seed`? I saw the documentation about `seed`, 0 was the default value.

**Comment by XLearner** [comment]
I've got it. I have tried multiple times. The random result is indeed a default configuration. And when I set `seed`, the result will change more, even in the code sequence. My question is done.
Thank guys. Have a good day.
