### ISSUE TITLE
Not able to install package via npm

### ISSUE THREAD

**Issue by xoraingroup** [javascript-obfuscator/javascript-obfuscator#1184]
Hi,

 Trying to run simply npm i @javascript-obfuscator/escodegen fails with 404 not found. Is the package removed by some one?

thanks

**Comment by gabrielmaldi** [comment]
Can confirm.

**Comment by garycrose** [comment]
Also confirming

**Comment by sanex3339** [comment]
That's strange.
Maybe some NPM issues?

The package itself is here https://www.npmjs.com/package/@javascript-obfuscator/escodegen

**Comment by sanex3339** [comment]
What `npm view @javascript-obfuscator/escodegen` show for you?

**Comment by sanex3339** [comment]
For me `npm i @javascript-obfuscator/escodegen` works

So i believe it was something on the NPM side

**Comment by sanex3339** [comment]
https://status.npmjs.org/ shows that there were some issues with `install` packages

**Comment by gabrielmaldi** [comment]
It works for me now. Must've been npm. Thanks!

**Comment by xoraingroup** [comment]
Yes working now. Thank you every one.

Closing.
