### ISSUE TITLE
Using existing sourcemap as input to produce a new one

### ISSUE THREAD

**Issue by JeViCo** [javascript-obfuscator/javascript-obfuscator#1185]
I have some code and a sourcemap that were generated after the bundling process. Am i able to use a sourcemap as an input to make it work after using a javascript-obfuscator?

Context:
I've made a custom esbuild plugin that processes production code. I'm able to read contents of a sourcemap (separate file) and a bundled code itself. I've tried a couple of things to combine two sourcemaps (@ampproject/remapping and combine-source-map) but failed.

**Comment by da411d** [comment]
Just randomly googled, that may help you:
https://github.com/Rich-Harris/sorcery
