### ISSUE TITLE
Failed to run after installed on windows 10

### ISSUE THREAD

**Issue by zengfanfan** [javascript-obfuscator/javascript-obfuscator#1186]
I want to use this tool in windows CLI, so I installed it as:
`npm install --save-dev javascript-obfuscator`

And it successed, saying `added 80 packages in 4s`.

Then I went to `node_modules\javascript-obfuscator\bin` and saw `javascript-obfuscator` without ext `.exe`.
And if I run `.\node_modules\javascript-obfuscator\bin\javascript-obfuscator --help`, I got:
`... is not recognized as an internal or external command,operable program or batch file.`

## Environment

* Obfuscator version used: newest on npm
* Node version used: v16.13.0
* Windows 10

## Minimal working example that will help to reproduce issue

1. run in cmd.exe window: `npm install --save-dev javascript-obfuscator`
2. try to run the tool: `.\node_modules\javascript-obfuscator\bin\javascript-obfuscator`

**Comment by slig** [comment]
Node version way too old. See https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/package.json#L15C14-L15C14

**Comment by zengfanfan** [comment]
My bad, the version is newest as:
```
D:\tools>npm -v
9.8.1

D:\tools>node -v
v16.13.0
```

**Comment by zengfanfan** [comment]
The file under `node_modules\.bin` is good to run.
