### ISSUE TITLE
Domain lock WIP feature

### ISSUE THREAD

**Issue by slig** [javascript-obfuscator/javascript-obfuscator#12]
Hi,

I've been studying your project and I loved it. Thanks for sharing.

I started a feature that I'm going to use and I'd like to know if you're interested in adding it to your project (I can create a PR) and if you can help me with some questions.

Here's what I've come up with: https://github.com/slig/javascript-obfuscator/tree/domain-lock

Things working right now:
- [x] Multiple domains and subdomains. (e.g: ".example.com" allows any example.com subdomain, and "example.com" matches exactly with "example.com"

Things that need to be done:
- [x] Now it only shows an alert displaying if the current domain is allowed or not. I've thought of using an while(1) or throwing an exception, and both seem to work, but I'm not sure what's the best, or what is the one that you recommend;
- [x] Update the README;
- [x] Write proper tests (not sure how to test this kind of feature, I'd love to hear your input);

Random questions:
- I wrote a simple function to hide the domain list inside a string and use a RegExp on the browser to get back the string. I found this method to be more resilient against closure compiler pretty print. What do you think?
- Should this feature be appended before the obfuscation or after? Right now I'm using before.
- For now, the code on DomainLockTemplate.ts is unobfuscated. Should I run it on jscrush or leave it as this?

Thank you very much for your time and patience!

**Comment by sanex3339** [comment]
Hi, @slig, i like that feature. I look deeply at this today/tomorrow. Thank you for your work!

**Comment by sanex3339** [comment]
```
d.length = 101
```
It is for more hard understanding of code?

Node can be applied before obfuscation, because it doesn't depends on any important obfuscation data like `unicodeArray` length, so `DomainLockTemplate` can be unobfuscated.

About behaviour when  domain doesn't match: i think in this situation best way to throw an exception.

**Comment by sanex3339** [comment]
You can make PR, i will merge it into `dev` branch and write some tests.

**Comment by sanex3339** [comment]
Instead `getRandomString` method it is better to use `chance` package which is already used in `javascript-obfuscator`.

http://chancejs.com/#string

**Comment by slig** [comment]
> > d.length = 101

> It is for more hard understanding of code?

No, that was a bug that I made by copy/pasting and worked by accident. Fixed it now!

> Instead getRandomString method it is better to use chance package which is already using in javascript-obfuscator.

Nice suggestion. Now the code is using it.

Made this changes and opened a PR #13.

**Comment by sanex3339** [comment]
found way to test code inside templates.
https://github.com/sanex3339/javascript-obfuscator/commit/19bfbd451425d27267606c0462e53ed728c38589

**Comment by slig** [comment]
Really nice solution!

**Comment by sanex3339** [comment]
For this, some previous and all next custom nodes i make two classes for intellectual getting node in which custom node should be appended.

https://github.com/sanex3339/javascript-obfuscator/commit/8571cef294d870af95a6d2b913ee0fa3fdd6be43

for example following code:

```javascript
function foo () {

}

function bar () {
    function inner1 () {
    
    }

    function inner2 () {
        var inner3 = function () {
            
        }
        
        inner3();
    }
    
    inner2();
    inner1();
}

function baz () {

}

baz(); // first call expression
foo();
bar();
```

Custom node will be inserted into `baz` function declaration block statement, because `CallExpression` of this function declaration is first in order of call expressions.

Next example:

```javascript
function foo () {

}

function bar () {
    function inner1 () {
    
    }

    function inner2 () {
        var inner3 = function () {
            
        }
        
        inner3(); // first call expression
    }
    
    inner2(); // first call expression
    inner1();
}

function baz () {

}

bar(); // first call expression
foo();
baz();
```

Custom node will be inserted into `inner3` function expression block statement, because `CallExpression`s chain has following structure:
`bar() -> inner2() -> inner3()`

With this new classes custom nodes should be more hardest to observe.

**Comment by sanex3339** [comment]
I will change `Exeption` to `while` loop because it is easy to detect function location by stack trace

**Comment by slig** [comment]
Really liked how you implemented the HiddenNodeAppender. Now I can see that the `while` option is better than the Exception.

**Comment by sanex3339** [comment]
New ObjectExpressionCalleeDataExtractor is ready.
https://github.com/sanex3339/javascript-obfuscator/commit/42657550d3f6756464bcd380aafbb3e4f475df16

Looking for any help in improving of this algorithm.

**Comment by slig** [comment]
Hi, I didn't understand where you're going to use this `ObjectExpressionCalleeDataExtractor` on the domain lock feature. Could you please tell us more?

**Comment by sanex3339** [comment]
For example following code:

```javascript
var object = {
    foo: {
        baz: function () {

        }
    },

    bar: function () {
        function inner () {

        }

        inner();
    }
};

object.foo.baz();
object['foo'].baz();
object.bar();
```

StackTraceAnalyzer with help of CalleeDataExtractors can give stacktrace data which will use CustomNodeAppender to append custom node (`DomainLockNode` for example) in the one of the first 10% root (relative to AST Tree Program Node) function declaration/expression calls.

In case of example above - it will be function expression which will be called by `object.foo.baz();` line.

```javascript
var object = {
    foo: {
        baz: function () {
            // CUSTON NODE WILL BE APPENDED HERE
        }
    },

    bar: function () {
        function inner () {

        }

        inner();
    }
};

object.foo.baz();
object['foo'].baz();
object.bar();
```

**Comment by sanex3339** [comment]
ready in dev release 
`npm i javascript-obfuscator@beta`
