### ISSUE TITLE
config js how

### ISSUE THREAD

**Issue by KnIfER** [javascript-obfuscator/javascript-obfuscator#1219]
how to pass js file (not json ) as config file in cli-mode, whats the format ?  I want to try js because json doesn't support comments.

![image](https://github.com/javascript-obfuscator/javascript-obfuscator/assets/11593903/41e75067-72af-4946-95bd-f4102d3b2d40)

**Comment by KnIfER** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/560

**Comment by Pixelsplasher** [comment]
--config doesn't seem to work on windows...
Solved by yours truly at #1234
