### ISSUE TITLE
Incompatible options: Mangle Variable Names + Debug Protection + Target=Extension

### ISSUE THREAD

**Issue by bibicron** [javascript-obfuscator/javascript-obfuscator#123]
Thank you for adding the Target=Extension option.

The issue appears when using these 3 options at the same time: Mangle Variable Names + Debug Protection + Target=Extension.

I use them for Firefox Add-ons. I tested and excluded the other options as a cause for the problem. When the 3 options are used then Firefox will start using the CPU intensely, the Add-on will not work and also some other Add-ons will freeze.

I think the thread loops indefinitely. 
The Debug Protection will add a function at the end of the code. Inside this function there is another function defined with a parameter named like _0xXXXXXX. The problem appears when the name of this parameter is changed to "b" by the Mangle Variable Names option. By my tests that is what causes the freeze.

**Comment by sanex3339** [comment]
Mangle option is unstable, use it on your own risk.

**Comment by sanex3339** [comment]
I'll release 0.12.3 in next few days

**Comment by sanex3339** [comment]
Check new `javascript-obfuscator@0.12.3`
