### ISSUE TITLE
Bug in dependency class-validator@0.14.0

### ISSUE THREAD

**Issue by MelanieW97** [javascript-obfuscator/javascript-obfuscator#1247]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `javascript-obfuscator@4.1.0` for the project I'm working on.

The version 0.14.0 of class-validator causes an error for me.
According to a post I found on GitHub, it's a bug in class-validator which is being fixed in version 0.14.1.
You can read about it right here: https://github.com/typestack/class-validator/issues/2370#issuecomment-1887787668

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/javascript-obfuscator/package.json b/node_modules/javascript-obfuscator/package.json
index f629417..a563577 100644
--- a/node_modules/javascript-obfuscator/package.json
+++ b/node_modules/javascript-obfuscator/package.json
@@ -27,7 +27,7 @@
     "assert": "2.0.0",
     "chalk": "4.1.2",
     "chance": "1.1.9",
-    "class-validator": "0.14.0",
+    "class-validator": "0.14.1",
     "commander": "10.0.0",
     "eslint-scope": "7.1.1",
     "eslint-visitor-keys": "3.3.0",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by sanex3339** [comment]
Will release a new version today with the fix. Thank you.

**Comment by sanex3339** [comment]
Released
