### ISSUE TITLE
Is it possible to disable RenameIdentifiers?

### ISSUE THREAD

**Issue by rationalthinker1** [javascript-obfuscator/javascript-obfuscator#1273]
Hello,
I'm trying to obfuscate a React build file. It's about 6mb overall.  I'm using this command ` javascript-obfuscator index-DvjbZnoh.js index-DvjbZnoh-OB.js  --options-preset low-obfuscation --control-flow-flattening false --log true --seed 1 --rename-globals false` However, the process takes about 25 minutes, and majority (95%) of that time is on renaming identifiers. if I can disable that, it will significantly reduce the amount of time.

**Comment by slig** [comment]
Hi,
Ideally you should use a bundler such as Webpack, use the Obfuscator webpack plugin and obfuscate only your code, not the dependencies. Otherwise you'll ship a massive file to the user and it will be very slow to parse and execute.

**Comment by rationalthinker1** [comment]
Hey. I just did that it works beautifully. Thanks a lot.

**Comment by slig** [comment]
That was fast, great!
