### ISSUE TITLE
Lots of "unreachable code after return statement" warnings in Firefox

### ISSUE THREAD

**Issue by jpodpro** [javascript-obfuscator/javascript-obfuscator#129]
If controlFlowFlattening is enabled I get a huge number of these warnings in Firefox. I'm assuming the obfuscation is adding code after return statements? 

Is there any solution that allows using controlFlowFlattening and avoiding these warnings?

**Comment by sanex3339** [comment]
What kind of warnings?

**Comment by jpodpro** [comment]
unreachable code after return statement:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return

perhaps this is what control flow flattening is intentionally doing?

**Comment by sanex3339** [comment]
Catch it, i'll fix it before 0.12.3 version

**Comment by sanex3339** [comment]
Check new `javascript-obfuscator@0.12.3`
