### ISSUE TITLE
Problem with generated source maps?

### ISSUE THREAD

**Issue by teleclimber** [javascript-obfuscator/javascript-obfuscator#131]
I have noticed some odd behavior when trying to use sourcemaps generted by javascript-obfuscator.

- I upload my sourcemaps to getSentry.com so I can see my stack trace relative to original source. Unfortunately sometimes the line pointed at by sourcemap is off from the actual line (sometimes off by 1, sometimes off by 10 or 20)
- when I use obfuscated code in chrome devtools it seems to have hard time matching lines in original source with lines obfuscated code (like when setting a breakpoint).

I got a bit suspicious so I decided to check sourcemaps against `sourcemap-validator` and it consistently picks up on issues.

Note that it is very possible that the validator is wrong, but I am seeing enough weird things that I thought I'd bring this up to you.

For reference this is the setup I use to validate sourcemaps:

```
const fs = require( 'fs' );
const javascript_obfuscator = require( 'javascript-obfuscator' );
const validator = require( 'sourcemap-validator' );

const obf_opts = require( './obf-opts.json' );

const raw = fs.readFileSync( 'test_files/angular.js', {encoding:'utf8'} );

const obf_results = javascript_obfuscator.obfuscate( raw, obf_opts );

validator( obf_results.getObfuscatedCode(), obf_results.getSourceMap(), { 'file.js': raw } );
```

Currently my `obf-opts.json` looks like this:

```
{
	"compact": true,
	"controlFlowFlattening": false,
	"controlFlowFlatteningThreshold": 0,
	"deadCodeInjection": true,
	"deadCodeInjectionThreshold": 0.7,
	"debugProtection": false,
	"debugProtectionInterval": false,
	"disableConsoleOutput": false,
	"log": false,
	"mangle": true,
	"renameGlobals": true,
	"rotateStringArray": false,
	"selfDefending": true,
	"stringArray": false,
	"stringArrayEncoding": false,
	"stringArrayThreshold": 0,
	"unicodeEscapeSequence": false,

	"sourceMap": true,
	"sourceMapMode": "separate"
}
```

The problem thrown by validator is:

```
Error: Warning: mismatched names
Expected: u || 'u' || 'u' || "u" || "u"
Got: w || win || win || win || win
Original Line: (function(window) {'use strict';
Mapping: 1:41484→6:10 "u" in sourceMap
```

Thanks!

**Comment by sanex3339** [comment]
I'll look into this. Can you give me small source code that will have incorrect source map after obfuscation?

**Comment by teleclimber** [comment]
Thanks.

The code block I pasted in the comment above triggers the problem in `sourcemap-validator` when obfuscated.

I tried different versions of javascript-obfuscator (0.7.0, 0.11.3 and 0.12.3) and all flunk the validator test.

I also minified some files with `uglify-es` and validated the sourcemaps using the same setup and they passed without problems.

**Comment by sanex3339** [comment]
I mean i need this code `test_files/angular.js` or something more simplier.

**Comment by teleclimber** [comment]
Yes that's what I meant. This code when obfuscated with `javascript-obfuscator` has sourcemaps that fail the validator.

```
const fs = require( 'fs' );
const javascript_obfuscator = require( 'javascript-obfuscator' );
const validator = require( 'sourcemap-validator' );

const obf_opts = require( './obf-opts.json' );

const raw = fs.readFileSync( 'test_files/angular.js', {encoding:'utf8'} );

const obf_results = javascript_obfuscator.obfuscate( raw, obf_opts );

validator( obf_results.getObfuscatedCode(), obf_results.getSourceMap(), { 'file.js': raw } );
```

Sorry, I realize it's a bit meta. 🤡

**Comment by sanex3339** [comment]
Ah, ok -)
