### ISSUE TITLE
There are random variable names exposed

### ISSUE THREAD

**Issue by chiflon** [javascript-obfuscator/javascript-obfuscator#135]
Hi guys, 
you developed an awesome tool! 
But when I'm trying to obfuscate any piece of javascript code, some random variable names were exposed. I tried many options and the result is the same.

**Comment by sanex3339** [comment]
By default all global variables without declaration will exposed.

With option `renameGlobals` - only global variables without declaration will exposed.

**Comment by chiflon** [comment]
Thank you @sanex3339 for your quick response :)
I show you an example, this code:
`a({
    x: 'info', z: {
      a: screen.width,
      b: screen.height,
      c: Math.max(window.innerWidth, document.documentElement.clientWidth, document.body.clientWidth, 0),
      d: Math.max(window.innerHeight, document.documentElement.clientHeight, document.body.clientHeight, 0),
      e: history.length,
      f: navigator.cookieEnabled,
      g: navigator.platform,
    }
  });`

Will show variables like "clienHeight" that I'd like to hide
![screenshot from 2017-11-30 12-49-20](https://user-images.githubusercontent.com/6804693/33429395-fa761f48-d5cc-11e7-87b0-93001fae30f5.png)

**Comment by sanex3339** [comment]
This is string literals. Set `stringArray` to `true` and `stringArrayThreshold` to `1`

**Comment by chiflon** [comment]
Awesome! Thank you!
And variables like document, navigator, screen... can I hide them as well?

**Comment by sanex3339** [comment]
This is variables without declaration, currently - no. But i'll work on it in the future releases.

**Comment by chiflon** [comment]
@sanex3339 great, good to know. Thank you very very much for your help!!

**Comment by sanex3339** [comment]
I can close this issue?
