### ISSUE TITLE
SyntaxError: 'super' keyword unexpected here

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/javascript-obfuscator#136]
Error with enabled `deadCodeInjection`
`SyntaxError: 'super' keyword unexpected here`

**Comment by malafaya** [comment]
That was quick! Kudos.
I will give it a shot on Monday.
Thanks.

**Comment by sanex3339** [comment]
To be clear - currently i didn't release 0.12.4 version. I'll release this weekend.

**Comment by sanex3339** [comment]
I just released `0.12.4` version.
