### ISSUE TITLE
Obfuscation takes extremely long for large files (12+ hours)

### ISSUE THREAD

**Issue by Seranth** [javascript-obfuscator/javascript-obfuscator#146]
I have a javascript file that's 24 MB big. In javascript terms, where things like jquery are about 84 KB, I would call my file above average big.

I had not issues running the obfuscation on the same file when it was just 500 KB large and I've tested running the program on the same file in both Linux and Windows.

Currently the obfuscation has been going for 12 hours, and is still going. Exactly what it's doing I don't know, but it's eating 50% of my CPU so I know it's still doing something and when it crashed once before due to Nodejs running out of memory I increased it to 6 GB and so now it's not crashing but as I said, it's been 12 hours already...

Here's the command I used (absolute paths due to my setup):
`/usr/bin/nodejs /home/$USER/Programs/emsdk/node/4.1.1_64bit/lib/node_modules/javascript-obfuscator/bin/javascript-obfuscator.js MyJavascript.js --output Build/MyJavascript.js  --compact true --controlFlowFlattening false --controlFlowFlatteningThreshold 0 --deadCodeInjection true --deadCodeInjectionThreshhold 0.1 --debugProtection true --debugProtectionInterval true --disableConsoleOutput true --log  --mangle false --renameGlobals false --rotateStringArray true --selfDefending true --sourceMap false --stringArray true --stringArrayEncoding 'rc4' --unicodeEscapeSequence false --domainLock "https://my.game.com" --sourceMapBaseUrl "https://my.game.com"`

Important thing to note here is that I've also tried running the obfuscation without any options (the above is for my release version) and it doesn't seem to make any difference.

Here's the output it's showing currently:
```
[javascript-obfuscator] Obfuscation started...

[javascript-obfuscator] Random generator seed: 229941782...

[javascript-obfuscator] Stage: preparing AST-tree...

[javascript-obfuscator] Stage: analyzing AST-tree...

[javascript-obfuscator] Stage: dead code injection...

[javascript-obfuscator] Stage: obfuscation...
```
As you can see, it's stuck at the obfuscation stage.

The source code I'm compiling is an Emscripten compiled file, which is why it's so large. I've had no issues in obfuscating code due to Emscripten, it works fine, the problem is almost definitely related to javascript-obfuscator not handling large files very well. And yes, I know the performance drops from obfuscation and that Emscripten is already very heavy for a browser to handle, but at the very least I want to disable console output, so even if I later on decide the performance drop is too big to do full obfuscation I still want javascript-obfuscator to handle disabling console output.

**Comment by sanex3339** [comment]
Can you send me this file (mail in the profile)? I'll look into this.

**Comment by Seranth** [comment]
Couldn't find your mail adress in your profile but here's a zip with the file instead:

[MyScript.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/1545496/MyScript.zip)

You won't be able to run the file since it's dependent on other files but you're free to experiment with as much as you like. My project is closed source but it's so early that the file right now is basically just Python for your browser. :)

**Comment by sanex3339** [comment]
Currently here one edge case, when obfuscation takes really long: when huge amounts of code are existing in one block scope, like in your file. This is really rare case, but i'll try to make some optimisations.

**Comment by Seranth** [comment]
Awesome :)

**Comment by sanex3339** [comment]
looks like i fixed it, now this file obfuscated in 77 seconds.

**Comment by sanex3339** [comment]
Will be ready with `0.13.0`, i think before 2018.

But you can temporary use version from `master` branch of this repository.

**Comment by Seranth** [comment]
Awesome!
I'll make a small donation to the project after the holidays :)

**Comment by sanex3339** [comment]
It it's possible, can you test that this file will correctly work after obfuscation?

**Comment by Seranth** [comment]
Works like a charm

**Comment by sanex3339** [comment]
Amazing

**Comment by Seranth** [comment]
Well I'm happy to inform you that the script is obfuscated correctly and I'm using more or less max security settings taking roughly 330 seconds to obfuscate (65 for minimum obfuscation version). 

The performance drop is a bit weird though because I see almost no difference in performance when using max and min settings. The script runs in about 8 sec unobfuscated, 16 seconds when obfuscated with minimum settings (basically just console output disabled) and 17 seconds with full on security with pretty much just mangling and control flow disabled. File size doesnt matter since I'm using a Service Worker, but it's weird that full obfuscation vs minimal obfuscation is only about 1 sec different in run time.

Still, very happy you could solve this so quickly, thanks a million. :)

**Comment by sanex3339** [comment]
`0.13.0` just released. Have a nice day!
