### ISSUE TITLE
stringArray doesn't respect condition comments

### ISSUE THREAD

**Issue by Kukunin** [javascript-obfuscator/javascript-obfuscator#147]
I try to keep one string literal AS IS without encoding while having other literals encoded with `stringArray`. Here is simple example:

```js
var a = "test";
/* javascript-obfuscator:disable */
var b = "another";
/* javascript-obfuscator:enable */

console.log(a);
console.log(b);
```

I expect `var b = "another";` to be as is in the result file, but it still encodes `"another"` into array, and I get 

```js
var _0xb752da=_0x74933d[_0xac92('0x17')];
var b=_0x74933d.vbhKc;
console[_0xac92('0x18')](_0xb752da);
console[_0xac92('0x18')](b);
```

In my case, string literal for `b` is too big, and I encoding it to stringArray making the resulting file even bigger and slower. 

Is it a bug or by design? 
Thanks for your great work!

**Comment by sanex3339** [comment]
Check your version of obfuscator, it should be 0.12.0+ version.

Here everything is OK:
https://javascriptobfuscator.herokuapp.com/

**Comment by sanex3339** [comment]
ping

**Comment by Kukunin** [comment]
Yeah, you're right. Sorry for late answer. I'm sorry for bothering

**Comment by Kukunin** [comment]
Actually, it is sensitive to `controlFlowFlattening`

with `controlFlowFlattening: false` it is `var b='another'`.

But with `controlFlowFlattening: true` it is `var b=_0x12f294.MVLge`;

**Comment by Kukunin** [comment]
I did more research. `controlFlowFlattering` doesn't affect my original code snippet as well. But does affect this snippet:

```
function my() {
    var a = "test";
    /* javascript-obfuscator:disable */
    var b = "another";
    /* javascript-obfuscator:enable */

    console.log(a);
    console.log(b);
  }
```

Originally, I run browserify before the obfuscation, so it wraps the code into a function. That caused the confusion. Sorry about that. 

The snippet above is reproducible at https://javascriptobfuscator.herokuapp.com/

**Comment by sanex3339** [comment]
Currently conditional comments affects only direct transformations.

This transformation `var b=_0x74933d.vbhKc;` - secondary transformation obtained with `controlFlowFlattening`. I'll think how to handle it.

**Comment by sanex3339** [comment]
Fixed. Will be out with 0.13.0 later this year.

**Comment by sanex3339** [comment]
Until 0.13.0 you can use version from `master` branch.

**Comment by sanex3339** [comment]
`0.13.0` just released. Have a nice day!

**Comment by Kukunin** [comment]
Thank you very much. You do very good support for the project!
