### ISSUE TITLE
Script does not work after the obfuscation

### ISSUE THREAD

**Issue by Yagun** [javascript-obfuscator/javascript-obfuscator#149]
Hi,

I found a bug in your tool.

I obfuscated this script: https://github.com/ondras/primitive.js/blob/master/js/app.js
and it does not work properly after that. (Options: compact, string array, rotate string array).

You can easily test it. Just download https://github.com/ondras/primitive.js and open index.html in your browser (it works locally, you do not need a server). Then click "Let's go!" button. It will show a test image at left and will start drawing resulting image at right.

Then obfuscate app.js (in "js" directory) and replace initial app.js. Open index.html again, click the "Let's go!" button. It will show the test image at left, but will not draw the 2nd image.

I tried both NPM javascript-obfuscator module and this UI: https://javascriptobfuscator.herokuapp.com/ . The result is the same: the obfuscation breaks the code.

This may be useful to find the bug:
You can see 10 JS files at https://github.com/ondras/primitive.js/tree/master/js/src Combined they become that app.js script. So, you can obfuscate them 1 by 1 to find the needed code.

Please fix it. Thank you!

**Comment by sanex3339** [comment]
I'll look into this.

**Comment by sanex3339** [comment]
Problem with class methods names obfuscation

**Comment by sanex3339** [comment]
Will be ready with 0.13.0

**Comment by Yagun** [comment]
Thanks a lot for the quick fix! When do you plan to release 0.13.0?

**Comment by sanex3339** [comment]
Later this year

**Comment by sanex3339** [comment]
`0.13.0` just released. Have a nice day!
