### ISSUE TITLE
return issue

### ISSUE THREAD

**Issue by akaJes** [javascript-obfuscator/javascript-obfuscator#154]
obfuscated version of this code gets undefined result of the function (used default setting of https://javascriptobfuscator.herokuapp.com/)
```
// Paste your JavaScript code here
function hi() {
  return "Hello \
	World!";
}
console.log(hi());
```

**Comment by sanex3339** [comment]
This is wrong javascript code and `esprima` parse it incorrectly.

**Comment by akaJes** [comment]
due to https://www.ecma-international.org/ecma-262/5.1/#sec-12.9
wrong if line-termination is between `return` and `expression`
but expression can has the line-terminations symbols

**Comment by sanex3339** [comment]
You can create issue in the `esprima` repository
