### ISSUE TITLE
Branded Identifier Names Generator

### ISSUE THREAD

**Issue by slig** [javascript-obfuscator/javascript-obfuscator#155]
I've got this suggestion on my mind and I'd to share with you to see if it's something you're interested in and, if so, I might try to submit a pull request.

Currently, there're two Identifier Names Generator, `hexadecimal` and `mangled` and I'd like to propose a `branded` one. Let's say my company name is `acme`, then the this new generator would return identifiers in the following order: `a`, `c`, `m`, `e`, `A`, `C`, `M`, `E`, `a1`, `c1`, `m1`, `e1`, `A1`, `C1`, etc in the same scope, resetting to `a`, `c`, `m`, `e`, etc, in every scope.

What do you think? I believe this would make it harder for people to simply re-use the code, even if they manage to remove the `selfDefending` feature.

**Comment by sanex3339** [comment]
> resetting to a, c, m, e, etc, in every scope.

This is problematic part. Currently here no way to reset identifier names for various scopes and it requires HUGE amount of work.

But in the future i'll probably add ability to set custom names generator as function for `identifierNamesGenerator` option.

**Comment by slig** [comment]
Using a custom names generator in the future would be awesome.

I can imagine that this feature won't be easy now. Thanks for replying!

**Comment by sanex3339** [comment]
Closed right now. In the future i'll think about it.
