### ISSUE TITLE
Recursive obfuscation support?

### ISSUE THREAD

**Issue by AndersonHappens** [javascript-obfuscator/javascript-obfuscator#157]
It would be nice if there was a command line flag to apply the obfuscator to a directory and all of it's sub directories. That way, I wouldn't have to call it on each folder separately.

**Comment by sanex3339** [comment]
Looks like i should make recursive directory compilation without flag like in other CLI tools like `babel`, `typescript` and others.

**Comment by sanex3339** [comment]
In 0.14.0 all directories will obfuscated recursively.

No release date - somewhere in january.

**Comment by spardue** [comment]
Hello, this would be awesome to have right about now.  Otherwise, I am going to do some shell script hacks.

**Comment by sanex3339** [comment]
I can release npm package under `beta` tag

**Comment by spardue** [comment]
Thanks a lot. 

I am a node noob but I assume the install command will look like this:

sudo npm install -g recursive-uglifyjs@beta

**Comment by sanex3339** [comment]
Yes. I published version to npm, you can install it with `npm i -g javascript-obfuscator@beta` command.
Read readme section about recursive directory obfuscation:
https://github.com/javascript-obfuscator/javascript-obfuscator#obfuscate-directory-recursively

**Comment by spardue** [comment]
Wow, good job. It obfuscated all the JS files under a directory recursively
very efficiently. Is there an option to replace the .js files with the
obfuscated contents instead of creating a -obfuscated.js file?

**Comment by sanex3339** [comment]
No and i won't do this, because it very dangerously

**Comment by spardue** [comment]
Cool, I understand. I plan on only using this command in a CI loop where the git repo is pulled daily. However, I can script that functionality. I appreciate your help.

**Comment by JahanzaibShah** [comment]
I am completely new to javaScript. Can anyone help me out how to use this : javascript-obfuscator ./dist [options] command ? my js files are in multiple folders under src/js/
I execute  "javascript-obfuscator ./src  --compact true --selfDefending true" but this command is not working. I want my all js and obfuscated files with post-fix of FILENAME-obfuscated under the same hierarchy.

**Comment by sanex3339** [comment]
> this command is not working

What version you using? Any output in the console?

**Comment by JahanzaibShah** [comment]
Nothing in console. a obfuscated folder was created in project with empty js files. I opened them and found nothing. I belief i am using 0.13.0 version. Is there any other way to do obfuscation? 

your help is much appreciated. 
Thanks alot.

**Comment by sanex3339** [comment]
Recursive directory obfuscarion - feature of 0.14.0 beta version. Try `0.14.0-beta.3` version.

**Comment by sanex3339** [comment]
out in `javascript-obfuscator@0.14.0`

**Comment by EgoPingvina** [comment]
Finally, I didn't understand, what I should write in my script to recursive directory obfuscation? I created this script in a root folder that contains folder Source with all scripts. Help please, what should I add to it?

    var JavaScriptObfuscator = require('javascript-obfuscator');

    var obfuscationResult = JavaScriptObfuscator.obfuscate(
    '/Source',
    {
        compact: true,

        controlFlowFlattening: true,
        controlFlowFlatteningThreshold: 0.75,

        deadCodeInjection: true,
        deadCodeInjectionThreshold: 0.5,

        debugProtection: true,
        debugProtectionInterval: true,
        disableConsoleOutput: true,

        identifierNamesGenerator: 'hexadecimal',

    	log: false,

    	renameGlobals: false,

        rotateStringArray: true,
        seed: new Date().getMilliseconds(),

        selfDefending: true,

        shuffleStringArray: true,

        stringArray: true,
        stringArrayEncoding: 'base64',
        stringArrayThreshold: 0.5,


    	transformObjectKeys: true,

    	unicodeEscapeSequence: false
    });
