### ISSUE TITLE
Leaking RC4 encrypted string information

### ISSUE THREAD

**Issue by stevefan1999** [javascript-obfuscator/javascript-obfuscator#159]
Just look at the generated source after obfuscation with RC4 string encryption, you can see that we have `rc4` and `rc4Bytes` and they are very dubious to malicious researchers. They cannot be obfuscated since they are prototype properties.

I was suggesting to add a symbol/identifier table for https://github.com/javascript-obfuscator/javascript-obfuscator/blob/0b48d69aeb41fa224bcaa7cd4e184827a93d4b51/src/templates/string-array-nodes/string-array-calls-wrapper/SelfDefendingTemplate.ts#L7-L46 but I doubt that would work.

**Comment by sanex3339** [comment]
This code - self defending code that wrapped in tricky dummy code. This code doesn't contain any information related to rc4-encoded strings.

**Comment by sanex3339** [comment]
out in `javascript-obfuscator@0.14.0`
