### ISSUE TITLE
obfuscating minified filed by closure-compiler?

### ISSUE THREAD

**Issue by hopewise** [javascript-obfuscator/javascript-obfuscator#163]
I have tried to obfuscate a minified file that was minified by closure-compiler, but I've noticed that the resulted obfuscated file got large again as if it wasn't minified.

How can I overcome this issue?

**Comment by sanex3339** [comment]
Obfuscared file will always larger than input source code. Chose one side)

**Comment by hopewise** [comment]
so, shall I obfuscate first,  then do minification? or what's the recommended way?

**Comment by sanex3339** [comment]
Ideally, you shouldn't touch obfuscated code after obfuscation.

**Comment by hopewise** [comment]
Do you mean that to obfuscate a minified file, I need to use the `identifierNamesGenerator: 'mangled'` option?

If so, can you please tell me how to use it in command line?

**Comment by sanex3339** [comment]
No. If you want that all identifier names in the obfuscated code will mangled - use this option. Probably you won't need to use uglify.js after that.

About command line - please read documentation.

**Comment by sanex3339** [comment]
Closed due inactivity. Please, reopen the issue if you'll have additional questions.
