### ISSUE TITLE
Suggestion: Conditional code

### ISSUE THREAD

**Issue by Seranth** [javascript-obfuscator/javascript-obfuscator#164]
Since there's already support for disabling obfuscation for pieces of code, wouldn't it be a relatively small addition to add conditional code?

I'm thinking something in the lines of:

``` javascript
var message = "";
function main () {
// # if ARG(PRODUCTION) == true
message = "Production";
// # else
message = "Development";
// # endif
alert(message)
}
```

And that code would output Production if the argument PRODUCTION is set to true, or Development if PRODUCTION is either false or unset.

The alternative right now is to use Preprocessor (https://www.npmjs.com/package/preprocessor) to create a temp file and then obfuscate that temp file, but I'd prefer it if I didn't have to involve temp file creation.

**Comment by sanex3339** [comment]
What is `production`? Global variable or node environment variable?

**Comment by Seranth** [comment]
I was thinking you could run the command like "javascript-obfuscator production=true", so "production" would be a command line argument. Another solution to the problem would be something along the lines of adding plugin support for javascript-obfuscator, so that e.g. Preprocessor could be added as an extra pre-obfuscation step. A third solution is to make it easy for javascript-obfuscator to be added as a plugin to some other program.

Of course, if it's not as easy to do as I thought then just disregard all this, I can use the temp file approach, sounds like it's less of a hassle for me to use a temp file than it is for conditional code to be added to javascript-obfuscator.

**Comment by sanex3339** [comment]
You can use obfuscator via node.js API, and write simple custom plugin that will give source code on input, than transform it with `preprocessor` and `javascript-obfuscator`.

Or look at my plugin for `webpack 2` with similar functionality.
https://github.com/sanex3339/editable-sources-webpack-plugin
