### ISSUE TITLE
Javascript-obfuscator does not work with Angular 1 

### ISSUE THREAD

**Issue by spardue** [javascript-obfuscator/javascript-obfuscator#179]
Hi,

When I run javascript-obfuscator on angular code, the code does not work. Are there any options around this?

Thanks

**Comment by sanex3339** [comment]
Hi, i need more details about configuration, angular version and other things.

**Comment by spardue** [comment]
Angular v1.4.14.

**Comment by sanex3339** [comment]
Please describe full info about obfuscator version, options and other things.
If angular thorws runtime errors - describe it.

**Comment by spardue** [comment]
javascript-obfuscator@0.13.0 (this is with the beta recursive directory function)
I did not run it with options.
Chrome does not load the app after obfuscating.

**Comment by sanex3339** [comment]
Any errors in the console?

**Comment by sanex3339** [comment]
Can you send me original and obfuscated files?

**Comment by spardue** [comment]
So I am obfuscating the core angular code. I assume that will break things (I read the doc haha)?

**Comment by sanex3339** [comment]
I tested obfuscator on the Angular 2 core and it working fine, so any errors in the console? can you send me project on that i can reproduce this erro?

**Comment by spardue** [comment]
We are using Angular 1. I can't send code at this time due to legal issues. However, I might be able to provide a simple spinet that shows the issues.

**Comment by sanex3339** [comment]
> I might be able to provide a simple spinet that shows the issues.
I'll be happy

**Comment by baichengzhou** [comment]
I'll be happy

**Comment by sanex3339** [comment]
any news?

**Comment by spardue** [comment]
Hi, I ran https://github.com/olov/ng-annotate on the files first and then
ran UgliyJS because I was directed to use it. However, I assume the same
thing would work for this tool.

On Tue, Jan 23, 2018 at 10:49 AM, Timofey Kachalov <notifications@github.com

**Comment by sanex3339** [comment]
Oh, i forgot that angular DI using constructor.toString(). So, can i close this issue?

**Comment by spardue** [comment]
Yes please
