### ISSUE TITLE
Javascript Obfuscator Web frontend - WIP

### ISSUE THREAD

**Issue by slig** [javascript-obfuscator/javascript-obfuscator#18]
Hi,

I made a web frontend using React+Redux that I intend to open-source soon.

Since there're no good free online obfuscators and lots of people have a hard time installing all the tooling needed to run this, I decided this was a good project to make and learn about React.

https://javascriptobfuscator.herokuapp.com/

I've just deployed it, so I'm sure there're bugs and lots of things to work on. Hope this can be useful or at least used to showcase your project. Currently I'm using the last stable version of your package, so the domain lock feature on the UI doesn't work.

PS: Since it's currently on the free heroku plan, the first request can take a while to process.

**Comment by sanex3339** [comment]
OMG, it's amazing!!!

**Comment by demidovakatya** [comment]
![img_2006](https://cloud.githubusercontent.com/assets/5788652/19618402/78f051d6-9852-11e6-98dc-0f70d2031183.PNG)
hey there, could you do something about this? :eyes:

**Comment by slig** [comment]
Sure, fixed it! I should've tested on small screens before.

I'm glad you liked it! If you have any suggestion of criticism, please let me know and I'll try to fix it ASAP.

**Comment by demidovakatya** [comment]
@slig wow, now that looks awesome. I'd add a couple of links to the top part of the page:

![i 2016-10-23 at 05 25 45](https://cloud.githubusercontent.com/assets/5788652/19623757/2d8abc10-98e1-11e6-92bf-edd210563212.png)

p.s. @sanex3339 are you going to further develop your project? I know you are, but I'm talking about, like, _exponential growth_ and doing serious bussiness.:D 
I suggest you create an organization – so the obfuscator and the website source code would be in one place (and some new repos as well, I hope 😸).

**Comment by sanex3339** [comment]
@demidovakatya https://github.com/JavaScript-Obfuscator

**Comment by sanex3339** [comment]
So, i can add @slig to organisation and he can add repo for his Web UI

**Comment by slig** [comment]
Added the repo to the organisation https://github.com/javascript-obfuscator/javascript-obfuscator-ui

I also submitted the project's URL to a React examples website and added a link to it on the React's Wiki page.

**Comment by slig** [comment]
@demidovakatya added the links as you suggested.

**Comment by slig** [comment]
Updated the frontend to use the 0.8.0-beta.1 release.

**Comment by sanex3339** [comment]
Please update frontend to 0.8.0 version

**Comment by slig** [comment]
Done!

**Comment by sanex3339** [comment]
Please update frontend to 0.8.1 version

**Comment by slig** [comment]
Done!

**Comment by sanex3339** [comment]
Please update frontend to 0.8.2 version.
New `seed` option is added.

**Comment by slig** [comment]
Updated to 0.8.2.

Do you think it's worth to add a field do enter the `seed` on the UI? Or maybe set it to a fixed number?

**Comment by sanex3339** [comment]
I think it is better to add field to ui with 0 value (cast it to number).  With value 0 seed is disabled

**Comment by slig** [comment]
Added the  `seed` field to the UI.

**Comment by sanex3339** [comment]
`0.8.3` Is out. Only change - `selfDefending` now disabled by default.

**Comment by slig** [comment]
Updated to `0.8.3` and the new default. Please note that since the last used options are stored on `localStorage`, current users will continue to see whatever options they last used, only new users will see the `selfDefending` unchecked by default.

**Comment by sanex3339** [comment]
It's not a problem, thank you.

**Comment by sanex3339** [comment]
I updated version to `0.8.5` with two bugfixes

**Comment by sanex3339** [comment]
I updated version to 0.8.6

**Comment by slig** [comment]
Heroku is returning some strange error now as I try to push the code there. Will investigate tomorrow.

**Comment by slig** [comment]
Updated to 0.8.6. Ended up removing `fsevents` from the devDependency as it looks like the latest yarn has a issue with it. Will try to add again in the future.

**Comment by sanex3339** [comment]
Please update frontend to 0.9.0 version.
Two new options

`controlFlowFlattening: false` boolean
`controlFlowFlatteningThreshold: 0.75` number `0-1`

**Comment by slig** [comment]
Sorry for the delay. Updated the UI.

I've written a small text trying to explain the Control Flow feature. Please see if I understood it right.

**Comment by sanex3339** [comment]
Hmm, no.

Control flow flattening doing two type of transformations right now (possible more in the future):
1) collects all Binary (1 + 1), Logical (foo === true) and Call (Foo()) expressions, places it into special objects in function, and instead original expression, puts call to this function.

For example for binary expression `var foo = 1 + 2` object will be like:
```
var _0xabc123 = {
   'randomKey': function (a, b) {
        return a + b;
    }
}
```

and call will be like:
```
var foo = _0xabc123['randomKey'](1, 2);
```

Same with logical and call expressions.

2) Finds all statements inside Block Statement, shuffles them and replaces them by while loop with switch-case statement inside, each case for each statement.

original
```
(function(){
    function foo () {
        return function () {
            console.log(1);
            console.log(2);
            console.log(3);
            console.log(4);
            console.log(5);
            console.log(6);
        }
    }
})();
```

transformed:
```
// output
(function () {
    function _0x425898() {
        return function () {
            var _0x170490 = '\x35\x7c\x34\x7c\x33\x7c\x32\x7c\x30\x7c\x36\x7c\x31'['\x73\x70\x6c\x69\x74']('\x7c'), _0x4f3437 = 0x0;
            while (!![]) {
                switch (_0x170490[_0x4f3437++]) {
                case '\x30':
                    console['\x6c\x6f\x67'](0x4);
                    continue;
                case '\x31':
                    console['\x6c\x6f\x67'](0x6);
                    continue;
                case '\x32':
                    console['\x6c\x6f\x67'](0x3);
                    continue;
                case '\x33':
                    console['\x6c\x6f\x67'](0x2);
                    continue;
                case '\x34':
                    console['\x6c\x6f\x67'](0x1);
                    continue;
                case '\x36':
                    console['\x6c\x6f\x67'](0x5);
                    continue;
                }
                break;
            }
        };
    }
}());
```

So, i think better solution just to copy description from readme 
https://github.com/javascript-obfuscator/javascript-obfuscator#controlflowflattening

Also, i will very happy if you will put `controlFlowFlattening` option to the left side of form, because it is one of the main features, thank you!

**Comment by slig** [comment]
Thanks for reviewing!

> So, i think better solution just to copy description from readme
https://github.com/javascript-obfuscator/javascript-obfuscator#controlflowflattening

Will do.

> Also, i will very happy if you will put controlFlowFlattening option to the left side of form, because it is one of the main features, thank you!

Of course. Where do you want to place this feature? Just let me know the position you want and I'll re-arrange.

**Comment by sanex3339** [comment]
Something like that:
![image](https://cloud.githubusercontent.com/assets/9210534/22486176/87cd7618-e819-11e6-8f17-0c874bbcfd14.png)

**Comment by slig** [comment]
Done. See if there's anything you'd like to change.

**Comment by sanex3339** [comment]
wow, i like new domain name

**Comment by slig** [comment]
> wow, i like new domain name

Hi, I did not change anything. What do you mean?

**Comment by sanex3339** [comment]
http://javascript-obfuscator.org/

**Comment by slig** [comment]
Ah, that's not mine. Someone is hosting the code. Unfortunately they copied all the text and Google will probably punish them for content copy.

**Comment by sanex3339** [comment]
Domain Name: JAVASCRIPT-OBFUSCATOR.ORG
Registry Domain ID: D402200000002086504-LROR
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: http://www.namecheap.com
Updated Date: 2017-04-17T12:24:16Z
Creation Date: 2017-04-17T12:24:14Z
Registry Expiry Date: 2018-04-17T12:24:14Z
Registrar Registration Expiration Date:
Registrar: NameCheap, Inc.
Registrar IANA ID: 1068
Registrar Abuse Contact Email: abuse@namecheap.com
Registrar Abuse Contact Phone: +1.6613102107
Reseller:
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
Domain Status: serverTransferProhibited https://icann.org/epp#serverTransferProhibited
Domain Status: addPeriod https://icann.org/epp#addPeriod
Registry Registrant ID: C191991423-LROR
Registrant Name: WhoisGuard Protected
Registrant Organization: WhoisGuard, Inc.
Registrant Street: P.O. Box 0823-03411
Registrant City: Panama
Registrant State/Province: Panama
Registrant Postal Code: 0
Registrant Country: PA
Registrant Phone: +507.8365503
Registrant Phone Ext:
Registrant Fax: +51.17057182
Registrant Fax Ext:
Registrant Email: 7ee1d595ab4d40d38bf839854e05273a.protect@whoisguard.com
Registry Admin ID: C191991426-LROR
Admin Name: WhoisGuard Protected
Admin Organization: WhoisGuard, Inc.
Admin Street: P.O. Box 0823-03411
Admin City: Panama
Admin State/Province: Panama
Admin Postal Code: 0
Admin Country: PA
Admin Phone: +507.8365503
Admin Phone Ext:
Admin Fax: +51.17057182
Admin Fax Ext:
Admin Email: 7ee1d595ab4d40d38bf839854e05273a.protect@whoisguard.com
Registry Tech ID: C191991425-LROR
Tech Name: WhoisGuard Protected
Tech Organization: WhoisGuard, Inc.
Tech Street: P.O. Box 0823-03411
Tech City: Panama
Tech State/Province: Panama
Tech Postal Code: 0
Tech Country: PA
Tech Phone: +507.8365503
Tech Phone Ext:
Tech Fax: +51.17057182
Tech Fax Ext:
Tech Email: 7ee1d595ab4d40d38bf839854e05273a.protect@whoisguard.com
Name Server: DNS1.REGISTRAR-SERVERS.COM
Name Server: DNS2.REGISTRAR-SERVERS.COM

**Comment by slig** [comment]
Hey @sanex3339 , I sent you a PM on reddit.

**Comment by sanex3339** [comment]
Check your email

**Comment by sanex3339** [comment]
I'll close this issue. For any improvements related to web UI i'll make issue in `javascript-obfuscator-ui` repo.
