### ISSUE TITLE
Problem with multi-line template literals

### ISSUE THREAD

**Issue by rustyblack** [javascript-obfuscator/javascript-obfuscator#181]
Hi, great project. Noticed an obscure bug, though:

Template literals starting with whitespace and containing a newline will sometimes confuse the obfuscator. For example:

    function hi() {
        return ` Hello
	        There`;
    }

This gets obfuscated into:

    function hi() {
        return;
        '\x20Hello\x0a\x09There';
    }

Note that the `return` got separated from the literal, so the obfuscated function returns nothing.

The same thing happens if the backtick is immediately followed by a newline, e.g.:

    function hi() {
        return `
            Hello There
        `;
    }

**Comment by sanex3339** [comment]
Related with `esprima`.
http://esprima.org/demo/parse.html?code=function%20hi()%20%7B%0A%20%20%20%20return%20%60%20Hello%0A%20%20%20%20%20%20%20%20There%60%3B%0A%7D

**Comment by sanex3339** [comment]
Same problem as here:
https://github.com/jquery/esprima/issues/1897

Fixed here:
https://github.com/jquery/esprima/commit/9973bab92f824db9ed44ae8931a8890309f2322b

But no release with fix yet.

**Comment by sanex3339** [comment]
You can request faster release here:
https://github.com/jquery/esprima/pull/1882

**Comment by sanex3339** [comment]
So, i think i will temporary fix it from my side by correcting wrong AST tree

**Comment by sido420** [comment]
any ETA on our side? I've pinged on esprima already.

**Comment by sanex3339** [comment]
this week

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/192

**Comment by sanex3339** [comment]
Fixed in `javascript-obfuscator@0.14.1`

**Comment by sanex3339** [comment]
With following source code still wrong obfuscated code:
```
function foo () {
	return`foo
bar` + 1;
}
```

**Comment by sido420** [comment]
yep, nothing changed it seems );

**Comment by sanex3339** [comment]
0.14.1 fixed template literals without additional expressions, like example in the first message

**Comment by sanex3339** [comment]
Fixed. Expect release in a hour or so.

**Comment by sanex3339** [comment]
Should be fixed in `javascript-obfuscator@0.14.2`

**Comment by bipinacellere** [comment]
it's not working with following syntax
sql_query = `select * from blahblah where myids in (${ids.map(d=>`'${d}'`).join(',')})
                                ${projectWhere}
                                `;

**Comment by sanex3339** [comment]
Hi, please format your code, looks like formatting is wrong.

**Comment by bipinacellere** [comment]
Actual code
```
sql_query = `select * from sub JOIN ps   ON 
sub.subsystem_id=ps.subsystem_id
                                JOIN project ON project.id = ps.project_id
                                where sub.subsystem_uid in (${ids.map(d=>`'${d}'`).join(',')})
                                ${otherWhere}
                                `;
```

**Comment by sanex3339** [comment]
Created issue: https://github.com/javascript-obfuscator/javascript-obfuscator/issues/288
