### ISSUE TITLE
Cocos game gets stuck after obfuscation (related to transformation of this._super)

### ISSUE THREAD

**Issue by riverstrong** [javascript-obfuscator/javascript-obfuscator#182]
with following options with 0.13.0 -

compact: false,
controlFlowFlattening: false,
deadCodeInjection: false,
debugProtection: false,
debugProtectionInterval: false,
disableConsoleOutput: false,
log: false,
mangle: false,
renameGlobals: false,
rotateStringArray: false,
selfDefending: false,
stringArray: false,
unicodeEscapeSequence: false

my game is still changed and gets stuck at asset loading. Game is made using cocos creator 1.6.1

**Comment by riverstrong** [comment]
The game freezes at loading. Here’s the error:
Uncaught TypeError: this[_0x38cd(...)] is not a function
at CCClass.show (cdn-h5turbo21-dev.pogospike.com/222/src/project.js:1)
at CCClass.start (cdn-h5turbo21-dev.pogospike.com/222/src/project.js:1)
at CCClass.eval [as _invoke] (eval at o (cdn-h5turbo21-dev.pogospike.com/222/cocos2d-js-min.js:1), :3:65)
at CCClass.invoke (cdn-h5turbo21-dev.pogospike.com/222/cocos2d-js-min.js:1)
at CCClass.startPhase (cdn-h5turbo21-dev.pogospike.com/222/cocos2d-js-min.js:1)
at e.mainLoop (cdn-h5turbo21-dev.pogospike.com/222/cocos2d-js-min.js:1)
at t (cdn-h5turbo21-dev.pogospike.com/222/cocos2d-js-min.js:1)

After checking the code, the original code is:
show:function(t,e,n,i){this._super(t,n,i),this.text2.string=e} 

As this._super is transformed, the code gets stuck.

Any may to escape the transformation by adding reserved name? We tried the following regular expression but it doesn't work:    '/\b\._super\b/'

**Comment by sanex3339** [comment]
Hi, update obfuscator version to 0.13.0.

Also, all common transformations are don't depend on options.

**Comment by riverstrong** [comment]
already 0.13.0, same issue occurs

**Comment by sanex3339** [comment]
I need minimal source code that will help me to reproduce this error

**Comment by sanex3339** [comment]
Also, you using `eval`. Eval obfuscation was added to 0.14.0 beta version.

Can you try to install and use `0.14.0-beta.3` version?

**Comment by riverstrong** [comment]
preparing the minimal code and trying the 0.14.0

**Comment by riverstrong** [comment]
[ObfuscatorTest.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/1672718/ObfuscatorTest.zip)

Mini source uploaded in attachment. You can see this._super is missing after obfuscation.

**Comment by sanex3339** [comment]
I check your example and it this._super is present in the code:

```
require = function e(_0x433933, _0x166238, _0x1c989e) {
    function _0x50b753(_0x500905, _0x1f1e9c) {
        if (!_0x166238[_0x500905]) {
            if (!_0x433933[_0x500905]) {
                var _0x277cfc = 'function' == typeof require && require;
                if (!_0x1f1e9c && _0x277cfc) {
                    return _0x277cfc(_0x500905, !0x0);
                }
                if (_0x17b171) {
                    return _0x17b171(_0x500905, !0x0);
                }
                var _0x710985 = new Error('Cannot\x20find\x20module\x20\x27' + _0x500905 + '\x27');
                throw _0x710985['code'] = 'MODULE_NOT_FOUND', _0x710985;
            }
            var _0x5f525c = _0x166238[_0x500905] = {
                'exports': {}
            };
            _0x433933[_0x500905][0x0]['call'](_0x5f525c['exports'], function(_0x4a12ae) {
                var _0x166238 = _0x433933[_0x500905][0x1][_0x4a12ae];
                return _0x50b753(_0x166238 || _0x4a12ae);
            }, _0x5f525c, _0x5f525c['exports'], e, _0x433933, _0x166238, _0x1c989e);
        }
        return _0x166238[_0x500905]['exports'];
    }
    var _0x17b171 = 'function' == typeof require && require;
    for (var _0x5e3cd5 = 0x0; _0x5e3cd5 < _0x1c989e['length']; _0x5e3cd5++) {
        _0x50b753(_0x1c989e[_0x5e3cd5]);
    }
    return _0x50b753;
}({
    'base': [
        function(_0x57c0e4, _0x1f3f3b, _0x176122) {
            'use strict';
            cc['_RF']['push'](_0x1f3f3b, '17e38P1TZZJboTjWusAxdj+', 'base');
            'use\x20strict';
            cc['Class']({
                'extends': cc['Component'],
                'show': function show(_0x4b5b51) {
                    console['log'](_0x4b5b51);
                }
            });
            cc['_RF']['pop']();
        },
        {}
    ],
    'child': [
        function(_0x408586, _0x292d5c, _0x11b3e4) {
            'use strict';
            cc['_RF']['push'](_0x292d5c, 'a6272WuadpC2ra3viD3yH82', 'child');
            'use\x20strict';
            var _0x4cbc7c = _0x408586('base');
            cc['Class']({
                'extends': _0x4cbc7c,
                'show': function show(_0x18bdf5) {
                    this['_super'](_0x18bdf5);
                }
            });
            cc['_RF']['pop']();
        },
        {
            'base': 'base'
        }
    ]
}, {}, [
    'base',
    'child'
]);
```

**Comment by sanex3339** [comment]
So firstly, you can debug - what inside `this._super` property.

**Comment by riverstrong** [comment]
Thanks for the update, we are checking if we can replace the _super function after the project.js is obfuscated with option stringArray=false.

**Comment by sanex3339** [comment]
Hi, any news?

**Comment by riverstrong** [comment]
Hi, we've removed all this._super() calls as it's not a best practice. Thanks for the follow up.

**Comment by sanex3339** [comment]
Can i close this issue?

**Comment by sanex3339** [comment]
Closed, reopen this issue if problem will happen again

**Comment by KimJuHeok** [comment]
It occures in 0.18.1 it saids "this[_0x123f(...)] is not a function". Did you solve these problems?

**Comment by KimJuHeok** [comment]
I found a solution for " this["_super"]() is not a function error ". You just change the function to this._super() then it all works well .
