### ISSUE TITLE
Adobe JSX Issue

### ISSUE THREAD

**Issue by pieczorx** [javascript-obfuscator/javascript-obfuscator#183]
Self defending gives the following error after executing in Adobe JSX.
![image](https://user-images.githubusercontent.com/14796199/35584908-b7a348b2-05f6-11e8-9ccb-e90b03da7134.png)

Used this code:
function test() {
	alert('hello');
}

**Comment by sanex3339** [comment]
Hi, can you show obfuscated code?

**Comment by sanex3339** [comment]
Looks like obfuscated code modified by adobe JSX and this triggers self defending mechanism.

**Comment by pieczorx** [comment]
Yup, that might be this. Obfuscated code works fine in browser but I don't know exactly the way JSX handles the code. So this issue is probably not related with javascript-obfuscator.

**Comment by sanex3339** [comment]
Can i close this issue?

**Comment by pieczorx** [comment]
Yes, thank you for your help :)
