### ISSUE TITLE
NodeJS shebang (#!) line issue

### ISSUE THREAD

**Issue by bouchezb** [javascript-obfuscator/javascript-obfuscator#185]
Hi,

I tried to use obfuscator on my project and got an issue with a shebang line
```
#!/usr/bin/env node
```
This is not a javascript comment line and i can't disable obfuscator on it with a comment
```
// javascript-obfuscator:disable
```
because it needs to be at first line.
How can i deal with ?
I think i may delete it before obfuscator runs and inject it after processing my file.

Thanks.

**Comment by sanex3339** [comment]
Hi. Obfuscator works with a valid JS code, so 

> I think i may delete it before obfuscator runs and inject it after processing my file.

you can do this.

**Comment by sanex3339** [comment]
So, shebang doesn't handled by `esprima`, you need to cutoff it before obfuscation.
https://github.com/jquery/esprima/issues/1151

**Comment by sanex3339** [comment]
In the upcoming 0.15.0 i'll switch `esprima` on `acorn` and hashbang will parse correctly

**Comment by sanex3339** [comment]
I was wrong, it won't working as expected with `acorn`. And for some other reasons i will switch from `esprima` on `espree`, so no shebang support.

**Comment by sanex3339** [comment]
Will supported in the upcoming `0.26.0`. Will release it tomorrow.
