### ISSUE TITLE
Nodejs project obfuscation and bundling

### ISSUE THREAD

**Issue by sido420** [javascript-obfuscator/javascript-obfuscator#188]
Can this obfuscator be used with pkg or nexe etc? 

Or, can it replace them to easily put all NodeJS project JS files together and later create an executable from it?

Can you share an example please?

**Comment by sanex3339** [comment]
Please, read the documentation. You can obfuscate directory recursively.

**Comment by sido420** [comment]
I've been trying to use directory based obfuscation but keep hitting the esprima.js err, which (after looking at other issues) I believe is related to some JS error in code. However, out of the hundreds of files that I have there is no easy way to figure out where the issue lies.

Unless I missed it, we need an --exclude parameter that lets you exclude some paths, scripts from obfuscation which helps ignore unnecessary files/directories and also help narrow down the issue in large code bases.

In the meantime, what would you suggest to solve this kind of problem?

**Comment by sanex3339** [comment]
I'll try to add `exclude` option in 0.15.0

**Comment by sanex3339** [comment]
> I've been trying to use directory based obfuscation but keep hitting the esprima.js err, which (after looking at other issues) I believe is related to some JS error in code. However, out of the hundreds of files that I have there is no easy way to figure out where the issue lies.

In master branch i just added logging of each obfuscated file name during CLI obfuscation.

**Comment by sanex3339** [comment]
Expect release with `exclude` option in the next week.

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/205

**Comment by sanex3339** [comment]
You can try `--exclude` option in `master` branch.

It accepts comma-separated list of globs, file paths, file names or directory paths.

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.15.0` just published to the npm!

Check `--exclude` CLI option
