### ISSUE TITLE
Reproducible bug found during obfuscation

### ISSUE THREAD

**Issue by sido420** [javascript-obfuscator/javascript-obfuscator#191]
Copy and paste the following code at https://javascriptobfuscator.herokuapp.com/ and run with compact code setting enabled. 
In the output you'll notice that TestFunc() call returns nothing since it puts a semi colon before the returned string.

```
function TestCaller(){
 console.log(TestFunc()); 
}

//
function TestFunc(id) {
    return `This is a 
${id ? 'id' : 'no id'} 
test string`;
}// Testfunc

TestCaller();
```

Any quick workarounds so I could proceed with my build process?

**Comment by sido420** [comment]
Please note that it still appears even if you selectively disable obfuscation (using comments) for affected part of the code. 

It might be show stopper if (like my case) backticks are used extensively.

**Comment by sanex3339** [comment]
Dublicate
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/181

**Comment by sanex3339** [comment]
Please, continue discussion in #181

**Comment by sanex3339** [comment]
So, i think i will temporary fix it from my side by correcting wrong AST tree
