### ISSUE TITLE
Old FF: `ReferenceError: _0xXXXXXX is not defined`

### ISSUE THREAD

**Issue by irudoy** [javascript-obfuscator/javascript-obfuscator#195]
Sometimes, everything breaks down in the Firefox, with an error `ReferenceError: _0x143f35 is not defined`, for example. Reproduces in Firefox 43.0 and other versions maybe.

The last time the problem was there:
`ReferenceError: _0x143f35 is not defined`
```javascript
if (/* (...) */ false) {
    // (...)
} else {
    var _0x2c7b7e = _0xe6bc0b[_0xef93('0xa6')](_0x1342f8, 1);
    var _0x5d86a1 = _0xe6bc0b[_0xef93('0xa7')](_0x143f35, _0x2c7b7e);
    var _0x160cc7 = _0x1342f8(3);
    var _0xd745f9 = _0xe6bc0b[_0xef93('0xa7')](_0x143f35, _0x160cc7);
    function _0x143f35(_0x3bedbb) {
        return _0x3bedbb && _0x3bedbb[_0xef93('0x103')] ? _0x3bedbb : {
            'default': _0x3bedbb
        };
    }
    // (...)
}
```

Seems like this piece of code was obfuscated incorrectly:
```javascript
// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
```

Relative:
https://gist.github.com/spjwebster/1074866/b217e429701bff1f5990e34bfd00c249b6f7859a
https://stackoverflow.com/questions/29812849/firefox-function-hoisting-error

My config:
```javascript
{
    compact: true,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 0.75,
    deadCodeInjection: true,
    deadCodeInjectionThreshold: 0.3,
    debugProtection: false,
    disableConsoleOutput: false,
    log: false,
    identifierNamesGenerator: 'hexadecimal',
    renameGlobals: false,
    reservedNames: [],
    seed: 1,
    selfDefending: false,
    stringArray: true,
    rotateStringArray: true,
    stringArrayEncoding: true,
    stringArrayThreshold: 1,
    target: 'browser',
    unicodeEscapeSequence: true,
    transformObjectKeys: true,
}
```

**Comment by sanex3339** [comment]
Interesting behaviour with firefox

**Comment by irudoy** [comment]
@sanex3339 can we prevent hoisting in blocks?

**Comment by sanex3339** [comment]
```
// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
```

Code above is not the same as obfuscated code. Can you try to find source of the obfuscated code by finding expressions with `3` number?

```
_0x1342f8(3);
```

**Comment by sanex3339** [comment]
But at first look - this wont work because of firefox scope hoisting inside block scopes bug and dead code injection that wrapping all block statements into `if () {} else {}` statements, so after wrapping this bug will happen.

**Comment by sanex3339** [comment]
I like this bug, very interesting behaviour.

**Comment by sanex3339** [comment]
So, until fix you can just disable `deadCodeInjection` option

**Comment by irudoy** [comment]
It will be great, if there is any solution. Anyway, thanks for the quick response!
For now, I changed `deadCodeInjectionThreshold` slightly. It will work until the next changes in source.

**Comment by sanex3339** [comment]
Can you test version from `master` branch with fix?

**Comment by irudoy** [comment]
@sanex3339 unfortunately, still reproduces

```javascript
if (_0x382204[_0xef93('0x1cb')](_0x382204[_0xef93('0x1f0')], _0xef93('0xaa'))) {
    var _0x22f86f = _0x382204[_0xef93('0x1f1')](_0x4e4ff5, 0x1);
    var _0x202f36 = _0x382204[_0xef93('0x1f1')](_0x1426cc, _0x22f86f);
    var _0x20f66e = _0x4e4ff5(0x3);
    var _0x78c491 = _0x382204[_0xef93('0x1f2')](_0x1426cc, _0x20f66e);
    function _0x1426cc(_0x3a2264) {
        return _0x3a2264 && _0x3a2264[_0xef93('0x24')] ? _0x3a2264 : { 'default': _0x3a2264 };
    }
    ...
}
```

**Comment by sanex3339** [comment]
Looks like i know what is the problem after previous fix.

**Comment by sanex3339** [comment]
Yep, fixed it. I'll push it into master in 30 minutes.

**Comment by sanex3339** [comment]
Please, try again

**Comment by irudoy** [comment]
Works just fine. Thank you!
Waiting for release 😄

**Comment by sanex3339** [comment]
I'll release it today or tomorrow

**Comment by sanex3339** [comment]
I'll reopened it until release

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.14.3` just out

**Comment by 1-Imperialdramon-1** [comment]
Hi, I have same error. 
Now I'm using javascript-obfuscator 0.14.3, and I'm still getting error.

I tried using:
        deadCodeInjection: false
        mangle: false
and the problem still occurs.

My configuration now is: 

        selfDefending: false,
        stringArrayEncoding: true,
        stringArrayThreshold: 1,
        deadCodeInjection: false,
        mangle: false


Can you give me a hand? I really need it.

**Comment by sanex3339** [comment]
Show me your part of source code and obfuscated code where this error was triggered.

**Comment by 1-Imperialdramon-1** [comment]
Hi @sanex3339,

sure, I just created the new issue: https://github.com/javascript-obfuscator/javascript-obfuscator/issues/207

Thanks in advance.
