### ISSUE TITLE
Can't disable stringArray on 0.8.0-dev.4

### ISSUE THREAD

**Issue by slig** [javascript-obfuscator/javascript-obfuscator#20]
Hi,

I'm trying to have stringArray disabled, and I'm getting my strings in the array no matter what. Here's how I'm running it:

    ./node_modules/javascript-obfuscator/bin/javascript-obfuscator.js file.js --stringArray false --selfDefending false --compact false --disableConsoleOutput false

Running it on:

    (function(){
        var variable = 'abc';
        console.log(variable);
    })();

Gives me:

    var _0x157f = ['\x61\x62\x63'];
    (function (_0x4757bc, _0x5f5a80) {
        var _0x53eef6 = function (_0x452baf) {
            while (--_0x452baf) {
                _0x4757bc['\x70\x75\x73\x68'](_0x4757bc['\x73\x68\x69\x66\x74']());
            }
        };
        _0x53eef6(++_0x5f5a80);
    }(_0x157f, 0x1c7));
    var _0x4c25 = function (_0x223bc3, _0x47330e) {
        var _0x223bc3 = parseInt(_0x223bc3, 0x10);
        var _0x40d778 = _0x157f[_0x223bc3];
        return _0x40d778;
    };
    (function () {
        var _0x29647c = _0x4c25('0x0');
        console['\x6c\x6f\x67'](_0x29647c);
    }());

I'm having the same trouble using the API. I must have been missing something.

Thanks!

**Comment by sanex3339** [comment]
Strange,  all tests runs fine.  I will look into this tomorrow.

**Comment by sanex3339** [comment]
Cannot reproduce.

CLI options exactly as this issue.

My input:
```
(function(){
    var variable = 'abc';
    console.log(variable);
})();
```

Output code:
```
(function () {
    var _0x19cac9 = '\x61\x62\x63';
    console['\x6c\x6f\x67'](_0x19cac9);
}());
```

**Comment by sanex3339** [comment]
Ah

**Comment by sanex3339** [comment]
Update to latest `javascript-obfuscator@beta`. I renamed `unicodeArray` to `stringArray` in 0.8.0-beta.1

**Comment by slig** [comment]
Thanks, Timofey! Sorry for wasting your time. I should've read with more attention the releases page.
