### ISSUE TITLE
cli throwing error "TypeError: undefined is not a function"

### ISSUE THREAD

**Issue by ReverseLogicSocial** [javascript-obfuscator/javascript-obfuscator#201]
I installed javascript-obfuscator as:

$ npm install --save-dev javascript-obfuscator

I cd into node_modules/javascript-obfuscator/

I ran the following command:
$ ./bin/javascript-obfuscator webpack.config.js --output webpack.config.test

I throws an error :: TypeError: undefined is not a function
![screen shot 2018-02-19 at 22 59 38](https://user-images.githubusercontent.com/20514062/36390577-9522fbce-15c9-11e8-8eb9-dbc34b6484df.png)

**Comment by sanex3339** [comment]
If you using obfuscator as CLI - install it globally with -g flag.

Also show me your node version, obfuscator version and full error log (line above `Type error`)

**Comment by ReverseLogicSocial** [comment]
1/How do I install gloablly? 
2/Please see the SS
![screen shot 2018-02-20 at 13 38 18](https://user-images.githubusercontent.com/20514062/36413217-6b2ad1f0-1643-11e8-80b5-998591c8b9d1.png)
3/I am using this tool outside of node.(frankly I am not using node, I only used it to fetch the package, that's it)
Still here is what you asked::
$node --version
v0.12.7
I  did javascript-obfuscator --version I got the same error, as attached in screen shot.
Now I did this to fetch the version::
$ cat package.json (inside ~.../node_modules/javascript-obfuscator)
{
...
"version": "0.14.3",
...
}

**Comment by sanex3339** [comment]
You using very old version of the node.js that not supported by obfuscator.
Install latest LTS version of the node.js.

You can install obfuscator globally with following command:
`npm i -g javascript-obfuscator`
