### ISSUE TITLE
Web version?

### ISSUE THREAD

**Issue by SuperOP535** [javascript-obfuscator/javascript-obfuscator#203]
I'd like to use this script in a browser without using a server, like <script src etc..

Is there a web version?

**Comment by sanex3339** [comment]
No and it not planned.

**Comment by SuperOP535** [comment]
Why not :(

**Comment by sanex3339** [comment]
Because it contains many node packages and final bundle will have very large size, also this packages may not work in the browser environment, also i don't want to support multiple project versions (for node and for browser).

Use existing tools: browser UI, CLI or node API

**Comment by sanex3339** [comment]
Hi. Check this
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/251

**Comment by SuperOP535** [comment]
Awesome!
