### ISSUE TITLE
not working on ios9 safari 

### ISSUE THREAD

**Issue by darkworks** [javascript-obfuscator/javascript-obfuscator#208]
i have obfuscated some js code with : https://javascriptobfuscator.herokuapp.com/

but it not work on iphone ios9 safari browser : https://www.useotools.com/hex-encoder

work from dekstop but not work on safari ,

**Comment by sanex3339** [comment]
I need more details. If there any errrors or something else.

**Comment by darkworks** [comment]
hmmm sorry ios safrari do not have developers tools like dekstops browsers where we can see errors etc , its just that i found that its not working on ios builtin safari browser on my iphone , i will search any tool on cydia if could catch safari error logs

**Comment by sanex3339** [comment]
You can debug ios safari, for example, via xcode ios simulator (on mac)

**Comment by sanex3339** [comment]
Also you can create minimal example that will trigger this error and i'll test it on my mac yourself.

**Comment by darkworks** [comment]
i have windows machine so cant capture error log because apple i think stopped safari development for windows : this maybe helpful : https://stackoverflow.com/questions/26014850/debugging-mobile-safari-in-ios-8-and-ios-9

to reproduce the error please visit on ios safari : [https://www.useotools.com/hex-encoder](url)

click on sample data button it will add simple text to text area then click on Encode button it should produce error in console ,   on chrome desktop its working show output of tool but when you press encode button on ios safar it not work 

thanks

**Comment by sanex3339** [comment]
Without obfuscation everything is ok?

**Comment by sanex3339** [comment]
I'll check it this weekend

**Comment by darkworks** [comment]
ya without obfuscation it works , 

thanks

**Comment by sanex3339** [comment]
Tried to test it on `ios simulator` with `ios9` but for some reason `safari` browser on my mac didn't see `safari` browser in simulator.

**Comment by darkworks** [comment]
ya i tried on my windows machine too , but same issue safari not detected

**Comment by sanex3339** [comment]
So. The error is `es6 default parameter value` error
```
SyntaxError: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration.
```
In this function:
```
function prepare_blob(_0x13b949, _0x38c7d2=![]) {
    var _0x19b1a9 = null;
    var _0x5a6a40 = '';
    if (_0x38c7d2 === !![]) {
        if (_0x4ceb('0x47', 'pcsE') !== _0x4ceb('0x48', 'LQd3')) {
            for (var _0x1ad202 = 0x0; _0x1ad202 < _0x13b949[_0x4ceb('0x49', 'uN!!')]; _0x1ad202++) {
                _0x5a6a40 = _0x5a6a40 + _0x13b949[_0x1ad202] + '\x0d\x0a';
            }
        } else {
            var _0x16e852 = unescape(encodeURIComponent(_0x13b949[i]));
            for (var _0x3796cb = 0x0; _0x3796cb < _0x16e852[_0x4ceb('0x4a', 'txLU')]; _0x3796cb++) {
                bytes[_0x4ceb('0x4b', 'U$HH')](_0x16e852[_0x3796cb][_0x4ceb('0x4c', 'XEHO')](0x0));
            }
        }
    } else {
        _0x5a6a40 = _0x13b949;
    }
    var _0x3f21fc = new Blob([_0x5a6a40], {
        'type': _0x4ceb('0x4d', '0ZPj')
    });
    if (_0x19b1a9 !== null) {
        window['URL']['revokeObjectURL'](_0x19b1a9);
    }
    _0x19b1a9 = window[_0x4ceb('0x4e', 'MyTJ')]['createObjectURL'](_0x3f21fc);
    return _0x19b1a9;
}
```

So, looks like even without obfuscation you should get this error.

**Comment by darkworks** [comment]
hmmmm ya looks like you right
