### ISSUE TITLE
Error if there is an "Import" statement at the beginning of js file

### ISSUE THREAD

**Issue by mvpkreddy** [javascript-obfuscator/javascript-obfuscator#210]
I am receiving an error if the js file consists of import statement. For example, here is the content of the test.js file:

```
import { test1} from "./test1";

window.onload = () => {
console.log("Test");
};
```
command executed: javascript-obfuscator test.js --compact true

Here is the error received:

Error: Line 1: Unexpected token
    at Function.value (C:\Users\pavma\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\index.js:24:270611)
    at Function.value (C:\Users\pavma\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\index.js:24:270464)
    at e.value (C:\Users\pavma\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\index.js:24:266641)
    at e.value (C:\Users\pavma\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\index.js:24:266398)
    at Function.value (C:\Users\pavma\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\index.js:24:28815)
    at Function.value (C:\Users\pavma\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\index.js:24:44810)
    at e.value (C:\Users\pavma\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\index.js:24:44551)
    at e.value (C:\Users\pavma\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\index.js:24:11351)
    at e.value (C:\Users\pavma\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\index.js:24:44257)
    at e.value (C:\Users\pavma\AppData\Roaming\npm\node_modules\javascript-obfuscator\dist\index.js:24:11351)

javascript-obfuscator -v
0.14.3
node -v
v8.9.4
npm -v
5.6.0

**Comment by sanex3339** [comment]
Probably related to `estraverse` or `escodegen`

**Comment by sanex3339** [comment]
Related to `esprima`. Obfuscator using `parseScript` method, but your code is `module`.

So i'll wrap it in try-catch. If it will fail on `parseScript`- obfuscator will run `parseModule`

**Comment by sanex3339** [comment]
Fix in master branch. Until release you can use `master` branch.

**Comment by mvpkreddy** [comment]
Thanks a lot Timofey! I will try with master branch.

FYI - I did not encounter this error when I integrated with [obfuscator-loader](https://github.com/javascript-obfuscator/obfuscator-loader) with mode as "development". But, I am receiving a different error when I enable mode as "Production" in webpack. 
Error:
bundle.js:1 Uncaught RangeError: Maximum call stack size exceeded

I am currently using the [low obfusctation](https://github.com/javascript-obfuscator/javascript-obfuscator#low-obfuscation-high-performance) option.

**Comment by sanex3339** [comment]
I dont know how exactly  webpack working after he applied loaders, but error above related with self defending. Looks like obfuscated was modified by some other loader or plugin and this was trigger self defending mechanism.

**Comment by mvpkreddy** [comment]
I tried using index.js but got errors. Can you let me know the steps on how to use the master branch? I am using babel-loader and here is my webpack config:
`var path = require('path');
var webpack = require('webpack');

module.exports = {
    entry: "./scripts/src/app.js",
    output: {
        filename: "bundle.js",
        path: __dirname + "/dist"
    },      
    resolve: {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: [".ts", ".tsx", ".js", ".json"]
    },

    module: {
        rules: [            
            // All files with a '.js' or '.jsx' extension will be handled by 'babel-loader'.
            {
                test: /\.jsx?$/,
                include: [path.resolve(__dirname, "scripts")],
                exclude: [
                    "./node_modules/"
                ],
                query: {
                    presets: ["env", "minify"]
                },
                loader: "babel-loader",                
            },
            // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
            { enforce: "pre", test: /\.js$/, loader: "source-map-loader" },
            {
                enforce: 'post',
                use: {
                    loader: 'obfuscator-loader', options: {
                        compact: true,
                        controlFlowFlattening: false,
                        deadCodeInjection: false,
                        debugProtection: false,
                        debugProtectionInterval: false,
                        disableConsoleOutput: true,
                        identifierNamesGenerator: 'hexadecimal',
                        log: false,
                        renameGlobals: false,
                        rotateStringArray: true,
                        selfDefending: false,
                        stringArray: true,
                        stringArrayEncoding: false,
                        stringArrayThreshold: 0.75,
                        unicodeEscapeSequence: false
                    }
                }
            }
        ]
    },    
};`

**Comment by sanex3339** [comment]
You should replace semver version of obfuscator by url to repository branch. Google it please.

**Comment by mvpkreddy** [comment]
Thanks Timofey!! The master branch works for this issue with javascript-obfuscator cli. 

I am looking into the issue with webpack production mode. The Babel loader is a pre loader and shouldnt make any difference whether it is dev or prod mode.

**Comment by jspenguin2017** [comment]
> So i'll wrap it in try-catch. If it will fail on `parseScript` - obfuscator will run `parseModule`

Why not just use `esprima.parse`? It will auto-detect whether the code is a `script` or `module`.

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.15.0` just published to the npm!
