### ISSUE TITLE
Add support for .html files

### ISSUE THREAD

**Issue by shaji-Dev** [javascript-obfuscator/javascript-obfuscator#212]
Could you please add support to .html files as well?

I'm using polymer-bundler(much like vulcanize) to bundle all the JS code inside one index.html file, and if the obfuscator could look for where the <script> starts and end and take the JS code from there and encode it would be great.

An example is with the babel-cli, it only uses .js files, but a developer made babel-html that browses the html file for the <script> tags and take the JS from there and use the babel-cli on it. Same idea.

Thank you.

**Comment by sanex3339** [comment]
Sadly, but i won't do this in any near future. You should obfuscate your js code before it will appended to the        html

**Comment by sanex3339** [comment]
But you can make a new tool that will use obfuscator and do this
