### ISSUE TITLE
I hate you! 😡

### ISSUE THREAD

**Issue by jimmywarting** [javascript-obfuscator/javascript-obfuscator#215]
Remove this repo/lib from github, npm and everywhere on the web
You are making the web worse, slower (up to 80%!!!) and less secure. anti virus reports your page as insecure (#51)
:angry:

Have some Content-Security-Policy (CSP) on my domain and don't allow eval b/c it's evil❗️ 
The service i used have obfuscated the code and it's bad! can't use there service b/c of it.

**Comment by StoicaNicusor** [comment]
@jimmywarting You are more evil than the developer of this beautiful masterpiece.
It's not his fault, so don't ask him to remove it.
There are gazillions of things that should be removed from github before even thinking of javascript-obfuscator. Just think about how many malware samples can be found on github + www , with source code ...

**Comment by sanex3339** [comment]
Have a nice day too.

**Comment by jimmywarting** [comment]
@StoicaNicusor how can i be any more "evil" than the developer of this <s>beautiful masterpiece</s> junk? by expressing my hatred for this obfusicator in a country with freedom of speech? The developer that has written this tool or everyone else that have some interest in this have the intention of using it themselves, either for protecting your own code or embedding malicious code. 
And do you know what...? Any javascript can be defused. It won't protect your code (only making it harder to read).

Obfusing code often involves execution methods that are create from strings (often used are `eval()`)
That is a security hole if anyone where to write any xss attack and developers where using `eval()` somehow. This can be secured with setting a CSP flag but now have to be disabled b/c of your **un**protected code. You are now lowering other developers standards and also making the code run slower. not to mention that the webpage now is blocked by a antivirus program - now who is the evil guy? The guy that express his feeling or the developer that writes this with the intention of using it or sharing it with others so other can use it?

**Comment by slig** [comment]
> by expressing my hatred for this obfusicator in a country with freedom of speech?

You clearly don't understand what freedom of speech means. See this for a TL;DR https://xkcd.com/1357/

> This can be secured with setting a CSP flag but now have to be disabled b/c of your (un)protected code. 

No, it doesn't. Simply don't host any code that uses `eval` on your code and you don't have to disable anything on your server.

> not to mention that the webpage now is blocked by some antivirus program

False positives happen all the time. If you're not happy with that, use a proper OS that doesn't need antivirus or learn how to use the Internet without getting virus. Better yet, if you can't do that, get an iPad.

There're paid SaaS that obfuscate JS code and they existed long before this project. Go fight them.

**Comment by sanex3339** [comment]
Hi, @jimmywarting. Obfuscator is just a tool, and it is choose of any developer: use obfuscate their project or not. It is not a simple tool and any person who will use it should know the price of it (performance decrease and increased file size).

So, if you have problem with CSP and evals that are existing in a some obfuscated code that you want to use as third-party in your site - you should contact with authors of this third-party libraries and let them know about your problem. Obfuscator allows to disable evals by choosing `target: 'extension'`.

Anyway, evals using in few places, mostly as compact way to get global variable.

**Comment by jimmywarting** [comment]
@sanex3339 that is something i can agree on.  I will also take it up with the authors of my third-party library.
If i could make a small request then it would be for target to change it's default to be extension so eval won't be used. since it's eval

**Comment by sanex3339** [comment]
I wont change default target to `extension` because browser is primary target for obfuscation.
Anyway, you should know that simple eval that just integrated in source code isn't dangerous.

Evals are becomes dangerous when they executed some external code that you can't control.
In case of `javascript-obfuscator`, `evals` - this just are isolated small parts of code and their primary goal is to get global object.

**Comment by sanex3339** [comment]
But i think i should rename `Extension` target on `BrowserNoEval`

**Comment by etienne-martin** [comment]
![image](https://user-images.githubusercontent.com/9700213/38283435-07a9e938-3784-11e8-960f-6a89d72f5467.png)

**Comment by SacDin** [comment]
This is beautiful project through which developers can protect their source code and even license commercially if needed. If you have an issue, find your solution rather than blaming artists.

**Comment by rinogo** [comment]
@sanex3339 Are there other Issues or resources that discuss the security implications of javascript-obfuscator's use of `eval()`? Also, how much does `browser-no-eval` reduce the usefulness of the obfuscation? I'm inclined to use `browser-no-eval` just to be safe.
