### ISSUE TITLE
Conflict with Q library

### ISSUE THREAD

**Issue by dcoliv** [javascript-obfuscator/javascript-obfuscator#216]
Hi!

This is the output of some obfuscated code of ours:

```javascript
l[b('0x21')][b('0x61')] = function (Q, R, S, T, U) {
    var V;
    var W = U || Q[b('0x24')]();
    h[b('0x1f')](k, b('0x62'));
    V = e[b('0x23')](b('0x26'), [{
        'method': i[b('0x27')][b('0x28')],
        'type': R ? i[b('0x29')]['SD'] : i[b('0x29')][b('0x2a')],
        'uri': Q
    }]);
```

The problem here is that, on the 3rd line, Q refers to a global variable, exported by Kris Kowal's Promises library (https://github.com/kriskowal).
But the obfuscated version of the code introduced a function parameter also named "Q". The obfuscator didn't seem to realize there was already an undeclared "Q" variable being used in this function.

We could be injecting the Q library using an IIFE, but at the moment we would have to change a large amount of our existing code.
We could also change the "identifierNamesGenerator" option to use "hexadecimal", but that significantly increases the size of our already large library.
The option "reservedNames" doesn't seem to help either.

Is there any option that we can use, or do you have any suggestion to help us overcome this problem?
Thanks in advance!

**Comment by sanex3339** [comment]
Hmm, looks like i should add new option with black list of identifiers that shouldn't be generated.

**Comment by sanex3339** [comment]
Actualli, i can use here `reservedNames` option values, because if this option has value `Q`, this identifier won't renamed and identifier with this name won't generated

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/226

**Comment by sanex3339** [comment]
Fix in `master` branch

**Comment by sanex3339** [comment]
Use `reservedNames` option. It takes `array` of `strings` that will passed to the `new RegExp(string)` constructor

**Comment by sanex3339** [comment]
Also, i'll release 0.15.0 with this fix in early april, so, temporary you should use version from `master` branch.

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.15.0` just published to the npm!

Check `reservedNames` option
