### ISSUE TITLE
Variable ... has already been declared

### ISSUE THREAD

**Issue by vagrantir** [javascript-obfuscator/javascript-obfuscator#217]
Merry Christmas everybody!

I often get situation where obfuscated code thow error as in subject.
The code below, obfuscated on JavaScript Obfuscator@0.14.3, constatntly evaluates with: **Identifier 'q' has already been declared**
Obfuscation options: 
- mangled
- rename globals
- string array with encoding off
- transform object keys
- target browser
```
(function () {
  console.log("Hello World!");
 function test(){
  function func1(){let a=1; return a}
  function func2(){let a=2; return a}
  function func3(){var a=3; return a}
  function func4(){let a=4; return a}
  function func5(){let a=5; return a}
  let a, b, c, d, e, f, g, h, i;
   func1(func2());
}
 (test)()
}
)();

```

**Comment by sanex3339** [comment]
Reproduced it, will see why this happening

**Comment by sanex3339** [comment]
Fixed it locally, expect merge in master branch in a hour. After that, you can use `master` branch version until first beta release.

**Comment by vagrantir** [comment]
thx, looks like its work
