### ISSUE TITLE
Problem using this module as it have`eval` statements 

### ISSUE THREAD

**Issue by venky352** [javascript-obfuscator/javascript-obfuscator#219]
I am using this module for my javascript libraries to render them browsers. One of the problems that I observed is that this module uses `eval` functions. I want to avoid `eval` altogether while executing my libraries on the browser.

I see you recommended options for extensions using `target` config. Can I safely use this and render the obfuscated code on the browsers? If not, what could be the problems that I can get?

Is it possible to avoid `eval` statements altogether for other environments as well?

**Comment by sanex3339** [comment]
Use `target: 'extension'`

In 0.15.0 i'll rename `extension` on `browser-no-eval`

**Comment by sanex3339** [comment]
Renamed `target` option value from `extension` on `browser-no-eval` now in `master` branch.

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.15.0` just published to the npm!
