### ISSUE TITLE
Obfuscated code fails to work in IE8

### ISSUE THREAD

**Issue by Wain-PC** [javascript-obfuscator/javascript-obfuscator#22]
Hello! I know IE8 is a little bit outdated, but still =)
Running the obfuscated script on IE8 outputs the following error:
`'filter' is null or not an object`

I assume this is caused by this JSFuck line, as Array.filter support started from IE9:
`Window: '[]["filter"]["constructor"]("return this")()',`

If this is the case, it should probably be safe to change this for a more supported method, such as _push_:
`Window: '[]["push"]["constructor"]("return this")()',`

**Comment by sanex3339** [comment]
what version you use?

**Comment by Wain-PC** [comment]
I've used 0.8.0. Should it help to update to 0.8.1?

**Comment by sanex3339** [comment]
Only one place where `[]["filter"]["constructor"]("return this")()` still using is following line:
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/templates/custom-nodes/debug-protection-nodes/debug-protection-function-node/DebugProtectionFunctionTemplate.ts#L13

I will replace this line today on `{}.constructor('debugger')()`

**Comment by Wain-PC** [comment]
Thanks! I see that this line is intended to be used with debug protection mode. However, my script has been built without **debugProtection** flag set to true (actually, without this flag at all, but readme says its default value is false). Is this a desired behavior?

**Comment by sanex3339** [comment]
maybe it is line here https://github.com/javascript-obfuscator/javascript-obfuscator/blob/0514793257b306d38b0936ec16031818b5e783c7/src/enums/JSFuck.ts
but i tested code before 0.8.0 release on ie9 in ie8 compatibility mode and it doesnt't throw any errors.

Anyway i change this lines today and i hope it helps for you.

**Comment by Wain-PC** [comment]
Thanks again! One more issue: **disableConsoleOutput** option works not as expected:
With value set to true, console.log function is replaced with the following one:
![image](https://cloud.githubusercontent.com/assets/3702965/20488246/5f9a5bdc-b017-11e6-9978-cbad2151cd4c.png)
This obviously hangs the page with an infinite loop, and surely this is not an expected behavior (this option is turned on by default!)

**Comment by sanex3339** [comment]
One more issue: disableConsoleOutput option works not as expected

already fixed in 0.8.1

**Comment by Wain-PC** [comment]
That's correct, I was using an outdated dependency, my fault.

**Comment by sanex3339** [comment]
reopen until fix

**Comment by sanex3339** [comment]
Ready in `javascript-obfuscator@0.8.2`

Please try and check.

**Comment by Wain-PC** [comment]
Thanks, I will perform heavier autotesting on it next week. For now, I've performed several manual builds and they seem to work in IE8.

**Comment by sanex3339** [comment]
Nice!

**Comment by sanex3339** [comment]
any test results?

**Comment by qingweiqm** [comment]
hi,I'm using the webpage to do the obfuscate, the obfuscated code doesn't work in IE8.

**Comment by sanex3339** [comment]
hi, show me your obfuscated code please

**Comment by qingweiqm** [comment]
@sanex3339 
hi, Timofey 

pls see below,

[obfuscated (1).js.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/674336/obfuscated.1.js.zip)

**Comment by sanex3339** [comment]
i will look into it

**Comment by sanex3339** [comment]
Haven't any runtime errors.

If you doesn't have any output to the console - set `disableConsoleOutput` to `false`

**Comment by qingweiqm** [comment]
thanks, after disable the consoleoutput, it works.

**Comment by sanex3339** [comment]
Nice!

**Comment by sanex3339** [comment]
So,  i will close this issue.  If you will any problems with ie8 just create new issue.
