### ISSUE TITLE
Concat + Obfuscate with Source maps

### ISSUE THREAD

**Issue by loopingLines** [javascript-obfuscator/javascript-obfuscator#220]
Hi,
Please close this if you find it irrelevant in this place. 

In my gulp build flow I have a scripts concatenation transform before final obfuscation. I want to have source maps in my dev environment but I cannot find a way to have source maps refer original sources instead of the concatenated script. Any ideas on how to make this happen? I am using gulp-concat to combine scirpts.

**Comment by sanex3339** [comment]
Hi. Your question is related to obfuscator plugin. Anyway, you should get all source maps from obfuscator (via `getSourceMap` method) and than build new source map with help of some tools that can combine source maps.
