### ISSUE TITLE
How to Callback?

### ISSUE THREAD

**Issue by MariSelvanDev** [javascript-obfuscator/javascript-obfuscator#222]
How do I make Callback to handle errors in the javascript code

```
var JavaScriptObfuscator = require('javascript-obfuscator').obfuscate;
//Error in console.log and I have to handle it. How to do?
var mycode='function hai(){console.log("hello world";} hai();';

var obfuscationResult = JavaScriptObfuscator(mycode,options,function(err, obfuscated){
if(err){
console.log("some error occurred");
}
else{
console.log("cool...");
}
})

```
the above code is not working to handle errors. 
Thanks in Advance...

**Comment by sanex3339** [comment]
Disable this option
https://github.com/javascript-obfuscator/javascript-obfuscator#disableconsoleoutput

**Comment by MariSelvanDev** [comment]
Hi sanex3339 . I have tried disableconsoleoutput, but still there is no flow to callback.

The following is my code .
```
 var JavaScriptObfuscator = require('javascript-obfuscator').obfuscate;
 var myCode='function hai(){console.log("hello world";} hai();';
 var options={
 compact: false,
 controlFlowFlattening: true,
 disableConsoleOutput:true
};
var obfuscationResult = JavaScriptObfuscator( myCode , options, function(err){
 if(err){
    console.log("some error occured");
}
else{
console.log("cool...");
}
})
console.log(obfuscationResult.getObfuscatedCode());
```
Clearly, you can see in the variable **myCode**, the console.log is not closed properly, That's the error which I have to handle , but unfortunately the callback is not working. am I written the callback correctly?, if so, then why its not working. I couldn't find any example with callback. If you rewrite the code, It will be more helpful. thank you

**Comment by sanex3339** [comment]
You should `disableConsoleOutput` false

**Comment by MariSelvanDev** [comment]
I tried with both true and false. Still the callback is not working. It doesn't consoled "some error occured" or the obfuscated output.

**Comment by sanex3339** [comment]
Show me your obfuscated code

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator#nodejs-usage

**Comment by MariSelvanDev** [comment]
This works only when the input is correct. 
how to handle the errors when you try to obfuscate 
`alert("helo" ;`
with missing close bracket?
it just throw the error openly.

**Comment by sanex3339** [comment]
Wrap it in try catch

**Comment by MariSelvanDev** [comment]
Thank you So much it worked.
