### ISSUE TITLE
Obfuscator date problem, Run using imacros

### ISSUE THREAD

**Issue by Fahri5567** [javascript-obfuscator/javascript-obfuscator#224]
Hi, 
Sorry my english is ugly, I am still a student.
And Sorry if I can not explain many things, but I get the problem as below.

Generate Online : https://javascriptobfuscator.herokuapp.com/
Identifier Names Generator : mangled
String Array: enable
Rotate String Array: enable
String Array Encoding: RC4
Target: Browser

Code:
```
function formattedDate() {
    var date = new Date();
    var month = date.getMonth() + 1;
    var day = date.getDate().toString();
    var year = date.getFullYear().toString();

    if (month.length < 2) {
        month = "0" + month;
    }
    if (day.length < 2) {
        day = "0" + day;
    }
    return day + "-" + month + "-" + year;
}
```
Output:
``
var a=['wqzDlMOlw5RGwoc=','w6kKw7zDhMOYSw==','w6DCvMKaAsKdw7zCjBQ=','w7ADd8KZw6bDmMO4','wrjCkyTCosOBbBfDoQ=='];(function(c,d){var e=function(f){while(--f){c['push'](c['shift']());}};e(++d);}(a,0x8e));var b=function(c,d){c=c-0x0;var e=a[c];if(b['mJUNXu']===undefined){(function(){var f;try{var g=Function('return\x20(function()\x20'+'{}.constructor(\x22return\x20this\x22)(\x20)'+');');f=g();}catch(h){f=window;}var i='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=';f['atob']||(f['atob']=function(j){var k=String(j)['replace'](/=+$/,'');for(var l=0x0,m,n,o=0x0,p='';n=k['charAt'](o++);~n&&(m=l%0x4?m*0x40+n:n,l++%0x4)?p+=String['fromCharCode'](0xff&m>>(-0x2*l&0x6)):0x0){n=i['indexOf'](n);}return p;});}());var q=function(r,s){var t=[],u=0x0,v,w='',x='';r=atob(r);for(var y=0x0,z=r['length'];y<z;y++){x+='%'+('00'+r['charCodeAt'](y)['toString'](0x10))['slice'](-0x2);}r=decodeURIComponent(x);for(var A=0x0;A<0x100;A++){t[A]=A;}for(A=0x0;A<0x100;A++){u=(u+t[A]+s['charCodeAt'](A%s['length']))%0x100;v=t[A];t[A]=t[u];t[u]=v;}A=0x0;u=0x0;for(var B=0x0;B<r['length'];B++){A=(A+0x1)%0x100;u=(u+t[A])%0x100;v=t[A];t[A]=t[u];t[u]=v;w+=String['fromCharCode'](r['charCodeAt'](B)^t[(t[A]+t[u])%0x100]);}return w;};b['WZQIfe']=q;b['cpmZqq']={};b['mJUNXu']=!![];}var C=b['cpmZqq'][c];if(C===undefined){if(b['vbpmyU']===undefined){b['vbpmyU']=!![];}e=b['WZQIfe'](e,d);b['cpmZqq'][c]=e;}else{e=C;}return e;};function formattedDate(){var c=new Date();var d=c[b('0x0','l16A')]()+0x1;var e=c[b('0x1','GlV!')]()[b('0x2','3VdH')]();var f=c['getFullYear']()['toString']();if(d[b('0x3','j$tm')]<0x2){d='0'+d;}if(e[b('0x4','gqzg')]<0x2){e='0'+e;}return e+'-'+d+'-'+f;}
``
error:
``
TypeError: b is not a function
``

**Comment by sanex3339** [comment]
This code working fine for me. What browser you are using?

**Comment by Fahri5567** [comment]
@sanex3339 Yes is working in browser, but not working in imacros.

**Comment by sanex3339** [comment]
What is `imacros`?
Chrome plugin? I won't support various custom environments with non-standard javascript.

**Comment by sanex3339** [comment]
Closed. I won't support various custom environments with non-standard javascript.
