### ISSUE TITLE
error: unknown option `--exclude'

### ISSUE THREAD

**Issue by danielravina** [javascript-obfuscator/javascript-obfuscator#225]
Hey guys,

The readme has an `exclude` option but after installing I get the error above.
I'm on version 0.14.3

Thanks

**Comment by danielravina** [comment]
Oh I see.. the exclude is in `0.15.0-dev.4`

**Comment by sanex3339** [comment]
Hi.

>the README on the master branch might not match that of the latest stable release!
https://github.com/javascript-obfuscator/javascript-obfuscator#note-the-readme-on-the-master-branch-might-not-match-that-of-the-latest-stable-release
