### ISSUE TITLE
Does this support polymorphic code?

### ISSUE THREAD

**Issue by AhsanEjazC** [javascript-obfuscator/javascript-obfuscator#229]
JScrambler offers polymorphic obfuscation, does this do the same thing?

**Comment by sanex3339** [comment]
What is it?

**Comment by AhsanEjazC** [comment]
Code that is different but give the same output. i.e 6-2 = 4 and 2+2 = 4 too.

**Comment by sanex3339** [comment]
Currently - no, but i want to investigate this in a future.

I'll close this issue in favour of https://github.com/javascript-obfuscator/javascript-obfuscator/issues/105
