### ISSUE TITLE
Suggestion - Method of additional minification and accelerating some JS.

### ISSUE THREAD

**Issue by peredozo** [javascript-obfuscator/javascript-obfuscator#230]
Hello. If JS code have already base64-encoded values (inline file content), after obfuscation is have dual-base64 values. Is unnecessary result increase, and unnecessary decoding slowdown. I suggest adding the `skipValuesEncoding` option - an array of variables whose values will not be encoded.

**Comment by sanex3339** [comment]
Hi. Just disable `stringArrayEncoding` option

**Comment by peredozo** [comment]
I know it. But if I need `stringArrayEncoding` for all except some big already encoded values.

**Comment by sanex3339** [comment]
Then wrap this values in conditional comments

**Comment by peredozo** [comment]
Thanks and sorry, I missed conditional comments.

**Comment by sanex3339** [comment]
Can i close this issue?

**Comment by peredozo** [comment]
Yes.
