### ISSUE TITLE
Not working with Async/Await

### ISSUE THREAD

**Issue by fab1o** [javascript-obfuscator/javascript-obfuscator#231]
How to make it work with async/await?

test.js
```js
export default class Request {
  static async get() {
   return window.fetch("...");
  }
}
```
`javascript-obfuscator test.js`

On Windows Powershell:
```powershell
               ^
Error: Line 2: Unexpected identifier
> ...tic async get() {...
    at Function.value (....\node_modules\javascript-obfuscator\dist\index.js:1:63377)
Exit code: 1
```

Tried `yarn add` using both `#master` branch and `@latest`

**Comment by sanex3339** [comment]
Related to `esprima`.
http://esprima.org/demo/parse.html?code=export%20default%20class%20Request%20%7B%0A%20%20static%20async%20get()%20%7B%0A%20%20%20return%20window.fetch(%22...%22)%3B%0A%20%20%7D%0A%7D

Looks like it not supported static async classes yet.

**Comment by sanex3339** [comment]
I'll investigate switch from `esprima` on `acorn`

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/233

**Comment by sanex3339** [comment]
I will switch from `esprima` on `espree`

**Comment by sanex3339** [comment]
Hi. Fix in `master` branch. You can use it from this branch until `0.15.0` release.

**Comment by fab1o** [comment]
Works! Thanks @sanex3339 here is my set up in package.json:
```
  "dependencies": {
    "javascript-obfuscator": "javascript-obfuscator/javascript-obfuscator#master",
    "webpack-obfuscator": "0.14.3"
  },
  "resolutions": {
    "webpack-obfuscator/**/javascript-obfuscator":
      "javascript-obfuscator/javascript-obfuscator#master"
  },
```

**Comment by sanex3339** [comment]
I reopened issue untill `0.15.0` release

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.15.0` just published to the npm!

**Comment by bgbruno** [comment]
it is @2021 and I have still that issue
**Q pls what is the solution ?**

**Comment by sanex3339** [comment]
@bgbrunoplease show me your code, obfuscator version and other details
