### ISSUE TITLE
Unable to run, what am I missing here?

### ISSUE THREAD

**Issue by Elite** [javascript-obfuscator/javascript-obfuscator#232]
I had an earlier version working perfectly, upgraded `npm` and installed the newest version and it's no longer working :(, what am I missing here now ?

![sshot-1](https://user-images.githubusercontent.com/5461439/37875737-f95d31ac-3060-11e8-9799-6c32ba16ecdf.jpg)

**Comment by sanex3339** [comment]
Try `npm link`

**Comment by Elite** [comment]
Already did, tried again, no luck :(

![sshot-2](https://user-images.githubusercontent.com/5461439/37887155-d98ea888-30dd-11e8-971f-ea5613177810.png)

**Comment by sanex3339** [comment]
Try you installed it?

**Comment by Elite** [comment]
Tried both this `npm install --save-dev javascript-obfuscator` and git + `npm install` as well

**Comment by sanex3339** [comment]
Try `npm link javascript-obfuscator` from `package.json` directory of obfuscator.
Or try to install it globally with `npm install -g javascript-obfuscator`

**Comment by Elite** [comment]
That worked :)

**Comment by sanex3339** [comment]
Added this to the FAQ
