### ISSUE TITLE
Upload JavaScript Files

### ISSUE THREAD

**Issue by carverdo** [javascript-obfuscator/javascript-obfuscator#236]
Hi. 
I usually use your "Copy & Paste JavaScript Code" tab but today tried using "Upload JavaScript Files" but nothing happens when I drag and drop. Yesterday, perhaps coincidentally, my browser froze immediately after.

If relevant, I'm using Chrome.

**Comment by sanex3339** [comment]
Hi. Wrong repo. Create issue here: 
https://github.com/javascript-obfuscator/javascript-obfuscator-ui

**Comment by carverdo** [comment]
Will do.
