### ISSUE TITLE
[feature request] Seed option to produce consistent output

### ISSUE THREAD

**Issue by Wain-PC** [javascript-obfuscator/javascript-obfuscator#24]
Hello again!

The problem:
Each obfuscator run on the same input with the same options produces different output. This is undesirable when deploying to multiple machines simultaneously (e.g. test build script and production build script must be the same).

The solution:
It would be great to have an ability to pass a seed option to the underlying **chance** random generator you use. I think it will be pretty easy to implement, just put the seed from options to this line:
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/Utils.ts#L9

Example with seed value = 123:
`private static randomGenerator: Chance.Chance = new Chance(123);`

I've tested it briefly with hardcoded values and it works as expected! The only problem I got is actually creating and passing the option from CLI/Node, as there're too many files containing options configuration.

Would you please add one? Thanks in advance!

**Comment by sanex3339** [comment]
will be out in 30 mins

**Comment by sanex3339** [comment]
ready in `javascript-obfuscator@0.8.2`

**Comment by Wain-PC** [comment]
Thank you, I've tested this options on various builds, seems working as expected!

**Comment by sanex3339** [comment]
Nice!
