### ISSUE TITLE
Error when code contains object spread syntax

### ISSUE THREAD

**Issue by Lumox100** [javascript-obfuscator/javascript-obfuscator#240]
I get the following error when trying to obfuscate Javascript code that uses the spread syntax to merge objects into one object using https://obfuscator.io/.

Error: Unknown node type ExperimentalSpreadProperty.

var newObj = {...obj1, ...obj2}
obj1 and obj2 only contain properties, no methods.

Array spread syntax does not cause any problems.

**Comment by sanex3339** [comment]
Related to third party library. Estraverse or escodegen.

**Comment by sanex3339** [comment]
Can fix it from my side. Expect update tomorrow.

**Comment by sanex3339** [comment]
PR with fix
Correct obfuscation of object rest and spread properties 

Expect release in a few days.

**Comment by sanex3339** [comment]
Fix in `master` branch. Until release you can use version from `master` branch.

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.16.0` is out.
