### ISSUE TITLE
error when package.joson don't exists

### ISSUE THREAD

**Issue by bato3** [javascript-obfuscator/javascript-obfuscator#245]
CLI version require `package.joson`

If file don't exists or have syntax error  - program fails

**Comment by sanex3339** [comment]
And it is ok. Package.json should always exist if you installed package with npm

**Comment by sanex3339** [comment]
Will try to fix this, but how did you install it that `package.json` was missing?

**Comment by sanex3339** [comment]
No. I using package `pjson` and it throwing exception when `package.json` is missing. So, because situation when `package.json` is missing shouldn't happen - i won't fix it.

**Comment by sanex3339** [comment]
You error is because you don't create package.json before you tried to install obfuscator. This is not related with obfuscator. Just run `npm init` to setup your package.json

**Comment by sanex3339** [comment]
Or if you want to use CLI only - install package globally witg `-g` flag
