### ISSUE TITLE
unicode-escape-sequence enhancement 

### ISSUE THREAD

**Issue by bato3** [javascript-obfuscator/javascript-obfuscator#248]
Is possible change `--unicode-escape-sequence` behavior? 

To replace not all characters - to reduce the size of the output file. I think that all of them `[^a-zA-Z\d]` and somethingg signs from the other range.

Would such a thing make sense?

BTW: json keys aren't escaped. It is JS limit or oversight?

**Comment by sanex3339** [comment]
If i remembered correctly - current range of characters is minimal working range that will work with any string (string can contain some code and special characters it should working fine)

**Comment by sanex3339** [comment]
Some symbols are not escaped. It is correct behaviour.

**Comment by bato3** [comment]
Now for code: `'la la la'` available options are:
* `'la\x20la\x20la'`
* `'\x6c\x61\x20\x6c\x61\x20\x6c\x61'`
* `'bGEgbGEgbGE='` and `'CcKFw5sEU8KJw5kT'`

I'm talking about something like this: `'\x6ca\x20la\x20l\x61'`
