### ISSUE TITLE
Move `string-array` to private namespace / try detect `private` namespace

### ISSUE THREAD

**Issue by bato3** [javascript-obfuscator/javascript-obfuscator#249]
Some libraries use private namespaces like this:

```
(function($){
        $('.foo');
})(jQuery);
```

But if I use `--string-array true` option this array is outside "private namespace"

Is possible:
- detect place where `string-array` should be
- add special tag like `// javascript-obfuscator:insert-string-array-here`
- add option like `--add-private-namespace passed,arguments,list`

adding last option with auto-detect or argument list can afford to make smaller result

**Comment by sanex3339** [comment]
All code inside private namespace will have access to the string array, so it is unnecessary to move string array inside function.

**Comment by bato3** [comment]
It's about the opposite situation, so that the code from outside does not have access to `string-array`.

The current solution gives a 90% chance to overwrite variables in large projects with the `mangled` option.

**Comment by sanex3339** [comment]
To prevent overriding check `identifiersPrefix` option
https://github.com/javascript-obfuscator/javascript-obfuscator#identifiersprefix
