### ISSUE TITLE
async functions not working

### ISSUE THREAD

**Issue by oallouch** [javascript-obfuscator/javascript-obfuscator#25]
Hi,

This function outputs an error:
`const hi = async () => {
  console.log("Hello World!");
}
hi();`

async/await is cutting edge, but do you plan to add this feature ?

Thx in advance,
Olivier

**Comment by sanex3339** [comment]
seems error related to esprima

**Comment by sanex3339** [comment]
Current stable version of `esprima` doesn't support async/await.
https://github.com/jquery/esprima/issues/1079

**Comment by sanex3339** [comment]
So i close this issue. As soon as `esprima` will have gotten update with `async/await` support, i update package.

**Comment by oallouch** [comment]
Hi,
esprima seems to have done something about this in its 3.1.2 version.
Might be worth checking.

Thx,
Olivier

**Comment by sanex3339** [comment]
No, with 3.1.2 still error

```
Error: Line 3: Unexpected token =>
    at ErrorHandler.constructError (/Users/sanex/projects/javascript-obfuscator/node_modules/esprima/dist/esprima.js:3390:22)
    at ErrorHandler.createError (/Users/sanex/projects/javascript-obfuscator/node_modules/esprima/dist/esprima.js:3408:27)

```

**Comment by oallouch** [comment]
Ok. I'm waiting for their version 4 to bother you again :)
Anyway, thx (a lot) for your quick answer !
