### ISSUE TITLE
Web version

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/javascript-obfuscator#251]
Looks like i can make web version with a minimal effort.

![image](https://user-images.githubusercontent.com/9210534/38949901-8c4a8de0-434c-11e8-99f5-98d6be2d3cb1.png)

**Comment by bato3** [comment]
Without full config this has no sense. Is many sites, who allow obfluscate JS online. 

In addition to the effect of your self-development, it has useless. In order to show the effects of faster and more effective be server-side version.

**Comment by sanex3339** [comment]
It will accept full options object

**Comment by sanex3339** [comment]
Web version in the `master` branch now. Anybody can test it?

**Comment by SuperOP535** [comment]
Nice! Will do soon.

**Comment by sanex3339** [comment]
@SuperOP535 hi, any news?

**Comment by sanex3339** [comment]
0.17.0 version in out!
