### ISSUE TITLE
Update CLI -h (target options)

### ISSUE THREAD

**Issue by bato3** [javascript-obfuscator/javascript-obfuscator#252]
Eg `--string-array-encoding <string|boolean> [true, false, base64, rc4]` has available options, but `--target` no.
```
--target <string>      Allows to set target environment for obfuscated code.
```

And I'm thinking, that all options should have described Default values

**Comment by sanex3339** [comment]
Thank you

**Comment by sanex3339** [comment]
I will change help format to this one:
```
--target <string>        Allows to set target environment for obfuscated code. Values: browser, browser-no-eval, node. Default: browser

```

**Comment by sanex3339** [comment]
Fix in the `master` branch now. You can use version from `master` branch until release.

**Comment by sanex3339** [comment]
0.17.0 version in out!
