### ISSUE TITLE
New CLI option --print-config

### ISSUE THREAD

**Issue by bato3** [javascript-obfuscator/javascript-obfuscator#254]
for `$ javascript-obfuscator --print-config >config-to-edit.json`

A small thing, and glad. So that you do not have to look in the documentation on www.

**Comment by sanex3339** [comment]
Sorry, but i won't see reasons to add this. I don't want to overload the list of options

**Comment by sanex3339** [comment]
PS: here many requests from you. Maybe you will add this requests here:
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/105

**Comment by bato3** [comment]
When you use special structure eg.:

```
{
"configOptionName": {"default": "val","description":"Lorem ipsum", "availableOptions":["opt1", "opt2"],"shortCLIName":"name"}
}

You can easily transform this to documentation, config generator and default config

PS: You say that you prefer to have everything mixed up, where subsequent messages do not create a coherent story and you do not know what will be done, what has been rejected, and what is being discussed ...

Once, it seemed to me that one thread is a good idea...
