### ISSUE TITLE
Cli stringArrayEncoding RC4/Base64/true not work

### ISSUE THREAD

**Issue by extensionsapp** [javascript-obfuscator/javascript-obfuscator#255]
```javascript-obfuscator code.js --output code.min.js --stringArrayEncoding rc4```
```javascript-obfuscator code.js --output code.min.js --stringArrayEncoding base64```
```javascript-obfuscator code.js --output code.min.js --stringArrayEncoding true```

Not encoding.

**Comment by sanex3339** [comment]
Hi. Please, check readme.
https://github.com/javascript-obfuscator/javascript-obfuscator#cli-options
