### ISSUE TITLE
Suggestion: Add CLI Parameter "Disable the Addition of Auxiliary Functions"

### ISSUE THREAD

**Issue by Geograph-us** [javascript-obfuscator/javascript-obfuscator#256]
When there are several encrypted scripts on the site, each one contains functions rc4(), base64(), md5().
If you added the disable include option for these functions in the CLI, I could add them only to the first script.

**Comment by sanex3339** [comment]
Hmm. This is good idea to add option like `noEmitHelpers`

**Comment by sanex3339** [comment]
In the current project state, i don't think that this option may be a good idea.
