### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by AhsanEjazC** [javascript-obfuscator/javascript-obfuscator#257]
On only enabling self defending and compact code (every other box unticked), Firefox gives "too much recursion".
On enabling Compact code + Self defending + Control flow flattering + String Array Rotate String array (RC4) + Transform Object Keys, give error "allocation size overflow" .
This behavior is observed on both Chrome and Firefox .
This behavior is caused when "Self Defending is enabled".  
This behavior is in both "Browser no eval" and "Browser"

**Comment by sanex3339** [comment]
👀

**Comment by AhsanEjazC** [comment]
Vs code auto formatting caused it.
