### ISSUE TITLE
--config support

### ISSUE THREAD

**Issue by MichaelWayneLIU** [javascript-obfuscator/javascript-obfuscator#259]
Hello~~~It seems that the --config is not supportted  yet?My local environment will always give this:
throw new ReferenceError("Given config path must be a valid `.js` or `.json` file path")

**Comment by sanex3339** [comment]
Hi, show your full command, directory from what you ran it.

**Comment by sanex3339** [comment]
Ping.

**Comment by MichaelWayneLIU** [comment]
hi ,the full command is F:\test\js obfuscator>javascript-obfuscator   --config config.json        base.js -o xxx.js

**Comment by sanex3339** [comment]
Show me content of your config file please

**Comment by sanex3339** [comment]
Closed as inactive. Reopen issue if you will have additional info.
