### ISSUE TITLE
`domainLock` not working

### ISSUE THREAD

**Issue by Bogdanp** [javascript-obfuscator/javascript-obfuscator#260]
I'm unable to use the `domainLock` config. I get `data is not defined` whenever I use it.

## Expected Behavior

I expect passing a list of domain names to `domainLock` to lock the obfuscated scripts to those domains.

## Current Behavior

Passing any domains to `domainLock` makes the script throw `data is not defined` regardless of what domain it's visited on.

## Steps to Reproduce (for bugs)

Using javascript-obfuscator version 0.15 or 0.16, obfuscate the script with the following options:

```javascript
const OBFUSCATION_OPTIONS = {
  domainLock: ['.examplea.com', '.exampleb.com'],
};
```

Finally, run a web server and point examplea.com or exampleb.com to localhost in your `/etc/hosts` file then try to load the script in an html file.

EDIT: This is also reproducible on https://obfuscator.io. If you obfuscate the sample script and lock it to `.obfuscator.io` then try to evaluate it, it'll fail.

## Your Environment

* Version used: 0.15 and 0.16

**Comment by Bogdanp** [comment]
Just confirmed that this was me misunderstanding how `domainLock` worked. It appears both styles are needed for an obfuscated script to work on a domain and all its subdomains (i.e. `domainLock: ["example.com", ".example.com"]`, not `domainLock: [".example.com"]`).

**Comment by Bogdanp** [comment]
It looks like there is an issue here after all. Wildcard domains don't work. i.e. while `domainLock: ["example.com"]` works just fine for http://example.com, `domainLock: [".example.com"]` doesn't work for any of its subdomains.

**Comment by sanex3339** [comment]
Reproduced it. Will fix it soon.

**Comment by sanex3339** [comment]
Fix in master branch. Until 0.17.0 release (when it's done) you can use version from master branch.

**Comment by Bogdanp** [comment]
Great! Thank you!

**Comment by sanex3339** [comment]
0.17.0 version in out!
