### ISSUE TITLE
Web version produces non-working code for a few days ("data is not defined")

### ISSUE THREAD

**Issue by serginho31** [javascript-obfuscator/javascript-obfuscator#261]
## Current Behavior
Until a few days ago, your website was working perfectly.
But now, it fails every time. The generated code has a bug "data is not defined".
See steps to reproduce below

## Steps to Reproduce (for bugs)
1. consider the following script:
console.log("foo")
2. Execute it
3. It works, the console says "foo"
4. Go to https://obfuscator.io/ and obfuscate that script. You can select or unselect any options, it doesn't matter for the following steps
5. You get something like this:
var c = function () {
    var e = !![];
    return function (f, g) {
        var h = e ? function () {
            if (g) {
                var i = g['apply'](f, arguments);
                g = null;
                return i;
            }
        } : function () {
        };
        e = ![];
        return h;
    };
}();
var d = c(this, function () {
    var j;
    try {
        var k = Function('return\x20(function()\x20' + '{}.constructor(\x22return\x20this\x22)(\x20)' + ');');
        j = k();
    } catch (l) {
        j = window;
    }
    var m = function () {
        return {
            'key': 'item',
            'value': 'attribute',
            'getAttribute': function () {
                for (var n = 0x0; n < 0x3e8; n--) {
                    var o = n > 0x0;
                    switch (o) {
                    case !![]:
                        return this['item'] + '_' + this['value'] + '_' + n;
                    default:
                        this['item'] + '_' + this['value'];
                    }
                }
            }()
        };
    };
    var p = new RegExp('[]', 'g');
    var q = ''['replace'](p, '')['split'](';');
    var r;
    var s;
    for (var t in j) {
        if (t['length'] == 0x8 && t['charCodeAt'](0x7) == 0x74 && t['charCodeAt'](0x5) == 0x65 && t['charCodeAt'](0x3) == 0x75 && t['charCodeAt'](0x0) == 0x64) {
            r = t;
            break;
        }
    }
    for (var u in j[r]) {
        if (u['length'] == 0x6 && u['charCodeAt'](0x5) == 0x6e && u['charCodeAt'](0x0) == 0x64) {
            s = u;
            break;
        }
    }
    if (!r && !s || !j[r] && !j[r][s]) {
        return;
    }
    var v = j[r][s];
    var w = ![];
    for (var x = 0x0; x < q['length']; x++) {
        var s = q[x];
        var z = v['length'] - s['length'];
        var A = v['indexOf'](s, z);
        var B = A !== -0x1 && A === z;
        if (B) {
            if (v['length'] == s['length'] || s['indexOf']('.') === 0x0) {
                w = !![];
            }
            break;
        }
    }
    **if (!w) {
        data;
    } else {
        return;
    }**
    m();
});
d();
console['log']('foo');

6. Execute it anywhere (browser, jsfiddle, ...)
7. You get an error:
Uncaught ReferenceError: data is not defined
    at (index):157
    at h ((index):88)
    at window.onload ((index):163)

## Your Environment
Chrome 66.0.3359.139 - 64bits

# Stack trace
Uncaught ReferenceError: data is not defined
    at (index):157
    at h ((index):88)
    at window.onload ((index):163)

![image](https://user-images.githubusercontent.com/39272897/40008269-33fb8bf0-579f-11e8-99aa-09c258c9360d.png)

IMPORTANT NOTE: That is just 1 bug I found in the console, but it seems there are other regressions since a few days ago. Like some code is not executed (but no stack trace in console). Before a few days ago, everything was working perfectly.

That is very annoying because you website was the best obfuscator online ever, and I'm using it for a very important software. 
I'm a huge fan of https://obfuscator.io/
This is why I'm craving for it to work like it worked before :)

Thanks.

**Comment by sanex3339** [comment]
This error is happens when you trying to run code that obfuscated with `domainLock` feature on wrong domain.

**Comment by serginho31** [comment]
Nope, I don't have domain lock.

![image](https://user-images.githubusercontent.com/39272897/40008548-db9a3942-579f-11e8-8d06-3bca03348ee6.png)

**Comment by serginho31** [comment]
Even if I uncheck all options and try to obfuscate some code as simple as "console.log('foo')", then when I execute it, I get that error.

**Comment by sanex3339** [comment]
From my side i should ignore empty values on web UI

**Comment by serginho31** [comment]
Woooow ! That's crazy I did not see it :)
I'm sorry for opening a ticket while it actually works
Thank you a lot !
Bye

**Comment by sanex3339** [comment]
Now empty values won't be added to the entries
