### ISSUE TITLE
mangled obfuscation breaks project while hexadecimal one works just fine

### ISSUE THREAD

**Issue by ArtemBogush** [javascript-obfuscator/javascript-obfuscator#262]
I'm using quite a few 3rd party libs in my projects, pack them in one file and obfuscate the whole file. 

Everything works just fine with **hexadecimal** generator but if I switch to **mangled** the projects starts to throw errors at random places like `"can't execute 'sdf' of undefined"` or `"kjh is not a function"` (using `seed: 0` and `deadCodeInjection:true`)

Just to give you some glue, those errors might be connected with using jquery in the same file but again, hexadecimal obfuscation works just fine.
It also makes difference if I switch on or off disableConsoleOutput option: with `disableConsoleOutput:true` and removing `deadCodeInjection` everything seems to work, while `(disableConsoleOutput:false or deadCodeInjection:true) + mangled` breaks the project.

I can't paste any code unfortunately but I'll leave the description here to bring your attention - maybe it will help to improve the great library even further!

**Comment by sanex3339** [comment]
Hi. At first - never obfuscate 3rd party because after obfuscation code will run much slower, so your whole project will run slower.

About your problem. How did you bundle files? With webpack or just concatenated files in one file?
Try to use `identifiersPrefix` option of obfuscator.

**Comment by ArtemBogush** [comment]
Hi, thanks for your tip - I'll consider this.

As for the bundle - it's just a concatenated file. I'll have a look at `identifiersPrefix` as well, but as I've mentioned above, with the hexadecimal generator everything works as expected.

**Comment by sanex3339** [comment]
For concatenated file try to use `identifiersPrefix` option alongside with `mangled` generator.

**Comment by sanex3339** [comment]
Closed as inactive. Please, reopen new issue if you will have additional info.
