### ISSUE TITLE
Improve `ObjectExpressionKeysTransformer` to works with `MemberExpression`

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/javascript-obfuscator#264]
I should improve `ObjectExpressionKeysTransformer` to works with `MemberExpression` nodes.

**Comment by sanex3339** [comment]
Looks like it was more easily than i expected.

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/265

**Comment by kenma9123** [comment]
@sanex3339 glad to hear that. Thanks!

**Comment by sanex3339** [comment]
0.17.0 version in out!
