### ISSUE TITLE
"Human readable" obfuscation option

### ISSUE THREAD

**Issue by arthabus** [javascript-obfuscator/javascript-obfuscator#268]
I was trying to submit a chrome extension obfuscated with the library with no success - they want it to be "human readable". Since it's commercial product, I can't publish it in open source and still looking for some kind of obfuscation.

I've ended up moving to uglify and adding kind of a hack so wondering if the following is possible/can be easily added in the library:

alongside with mangled/hex obfuscation generator to have something like "random words" generator so it will pick from a list of random english words to use for obfuscation - while it will be human readable the code won't make much sense, just like with other generators.

I've ended up moving to doing this manually (downloaded 5000 most frequent english words and mapped them with the functions in my project) - quite time consuming and I thought to propose it here since the library is really great and offers a good level of obfuscation so maybe it can be extended even further.

Or maybe there is a way for me to implement a custom generator and to supply it to the obfusctor?

**Comment by sanex3339** [comment]
Hi. I though about generator with random words. So, it can be nice feature.

**Comment by slig** [comment]
> Or just add function value for identifierNamesGenerator option.

This would be great. It would make possible to build #155 easily. One suggestion is to add one parameter to this function: a ID to uniquely identify the variable (so a `foo` variable on the same scope would have the same ID, and on other scope another ID).

**Comment by sanex3339** [comment]
> ID to uniquely identify the variable

I should investigate this, because this is really hard part for current architecture.

**Comment by ArtemBogush** [comment]
@sanex3339 Thanks for your quick reply.

 I'm wondering based on your comment:

> Or just add function value for identifierNamesGenerator option.

Is this something I can do right in the gulp script? Like providing a function that can return a word based on incoming function parameter or something:

```
identifierNamesGenerator:function(param){
      return wordsMapping[param];
}
```

Or did I misunderstand it?

**Comment by sanex3339** [comment]
I'm doing some work related with this. All progress will here:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/282

There many work.

**Comment by ArtemBogush** [comment]
thanks for the update @sanex3339 - really looking forward to it as maintaining mapping manually for new functions/variables + refactoring appeared to be not that trivial task :)

**Comment by zamotkin** [comment]
@sanex3339 thanks for a good start, I'll to finish it.

**Comment by slig** [comment]
Thank you @zamotkin for helping so much!

**Comment by sanex3339** [comment]
Hi. Right now you can use new dictionary identifier names generator that will out soon in 0.20.0 version.

**Comment by sanex3339** [comment]
Closed in favor of https://github.com/javascript-obfuscator/javascript-obfuscator-ui/issues/42
