### ISSUE TITLE
Obfuscation and reflection

### ISSUE THREAD

**Issue by jolafrite** [javascript-obfuscator/javascript-obfuscator#27]
Hi,
I'm facing a problem with angular1

I have a class :
```js
@Provider()
export default class User {}
```

The decorator:
```js
function Provider() {
  return function decorator(target) {
    module.provider(target.name, target);
  };
}
```

The class is obfuscated so when I try to register my provider using reflection, I get the obfuscated version of the class name.
This looks logical but breaks the application. Do you have an idea to solve this issue ?

**Comment by sanex3339** [comment]
1) You can add class names to `reservedNames` option (array of strings).
2) You can pass second argument `className` to the decorator and manually pass all class names as string, like it have done with DI in angular 1.

**Comment by jolafrite** [comment]
I have to find a way to automatize this.
I'm surprise babel doesn't explicitly set ```class.name = "User";```

**Comment by sanex3339** [comment]
So, i can close issue?

**Comment by jolafrite** [comment]
Yes many thanks for your help
