### ISSUE TITLE
Minify, Compress, Optimize, Obfuscate

### ISSUE THREAD

**Issue by Extarys** [javascript-obfuscator/javascript-obfuscator#272]
Was it the right order?

## Expected Behavior

The user have the possibility/option to minify, compress and optimize the code before obfuscating it.

## Current Behavior
Currently it seems it only minify then obfuscate.

Closure Compiler seems to minify, optimize and compress but doesn't obfuscate. This library seems to be doing an amazing job at obfuscating.

By optimizing the code before obfuscating it with dead code, it would improve overall performance and file size and add more awesomeness to this library.

**Comment by sanex3339** [comment]
This library should do one thing. You can optimize code before obfuscation with other tools.
Also obfuscator has `identifierNamesGenerator: 'mangled'` for minification.

**Comment by Extarys** [comment]
Ok thanks for your time and your answer.
I read something about jscrambler that they do "everything" and that a good obfuscator should be able to do all of them. But indeed making them a separate process makes 1) less work 2) better tuning.

Could I optimize with Closer Compiler before using this without issues? Is it recommended?

**Comment by sanex3339** [comment]
You can.

**Comment by Extarys** [comment]
Awesome thx (I still have issues with Closer compiler that is why I cannot test it right now)
