### ISSUE TITLE
domainLock should work in SVG like in HTML

### ISSUE THREAD

**Issue by srguiwiz** [javascript-obfuscator/javascript-obfuscator#273]
## Expected Behavior
domainLock should work in SVG like in HTML.

## Current Behavior
JavaScript in SVG always fails if using domainLock.

## Steps to Reproduce (for bugs)
Any JavaScript file included in SVG will fail if domainLock.

Problem apparently is it looks for `document.domain`, which only is there in HTML, but not in SVG.

What it should do is if `document.domain` doesn't exist it should look at `document.location.hostname`, which is there in SVG.

Apparently `document.location.hostname` is there in both HTML and SVG, maybe just use that.

Wasn't able to tell for sure how that code works in `javascript-obfuscator/src/templates/domain-lock-nodes/domain-lock-node/DomainLockNodeTemplate.ts` else would have forked and tried to fix.

**Comment by srguiwiz** [comment]
I have succeeded at rigging my locally installed copy to run in both SVG and HTML with `DomainLockNodeTemplate.ts` having

```
if ((!document && !domain) || (!that[document] && !that[document][domain] &&
     !that[document]["location"] && !that[document]["location"]["hostname"])) {
    return;
}

var currentDomain = that[document][domain] || that[document]["location"]["hostname"];
```

but as I see interesting choices made around that, I let @sanex3339 pick how exactly he wants to roll that in.

As mentioned, maybe just use `document.location.hostname` instead of `document.domain` for less conditionals, shorter overall code?

**Comment by sanex3339** [comment]
0.17.0 version in out!
