### ISSUE TITLE
The sources field in the generated sourceMap is always ["sourceMap"]

### ISSUE THREAD

**Issue by zhaochy1990** [javascript-obfuscator/javascript-obfuscator#276]
I obfuscate my code use config 
```
{
    compact: true,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 1,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: false,
    identifierNamesGenerator: 'hexadecimal',
    log: true,
    renameGlobals: false,
    rotateStringArray: true,
    selfDefending: true,
    stringArray: true,
    stringArrayEncoding: 'rc4',
    stringArrayThreshold: 1,
    transformObjectKeys: true,
    unicodeEscapeSequence: false,
    sourceMap: true,
    sourceMapMode: 'inline',
}
```
after I decode the base64 encoded sourceMap, I found "sources":["sourceMap"], this made all the error stack shows the correct line number with wrong filename ''sourceMap"

## Expected Behavior

the error stack from a file `a.js` should have error stack with filename `a.js`

## Current Behavior

the error stack from a file `a.js` have error stack with filename `sourceMap.js`

## Steps to Reproduce (for bugs)

1. create a file 'a.js'
2. the first line of 'a.js' should `require('source-map-support').install();`.
3. throw error in 'a.js', use `console.log()` print the error stack
4. do obfuscate with the config above
5. run the obfuscated `a.js`
6. the error stack show the bug

## Your Environment

* Version used:
node: 8.10.0
javascript-obfuscator: latest

# Stack trace

**Comment by sanex3339** [comment]
You using CLI version, right?

**Comment by sanex3339** [comment]
Problem here:
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/JavaScriptObfuscator.ts#L200

**Comment by zhaochy1990** [comment]
Thanks @sanex3339. I'm using `gulp-javascript-obfuscator`. It seems the filename is hardcoded.

**Comment by sanex3339** [comment]
Ok. Looks like the best way is to add new option `inputFileName` (optional), so source map source name will based on this option value. With CLI this option will replaced by actual input file name. But plugins, like gulp plugin should be updated to support new option.

**Comment by sanex3339** [comment]
Fix in `master` branch now. Until release you can use version from `master` branch.

When 0.17.0 will released, you have two options:
* wait until author of plugin manually added passthrough of input file name to the `inputFileName` option
* manually add input file name as value of `inputFileName` option.

**Comment by sanex3339** [comment]
What you mean when saying `raw`?

**Comment by sanex3339** [comment]
Obfuscator has two interfaces: CLI and Node API.

With CLI - obfuscator reads file and know file name of this file. With CLI obfuscator passing internally`inputFileName` based on name of the input file, and as result - you wont to do this manually. `inputFileName` is not available with CLI.

With Node API (all plugins use this variant) obfuscator know nothing about files. It obfuscating strings with source code and you should pass `inputFileName` value, so obfuscator will know name of the file that contains source code.

**Comment by sanex3339** [comment]
0.17.0 version in out!
