### ISSUE TITLE
"\0" and "\u0000" being converted to NUL character

### ISSUE THREAD

**Issue by derrickb** [javascript-obfuscator/javascript-obfuscator#281]
## Expected Behavior
The character is left in its original format

## Current Behavior
In obfuscated file, the code is converted to the NUL character, which doesn't work in my use case.

![image](https://user-images.githubusercontent.com/1793769/41195010-4761c1ea-6c1d-11e8-998b-ada5ee781b79.png)

## Your Environment

* Version used: 0.16.0
* Windows 10 Pro

## Minimal working example that will help to reproduce issue

`var nullChar = '\0';`

**Comment by sanex3339** [comment]
Can you reproduce it on the latest versions?

**Comment by kittenswolf** [comment]
I can confirm that this was fixed.

**Comment by sanex3339** [comment]
Ok. If you will have this error, create a new issue
