### ISSUE TITLE
javascript obfuscator changes the browser's finger print

### ISSUE THREAD

**Issue by levineran** [javascript-obfuscator/javascript-obfuscator#283]
fingerprintjs2 is a very popular finger printing library.
whenever I try to obfuscate the library, my browser's  finger print changes.
 What is odd, that it changes only once, meaning that if I will re-obfuscate, the finger print won't change and remain constant (which leads me to assume that the obfuscation breaks something)
## Expected Behavior
The finger print should not be changed compared to non-obfuscate code.

## Current Behavior
finger print should be not changed

## Steps to Reproduce (for bugs)

1.install fingerprintjs2 
2. get your browser finger print in index.html (in the library )
3. obfuscate fingerprint2.min.js
4. redo 2, and see that you get a different result.

## Your Environment

* Version used:  0.16.0
windows 10, chrome 67

## Minimal working example that will help to reproduce issue

example files:
[dist.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/2130332/dist.zip)

**Comment by sanex3339** [comment]
Hi, as i wrote in the README - don't obfuscate third-party libraries.
I don't know how this library works.
Try to uglify library with UglifyJS2. It will work as expected?

If no - it is a library problem. 

If yes - let me know and i'll investigate this.

**Comment by sanex3339** [comment]
Ping

**Comment by levineran** [comment]
Hey there. My computer is dead, it will take a while to answer.

בתאריך יום ד׳, 27 ביונ' 2018, 12:30, מאת Timofey Kachalov ‏<
notifications@github.com>:

**Comment by sanex3339** [comment]
Ok

**Comment by sanex3339** [comment]
Ping
