### ISSUE TITLE
Query: Option to obfuscate JS code present in HTML extension file?

### ISSUE THREAD

**Issue by ajaykools** [javascript-obfuscator/javascript-obfuscator#284]
How can we obfuscate JavaScript code present in HTML page with extension ".html".
Most of the times JavaScript is defined in HTML page and want to obfuscate whole single page (Obfuscate JS, minify HTML), how can we achieve this using "javascript-obfuscator" tool?

I know solution can be moving all JS code to separate ".js" file. But sometimes we dont want to move JS code to separate file and import in HTML page.

## Expected Behavior

Option to provide extensions like "--input_file_extensions html, htm, js".
This option should search for all file present in mentioned directory or sub-subdirectory, if JS code is present in between <script> tag then that particular section of JS code to be obfuscated.

## Current Behavior

No provision of obfuscating JS code present in HTML page. May be I don't know or not documented if already available.
Please let me know if already such option is available.
## Your Environment

* Version used:
0.16.0

#### Input
```
<HTML>
  <BODY>
      You can define you JavaScript here
      <script>
          var variable = "Hello World";
      </script>
  </BODY>
</HTML>
```

#### Output
```
<HTML>
  <BODY>
      You can define you JavaScript here
      <script>
          var _0x234eab = a10_0x15ca;
      </script>
  </BODY>
</HTML>
```

**Comment by sanex3339** [comment]
Hi. This is not planned. Use other tools to extract js code from .html files and pass it to the obfuscator.

**Comment by ajaykools** [comment]
Are you adding this suggestion in your roadmap or todo list?
