### ISSUE TITLE
Error: Cannot read property 'ecmaFeatures' of undefined

### ISSUE THREAD

**Issue by shaji-Dev** [javascript-obfuscator/javascript-obfuscator#287]
Hi,

I'm getting this error when trying to obfuscate the code in Node.js:

Error: Cannot read property 'ecmaFeatures' of undefined
    at Function.value (C:\Users\smiki\WebstormProjects\measure-map-web\awesome-obfuscator-html\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\EspreeFacade.ts:82:19)
    at Function.value (C:\Users\smiki\WebstormProjects\measure-map-web\awesome-obfuscator-html\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\EspreeFacade.ts:44:46)
    at e.value (C:\Users\smiki\WebstormProjects\measure-map-web\awesome-obfuscator-html\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:153:29)
    at e.value (C:\Users\smiki\WebstormProjects\measure-map-web\awesome-obfuscator-html\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscator.ts:134:46)
    at Function.value (C:\Users\smiki\WebstormProjects\measure-map-web\awesome-obfuscator-html\node_modules\javascript-obfuscator\dist\webpack:\JavaScriptObfuscator\src\JavaScriptObfuscatorFacade.ts:31:76)

But doing it from the console works just fine.

Is there anything missing in my node_modules? Here are the dependencies in package.json:

...
  "dependencies": {
    "cheerio": "^0.22.0",
    "chokidar": "^2.0.4",
    "co": "^4.6.0",
    "html-minifier": "^3.5.18",
    "javascript-obfuscator": "^0.17.0",
    "mkdirp": "^0.5.1",
    "pify": "^3.0.0",
    "polymer-bundler": "^4.0.2",
    "yargs": "^12.0.1",
    "parse5": "^5.0.0",
    "eslint": "^5.0.1"
  }
....

**Comment by sanex3339** [comment]
Hi. Try to disable eslint, same error will happen few weeks ago and disabling of eslint was help.

**Comment by shaji-Dev** [comment]
Could you please tell me how to disable it? I'm not sure how to do so? In the .eslintrc.json file or the package.json file? Thank you.

**Comment by sanex3339** [comment]
Hi, check this 
https://github.com/javascript-obfuscator/webpack-obfuscator/issues/35

**Comment by sanex3339** [comment]
What is `awesome-obfuscator-html`? Can't found this package in `npm`

**Comment by sanex3339** [comment]
This error happens with any input code?

**Comment by sanex3339** [comment]
Can you sent me a project (via email) that will help me reproduce this error?

**Comment by shaji-Dev** [comment]
I don't think the issue is with the code, because I use the same code on my other computer and it runs fine. I get this error as if something is missing on my computer or something. All the code runs fine until I call this line:

var output = jsObfuscator.obfuscate(input, {
                compact: true
            }).getObfuscatedCode();

No need to have the full code, it crashed here in this line, the rest of the code is fine. Tried messing with a lot of options to obfuscate the code and still gives the same error. I'm using it the same way as in the documentation.

**Comment by shaji-Dev** [comment]
Ok, here's how it was FIXED:

I had the packages imported in the code in this order:


`
const {minify: htmlMinify} = require('html-minifier');
const co = require('co');
const p = require('pify');
const path = require('path');
const chokidar = require('chokidar');
const cheerio = require('cheerio');
const fs = require('fs');
**const jsObfuscator = require('javascript-obfuscator');**
const mkdirp = require('mkdirp');

const parse5 = require('parse5');

const {Bundler} = require('polymer-bundler');
const bundler = new Bundler({
    excludes: [],
    inlineScripts: true,
    inlineCss: true,
    rewriteUrlsInTemplates: false,
    stripComments: true,
});`

I simply moved the javascript-obfuscator to the end and it worked!
 
`const {minify: htmlMinify} = require('html-minifier');
const co = require('co');
const p = require('pify');
const path = require('path');
const chokidar = require('chokidar');
const cheerio = require('cheerio');
const fs = require('fs');
const mkdirp = require('mkdirp');

const parse5 = require('parse5');

const {Bundler} = require('polymer-bundler');
const bundler = new Bundler({
    excludes: [],
    inlineScripts: true,
    inlineCss: true,
    rewriteUrlsInTemplates: false,
    stripComments: true,
});
**const jsObfuscator = require('javascript-obfuscator');**`

After testing moving the require for the `javascript-obfuscator` one line down everytime to see after which package it should reside, it appears that it cannot before the `polymer-bundler`, it has to be after, some sort of conflict in libraries or something..

Anyways, now it's fixed.
