### ISSUE TITLE
object not renaming

### ISSUE THREAD

**Issue by ewwink** [javascript-obfuscator/javascript-obfuscator#289]
I set "Transform Object Keys" to true.
input 
```
function tes() {
  return { 'key': 'val' }
}
```
output

```
function _0x331670() {
    return { 'key': '\x76\x61\x6c' };
}
```

it should be like this or not?
```
function _0x331670() {
    return { '\x6b\x65\x79': '\x76\x61\x6c' };
}
```

**Comment by sanex3339** [comment]
At first, `Transform Object Keys` option is not affects your example, but looks like keys should be encoded with `unicode escape sequence`

**Comment by ewwink** [comment]
OK thank you very much.

**Comment by sanex3339** [comment]
Out in `javascript-obfuscator@0.17.1`
