### ISSUE TITLE
Error with es6 destructuring

### ISSUE THREAD

**Issue by eltiodelsofa** [javascript-obfuscator/javascript-obfuscator#29]
Create test.js file with

```js
function foo({bar}) {
  return bar;
}

foo({bar: 'baz'});
```

$ javascript-obfuscator test.js
$ node test-obfuscated.js

ReferenceError: _0x5c1443 is not defined

`_0x5c1443` is `bar` in original `return bar;` but `foo({bar})` can not be changed.
I think the only solution is with _0x5c1443 = obj.bar;
I am using babel over the obfuscated file to solve the problem

$ node -v
v6.9.4

$ javascript-obfuscator --version
0.8.4

**Comment by sanex3339** [comment]
Thank you for the issue. I will fix it later today.

**Comment by sanex3339** [comment]
Looks like you changed your example from `array destructing` to `object destructing`. Object destructing is `es2017` feature and `es2017` currently not supported by `javascript-obfuscator` because stable `esprima` doesn't support it.

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.8.5` and `webpack-obfuscator@0.8.5` are out

After fix all `Identifier` nodes inside object destructing inside function params and variable declaration will be skipped, so after obfuscation your example will be like:

```js
    function _0x303cfa({
        bar
    }) {
        return bar;
    }
    _0x303cfa({
        '\x62\x61\x72': '\x62\x61\x7a'
    });
```

**Comment by sanex3339** [comment]
Hoops, i forget about catch clause =(

**Comment by sanex3339** [comment]
javascript-obfuscator@0.8.6 and webpack-obfuscator@0.8.6 are out (with fix of CatchClause node ObjectPattern parameter)

**Comment by sanex3339** [comment]
Also latest changes available under `dev` tag - `javascript-obfuscator@0.9.0-dev.10` or `javascript-obfuscator@dev`

**Comment by eltiodelsofa** [comment]
Thanks for the quick fix, its works perfect.
IMO is bad idea to make that babel do with variables because the purpose of the library is obfuscate, not transform es6 in es5. If someone want this behavior, always can use babel before obfuscate it.

**Comment by sanex3339** [comment]
Thank you!
