### ISSUE TITLE
Feature request: seed = source crc

### ISSUE THREAD

**Issue by alpha-and-omega** [javascript-obfuscator/javascript-obfuscator#292]
Web cache is very important for large javascript projects.
By default javascript-obfuscator uses random seed, and this prevents caching of unmodified source files.
Providing static seed probably not very secure.

I suggest adding a new option: seed = crc of the source files, probably with a salt.
This algorithm will keep obfuscated files unchanged for unmodified source files, while protecting new sources with a new seed.

**Comment by ewwink** [comment]
it not related to issue just asking. if I set seed with higher value will generated code have slower performance?

**Comment by sanex3339** [comment]
No

**Comment by sanex3339** [comment]
Closed as old.
