### ISSUE TITLE
Composed source map

### ISSUE THREAD

**Issue by mastef** [javascript-obfuscator/javascript-obfuscator#298]
Scenario :  

1. You've built a .js file from .ts or coffee script with source maps enabled
2. You've uglified the resulting .js files, inheriting the source maps ( with the composed source map option )
3. Now you want to obfuscate the .js files, but you lose your existing source map bindings, as the resulting source map refers to the uglified .js, instead of the original sources

Would it be possible to take existing source maps into account when generating new source maps? This process is called "[composed source map](https://github.com/mishoo/UglifyJS2#composed-source-map)" in uglifyjs. ( `uglifyjs --source-map "content='existing.map'" // Input source map, useful if you're compressing JS that was generated from some other original code.` )

The idea is that if \x12\x02 fails with undefined, it will refer you to the correct .ts / .coffee file and line number, instead of the compiled uglified .js file.

**Comment by mastef** [comment]
I'm currently testing if sorcery can fix this https://github.com/rich-harris/sorcery

**Comment by sanex3339** [comment]
Can you add example of your sorcery code?

**Comment by mastef** [comment]
Just `sorcery -i code.min.js -o newfile.min.js`

I was fighting with filenames and infinite loops at first ( something about source maps referencing themselves ), so for simplicity's sake the whole thing ended up as something like this : 

```bash
// input file is a generated file.js which has a
// file.js.min source-map that links to 3rd party
// source files ( e.g. typescript, haxe, etc )
// also: removed most options for clarity

uglifyjs \
    --compress \
    --output "file_min.js" \
    -b max_line_len=1000,beautify=false \
    --source-map "content='file.js.map',url='file_min.js.map',filename='file_min.js.map'" \
    -- "file.js"

javascript-obfuscator \
    file_min.js \
    --output file_obf.js \
    --rotate-string-array true \
    --source-map true \
    --source-map-mode separate 

rm file.js
rm file.js.map

sorcery -i file_obf.js -o file.js

rm file_obf.js
rm file_obf.js.map
rm file_min.js
rm file_min.js.map

// result:
// file.js
// file.js.map
// with embedded source-file references
```
