### ISSUE TITLE
CLI examples in readme have wrong syntax

### ISSUE THREAD

**Issue by mastef** [javascript-obfuscator/javascript-obfuscator#299]
The CLI examples in the readme, like e.g. `javascript-obfuscator input.js --output out.js --sourceMap true --sourceMapBaseUrl 'http://localhost:9000' --sourceMapFileName example` have the wrong syntax. They use the JS options syntax, instead of the CLI syntax.

The example in this case should be : 
`javascript-obfuscator input.js --output out.js --source-map true --source-map-base-url 'http://localhost:9000' --source-map-file-name example`

I was fighting with this for a bit wondering why the source maps were not generated.

**Comment by sanex3339** [comment]
Wow, thank you. Eill fix it today

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.18.0` is out!
