### ISSUE TITLE
Old NPM package version

### ISSUE THREAD

**Issue by ritmas** [javascript-obfuscator/javascript-obfuscator#301]
Since commit [4aff0ec](https://github.com/javascript-obfuscator/javascript-obfuscator/commit/4aff0ec0462774ca2bc6f34a3f009e3f1edf3ba8) (v0.18.0-dev.1) new option `reservedStrings` was introduced, but on [npmjs.com](https://www.npmjs.com/package/javascript-obfuscator) it's still v0.17.1
Any ETA of new NPM package release?

**Comment by sanex3339** [comment]
Hi. No release date yet, but i want to release 0.18.0 after `DateLock` feature will completed. Expect late august, early september. Until release you can use version from `master` branch of this repository.
