### ISSUE TITLE
TypeScript support is broken

### ISSUE THREAD

**Issue by tyronedougherty** [javascript-obfuscator/javascript-obfuscator#303]
The `interfaces/IObfuscationResult` type seems to no longer exist (instead it looks like it has been replaced with `interfaces/source-code/IObfuscatedCode` ).

This means you are unable to use the `getObfuscatedCode()` method on the result of `obfuscate()`.

Here are some screenshots to demonstrate the issue:

![screen shot 2018-07-31 at 1 57 16 pm](https://user-images.githubusercontent.com/4608024/43436996-39b5dc2c-94ca-11e8-9dd9-cd44fcef31b7.png)
![screen shot 2018-07-31 at 1 57 07 pm](https://user-images.githubusercontent.com/4608024/43436999-3b51aeee-94ca-11e8-8fc5-5785cce930a6.png)
![screen shot 2018-07-31 at 1 56 55 pm](https://user-images.githubusercontent.com/4608024/43437010-46b38d98-94ca-11e8-962e-fc64c5793d1f.png)

**Comment by tyronedougherty** [comment]
I've submitted a PR that fixes this issue, and would love for it to be merged :)

**Comment by sanex3339** [comment]
PR:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/305

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.17.3` is out
