### ISSUE TITLE
Obfuscate contents of a directory and overwrite existing files 

### ISSUE THREAD

**Issue by shazaddin** [javascript-obfuscator/javascript-obfuscator#306]
javascript-obfuscator ./www/scripts/

The above command obfuscates all the JS files under the scripts folder. However it creates a new file for each found JS file. I am obfuscating my code base and do not want to create new files i want to overwrite existing files. 

My JS files are referenced from index.html therefore i do not want to rename them.  If they are renamed then all my codebase breaks. I cannot see an option that allows me to specify to overwrite existing files. 

Thanks

**Comment by sanex3339** [comment]
It's dangerous, i won't add this feature, because you can loose all your original code after obfuscation.
