### ISSUE TITLE
Renaming issue

### ISSUE THREAD

**Issue by sashee** [javascript-obfuscator/javascript-obfuscator#307]
For this script, the obfuscator produces incorrect results:

```
const arr = [{id: "id"}];
arr.map(({id}) => {
    arr.filter(({id: newid}) => {
      return id !== newid;
    });
})
```

## Expected Behavior

The resulting obfuscated script should run without errors

## Current Behavior

It produces ```c is not defined``` error.

## Steps to Reproduce (for bugs)

1.Open [https://obfuscator.io/](https://obfuscator.io/)
2. Paste this code:

```
const arr = [{id: "id"}];
arr.map(({id}) => {
    arr.filter(({id: newid}) => {
      return id !== newid;
    });
})
```
3. Click Obfuscate
4. Click Evaluate and observe the error

## Your Environment

* Version used: 0.17.3

# Stack trace

**Comment by sanex3339** [comment]
PR:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/310

**Comment by sanex3339** [comment]
Fix in `master` branch. Until `0.18.0` release you can use version from `master` branch

**Comment by vipin-mehta** [comment]
I am facing same bug, please release this bug fix as 0.17.4 patch release asap because current stable version 0.17.3 is not working

**Comment by sanex3339** [comment]
I'll release 0.18.0 tomorrow with current closed issues.

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.18.0` is out!
