### ISSUE TITLE
"use strict"; causes comments to be kept

### ISSUE THREAD

**Issue by robinwassen** [javascript-obfuscator/javascript-obfuscator#308]
Running obfuscation on a file that has "use strict"; immediately followed by a comment will cause the comment to be preserved.

New lines has been added to the screenshot for clarity.

![screen shot 2018-08-07 at 16 01 40](https://user-images.githubusercontent.com/302151/43780580-38174158-9a5b-11e8-82e7-a424cfa23ff4.png)

## Expected Behavior
- The comment is removed

## Current Behavior
- The comment is preserved

## Steps to Reproduce (for bugs)
1. Run javascript-obfuscator on the sample below

## Your Environment
* Version used: HEAD of master

## Minimal working example that will help to reproduce issue

```
var strict1 = function () {
	"use strict";
	// comment1
};

var strict2 = function () {
	"use strict";
	/* comment2 */
	var a = 2;
	/* comment3 */
};

var strict3 = function () {
	"use strict";
	var a = 3;
	/* comment4 */
};

var noStrict = function () {
	/* comment5 */
	var a = 4;
	/* comment6 */
}
```

**Comment by zamotkin** [comment]
Fixed in 0.18.7
