### ISSUE TITLE
how to update the web UI with new version of javascript-obfuscator

### ISSUE THREAD

**Issue by qingweiqm** [javascript-obfuscator/javascript-obfuscator#31]
just want to know how to update the javascript-obfuscator on  UI.

Regards!

**Comment by sanex3339** [comment]
I think it's question to @slig 
https://github.com/javascript-obfuscator/javascript-obfuscator-ui

But i can predict what you should clone `javascript-obfuscator-ui
` repo and edit `package.json` and run UI locally https://github.com/javascript-obfuscator/javascript-obfuscator-ui#running-it

**Comment by slig** [comment]
@sanex3339 is right, just follow his instructions and it should work.

**Comment by qingweiqm** [comment]
I have the UI running with the from the newest repo, but not for sure its version, how to check it ?

**Comment by slig** [comment]
Open its `package.json` and you'll see that the `javascript-obfuscator` dependency is the last stable one. Change the version for the one that you want and run the procedure that @sanex3339 mentioned before.

**Comment by sanex3339** [comment]
Also latest beta version is 0.9.0-beta.2

**Comment by qingweiqm** [comment]
cool, fully understood. 
Many thanks!
