### ISSUE TITLE
Quotes not being properly transformed since 0.18

### ISSUE THREAD

**Issue by mastef** [javascript-obfuscator/javascript-obfuscator#319]
## Expected Behavior ( 0.17 )
```
var _0x411689 = new Error('Cannot\x20find\x20module\x20\x27' + _0x11707c + '\x27');
```
## Current Behavior ( 0.18 )
```
var _0x697240 = new Error('Cannot find module '' + _0x7af0b2 + '\x27');
```

## Steps to Reproduce (for bugs)
- Add *any* string to "Reserved Strings" option
- Try to obfuscate https://github.com/nodeca/pako/blob/master/dist/pako.min.js

## Your Environment

* Obfuscator version used: 0.18.1
* Node version used: 8.9.4

## Minimal working example that will help to reproduce issue
```
var s = "something";
var h=new Error("Cannot find module '"+s+"'");
```

**Comment by sanex3339** [comment]
Hi. Tried here: https://obfuscator.io/

Result:
```
var s = 'something';
var h = new Error('Cannot\x20find\x20module\x20\x27' + s + '\x27');
```

**Comment by mastef** [comment]
🤔 must be a setting although I had them all set to false. OK, I'll revert back in a moment

**Comment by mastef** [comment]
If I add any value to `reserved-strings` it happens for me : `javascript-obfuscator test.js --output test.obf.js --reserved-strings 'a'`

Also happens on the website, just by adding any reserved-string like e.g. 'a' and then pressing the + button. ( Missed that one when testing at first )

**Comment by sanex3339** [comment]
Will fix it in 0.18.2

**Comment by sanex3339** [comment]
PR with fix
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/322

**Comment by Slapbox** [comment]
@sanex3339 thanks for all your hard work on this. Is there at ETA for 0.18.2?

**Comment by sanex3339** [comment]
Next week. I bery busy right now and before release should fix wrong functions obfuscation
