### ISSUE TITLE
0.18.1 runs (seemingly) indefinitely on some files

### ISSUE THREAD

**Issue by Slapbox** [javascript-obfuscator/javascript-obfuscator#323]
I understand this is not an actionable bug report, but I am posting it so that the maintainers are aware this may be an issue.

I've got a file that took about 8 seconds to obfuscate in `0.16.0` which now took at least 10 minutes before I canceled it. The file I was attempting to obfuscate was an entry point for the main process of an `Electron@3.0.0-beta.7` application. My other files obfuscate in a comparable time as in `0.16.0`, though my sample size is quite small.

**Comment by sanex3339** [comment]
Interesting, can you upload this file?

**Comment by sanex3339** [comment]
Hi, i'll look into this issue but currently i take a 1-2 months timeout with this project to doing renovations on my flat. So, until october i'll have no time to look into this.

If i'll have time - i'll fix it.

**Comment by zamotkin** [comment]
@Slapbox if you still have this problem, please share a code with me, I'll try to solve it.

**Comment by Slapbox** [comment]
@zamotkin I downgraded long ago, but I see some fixes have been made since then so I'll share problem code when I upgrade, if it still occurs. It could be a while before I have a chance to give `0.18.x` a shot.

**Comment by sanex3339** [comment]
Any news?

**Comment by sanex3339** [comment]
Probably will be fixed in upcoming 0.24.0, in which i completely reworked how identifiers are renamed
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/503

**Comment by Slapbox** [comment]
@sanex3339 I tested `0.21.1` and didn't have this problem, although our code has also changed a lot, so, tough to say for sure whether it's fixed.

**Comment by sanex3339** [comment]
Ok, i will close. Reopen new issue if you will have the same problems
