### ISSUE TITLE
How to disable Parenthesis removal?

### ISSUE THREAD

**Issue by invertedvisuals** [javascript-obfuscator/javascript-obfuscator#325]
The obfuscator seems to remove all parenthesis it doesn't think are necessary, which has lead to several errors in my resulting code. Is there an option or workaround to disable this?

For instance

`if((conditionA && conditionB) || (conditionC && conditionD))`

gets converted to

`if(conditionA && conditionB || conditionC && conditionD)`

and other instances which is breaking my code. (in an Adobe Extendscript environment)

Thanks!

Current Specs:

javascript-obfuscator - 1.1.4 
Gulp - 3.9.1
Node - 6.4.0

**Comment by sanex3339** [comment]
Hi, i'll look into this issue but currently i take a 1-2 months timeout with this project to doing renovations on my flat. So, until october i'll have no time to look into this.

If i'll have time - i'll fix it.

**Comment by sanex3339** [comment]
Hi. This is `escodegen` problem. Not sure how to fix this.

**Comment by sanex3339** [comment]
Not sure how to fix it even on `escodegen` side. Closed as `wontfix`
