### ISSUE TITLE
Breaks conditional extends by removing parenthesis

### ISSUE THREAD

**Issue by johanjisu** [javascript-obfuscator/javascript-obfuscator#326]
## Expected Behavior
This should work after obfuscation:

export default Target => class Events extends (Target || Base) {

}

## Current Behavior
Obfuscation removes () around Target || Base, which breaks it.

(the code above is used for mixins, Base is an existing class)

## Your Environment
ES6

**Comment by sanex3339** [comment]
Hi, i'll look into this issue but currently i take a 1-2months timeout with this project to doing renovations on my flat. So, until october i'll have no time to look into this.

**Comment by johanjisu** [comment]
We currently work around it by regexing the parentheses back in place after obfuscation, so we are ok anyway. But would be nice to have it fixed when you have the time. Good luck with the renovation and thanks for a great utility!

**Comment by asifshfq** [comment]
> 
> 
> We currently work around it by regexing the parentheses back in place after obfuscation, so we are ok anyway. But would be nice to have it fixed when you have the time. Good luck with the renovation and thanks for a great utility!

Can you please elaborate this, because I am also facing the same issue.

**Comment by sanex3339** [comment]
Hi. This is `escodegen` problem. Will try to create a PR to the `escodegen`

**Comment by sanex3339** [comment]
I created the PR with fix for `escodegen`
It is better to ping this PR, because maintainers is not so active:
https://github.com/estools/escodegen/pull/404

**Comment by sanex3339** [comment]
Fixed in `0.23.2` release
