### ISSUE TITLE
option reservedNames not work

### ISSUE THREAD

**Issue by muzuiget** [javascript-obfuscator/javascript-obfuscator#327]
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/1d1b65b693f39edb5aeb6737939566557b18b0ec/src/node-transformers/obfuscating-transformers/obfuscating-replacers/identifier-obfuscating-replacers/BaseIdentifierObfuscatingReplacer.ts#L110

This shoule be a `reservedNames`?

**Comment by sanex3339** [comment]
Thank you, will fix it as soon as i'll have a time

**Comment by sanex3339** [comment]
Too late, but fixed in `0.19.4`
