### ISSUE TITLE
stringArray: true causing issues in Chrome and FF (browsers that do blobs) when using webpack

### ISSUE THREAD

**Issue by qchroman** [javascript-obfuscator/javascript-obfuscator#329]
Hello JS Obfuscator team,

First of all, thank you for the great product, it really kicks some... you know...

Now for the problem. I'm using webpack-obfuscator 0.18.0 and I have noticed that the stringArray: true causes some issues when using the webpack. It seems that the issue is in the webpacks bootstrap code. I have also noticed that this happens only in Chrome and Firefox i.e. browsers that uses blob:// to work with the code they loaded into their memory.

The unobfuscated code inside the blob looks as follows:

```
var fn = (function(modules) {
  // The module cache
  var installedModules = {};

  // The require function
  function __webpack_require__(moduleId) {

    // Check if module is in cache
    if(installedModules[moduleId]) {
      return installedModules[moduleId].exports;
    }
    // Create a new module (and put it into the cache)
    var module = installedModules[moduleId] = {
      i: moduleId,
      l: false,
      exports: {}
    };

    // Execute the module function
    modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

    // Flag the module as loaded
    module.l = true;

    // Return the exports of the module
    return module.exports;
  }
...
```

The obfuscated part of the code w/ the following config looks as follows.

Config:
```
new JavaScriptObfuscator({
    compact: true,
    controlFlowFlattening: false,
    deadCodeInjection: false,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: false,
    identifierNamesGenerator: 'hexadecimal',
    log: false,
    renameGlobals: false,
    rotateStringArray: true,
    selfDefending: false,
    stringArray: true,
    stringArrayEncoding: false,
    stringArrayThreshold: 0.75,
    unicodeEscapeSequence: false
})
```

Code:
```
var fn = (function(e) {
    var x = {};
    function a(t) {
        if (x[t])
            return x[t].exports;
        var _ = x[t] = {
            i: t,
            l: !1,
            exports: {}
        };
        return e[t].call(_.exports, _, _[_0x56ae("0x24")], a),
        _.l = !0,
        _[_0x56ae("0x24")]
    }
    return a.m = e,
...
```

You see that this:

`modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);`

became this:

`e[t].call(_.exports, _, _[_0x56ae("0x24")], a)`

And browser throws an error saying

> Uncaught ReferenceError: _0x56ae is not defined

When setting stringArray: false, the obfuscated code becomes:

```
var fn = (function(e) {
    var t = {};
    function i(n) {
        if (t[n])
            return t[n].exports;
        var r = t[n] = {
            i: n,
            l: !1,
            exports: {}
        };
        return e[n].call(r.exports, r, r.exports, i),
        r.l = !0,
        r.exports
    }
    return i.m = e,
...
```

That problematic line is now `e[n].call(r.exports, r, r.exports, i)` and this doesn't cause any issues.

I hope information I have provided will help you resolve the issue.

**Comment by sanex3339** [comment]
Firstly, try 0.17.3 version, 0.18.0 is very buggy.
Secondly, i'll look into all issues in october, currently i took a break in a few months.

**Comment by zamotkin** [comment]
@qchroman Did you try the latest 0.18.7 release? It should be fixed there.

**Comment by sanex3339** [comment]
Ping

**Comment by qchroman** [comment]
@sanex3339, Happy New Year!

Thank you for the update. I will check as soon as possible. Kind of got distracted from the project.

**Comment by sanex3339** [comment]
Hi, any news?

**Comment by sanex3339** [comment]
Any news?

**Comment by qchroman** [comment]
Hello @sanex3339,

I apologize for such a late response. I was removed from that project so I didn't have a chance to check the fix. I did it just now. It works ok. Thank you for your hard work! 

Best Regards
