### ISSUE TITLE
'\n' gets returned as '{newlinecharacter}'

### ISSUE THREAD

**Issue by rlaPHOENiX** [javascript-obfuscator/javascript-obfuscator#335]
Instead of doing `\\n` it does` \n` and actually parses it as a LF character.

## Expected Behavior
`'\\n'`

## Current Behavior
```
'
'
```

## Steps to Reproduce (for bugs)
1. Code to Obfuscate: var t = "Hello Bugs" + "\n"; 
2. Have everything default
3. Set both the reserved inputs as `.*`
4. Obfuscate. Done you will see.

## Your Environment
* Obfuscator version used: obfuscator.io
* Node version used:obfuscator.io

**Comment by sanex3339** [comment]
Need more info. Closed as old. Please reopen another issue if you still have this problem
