### ISSUE TITLE
Problems with fesm5 export import  from 

### ISSUE THREAD

**Issue by LabDeve** [javascript-obfuscator/javascript-obfuscator#336]
* Obfuscator version used:
`"javascript-obfuscator": "^0.18.1"`

* Node version used:
`8`

# Stack trace while using my lib
`
ERROR in ./node_modules/@my/lib/fesm5/mylib.js
Module parse failed: Unexpected token (1:4028)
You may need an appropriate loader to handle this file type.
.....68fe();}}});_0x37f41d();export*from_0xb355('0x10');
 @ ./src/app/components/home/home.component.ts 16:0-86
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

`
## Minimal working example that will help to reproduce issue
Try to obfuscate `export {MyModule} from './src';` with your site "obfuscator.io"

**Comment by zamotkin** [comment]
Can't reproduce in 0.18.4

**Comment by zamotkin** [comment]
@LabDeve if you still have this issue feel free to re-open it.
