### ISSUE TITLE
Cannot get the obfuscated code within the correct path

### ISSUE THREAD

**Issue by gigouni** [javascript-obfuscator/javascript-obfuscator#337]
Hi @sanex3339 ,

I'm transpiling source code to a "**transpiled"** folder. Then, I obfuscate the transpiled code within a **"dist"** folder.

## Expected Behavior

The obfuscated code is found at the root of the **"dist"** folder.

## Current Behavior

 The obfuscated code goes to **"dist/transpiled"** instead of directly in **"dist"**.

**From**

|
| dist
|    | transpiled
|    |     | my transpiled and obfuscated code
| transpiled
| src

**To**

|
| dist
|    | my transpiled and obfuscated code
| transpiled
| src

The complete npm script

```shell
"obfuscate": "javascript-obfuscator transpiled --output dist",
```

## Steps to Reproduce (for bugs)

1. Create a dummy Node.JS project with BabelJS 
2. Transpile your code `babel src --out-dir transpiled -D`
3. Obfuscate the code `javascript-obfuscator transpiled --output dist`

The script does not crash but create the content to the wrong folder.

## Your Environment

* OS: Microsoft Windows 10 Professionnel
* Obfuscator version used: 0.18.1
* Node version used: v8.10.0, npm 5.6.0

# Stack trace

```shell
> [...]
> javascript-obfuscator transpiled --output dist

[javascript-obfuscator-cli] Obfuscating file: transpiled\api\index.js...
[javascript-obfuscator-cli] Obfuscating file: my other files...
```

**Comment by napter** [comment]
Hi - not related to your issue but how did you get this to run on windows? When I run npm install --save-dev javascript-obfuscator it creates a folder for javascript-obfuscator I don't see any .exe in the folder and running javascript-obfuscator gives me javascript-obfuscator"' is not recognized as an internal or external command, operable program or batch file. Thank you

**Comment by khadakeb** [comment]
@gigouni Have you got any solution for this?

**Comment by gigouni** [comment]
No, sorry @khadakeb , it was paused in favor of other features. But I think we won't use it anyway, we prefer using compilation like https://github.com/zeit/pkg or https://github.com/nexe/nexe instead of obfuscation to avoid lake of performance.

But this issue is still relevant, not closing...

**Comment by sanex3339** [comment]
Closed as old
