### ISSUE TITLE
Large Javascript file of size around 10MB with requirejs module definitions is taking around 28 minutes of time for Obfuscation.  Is there a way to optimize this?

### ISSUE THREAD

**Issue by govind4u** [javascript-obfuscator/javascript-obfuscator#339]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Obfuscator version used: 0.18.1
* Node version used: 6.10.3

# Stack trace

## Minimal working example that will help to reproduce issue

define("<module_name_1>", [], function() { 
    ...
    ... 
    var i = {serviceName: "Sample", tableName: "Test" }; 
    return Object.freeze(i), i }
),define("<module_name_2>", [], function() { 
    ...
    ... 
    var i = {serviceName: "Sample2", tableName: "Test2" }; 
    return Object.freeze(i), i }
),
.....

**Comment by sanex3339** [comment]
Hi, try 0.17+ versions. 0.18+ is buggy

**Comment by govind4u** [comment]
I have tried with 0.17.3, but still the obfuscation is taking 28 minutes.

**Comment by zamotkin** [comment]
@govind4u if you still have this problem and need to solve it - please share your code with, I'll try to solve this issue.

**Comment by sanex3339** [comment]
Closed as old. Please, create another issue if you still have this problem on the latest version.
