### ISSUE TITLE
Can i do a AppLock like domainLock

### ISSUE THREAD

**Issue by kindLee-alasikoo** [javascript-obfuscator/javascript-obfuscator#344]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Obfuscator version used:
* Node version used:

# Stack trace

**Comment by longcnn** [comment]
+1
For example my project had the app ID and i want my code just run in my own app

**Comment by sunwei415** [comment]
If Cordova is used, we can duplicate DomainLock logic in javascript-obfuscator and replace the domain fetching with App ID fetching via [cordova-plugin-buildinfo](https://www.npmjs.com/package/cordova-plugin-buildinfo).

Extra configuration option for declaring legal package names should be introduced.

**Comment by sanex3339** [comment]
Closed. Need proposal.
