### ISSUE TITLE
Obfuscator.io mirror?

### ISSUE THREAD

**Issue by egfx** [javascript-obfuscator/javascript-obfuscator#349]
Is there a working mirror of the online version? It appears https://obfuscator.io is down.

524 Timeout Error

**Comment by mattpass** [comment]
Same - need to use it and offline. Eeek!

**Comment by zarza** [comment]
Looks like use uptimerobot.com to monitoring it could be a good idea if admin is still alive... It has been down for few days in a row.

**Comment by djape007** [comment]
try this website https://javascript-obfuscator.org/ it worked for me

**Comment by sanex3339** [comment]
Sorry for delay, i reloaded https://obfuscator.io/.

javascript-obfuscator.org - is not official

**Comment by piptan** [comment]
Is https://obfuscator.io down ?

**Comment by mattpass** [comment]
Hiya @sanex3339 obfuscator.io seems to be down.

**Comment by sanex3339** [comment]
Hi, I'll look into this

**Comment by sanex3339** [comment]
Should work now

**Comment by mattpass** [comment]
@sanex3339 it does, thank you 👍

**Comment by crisvera** [comment]
It's down again, please 🙏🏻🙏🏻🙏🏻

**Comment by sanex3339** [comment]
Done

**Comment by BattleDashLeaks** [comment]
down again it seems

**Comment by xeydod** [comment]
Down again. Do you need help hosting it?

**Comment by egfx** [comment]
It's down again..

**Comment by egfx** [comment]
down.

**Comment by sanex3339** [comment]
Working for me

**Comment by micheldaoud** [comment]
its down for me

**Comment by gnawh** [comment]
down again..

**Comment by zarza** [comment]
We can offer you sponsored hosting for this tool. It is really important and cannot be down. 
Please get it back online soon :)

**Comment by slig** [comment]
If your work depends on the tool, you should self-host it locally (https://github.com/javascript-obfuscator/javascript-obfuscator-ui) or integrate it in your build process.

**Comment by sanex3339** [comment]
Should work now.
The problem that obfuscator server sometimes is stopped and currently the only way to rerun it is to restart instance manually.

I tried to enable pm2 (https://github.com/javascript-obfuscator/javascript-obfuscator-ui/blob/master/ecosystem.config.js), but got strange problem with Gandi simple hosting.

Will try again in the future.
