### ISSUE TITLE
The sources field in the generated sourceMap is always {dirname}

### ISSUE THREAD

**Issue by beeing** [javascript-obfuscator/javascript-obfuscator#353]
All the source map files generated is following the directory name from the CLI.

I am obfuscating the entire directory from the CLI, rather than individual files.

## Expected Behavior

```
{"version":3,"sources":["same-name-as-obfuscated-file.js"]...
```

## Current Behavior

All source map files are generated properly but the sources is the same following the provided dirname from the CLI.
```
{"version":3,"sources":["dist.js"]...
```

## Steps to Reproduce (for bugs)

1. Create `dist` directory and put some .js files in
2. Run the command below in working example
3. Inspect the content of generated source maps 

## Your Environment

* Obfuscator version used: 0.18.1
* Node version used: 8.12.0

## Minimal working example that will help to reproduce issue
```
javascript-obfuscator ./dist --config .obfuscate --exclude public --output out
```

**Comment by sanex3339** [comment]
Will check it this week

**Comment by sanex3339** [comment]
Cannot reproduce it now. Looks like it has been fixed.

**Comment by sanex3339** [comment]
Please, create a new issue if this problem will happen again.

**Comment by beeing** [comment]
No worries. Thanks.
