### ISSUE TITLE
ControlFlowStorage without var parent node

### ISSUE THREAD

**Issue by devtest1990** [javascript-obfuscator/javascript-obfuscator#358]
ControlFlowStorage produces the following:
var myFunction() {
   var ak = {
        'cqEBl': function(al, am) {
            return al == am;
        }

Is there any option to create it without parent var, as the following:
var myFunction() {
        function cqEBl(al, am) {
            return al == am;
        }

**Comment by zamotkin** [comment]
@devtest1990 I can't understand your issue. If you still have this issue, could you provide more detailed description or re-phrase it?

**Comment by sanex3339** [comment]
@devtest1990 Hi. Here is no way to do this.
