### ISSUE TITLE
Support .json files

### ISSUE THREAD

**Issue by adamhamlin** [javascript-obfuscator/javascript-obfuscator#359]
## Expected Behavior

This utility can only handle .js files,  but if it's a Node project you're trying to package up there is going to be at least one, if not many JSON files.  I don't know if they can really be obfuscated (which would be fine), but they could at least be minified and inserted into the result. It shouldn't cause an error if there happen to be a few in a directory.

## Current Behavior

You get a parse error if it's a JSON file -- Error: Line 2: Unexpected token :

**Comment by bearer-syntaxerror** [comment]
I have a use for this feature as well.

**Comment by hk-ng** [comment]
It seems a job for bundler. I was able to bundle json file into js file with webpack.

**Comment by zamotkin** [comment]
This project does not support JSON obfuscation. It was a good advice from @hk-ng above, please follow it.
