### ISSUE TITLE
Two import statements exposes variables

### ISSUE THREAD

**Issue by DaviUchoa** [javascript-obfuscator/javascript-obfuscator#360]
## The problem
Trying to obfuscate the following code:
```
import ok from 'lib1';
import ok2 from 'lib2';

let simple = null;
let test = null;
```
Results in:
```
import _0x19aaee from'lib1';import _0x279d2c from'lib2';let simple=null;let test=null;
```
Exposing the **let simple=null;let test=null;** even if Rename Globals is **enabled**.
 It seems to me that it is not right.

But with only one import statement like:
```
import ok2 from 'lib2';

let simple = null;
let test = null;
```
Results in:
```
import _0x408065 from'lib2';let _0x39e0d2=null;let _0x5f02c4=null;
```
I think this is correct :+1: 
## Configs used

* Obfuscator version used: 0.18.1 (tested on the website too)
* Compact code: true
* Rename Globals: true

**Comment by zamotkin** [comment]
Confirm: this bug still exists.

**Comment by sanex3339** [comment]
Yep, reproduced it yesterday. Dont know why this happens, should look into that.

**Comment by zamotkin** [comment]
@sanex3339 I'm working on this issue.
