### ISSUE TITLE
[Request] Encode Object Keys 

### ISSUE THREAD

**Issue by florentpeyrard** [javascript-obfuscator/javascript-obfuscator#362]
As for String Array. 

This would allow better hiding the code purpose. Would be very helpful for vuejs app, as all variables/functions are actually object keys.

**Comment by sanex3339** [comment]
Mangle props discussed here:
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/270

**Comment by sanex3339** [comment]
I implemented it here:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/625

**Comment by sanex3339** [comment]
`renameProperties` option released as `1.1.0` version.
