### ISSUE TITLE
Regular expression: modifier "s" (dotall) is not supported!

### ISSUE THREAD

**Issue by STK913** [javascript-obfuscator/javascript-obfuscator#369]
Hello,

The obfuscation of this code: let regex=/test/gmis;
Generates this code: let regex=null;
But this one works well: let regex=/test/gmi;

Some modifiers like the "s" (dotall) is not supported. Can you fix the problem please?
I think obfuscation works this way: new RegExp("test", "gims"); but for my case, I can not because of the minification.
I am using version 0.18.1.

**Comment by zamotkin** [comment]
@STK913 cannot reproduce in 0.18.4. Please feel free to re-open an issue if still have a problem.
