### ISSUE TITLE
Ability to turn off js obfuscator with comments

### ISSUE THREAD

**Issue by Extarys** [javascript-obfuscator/javascript-obfuscator#370]
## Expected Behavior

javascript-obfuscator should not obfuscate js lines between 2 specific comments

## Current Behavior

javascript-obfuscator obfuscate the entire file

## Your Environment

* Obfuscator version used: latest

## Minimal working example that will help to reproduce issue

```
var mysupervar = 1
/* js-obfs off*/
function myeasytoreadfunction() {
  // Code that need performance
  return true
}
/* js-obfs on*/
```

**Comment by Extarys** [comment]
@Andrews54757 What do you think?

**Comment by LowderPlay** [comment]
> You can disable and enable obfuscation for specific parts of the code by adding following comments:
> 
> disable: // javascript-obfuscator:disable or /* javascript-obfuscator:disable */;
> enable: // javascript-obfuscator:enable or /* javascript-obfuscator:enable */.

**Comment by Extarys** [comment]
Oh damn. Thanks I totally missed that!! :heart:
