### ISSUE TITLE
Idea: Locally scoped variable can have the same mangled name

### ISSUE THREAD

**Issue by Extarys** [javascript-obfuscator/javascript-obfuscator#371]
## Expected Behavior

Obfuscated code can have multiple locally scoped variable name identical.
I know this could be difficult to implement, it is an idea, if someone have the skills to implement this.

It would make de obfuscation much harder

Example:
```
var a = 2 // can't use 'a' anymore as it is in the top scope
function(b, c) {
  return window[b] = c
}
for(var b = 0; b < c; b++) { // notice 'b', 'c' is also in the function, they where in local scope in the previous function
    var d = 5+b
}
```

This would be harder to de obfuscate as a variable name can have multiple purposes.

## Current Behavior
Raw code
```
var myvalue = 2
function(key, value) {
  return window[key] = value
}
for(var i = 0; i < myvalue; i++) {
    var mycounter = 5+i
}
```

Obfuscated code
```
var a = 2
function(b, c) {
  return window[b] = c
}
for(var d = 0; d < e; d++) {
    var e = 5+d
}
```

**Comment by zamotkin** [comment]
Interesting idea, I think it's possible.

**Comment by Extarys** [comment]
I hope so. I don't have to knowledge to implement this though, sadly.

**Comment by sanex3339** [comment]
As a start point, you can use this branch
https://github.com/javascript-obfuscator/javascript-obfuscator/tree/identifier-names-generator-block-scope

I updated it to beeing up to date with the master branch.
I tried to implement this feature in 2018 but got few bugs.
Currently, it has 10 failing tests.

**Comment by sanex3339** [comment]
Also, the code that produced the bug:
```
(function () {
            let a = 0;
            
            function param1 (param1, param2) {
                var bar0 = 1;
                var baz0 = 2;
                
                foo1();
                
                function c () {
                    var a = 3;
                }
            }
            
            var foo1 = function (param1, param2) {
                var bar1 = 4;
                var baz1 = '55555'
            }
        })();
```

The result will be:
```
var a = ['55555'];
var b = function (c, d) {
    c = c - 0x0;
    var e = a[c];
    return e;
};
(function () {
    let c = 0x0;
    function d(d, d) { // <- error here
        var e = 0x1;
        var f = 0x2;
        h();
        function g() {
            var c = 0x3;
        }
    }
    var h = function (d, d) {
        var e = 0x4;
        var f = b('0x0');
    };
}());
```

**Comment by zamotkin** [comment]
@sanex3339 thanks for a right direction!

**Comment by sanex3339** [comment]
Much smallest minimal example with bug
```
 let obfuscatedCode: string = JavaScriptObfuscator.obfuscate(
        `
        (function () {
            let a = 0;
            
            function param1 (param1, param2) {
               
            }
        })();
        `,
        {
            ...NO_ADDITIONAL_NODES_PRESET,
            compact: false,
            stringArray: false,
            stringArrayThreshold: 1,
            transformObjectKeys: true,
            identifierNamesGenerator: IdentifierNamesGenerator.MangledIdentifierNamesGenerator,
            seed: 1
        }
    ).getObfuscatedCode();
```

Obfuscated code with error:
```
(function () {
    let c = 0x0;
    function d(d, d) {
    }
}());
```

**Comment by sanex3339** [comment]
In this branch, I added the new preparing transformer, called `ScopeTransformer`, that added `scope` property to all nodes.

Then, in `MangledIdentifierNamesGenerator` identifiers for each scope are tried to generate.

**Comment by sanex3339** [comment]
Looks i got working implementation. Still need optimize things, but it works without errors.

**Comment by sanex3339** [comment]
Currently it looks like this
https://gist.github.com/sanex3339/fe0f9a956ac3e42fbbe18a3f17adec3e

**Comment by sanex3339** [comment]
The WIP PR
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/555
