### ISSUE TITLE
Is there any way how to no obfuscate name of required files?

### ISSUE THREAD

**Issue by JaLe29** [javascript-obfuscator/javascript-obfuscator#372]
I don't want obfuscate name in require like this `require("./core")`

I tried to put regexpt into config file:

			reservedNames: ["require\\('.{1,}'\\)"],
			reservedStrings: ["require\\('.{1,}'\\)"],
			domainLock: ["require\\('.{1,}'\\)"],

But it ignore require totally - required files are not obfuscated.

Thank you for any help.

**Comment by zamotkin** [comment]
@JaLe29 The Obfuscator cannot extract all names from require, you need to prepare this names before calling the Obfuscator.

**Comment by zamotkin** [comment]
Closing this issue, need more details. Feel free to open a new one if you still need a solution.
