### ISSUE TITLE
Unexpected output sub-directory when obfuscating directories recursive

### ISSUE THREAD

**Issue by ronny1982** [javascript-obfuscator/javascript-obfuscator#373]
In some cases when using the obfuscator to process an input directory, there will be an additional sub-directory created in the output directory with the same name of the input directory.

Steps to reproduce (bash):

```bash
# create a project directory:
mkdir test
cd test
npm install javascript-obfuscator

# create a dummy structure:
mkdir in
touch in/1.js
touch in/2.js

# obfusacte the dummy files
javascript-obfuscator ./in --output ./out
```

It would be expected that the files after obfuscation are placed directly under the output directory `out/1.js` and `out/2.js`, but instead there is an additional sub-directory with the name of the input directory and the files are placed in `out/in/1.js` and `out/in/2.js`.

**Comment by khadakeb** [comment]
@ronny1982 Have you got solution for this?

**Comment by ronny1982** [comment]
I added a script in my build chain to move the files into the correct directories

**Comment by zamotkin** [comment]
I think this work is for bundler.
