### ISSUE TITLE
Use of "var" draws attention to obfuscator helpers in ES6

### ISSUE THREAD

**Issue by toddbu** [javascript-obfuscator/javascript-obfuscator#376]
For code that had been fully converted to ES6, the use of `var` throughout the obfuscated code makes it easy to spot helper functions in the code. For example...

```
var a12_0x20ff=['calibrate',...];(function(_0x38288e,_0x1a006f){var _0x1f4c32=function(_0x70d678){while(--_0x70d678){_0x38288e['push'](_0x38288e['shift']());}};_0x1f4c32(++_0x1a006f);}(a12_0x20ff,0x1b4));var a12_0x5d03=function(_0x1ccae0,_0x5b3cf8){_0x1ccae0=_0x1ccae0-0x0;var _0x5a1c45=a12_0x20ff[_0x1ccae0];return _0x5a1c45;};...
```

All of the obfuscated code that I truncated uses the ES6 `const` and `let` constructs for declaring variable. This makes the helpers stand out as something different than the rest of the code, thereby drawing attention to them for further scrutiny. Ideally, javascript-obfuscator would support something like an `--es6` flag that would use `const` in place of `var` for these helpers

**Comment by sanex3339** [comment]
I thinking about this today.
I have two variants:
- ability to select between `var`, `let` and `const` kinds of variables via option
- analyze the input source code and automatically detect the best kind based on the prevailing kind

I prefer the second variant

**Comment by zamotkin** [comment]
Yes, I think the second option is better.

**Comment by sanex3339** [comment]
Hi, implemented. Can you test this branch on a large code (10+ loc) with const and let variables?

```
declaration-kind-analyzer
```

**Comment by sanex3339** [comment]
Merged in `master`. Expect release tomorrow.
