### ISSUE TITLE
@sanex3339 => react-native-obfuscating-transformer maintainership

### ISSUE THREAD

**Issue by ds300** [javascript-obfuscator/javascript-obfuscator#378]
Hi @sanex3339! :wave: Sorry for making this a github issue, I didn't know how else to contact you.

I'm no longer actively maintaining react-native-obfuscating-transformer so would like to add some more maintainers who can keep it up to date. Unfortunately I don't have admin rights over that repo after transferring ownership to the javascript-obfuscator org. Can you give me those rights? Or if not, then can you at least add @jesucarr  as a collaborator?

Thanks :heart:

**Comment by zamotkin** [comment]
@sanex3339 yes, and I see a long-waiting [pull request](https://github.com/javascript-obfuscator/react-native-obfuscating-transformer/pull/15) in that repo. I don't have enough expertise in React Native to merge this PR.

**Comment by sanex3339** [comment]
Hi. Sorry, i'm to late. Sent the invite for you

**Comment by sanex3339** [comment]
The invite is sent, closed.
