### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by senro** [javascript-obfuscator/javascript-obfuscator#379]
## Your Environment

* Obfuscator version used:0.18.1
* Node version used:v8.9.3

# Stack trace
<--- Last few GCs --->

[6336:00000202C2F62ED0]   621993 ms: Mark-sweep 1414.4 (1825.0) -> 1414.4 (1795.5) MB, 1507.1 / 0.0 ms  last resort GC in old space requested
[6336:00000202C2F62ED0]   623483 ms: Mark-sweep 1414.4 (1795.5) -> 1414.3 (1795.0) MB, 1489.9 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000029FF38A5EE1 <JSObject>
    2: ExpressionStatement [E:\GitProjects\xxx\node_modules\javascript-obfuscator\node_modules\escodegen-wallaby\escodegen.js:~1291] [pc=000001088DC48244](this=000002E555AF9E19 <CodeGenerator map = 0000006AFD199D81>,stmt=0000
00ADFB1A31B9 <Node map = 0000006AFD18A659>,flags=49)
    3: /* anonymous */(aka /* anonymous */) [E:\GitProjects\xxx\node_modules\javascript-obfuscator\node_mo...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by zamotkin** [comment]
Please try to increase max heap size with _node_ flag _max_old_space_size_.

**Comment by sanex3339** [comment]
Also, try to use the latest version of obfuscator, I replaced `escodegen-wallaby` on `escodegen`

**Comment by sanex3339** [comment]
Also need more details: 
- source code (if possible) to reproduce this problem
- options

**Comment by sanex3339** [comment]
Closed as inactive. Recreate this issue if you will have additional details and this bug still exists on the latest version

**Comment by Zaibali9999** [comment]
> Please try to increase max heap size with _node_ flag _max_old_space_size_.

NODE_OPTIONS=--max_old_space_size=8192 node

**Comment by Zaibali9999** [comment]
export NODE_OPTIONS=--max_old_space_size=8192
