### ISSUE TITLE
Async/await

### ISSUE THREAD

**Issue by tomekmarchi** [javascript-obfuscator/javascript-obfuscator#38]
This is a must need as a ton of code I write now is using async/await.

**Comment by sanex3339** [comment]
Esprima stable currently not supporting this..

**Comment by sanex3339** [comment]
You can ask them to release `beta` version here
https://github.com/jquery/esprima/issues

**Comment by sanex3339** [comment]
https://github.com/jquery/esprima/issues/1749

**Comment by sanex3339** [comment]
finally 
https://github.com/jquery/esprima/commit/d95fac62108c4a45139c4fe60c6c3155f585342a

**Comment by sanex3339** [comment]
Hi! Please try new javascript-obfuscator@0.10.0-beta.4, it support async functions now.

**Comment by sanex3339** [comment]
Closed. Beta version supports async functions.
