### ISSUE TITLE
Maintainer call

### ISSUE THREAD

**Issue by sumleo** [javascript-obfuscator/javascript-obfuscator#381]
I am a thrid-year undergraduate, I wanna take this topic as my final thesis. So I wanna learn and maintain this project.

**Comment by sumleo** [comment]
Anybody here?

**Comment by slig** [comment]
Well, the code is here. You can study it and propose new features and work on them.

**Comment by sanex3339** [comment]
Hi. Create new features through PRs, i'll check it and will merge it.
If everything will ok, after some time i will add you as project maintainer.

**Comment by sumleo** [comment]
Ok. Thanks for replying.
