### ISSUE TITLE
Obfuscating simple JavaScript file requires (require,module), which doens't work in browser

### ISSUE THREAD

**Issue by chiralsoftware** [javascript-obfuscator/javascript-obfuscator#382]
## Expected Behavior

I should be able to run it in a basic configuration, have it generate a .js output file, and reference that file using a <script> tag, and use functions defined in that file.
However, it generates code that requires (require,module) in it, so it doesn't work in browsers.

## Steps to Reproduce (for bugs)

Start with a simple JS file like this:
greeter.js 
```
function greeter(person) {
    return "Hello, " + person;
}
```
Process it and the result is:

`!function(a,b){function c(b,d){var e,f;if("\x2e"!=b[0]&&"\x2f"!=b[0])return a(b);if(d=d||"\x72\x6f\x6f\x74",e=c.resolve(b),!e&&/\.json$/i.t...snip...\x72\x2e\x6a\x73")}(require,module);`

When that is included using a script tag, the browser fails with:

`ReferenceError: require is not defined`

This seems like a fatal bug in this version.

## Your Environment

* Obfuscator version used: 0.18.1
* Node version used: v10.15.3

Here are the obfuscator options:

```
            files: [ 'target/js/greeter.js'],
            entry: "target/js/greeter.js",
            out: 'target/js/code.js',
            strings: true,
            target: 'browser-no-eval',
            sourceMap: false,
            root: __dirname
```

I tried it with all three possible targets (browser, browser-no-eval, and node).

**Comment by zamotkin** [comment]
@chiralsoftware are you using Javascript Obfuscator directly? It has no options you described above except _target_ and _sourceMap_

**Comment by zamotkin** [comment]
I'm closing it as an old issue with no response. Feel free to open a new one with detailed description if you still need a solution.
