### ISSUE TITLE
Web UI Issue

### ISSUE THREAD

**Issue by I-am-Orion** [javascript-obfuscator/javascript-obfuscator#384]
How to create a web UI which will not send the data in server but only obfuscate the code in browser using the following code:

```
<script src="https://cdn.jsdelivr.net/npm/javascript-obfuscator/dist/index.browser.js"/>
```

Please kindly help.

**Comment by Ashesh3** [comment]
See https://github.com/javascript-obfuscator/javascript-obfuscator-ui/issues/1

**Comment by zamotkin** [comment]
Closing as duplicate.

**Comment by sanex3339** [comment]
Done. https://obfuscator.io/ now completely client side
