### ISSUE TITLE
obfuscator.io is down

### ISSUE THREAD

**Issue by RyadPasha** [javascript-obfuscator/javascript-obfuscator#392]
obfuscator.io is down again since today’s morning
I’ve used it yasterday and it was working.

**Comment by Xedoll** [comment]
I notice it today, error 524 from CloudFlare.

**Comment by tinyCoder32** [comment]
Any idea how long is it gonna stay like that?

**Comment by RyadPasha** [comment]
Timofey usually takes so long to response, and the server gives no response at all.

Is there a working mirror of it?

**Comment by tinyCoder32** [comment]
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/17817239/60043953-f97fb580-96c9-11e9-9143-8a8977c591d5.png">


I set it up on my local host, you can do it easily from here:
https://github.com/javascript-obfuscator/javascript-obfuscator-ui

**Comment by RyadPasha** [comment]
DM me on Twitter I wanna ask you about something; @RyadPasha

**Comment by davyk7** [comment]
PLease up up up ! it's such a wonderful tool !
how can we make it live again ?

**Comment by davyk7** [comment]
> <img alt="image" width="1222" src="https://user-images.githubusercontent.com/17817239/60043953-f97fb580-96c9-11e9-9143-8a8977c591d5.png">
> 
> I set it up on my local host, you can do it easily from here:
> https://github.com/javascript-obfuscator/javascript-obfuscator-ui

sorry but how did you that. I don't think that I'm 43 YO noob but didn't understand nothing about installing a node.js server easyly on W10

**Comment by sanex3339** [comment]
Should work now

**Comment by davyk7** [comment]
> Should work now

You really rock ! Thanx a bunch !
