### ISSUE TITLE
domainLock is easy to circumvent

### ISSUE THREAD

**Issue by mauricedoepke** [javascript-obfuscator/javascript-obfuscator#395]
* Obfuscator version used: 0.18.1

It is pretty easy to circumvent the domainLock. Just replace "{data;}else{return;}"  with "{return;}else{return;}"

**Comment by Bangkokian** [comment]
You could use [DomainLockJS](https://domainlockjs.com) if you need something harder. But anything in javascript can be circumvented. It's all about deterrence... not prevention. The chances of 99% of users doing what you just did are pretty slim. What's obvious for you is probably pretty non-obvious for everyone else.

**Comment by J-Rojas** [comment]
It's probably best that you write your own variant of this - there's a template that you can modify. You might choose to implement some non-obvious deterrence that would be hard to trace and therefore remove. If everyone used the same domain lock, it would be easy to identify by just looking at this source code.

**Comment by sanex3339** [comment]
PR with better implementation is welcomed

**Comment by da411d** [comment]
What about insert some flag to string-array-rotation function, so it will rotate array incorectly and all code won't work properly?

Also i think that string-array-iterations number can be divided to severap parts and be located in diferent parts of code;

**Comment by da411d** [comment]
Something like:

```
//...
stringRotationIterationCount = ...;
ok = true;
let someRandomBoolean = 5 < 8 - 1;
//...
someRandomBoolean = !someRandomBoolean;
//...

if(!someRandomBoolean && ok){
  stringRotationIterationCount += 123;
}else if(someRandomBoolean){
  stringRotationIterationCount += 234;
// 100500 variants of else-if
}else{
  stringRotationIterationCount -= 321;
}
```

**Comment by sanex3339** [comment]
Now domain lock works in a different way with a redirect.
