### ISSUE TITLE
Mangling class property names

### ISSUE THREAD

**Issue by TorRanfelt** [javascript-obfuscator/javascript-obfuscator#396]
I can't seem to find an option that mangle class properties to the point that they are removed from the code. I know this can break java-script, but when I know what code I'm obfuscating this isn't a problem.

Does such a feature exists?

**Comment by zamotkin** [comment]
@TorRanfelt i think you mean [transformObjectKeys](https://github.com/javascript-obfuscator/javascript-obfuscator#transformobjectkeys)

**Comment by sanex3339** [comment]
No. `transformObjectKeys` currently does not rename object keys. Sadly, but currently this feature is not in the roadmap.
