### ISSUE TITLE
source map from TS files after obfuscation

### ISSUE THREAD

**Issue by GaikwadPratik** [javascript-obfuscator/javascript-obfuscator#397]
## Your Environment

* Obfuscator version used: 0.18.1
* Node version used: 10.16.0

Creating the question to extend issue #298, I have a typescript project for which I am generating sourcemap during compilation. What configuration options should I use so that stack trace is generated as per original ts file?

**Comment by GaikwadPratik** [comment]
@sanex3339/ maintainer/contributor,

any insights, thoughts?

**Comment by konstantin24121** [comment]
@GaikwadPratik I think there is no option for you case, you can try https://github.com/azu/multi-stage-sourcemap/ package for converting js sourceMap to your ts source maps.

In my case this lib works perfectly

**Comment by zamotkin** [comment]
If you are using gulp you can use [gulp-javascript-obfuscator](https://github.com/javascript-obfuscator/gulp-javascript-obfuscator), if webpack - [webpack-obfuscator](https://github.com/javascript-obfuscator/webpack-obfuscator), they are support source maps.
