### ISSUE TITLE
Domain lock not working on obfuscator.io?

### ISSUE THREAD

**Issue by ks1505** [javascript-obfuscator/javascript-obfuscator#399]
domain lock used to work but is not working now. Does node.js has any affect on domain lock..?

**Comment by xbaha** [comment]
not working here too, did you find out solution?

**Comment by zamotkin** [comment]
@xbaha I need an example of your code to solve a problem,

**Comment by sanex3339** [comment]
Closed because of no response from @xbaha.
Please, recreate a new issue if you will have additional questions.

**Comment by sanex3339** [comment]
@ks1505 cannot reproduce. For me, `domainLock` option is working.
