### ISSUE TITLE
What frameworks are used

### ISSUE THREAD

**Issue by lonewolfyx** [javascript-obfuscator/javascript-obfuscator#401]
can you tell which frameworks are used, because I want to convert this tool into a PHP version

Thanks

**Comment by sanex3339** [comment]
Hi. Not sure if it possible without huge rework:
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/package.json#L23

Inversify.js for DI
espree for AST parsing
estraverse for AST traverse
escodegen-wallaby for AST to code transformation
chance for random generator

**Comment by lonewolfyx** [comment]
Okay, I will try it

**Comment by zamotkin** [comment]
I'm closing it as far you have no more questions. Feel free to open a new one if you have further questions.
