### ISSUE TITLE
Maintaining this project.

### ISSUE THREAD

**Issue by lilabyte** [javascript-obfuscator/javascript-obfuscator#402]
Hello, i want to contact you on e-mail or something.

**Comment by sanex3339** [comment]
Hi. sanex3339 at yandex.ru

**Comment by bmblb** [comment]
Is someone maintaining this project still? I found a bug and was planning to file issue, but not sure if anyone will fix it. What if I come up with PR, would there be someone to approve it?

**Comment by sanex3339** [comment]
Hi. Currently i have no time to work on this project, but I will review and merge your PR.

**Comment by zamotkin** [comment]
@bmblb you can also contact me, I have a bit more time ;-)

**Comment by sanex3339** [comment]
Closed as old.
Please, recreate a new issue if you will have additional questions.
