### ISSUE TITLE
Obfuscate folder but keep same file names

### ISSUE THREAD

**Issue by PeterHdd** [javascript-obfuscator/javascript-obfuscator#403]
Is there a way using the CLI to obfuscate a folder example `/dist` but keep the same file names. Example if I have:

`/dist/14a3.js`
`/dist/qe3g.js`

When I obfuscate using:

`javascript-obfuscator ./dist`, I will get the following files:

`/dist/14a3.js`
`/dist/qe3g.js`
`/dist/obfuscated-14a3.js`
`/dist/obfuscated-qe3g.js`

What I want to actually happen, is to obfuscate those two files but just override the content inside them with obfuscation, therefore when I execute the command `javascript-obfuscator ./dist`, i will still have only the two original files but with obfuscated code.

**Comment by slig** [comment]
You have to write a simple shell script to do that. See here an example https://stackoverflow.com/questions/602706/batch-renaming-files-with-bash

Take care to not run this on a folder with stuff that you might lose if it gets overwritten.

**Comment by sanex3339** [comment]
My position is not changed, it could potentially "lose you code".
As @zamotkin said, better to write your shell script to do that.

**Comment by omkar-tenkale** [comment]
Here's how i did it

`sudo apt-get install mmv`

`mmv '*-obfuscated*' '#1#2'`

Reference https://unix.stackexchange.com/a/237383

**Comment by canaanites** [comment]
Use this.. you can add it to the npm build script
`cd src/ && javascript-obfuscator ./ --output ../dist/`

**Comment by tarik0** [comment]
You can code a simple script like that.

```js
const fs = require("fs");
const path = require("path");
const JavaScriptObfuscator = require('javascript-obfuscator');

const settings = {
    compact: true,
    controlFlowFlattening: false,
    deadCodeInjection: false,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: false,
    identifierNamesGenerator: 'hexadecimal',
    log: true,
    numbersToExpressions: false,
    renameGlobals: false,
    rotateStringArray: true,
    selfDefending: true,
    shuffleStringArray: true,
    simplify: true,
    splitStrings: false,
    stringArray: true,
    stringArrayEncoding: [],
    stringArrayIndexShift: true,
    stringArrayWrappersCount: 1,
    stringArrayWrappersChainedCalls: true,
    stringArrayWrappersParametersMaxCount: 2,
    stringArrayWrappersType: 'variable',
    stringArrayThreshold: 0.75,
    unicodeEscapeSequence: false
}

function obfuscateDir(dirPath) {
    var dirents = fs.readdirSync(dirPath, { encoding: "utf8", withFileTypes: true });
    for (let i = 0; i < dirents.length; i++) {
        let dirent = dirents[i];
        
        if (dirent.isDirectory()){
            obfuscateDir(path.join(dirPath, dirent.name));
            continue;
        }

        if (path.extname(dirent.name) !== ".js") continue;

        let filePath = path.join(dirPath, dirent.name);
        let content = fs.readFileSync(filePath, { encoding: "utf8" });

        let obfuscator = JavaScriptObfuscator.obfuscate(content, settings);
        let obfuscatedCode = obfuscator.getObfuscatedCode();

        fs.writeFileSync(filePath, obfuscatedCode, { encoding: "utf8", flag: "w+" });
    }
}

obfuscateDir(path.join(__dirname, "build"));
```
