### ISSUE TITLE
in vue project,stringArray option Causing errors

### ISSUE THREAD

**Issue by xpf0000** [javascript-obfuscator/javascript-obfuscator#405]
this is my webpack config
### rules: [
            {
                test: /\.js$/,
                enforce: 'post',
                use: { loader: 'obfuscator-loader', options: {
                    stringArray: true,
                    //删除字符串文字并将它们放在一个特殊的数组中
                    stringArrayThreshold: 1.0,
                } }
            },
            {
                test:/\.js$/,
                loader:'babel-loader',
                query:{
                    presets:['@babel/preset-env']
                    //告诉babel-loader处理怎样js转换成浏览器支持的js代码
                },
            },
            {
                test: /\.vue$/,
                loader: 'vue-loader'
            },
            {
                test:/\.css$/,
                use: [
                    'vue-style-loader',
                    'style-loader',
                    'css-loader',
                    'postcss-loader'
                ]
            },{
                test:/\.less$/,
                loader:'style!css!postcss!less'
            },{
                test:/\.scss$/,
                loader:'style!css!postcss!scss'
            }
        ]

this is webpack error:

### ERROR in ./test/test.vue?vue&type=script&lang=js& 1:763
Module parse failed: Unexpected token (1:763)
File was processed with these loaders:
 * ./node_modules/obfuscator-loader/lib/index.js
 * ./node_modules/vue-loader/lib/loaders/pitcher.js
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
> var _0x31d3=['-!../node_modules/obfuscator-loader/lib/index.js??ref--0!../node_modules/babel-loader/lib/index.js??ref--1!../node_modules/vue-loader/lib/index.js??vue-loader-options!./test.vue?vue&type=script&lang=js&'];(function(_0x18908c,_0x546bbe){var _0x2d4583=function(_0x42efee){while(--_0x42efee){_0x18908c['push'](_0x18908c['shift']());}};_0x2d4583(++_0x546bbe);}(_0x31d3,0x147));var _0x40e9=function(_0x4c078e,_0x299df6){_0x4c078e=_0x4c078e-0x0;var _0x475106=_0x31d3[_0x4c078e];return _0x475106;};import _0x36b62a from'-!../node_modules/obfuscator-loader/lib/index.js??ref--0!../node_modules/babel-loader/lib/index.js??ref--1!../node_modules/vue-loader/lib/index.js??vue-loader-options!./test.vue?vue&type=script&lang=js&';export default _0x36b62a;export*from_0x40e9('0x0');
 @ ./test/test.vue 2:0-56 3:0-51 3:0-51 10:2-8
 @ multi ./test/test.vue ./test/index.js

**Comment by zamotkin** [comment]
@xpf0000 I suggest using _obfuscator-loader_ after _babel-loader_ eg

```
        test: /\.js$/,
        use: [
          { 
            loader: 'babel-loader' 
            options: {...}
          },
          {
            loader: 'obfuscator-loader',
            options: {...}
          },
        ]
```

**Comment by sanex3339** [comment]
I see `_0x18908c'push';` in your code and this is invalid code. Obfuscator itself does not produce this code, so, i guess that some of the other loaders in the loaders chain modify this code.

**Comment by sanex3339** [comment]
Closed. Please, create the issue if you will have other questions

**Comment by sanex3339** [comment]
Can you try this branch?
transform-object-keys-return-object
