### ISSUE TITLE
Can't use sourceMapFileName for webpack chunks

### ISSUE THREAD

**Issue by konstantin24121** [javascript-obfuscator/javascript-obfuscator#406]
Can't use sourceMapFileName like app.[hash] because sourceMapFileNameRule cut hash. Why not cutting only file extension?

**Comment by sanex3339** [comment]
Will fix it

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/478

I hope, I will not break anything, because it is hard to determine if the last part is extension or hash or just part of the file name.
