### ISSUE TITLE
does debugProtectionInterval affects the performance of requestAnimationFrame loop?

### ISSUE THREAD

**Issue by zh99998** [javascript-obfuscator/javascript-obfuscator#408]
my project is a PIXI.js game. It will do requestAnimationFrame() loop to run game at 60fps.
I want to know does `debugProtectionInterval` have performance problem here

will it be better to alignment timers using PIXI ticker or requestAnimationFrame() ?

**Comment by sanex3339** [comment]
It is better to try, i did never tested this behavior

**Comment by sanex3339** [comment]
Closed. Please, recreate the issue if you will have other questions
