### ISSUE TITLE
Include excluded files in output

### ISSUE THREAD

**Issue by petr24** [javascript-obfuscator/javascript-obfuscator#409]
Is it possible to include non-obfuscated files in the output? 

I.e I run javascript-obfuscator. When it creates a new directory with the newly obfuscated code it only has the files that have been obfuscated. Anyway to include the excluded files in the output?

Thanks!

**Comment by slig** [comment]
This feature is not in the scope of the project, so a suggestion is to write a simple shell script to copy the files.
