### ISSUE TITLE
ES5 React class

### ISSUE THREAD

**Issue by bebeun** [javascript-obfuscator/javascript-obfuscator#41]
For a very simple React es5 class exemple I have this error:

Error: Line 1: Unexpected token <
Code : 

`var Answer = React.createClass({render() {return (<div>Hello World </div> );}});`

Any idea how to have the React syntax "return(<div>..." accepted by the obfuscator ?

Thk U !!

**Comment by slig** [comment]
That (XML syntax mixed with JS) is not pure ES5, it's called JSX. You have to compile it down to ES5 first.

Are you using webpack to compile your React project? If so, the easier way to go is to use this webpack plugin https://github.com/javascript-obfuscator/webpack-obfuscator

**Comment by sanex3339** [comment]
`esprima` accepts `jsx: true` option, so i can create option for controlling `esprima` `jsx` option.

**Comment by bebeun** [comment]
In fact I am using JSX in a rails 4 application( gem react-rails). Jsx is transformed in JS through Babel (and Browserify ?). I am really not a specialist of how it works and I have no idea how to set custom parameters.
My aim is to automatically obfuscate assets in dev and prod. I could obfuscate .js asset files one by one but it is a bit boring. 
I gonna provide you with a few JSX examples as you requested.

thank you very much for your help ! :-)

**Comment by sanex3339** [comment]
Hmm. Looks i was wrong about easy implementation of this feature.

`esprima` supports `jsx` but `escodegen` not.

So in your case you should do following:
- translate `jsx` to `es5` with `Babel`
- obfuscate it

How you will do it depends on your building process on front-end.  `javascript-obfuscator` has plugins for all popular bundlers.

**Comment by bebeun** [comment]
Ok, 
I am trying to pass Babel options to rails like
config.react.jsx_transform_options = {plugins: ['javascript-obfuscator']} but I perhaps have to first create a babel plugin which only role would be to obfuscate the code ?
Do you have any idea if it is possible to directly pass the obfuscator parameters as a function to babel ? Like:
`config.react.jsx_transform_options = {plugins: [require('javascript-obfuscator').obfuscate(*ref_to_code,{compact: false,controlFlowFlattening: true});]}`

**Comment by sanex3339** [comment]
With 0.9.3 version i switched from `escodegen` on `escodegen-wallaby` (which supports `jsx`) and now will look into this issue again.

**Comment by sanex3339** [comment]
For testing purposes, i need standalone, simple and small sample of working project with following compilation steps: 
`jsx->obfuscator (over jsx)->babel (jsx to es5)`

**Comment by bebeun** [comment]
Hi timofey !I am on vacation for a few days but it is ok for you i will get you 3 three steps on friday with 3 example files ?Thk u for all that you do !
-------- Message d'origine --------De : Timofey Kachalov <notifications@github.com> Date : 03/05/2017  08:27  (GMT+01:00) À : javascript-obfuscator/javascript-obfuscator <javascript-obfuscator@noreply.github.com> Cc : Benoit <benoit.schulman@gmail.com>, Author <author@noreply.github.com> Objet : Re: [javascript-obfuscator/javascript-obfuscator] ES5 React class (#41) 
For testing purposes, i need standalone, simple and small sample of working project with following compilation steps:

jsx->obfuscator (over jsx)->babel (jsx to es5)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/javascript-obfuscator/javascript-obfuscator","title":"javascript-obfuscator/javascript-obfuscator","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/javascript-obfuscator/javascript-obfuscator"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sanex3339 in #41: For testing purposes, i need standalone, simple and small sample of working project with following compilation steps: \r\n`jsx-\u003eobfuscator (over jsx)-\u003ebabel (jsx to es5)`"}],"action":{"name":"View Issue","url":"https://github.com/javascript-obfuscator/javascript-obfuscator/issues/41#issuecomment-298832164"}}}

**Comment by sanex3339** [comment]
Ok, i'm just want to play with it, i still not sure what obfuscator need this feature.

**Comment by sanex3339** [comment]
After some thinking I decided to refuse jsx support, because many plugins like `estraverse` still not support it, fork with `jsx` support older than main versions `estraverse`.

And finally - `jsx` support in obfuscator have no sense because we can easily obfuscate all JS code after `jsx` transformation with babel.
