### ISSUE TITLE
The website can't be opened.

### ISSUE THREAD

**Issue by xflihaibo** [javascript-obfuscator/javascript-obfuscator#411]
The website can't be opened. https://obfuscator.io

**Comment by mbergwall2222** [comment]
+1

**Comment by egfx** [comment]
+1 goes down multiple times per day

**Comment by sanex3339** [comment]
Looks like I need to run it through pm2

**Comment by egfx** [comment]
pm2 or forever

**Comment by sanex3339** [comment]
Closed. Will look on `forever` when i'll have a time
