### ISSUE TITLE
what is the password for RC4 encoding option? Is the password revealed in the code?

### ISSUE THREAD

**Issue by letmegoforit** [javascript-obfuscator/javascript-obfuscator#416]
what is the password for RC4 encoding option? Is the password revealed in the code?

**Comment by letmegoforit** [comment]
Anyone can help? Many thanks1

**Comment by DecodeMehh** [comment]
RC4 key is being used within decryption function in second parameter.

**Comment by sanex3339** [comment]
Closed, because of answer
