### ISSUE TITLE
About Identifier Names Generator

### ISSUE THREAD

**Issue by lonewolfyx** [javascript-obfuscator/javascript-obfuscator#420]
can the Identifiers option in http://stunnix.com/prod/jo/be added to the Identifier Names Generator of this project?

**Comment by sanex3339** [comment]
Hi. Can you provide an example? Your link did not work for me

**Comment by zamotkin** [comment]
@sanex3339 http://stunnix.com/prod/jo/

**Comment by sanex3339** [comment]
I like `IIIllIII` option

**Comment by sanex3339** [comment]
I referenced your issue in the main suggestions issue and will close this issue
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/105

**Comment by da411d** [comment]
> I like `lllIIIlllI ` identifier names.
> Also later i want to implement the transformation of numbers to expressions:
> `1` -> `0x279+8794-0x24d2`
> Just need to think about the algorithm

I have idea, just made the snippet
https://gist.github.com/da411d/0e59f79dcf4603cdabf0024a10eeb6fe

**Comment by sanex3339** [comment]
Interesting! Thank you! I'll implement this feature (`0x279+8794-0x24d2`) after this PR https://github.com/javascript-obfuscator/javascript-obfuscator/pull/645

**Comment by sanex3339** [comment]
> > `1` -> `0x279+8794-0x24d2`
> > Just need to think about the algorithm
> 
> I have idea, just made the snippet
> https://gist.github.com/da411d/0e59f79dcf4603cdabf0024a10eeb6fe

https://github.com/javascript-obfuscator/javascript-obfuscator/pull/664

**Comment by sanex3339** [comment]
Released as `1.6.0`
