### ISSUE TITLE
Is there a way to exclude a function name from obfuscation?

### ISSUE THREAD

**Issue by andyhgames** [javascript-obfuscator/javascript-obfuscator#422]
Hello,

I am trying to obfuscate a javascript file using the _renameGlobals: true_ property.
I would like to exclude a particular function name from obfuscation.

**Here the smallest example of what I would like to achieve:**

function setup(){
 let a = 1;
 let b = 2;
 let c = 3;
}

**Using the obfuscation on the above function the result is:**

function _0x43764c(){
 let _0x2db121=0x1;
 let _0x3738c9=0x3;
 let _0x41faf2=0x4;
}

**Is there a way to keep the function name unchanged, like below?**

function setup(){
 let _0x2db121=0x1;
 let _0x3738c9=0x3;
 let _0x41faf2=0x4;
}

Thanks a lot for your help in advance.
Andrea

**Comment by slig** [comment]
Yes, use `Reserved Names` on the interface or look up the docs to see how to do it using the library/CLI.

**Comment by andyhgames** [comment]
> Yes, use `Reserved Names` on the interface or look up the docs to see how to do it using the library/CLI.

Thanks for your quick reply.
I tried to add 'setup' to the Reserved Names filed but the setup() function name does still get obfuscated.
I tried [setup], [^setup] and [/setup/] but no luck.

**Comment by andyhgames** [comment]
I solved my issue by adding 'setup' to both the Reserved Names and Reserved Strings field.
