### ISSUE TITLE
Preserving UserScript metadata

### ISSUE THREAD

**Issue by Racso** [javascript-obfuscator/javascript-obfuscator#423]
Hello.

UserScripts (such as those created for TamperMonkey or GreaseMonkey) require a [metadata block](https://wiki.greasespot.net/Metadata_Block) in order to work. A metadata block consists in several comments that describe aspects of the script. It's located in the beginning of the UserScript:

```
// ==UserScript==
// @key value
// @key value
// @key value
// ==/UserScript==

/* script goes here */
```

Would it be possible to preserve those metadata blocks after obfuscating? Perhaps a simple "Preserve comments" option would do.

Regards!
Ó.

**Comment by zamotkin** [comment]
You can use [conditional comments](https://github.com/javascript-obfuscator/javascript-obfuscator#conditional-comments) to skip obfuscation.

**Comment by zamotkin** [comment]
@Racso I'm closing this issue, if you have further questions feel free to ask.
