### ISSUE TITLE
generated wrong code

### ISSUE THREAD

**Issue by e12009** [javascript-obfuscator/javascript-obfuscator#424]
## Expected Behavior

With the following code snippet, after obfuscation, it reports undefined object.

 !function() {
    if (true) {
        let name = "charles";
    }
    if (true) {
        let {name, age} = {name: "foo", age: 100};
        console.log(name);
    }
}()

## Current Behavior

With above code, the generated code is like below 
( javascript-obfuscate <above-source-file> --compact false --seed 1)

var _0x3eb7 = [
    'foo',
    'log',
    'charles'
];
(function (_0x1c3ed4, _0x5087a2) {
    var _0x4a5a26 = function (_0x1c70bb) {
        while (--_0x1c70bb) {
            _0x1c3ed4['push'](_0x1c3ed4['shift']());
        }
    };
    _0x4a5a26(++_0x5087a2);
}(_0x3eb7, 0x119));
var _0x2857 = function (_0x590bb1, _0x2ddabf) {
    _0x590bb1 = _0x590bb1 - 0x0;
    var _0x280a78 = _0x3eb7[_0x590bb1];
    return _0x280a78;
};
!function () {
    if (!![]) {
        let _0x4f5231 = _0x2857('0x0');
    }
    if (!![]) {
        let {name, age} = {
            'name': _0x2857('0x1'),
            'age': 0x64
        };
        console[_0x2857('0x2')](_0x4f5231);
    }
}();

when running the generated code,  it reports: 
console[_0x2857('0x2')](_0x4f5231);
                                           ^

ReferenceError: _0x4f5231 is not defined

## Your Environment

* Obfuscator version used:  0.18.1
* Node version used:  v8.9.4

# Stack trace

**Comment by zamotkin** [comment]
I think the issue with variable _name_, the obfuscator creates the wrong scope for it. Try not to use the same variable's name in function's scope twice.

**Comment by e12009** [comment]
> I think the issue with variable _name_, the obfuscator creates the wrong scope for it. Try not to use the same variable's name in function's scope twice.

Yes, the obfuscator creates the wrong scope for the destructuring  assignment variables, if that variable name is used in some other scope.  

We are now trying to obfuscate our existing project, which has many similar case , so trying avoiding this syntax is a lot of work .   This should be fixed in obfuscator.

Our workaround is to first use babel to transcode before obfuscator.  But this should really be fixed in the obfuscator so that we can remove the babel transcoder.

**Comment by KonovalovaKV** [comment]
Hi!
Is there any news on this issue?

**Comment by e12009** [comment]
This problem is seriously preventing this obfuscator from a real project use.  Anybody working on it ?

**Comment by zamotkin** [comment]
I made Pull Request to solve this problem, the link above.

**Comment by sanex3339** [comment]
Thank you

**Comment by sanex3339** [comment]
`0.18.3` version is out

**Comment by e12009** [comment]
Great. It's now working !
