### ISSUE TITLE
reduce vulnerability

### ISSUE THREAD

**Issue by srguiwiz** [javascript-obfuscator/javascript-obfuscator#425]
The solution would be in `package.json` to increase:
```
  "opencollective": "~1.0.3",
```
and
```
  "version": "0.18.2",
```

That would make it ready for when `opencollective` fixes opencollective/opencollective-cli#17.

It is annoying when left as only vulnerability in an `npm install`.

**Comment by cekvenich** [comment]
Yes, I get a warning when users install my lib:

javascript-obfuscator > opencollective > babel-polyfill > core-js@<3.0 is no longer maintained and not recommended due to issues. Upgrade your dependencies to the actual version of core-js@>=3

Can we please do a version bump and a release.

**Comment by sanex3339** [comment]
Fixed in 
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/467
