### ISSUE TITLE
Is it possible to run the javascript-obfuscator in the browser?

### ISSUE THREAD

**Issue by andyhgames** [javascript-obfuscator/javascript-obfuscator#426]
Hello,
Is it possible to run the javascript-obfuscator directly in the browser?

I have installed the javascript-obfuscator  correctly using NPM and included the the reference link inside the head of my index.html:

     <script src="node_modules/javascript-obfuscator/dist/index.browser.js"></script>

I am not sure how to reference the instance of the obfuscator and the code gives me an error that the jsObfuscator is not defined:

      function obfuscation(data) {
       let obfuscationResult = jsObfuscator.obfuscate(data, {
       compact: true,
       controlFlowFlattening: true,
       deadCodeInjection: true,
       deadCodeInjectionThreshold: 0.4,
       reservedNames: [
        'setup',
        'draw'
      ],
      reservedStrings: [
        'setup',
        'draw'
      ],
      renameGlobals: true
    });
    return obfuscationResult;}

I cannot use the require method as I want to run this in the browser.
Is this possible?

Thanks in advance,

Andrea

**Comment by slig** [comment]
Hi,

By looking at the `index.browser.js` in the `dist` folder of this project, it looks like the package is exported as `JavaScriptObfuscator`, so you have to reference that instead of `jsObfuscator`.

**Comment by andyhgames** [comment]
> Hi,
> 
> By looking at the `index.browser.js` in the `dist` folder of this project, it looks like the package is exported as `JavaScriptObfuscator`, so you have to reference that instead of `jsObfuscator`.

Thanks for your reply, you are right! It exports the module as JavaScriptObfuscator.

Andrea
