### ISSUE TITLE
Javascript-obfuscator not working in CLI

### ISSUE THREAD

**Issue by PeterHdd** [javascript-obfuscator/javascript-obfuscator#433]
After installing javascript-obfuscator by doing:

```
npm install --save-dev javascript-obfuscator
```

and then trying to use it in the terminal in vscode, I keep getting the following error:

```
javascript-obfuscator: the term "javascript-obfuscator" is not recognized  as the name of the cmdlet or function,script file..
```

Should i do something else other than npm install?

**Comment by sanex3339** [comment]
Hi, try `npm link`

**Comment by bard0x** [comment]
Hi, I have the same issue installing javascript-obfuscator into an angular app also running npm link command

**Comment by hastalamuerte** [comment]
Same , was try to install via yarn, npm  with 
npm install -g javascript-obfuscator
npm i @javascript-obfuscator/escodegen
Nothing. plz help. Also where is Dist folder now? i can found it on older branches , but not in main. 
maybe it possible to create some cli tool? jar?

**Comment by slig** [comment]
@hastalamuerte 
It has a CLI tool https://github.com/javascript-obfuscator/javascript-obfuscator?tab=readme-ov-file#cli-usage

Probably your NPM's path install is incorrect, that's why you can't run it directly after installing with `-g`.

**Comment by hastalamuerte** [comment]
> @hastalamuerte It has a CLI tool https://github.com/javascript-obfuscator/javascript-obfuscator?tab=readme-ov-file#cli-usage
> 
> Probably your NPM's path install is incorrect, that's why you can't run it directly after installing with `-g`.

maybe there is some conflicts in windows PATH . i will check , thanks for answer. Found C:\Users\Username\AppData\Roaming\npm> cmd file and it work perfectly but seems it not use same configuration options by default like https://obfuscator.io/  (how it can be configured same?)

And yep it cant take as input whole file html/hta wich contain a bunch of scripts to obfuscation the script body of em.
