### ISSUE TITLE
Create page as https://www.obfuscator.io/?

### ISSUE THREAD

**Issue by goodwin74** [javascript-obfuscator/javascript-obfuscator#435]
I can’t understand from the description how to create a similar page at https://www.obfuscator.io/ ?!
It would be convenient if the description contained the item “Sample project” and a link to the GitHub folder, where files would be located, downloading which a person can run html directly on his PC. Without installation via NPM.

**Comment by sanex3339** [comment]
Hi. If you want to create web-UI for obfuscator, check this repo
https://github.com/javascript-obfuscator/javascript-obfuscator-ui

**Comment by sanex3339** [comment]
Closed. Reopen the issue if you need more info.
