### ISSUE TITLE
Stuck all the time

### ISSUE THREAD

**Issue by kiliaosi** [javascript-obfuscator/javascript-obfuscator#438]
![OWLIZNC`SO 8O(YS(_`0UZM](https://user-images.githubusercontent.com/35328622/69234279-bb7bb480-0bc9-11ea-8756-f7a4c4563c92.png)

Code cannot be disclosed。
What could be the problem？

**Comment by pawelzwronek** [comment]
Maybe accidentally you are trying to obfuscate already obfuscated code? It should work anyway, but it takes much more time so it appears as stuck.

**Comment by zamotkin** [comment]
Please post a minimal working code example to reproduce this issue.

**Comment by kiliaosi** [comment]
> 也许是偶然地您试图混淆已经混淆的代码？无论如何，它应该可以工作，但是要花费更多的时间，因此看起来像卡住了。



> Maybe accidentally you are trying to obfuscate already obfuscated code? It should work anyway, but it takes much more time so it appears as stuck.

> Yes, about an hour.  thank you.

**Comment by kiliaosi** [comment]
> Maybe accidentally you are trying to obfuscate already obfuscated code? It should work anyway, but it takes much more time so it appears as stuck.

>Yes, about an hour. thank you.
