### ISSUE TITLE
domainLock

### ISSUE THREAD

**Issue by bebeun** [javascript-obfuscator/javascript-obfuscator#45]
Hi, 

Could you confirm the syntax for domain lock ?

I use 

--domainLock [localhost, .example.com]

but it locks the file also on localhost. 

Thk U much !!

B

**Comment by sanex3339** [comment]
--domainLock 'localhost,.example.com'

**Comment by bebeun** [comment]
thk U so much for such a fast answer and for this wonderful tool ! You have
certainly save me hours of headache ! ;-)



2017-03-23 11:08 GMT+01:00 Timofey Kachalov <notifications@github.com>:

**Comment by sanex3339** [comment]
I hope you enjoy it!
