### ISSUE TITLE
Svelte/Sapper Project Obfuscating 

### ISSUE THREAD

**Issue by ehsanonline** [javascript-obfuscator/javascript-obfuscator#450]
is it possible to obfuscate svelte/sapper finished (build) project? if yes, how? and how much it will be obfuscated? that tools like Wappalyzer couldn't detect it.

**Comment by zamotkin** [comment]
If you are using rollup bundler please try [rollup-plugin-javascript-obfuscator](https://github.com/javascript-obfuscator/rollup-plugin-javascript-obfuscator)

You can play with [online obfuscator](obfuscator.io) options to review they.
