### ISSUE TITLE
Error on node 13.5.0

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/javascript-obfuscator#452]
Error on node 13.5.0
https://travis-ci.com/javascript-obfuscator/javascript-obfuscator/jobs/269066094

```
Error: The number of constructor arguments in the derived class ObfuscationEventEmitter must be >= than the number of constructor arguments of its base class.
```

**Comment by sanex3339** [comment]
Should replace `events` module on `eventemitter3` module

**Comment by thisismydesign** [comment]
Got the same issue on Node.js 12.16.0. The fix works.

**Comment by PeterHdd** [comment]
Im still getting this issue

**Comment by sanex3339** [comment]
What obfuscator version are you using?

**Comment by PeterHdd** [comment]
Latest one, I just did:

npm install --save-dev javascript-obfuscator 

In package.json:

```
    "javascript-obfuscator": "^1.1.0",
```

The error:

```
Error: The number of constructor arguments in the derived class t must be >= than the number of constructor arguments of its base class.
```

**Comment by PeterHdd** [comment]
any idea?

**Comment by sanex3339** [comment]
No. Try to completely remove your package-lock file and reinstall all packages from scratch

**Comment by sanex3339** [comment]
Also show me the output of `javascript-obfuscator -v` command

**Comment by sanex3339** [comment]
Any news?

**Comment by thanhpcc96** [comment]
issue too!

**Comment by sanex3339** [comment]
To everyone: try to remove package-lock.json and completely reinstall all your modules. Will it help?

**Comment by sanex3339** [comment]
Did you try this?

**Comment by sanex3339** [comment]
I will close this issue. Create another one if this problem exists after removing of `package-lock.json`

**Comment by Eljoy** [comment]
Facing the same issue using  1.8.1 version

**Comment by sanex3339** [comment]
This error is not possible on 1.8.1 because I changed the package that was the reason for this error.
Are you sure that you're using 1.8.1? 

Try to completely remove your package-lock file and reinstall all packages from scratch.
Also, show me the output of `javascript-obfuscator -v` command

**Comment by Eljoy** [comment]
Yes, my bad. I incorrectly overrode the nested dependency javascript-obfuscator dependency for react-native-obfuscating-transformer. Is there any chance that  javascript-obfuscator can be updated for react-native-obfuscating-transformer any time soon? That would be a massive help to everyone using it.

**Comment by aureliopetrone** [comment]
I get the same issue using react-native-obfuscating-transformer

**Comment by sanex3339** [comment]
As usual, try to completely remove your package-lock file and reinstall your dependencies.

Also, react native plugin is old, and you can use only obfuscator versions below 1.0.0.

**Comment by quantjamespecutus** [comment]
same issue with react-native-obfuscating-transformer here.

**Comment by sanex3339** [comment]
Same answer, try to remove package-lock.json and reinstall dependencies. Thisbpackage requires obfuscator versions ^0.13.0 and above, so it should install 0.28.5 version.

Also be aware that latest actual version is 1.11.0 and this package does not supports it. Maybe its a time to create the fork?

**Comment by sanex3339** [comment]
@quantjamespecutus also `react-native-obfuscating-transforner` has issue about this problem:
https://github.com/javascript-obfuscator/react-native-obfuscating-transformer/issues/35

**Comment by quantjamespecutus** [comment]
> @quantjamespecutus also `react-native-obfuscating-transforner` has issue about this problem:
> [javascript-obfuscator/react-native-obfuscating-transformer#35](https://github.com/javascript-obfuscator/react-native-obfuscating-transformer/issues/35)

thanks, appreciate the help

**Comment by qq1170623178** [comment]
hello,when i use laset version and more version ,the error is "Cannot read property 'sourceAndMap' of undefined  " so i use 0.18.3 ,that error is disappear，but error  ‘The number of constructor arguments in the derived class ObfuscationEventEmitter must be >= than the number of constructor arguments of its base class.’，please help me

**Comment by sgshy1995** [comment]
When I use `webpack-obfuscator@2.6.0`, this issue shows. Can any methods to reslove it without removing `yarn.lock` or `package-lock.json`? Because after I remove it and install again, the webpack throws an error that`WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.`, it tells me that my config has some wrongs but I cant find it. I use `javascript-obfuscator@latest` and  `webpack@4`.
