### ISSUE TITLE
Obfuscator complains about arrow function syntax 

### ISSUE THREAD

**Issue by toddrimes** [javascript-obfuscator/javascript-obfuscator#455]
The obfuscator is complaining about arrow function syntax such as:

```componentDidMount = async () => {... ```
or 
```setStuff = (i) => {...```

Is there an option to make this syntax acceptable?

Thank you,
~Todd

**Comment by sanex3339** [comment]
`espree` parser currently does not support `class-fields` proposal
https://github.com/eslint/espree#what-ecmascript-2019-features-do-you-support

I think because of this proposal currently in stage 3.
So, you should transform this code with babel before obfuscation.
