### ISSUE TITLE
Not able to handle the Invalid Domain - DomainLock

### ISSUE THREAD

**Issue by avneeshroks** [javascript-obfuscator/javascript-obfuscator#46]
Hi,

I am using Domain Lock feature, and when the domain is incorrect if throws this error: 

`Uncaught ReferenceError: data is not defined
    at out.js:1
    at _0xd895e (out.js:1)
    at out.js:1`

Is there any way to handle this? I need to show popup which says "Invalid Domain". Is there any way to achieve this?

Thanks in advance.

**Comment by sanex3339** [comment]
```
Uncaught ReferenceError: data is not defined at out.js:1 at _0xd895e (out.js:1) at out.js:1
```

It's by design. This error should confuse "hacker". No, currently no way to change this behaviour.

**Comment by slig** [comment]
If you desperately needs this feature, you can always see how it's originally implemented, copy and adapt to show your alert and paste it inside your original code. Then, you obfuscate normally without this option.

Keep in mind that, as @sanex3339 said, if you place an alert or something like that it will become easier to figure out where the protection is happening and to remove it.

**Comment by avneeshroks** [comment]
Good point guys, i didn't think of this.

Thanks for investing time.
