### ISSUE TITLE
Express Middleware

### ISSUE THREAD

**Issue by PDanielY** [javascript-obfuscator/javascript-obfuscator#464]
**Is your feature request related to a problem? Please describe.**
I think adding this feature would benefit a lot of developers looking to "hide" their code from the public

**Describe the solution you'd like**
A nodejs express middleware that automatically obfuscator your js code;

**Describe alternatives you've considered**
There are modules like ```express-minify``` that do this but they aren't reliable

**Comment by sanex3339** [comment]
Hi. This is not a feature, but a request for the standalone plugin. I don't know if this plugin already exists or not.
Anyway, I won't do it

**Comment by PDanielY** [comment]
@sanex3339 How is this invalid?

**Comment by PDanielY** [comment]
oof

**Comment by sanex3339** [comment]
You can do it by yourself and publish to the npm

**Comment by PDanielY** [comment]
.
