### ISSUE TITLE
warning:  Please, upgrade your dependencies to the actual version of core-js@3

### ISSUE THREAD

**Issue by cekvenich** [javascript-obfuscator/javascript-obfuscator#465]
warning: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues.

**Comment by sanex3339** [comment]
Upgraded in
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/467

**Comment by cekvenich** [comment]
Thanks, the new .2 release appears to remove the warning.
