### ISSUE TITLE
[Bug] splitStrings breaks reservedStrings

### ISSUE THREAD

**Issue by Akuka** [javascript-obfuscator/javascript-obfuscator#468]
I am trying to upgrade from version 0.19.2 to 0.19.4
The new option of `splitStrings` is not taking into account the strings in `reservedStrings`

I not sure, but it might related to https://github.com/javascript-obfuscator/javascript-obfuscator/pull/451 somehow

## Your Environment

* Obfuscator version used: 0.19.4
* Node version used: v12.14.0

**Comment by sanex3339** [comment]
Oh, thank you.
Should not split reserved string

**Comment by sanex3339** [comment]
`0.20.2` version is released
