### ISSUE TITLE
Should be able to obfuscate bin file for js

### ISSUE THREAD

**Issue by quickAppPlus** [javascript-obfuscator/javascript-obfuscator#471]
**Is your feature request related to a problem? Please describe.**
Now use this tool to obfuscate bin file will throw a error. eg.
```javascript
#!/usr/bin/env node

const process = require('process')
const path = require('path')
const cmd = require('commander')
const pkgInfo = require('../package.json')
```
output:
```bash
Error: Line 1: Unexpected character '#'
> ...#!/usr/bin/env n...
```

**Describe the solution you'd like**
Don't obfuscate this first line for this file will be ok.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/48240828/71706052-9b245400-2e1d-11ea-98f9-ae0c4f9621cf.png)

![image](https://user-images.githubusercontent.com/48240828/71706061-aa0b0680-2e1d-11ea-960e-76ddeb88ff22.png)

**Comment by sanex3339** [comment]
Hi. Currently `hashbang` operator is in stage 3 and `espree` parser does not support it.

Will process it on the obfuscator side before official support.

**Comment by sanex3339** [comment]
Hi. You need to keep `#!/usr/bin/env node` after obfuscation?

**Comment by quickAppPlus** [comment]
> Hi. You need to keep `#!/usr/bin/env node` after obfuscation?

yes  :smile:

**Comment by zpzxgcr** [comment]
@sanex3339 HI!  is there a solution?

**Comment by sanex3339** [comment]
Will fixed in https://github.com/javascript-obfuscator/javascript-obfuscator/pull/580
I'll release with it tomorrow

**Comment by sanex3339** [comment]
Merged. Will release `0.26.0` tomorrow

**Comment by sanex3339** [comment]
Released
