### ISSUE TITLE
Dead code injection always injects same string

### ISSUE THREAD

**Issue by yotamshapira** [javascript-obfuscator/javascript-obfuscator#476]
When I run the sample code below, the result returned is obfuscated code with two instances of `new Function('_FUNCTION_STRING_WILL_BE_HERE_');`.
In my use case, I obfuscate the code and later on replace `'_FUNCTION_STRING_WILL_BE_HERE_'` with other obfuscated code, so having 2 instances of that string really blows up my code and makes it too large.

## Expected Behavior

Only one instance of `new Function('_FUNCTION_STRING_WILL_BE_HERE_');` should be found in the obfuscated code.
## Current Behavior

Two instances of `new Function('_FUNCTION_STRING_WILL_BE_HERE_');` are found in the obfuscated code.
## Steps to Reproduce

Just run the sample code below, it will obfuscate the code and print out the obfuscated result.

## Your Environment

* Obfuscator version used: `0.20.4`, but the issue reproduced in `0.12.0` as well (I didn't check earlier versions)
* Node version used: `v12.6.0`

# Stack trace

## Minimal working example that will help to reproduce issue

```javascript
const obfuscatorConfig = {
    "deadCodeInjection": true,
    "deadCodeInjectionThreshold": 1,
    "reservedStrings": ["_FUNCTION_STRING_WILL_BE_HERE_"],
  }
;
const javaScriptObfuscator = require('javascript-obfuscator');
const FUNCTION_STRING_WILL_BE_HERE = "_FUNCTION_STRING_WILL_BE_HERE_";

const code = `function foo() {
  if (true) {
    return;
  }
}

  function boo() {
    if (true) {
      if (true) {
        new Function("${FUNCTION_STRING_WILL_BE_HERE}");
      }
    }
  }
`;

for (let i = 0; i < 10; i++) {
  console.log(`Obfuscation #${i + 1}`);
  let obfuscatedCode = javaScriptObfuscator.obfuscate(String(code), obfuscatorConfig).getObfuscatedCode();

  let _FUNCTION_STRING_WILL_BE_HERE_instanceCount = (
    obfuscatedCode.match(new RegExp(`${FUNCTION_STRING_WILL_BE_HERE}`, "g")) || []
  ).length;

  if (_FUNCTION_STRING_WILL_BE_HERE_instanceCount > 1) {
    console.log(obfuscatedCode);
    process.exit(1);
  }
}
```

**Comment by sanex3339** [comment]
Hi. Try to wrap 

```
function boo() {
    if (true) {
      if (true) {
        new Function("${FUNCTION_STRING_WILL_BE_HERE}");
      }
    }
  }
```

With the conditional comments, to prevent obfuscation if this function:
https://github.com/javascript-obfuscator/javascript-obfuscator#conditional-comments

**Comment by sanex3339** [comment]
Closed as inactive. Please, create another issue if you still have this problem and conditional comments did not help
