### ISSUE TITLE
Foreign letters are transformed as when UTF-8 encoding is interpreted as windows-1252

### ISSUE THREAD

**Issue by TorRanfelt** [javascript-obfuscator/javascript-obfuscator#481]
Only when I use JavaScriptObfuscator æ, ø and å are transformed; like "æ" to "Ã¦".
To avoid this I have been forced to enable unicodeEscapeSequence.

Is this a bug?
Is there a feature that I don't know of to avoid using unicodeEscapeSequence? I ask because the documentation advice against this with big source-codes, and I am obfuscating a big source-code.

**Comment by zamotkin** [comment]
I cannot reproduce this issue. Please share your obfuscator version, options, and a minimal code sample if possible.

**Comment by sanex3339** [comment]
Cannot reproduce here:
https://obfuscator.io/

**Comment by TorRanfelt** [comment]
I use webpack-obfuscator 0.21.0

Part of my webpack-configuration where changing unicodeEscapeSequence to false give the aforementioned strange behavior:
    const production = {
        plugins: [
            new JavaScriptObfuscator({
                compact: true,
                controlFlowFlattening: false,
                deadCodeInjection: false,
                debugProtection: false,
                debugProtectionInterval: false,
                identifierNamesGenerator: 'hexadecimal',
                log: false,
                renameGlobals: false,
                selfDefending: true,
                stringArray: false,
                stringArrayEncoding: false,
                unicodeEscapeSequence: true, // Only used to avoid æ, ø and å being transformed.
            }, ['*', '!main*.js'])
        ],
        optimization: {
            [ ... ]
            },
            minimizer: [
                new TerserPlugin({
                    parallel: true,
                    terserOptions: {
                        mangle: {
                            properties: {
                                regex: /_$/
                            }
                        }
                    }
                }),
                new OptimizeCSSAssetsPlugin({})
            ]
        }
    }

I experienced the same weird behavior with uglify-loader. Terser doesn't have any problems though.

In crunch mode now. I'll try and get back get to it in the future.

**Comment by TorRanfelt** [comment]
Sorry for wasting your time. My files were encoded with UTF-8, but the Content-Type header was set incorrectly.
Don't understand why webpack by default encode ø as \xf8 when it is UTF-8 anyway. Oh Well.
