### ISSUE TITLE
Content Security Policy (CSP) restrictions - "call to Function() blocked by CSP"

### ISSUE THREAD

**Issue by nunofaria11** [javascript-obfuscator/javascript-obfuscator#49]
Hi, I'm trying to obfuscate in a restricted CSP environment.

Obfuscated code:
```
var _0x330cf6 = Function(_0x2560('0x1') + _0x2560('0x2') + '\x29\x3b');
```
Console output:
```
Error: call to Function() blocked by CSP
```
Is there any way to somehow _deactivate_ the use of dynamic functions?

**Comment by sanex3339** [comment]
I'll thinking about that

**Comment by sanex3339** [comment]
Right now you should set to false following options that using Function(...) in their code:
disableConsoleOutput
domainLock
stringArrayEncoding

Currently Function(...) using in third places (equal lines) for getting global object:
var getGlobal = Function('return (function() ' + '{}.constructor("return this")( )' + ');');

So i should change way of getting global object.

**Comment by sanex3339** [comment]
Please try new `javascript-obfuscator@0.10.0-beta.8`
`eval` and `Function(...)` are no more using in code of custom nodes.

**Comment by sanex3339** [comment]
And with feedback please move to this issue:
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/65
