### ISSUE TITLE
disableConsoleOutput check if function was replaced

### ISSUE THREAD

**Issue by ddzobov** [javascript-obfuscator/javascript-obfuscator#500]
I think that will be good idea to check with interval if console.* functions were replaced by user again.
I think that It can be possible by something like this:
```
let console_copy = {
     log: console.log
};

setInterval(() => {
     console.log = console_copy.log;
}, 5);

var _0x3095=['Module','__esModule','Cannot\x20call\x20a\x20class\x20as\x20a\x20...
```

I think that you can check, if console.* functions are equivalent to your stubs:
```
let stub = function() {};

setInterval(() => {
     if(console.log !== stub) {
          console.log = stub;
     }
}, 5);
```

**Comment by sanex3339** [comment]
Not in near plans, currently i'm focusing on code transformations

**Comment by sanex3339** [comment]
I will link this issue with main feature suggestions issue, so i wont loose it
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/105
