### ISSUE TITLE
Disable using of browser-based features when target=node

### ISSUE THREAD

**Issue by ddzobov** [javascript-obfuscator/javascript-obfuscator#501]
I think that it will be good idea to disable these features when **target=node** with throwing exceptions to console:
- debugProtection
- domainLock
- sourceMap
- sourceMapBaseUrl
- sourceMapFileName
- sourceMapMode

**Comment by sanex3339** [comment]
Will be easy to implement

**Comment by sanex3339** [comment]
Disagree with `debugProtection`, because for some reason someone can try to inspect obfuscated `node.js` module

**Comment by sanex3339** [comment]
Added as an experimental feature. Will disable it if the feedback will negative.

**Comment by sanex3339** [comment]
Closed. Will released as part of `0.24.0` next week

**Comment by sanex3339** [comment]
Released as `0.24.0`

**Comment by dusan-dragon** [comment]
@sanex3339 why the sourcemap is not allowed for node target?

When you have application which does not run in browser you would like to have sourcemap so you can decode where the error happened. 🤔

**Comment by sanex3339** [comment]
Hmm

**Comment by sanex3339** [comment]
probably yes

**Comment by sanex3339** [comment]
Ok, i'll revert this rules for `sourceMap*` options

**Comment by dusan-dragon** [comment]
I mean I am using this lib for react native, so it is not really node either 😄  but I feel more comfortable to set it to node instead of browser.

**Comment by sanex3339** [comment]
Ok, will revert it

**Comment by sanex3339** [comment]
Reverted all options except `dimainLock` in `0.24.2` release
