### ISSUE TITLE
Is there a way to exclude entire directories instead of files?

### ISSUE THREAD

**Issue by mvillaizan** [javascript-obfuscator/javascript-obfuscator#504]
Is there a way to exclude entire directories instead of files?

**Comment by sanex3339** [comment]
Hi, exclude option accepts globs, so you can describe a path via glob pattern

**Comment by sanex3339** [comment]
Did I help you?

**Comment by sanex3339** [comment]
Closed. Feel free to create a new issue if you will have same problem
