### ISSUE TITLE
Handle import.meta

### ISSUE THREAD

**Issue by vincentvictoria** [javascript-obfuscator/javascript-obfuscator#505]
`import.meta` emits an error.
dynamic `import( './module.js' )` also emits an error.

I tried to avoid the issue with `// javascript-obfuscator:disable`, but that didn't help 🐙 

## Current Behavior
throws `Error: Unexpected token import`

## Minimal working example that will help to reproduce issue

1. import.meta

    console.log( import.meta );

2. dynamic import

    import( './module.js' );

3. dynamic import with an attempt to avoid obfuscating

    // javascript-obfuscator:disable
    import( './module.js' );
    // javascript-obfuscator:enable

**Comment by sanex3339** [comment]
Will fix it in a new version

**Comment by vincentvictoria** [comment]
Okay, Thanks!

**Comment by sanex3339** [comment]
Released as `0.24.0`

**Comment by vincentvictoria** [comment]
Didn't expect this ping. Thanks @sanex3339!

**Comment by sanex3339** [comment]
Np. `0.24.0` is a pretty big release and it took time.

**Comment by vitaliitrush** [comment]
any updates? :D
