### ISSUE TITLE
obfuscator.io obfuscate button not working

### ISSUE THREAD

**Issue by lazercorn** [javascript-obfuscator/javascript-obfuscator#529]
clicking the obfuscate button results in loading animation going on indefinitely

**Comment by sanex3339** [comment]
Hi. From today, obfuscation is completely client side with help of web workers.
So, what browser you are using? And show browser console output

**Comment by sanex3339** [comment]
Also, because now obfuscation is client-size, obfuscation speed depends on your hardware

**Comment by lazercorn** [comment]
It was working in my browser before. I will restart my computer then. Didn't realize it was client side. good to know!

**Comment by lazercorn** [comment]
so i open console, and it's saying "Uncaught SyntaxError: Unexpected token ... /workers/obfuscation-worker.js:25 Uncaught SyntaxError: Unexpected token ..."

**Comment by sanex3339** [comment]
What browser you are using?

**Comment by sanex3339** [comment]
Also can you show me code part that related with this error? Just click on the line number of error message.

**Comment by lazercorn** [comment]
SyntaxError: expected property name, got '...'  obfuscation-worker.js:25:205287

row 25 column 205287

I click it and it's just one line because it's minified. Tried on both firefox and chrome. Weirdly it works on my phone. Restarted computer still same error.

**Comment by sanex3339** [comment]
What chrome version you are using?

**Comment by lazercorn** [comment]
chrome 68. it was working on all the browsers on my pc not too long ago.

**Comment by lazercorn** [comment]
hm..not sure why but it it works now. 

Thanks.

**Comment by sanex3339** [comment]
You are used old chrome version that looks like not supported object rest or spread ({...foo}) syntax.

When you opened `About` info, looks like chrome started to update browser to the latest version. So, looks like now your chrome version is 79
