### ISSUE TITLE
target node change class name

### ISSUE THREAD

**Issue by LiadDrori** [javascript-obfuscator/javascript-obfuscator#531]
## Expected Behavior

1. As the documentation says 

> Currently the output of browser and node is identical.
 
But there is a difference between them.

2. When a class name change it should change the class name in static method calls
 
 
## Current Behavior

1. difference between the target node and browser
2. when calling static methods class name should also change
## Steps to Reproduce

Code exmple:
```
class A { 
	static async one(){
    	
    }
  
  	static async two(){
    	await A.one()
    }

}
```

When using target=Brwoser:

```
class A {
    static async ['one']() {
    }
    static async ['two']() {
        await A['one']();
    }
}

```
When using target=node:
```
class _0xd91f5a {
    static async ['one']() {
    }
    static async ['two']() {
        await A['one']();
    }
}
```

When running with a target node you get error because A is not defined 

## Your Environment

* Obfuscator version used: 0.24.0
* Node version used: 12.4

**Comment by sanex3339** [comment]
Will try to fix soon

**Comment by LiadDrori** [comment]
Besides this, are there are any other differences between node and browser? 
I run my code on node, so is it safe for now, until you fix the bug,  to change to browser?

**Comment by sanex3339** [comment]
`renameGlobals` breaking this code too

**Comment by sanex3339** [comment]
@LiadDrori currently Node target should affect only how identifiers are renamed

**Comment by sanex3339** [comment]
Should sanitize class scopes like this:
```
// fast fix of class scopes
        scope.childScopes.filter((scope: eslintScope.Scope) => {
            if (scope.type === 'class') {
                const upperVariable: eslintScope.Variable = <any>scope.upper?.variables.find((variable: eslintScope.Variable) => {
                    return variable.name === scope.variables[0].name;
                });

                upperVariable.references.push(...scope.variables[0].references);

                return false;
            }
        });
```

**Comment by sanex3339** [comment]
After this pr, here should be no difference between Node and Browser targets in terms of variable names.

**Comment by sanex3339** [comment]
Released as `0.24.1` please try it

**Comment by LiadDrori** [comment]
Seems to work for me to,

Thanks for the help!!!

**Comment by sanex3339** [comment]
Nice!
