### ISSUE TITLE
Removed brackets when ** operator is used

### ISSUE THREAD

**Issue by pawelzwronek** [javascript-obfuscator/javascript-obfuscator#534]
## Expected Behavior
`console.log((1-2) ** 2)` should be obfuscated to `console['log']((0x1 - 0x2) ** 0x2)`

## Current Behavior
Now it's obfuscated to `console['log'](0x1 - 0x2 ** 0x2)`

## Your Environment
https://obfuscator.io/

**Comment by sanex3339** [comment]
Hi. This is escodegen problem, this package does not support this operator properly.
The fix can take long time from them, so better to use Math.pow until fix

**Comment by sanex3339** [comment]
I'll try to make PR

**Comment by sanex3339** [comment]
Created the PR
https://github.com/estools/escodegen/pull/407

So, you can ping it.

**Comment by pawelzwronek** [comment]
Great! But what do you mean ping it? :)

**Comment by sanex3339** [comment]
Just write there something, that you need this fix, because this PR can take a few days or even week to merge and release version with fix

**Comment by sanex3339** [comment]
Released as `0.24.6`

**Comment by pawelzwronek** [comment]
Great, it's working, thanks!
