### ISSUE TITLE
No PayPal link

### ISSUE THREAD

**Issue by pawelzwronek** [javascript-obfuscator/javascript-obfuscator#536]
Hi Timofey!

I've just donated 30$ over https://opencollective.com/ but the fees are 15%. Can you give me your paypal address so I can send more money :) It would be convenient if there were PayPal link in README.md

Best regards!

**Comment by sanex3339** [comment]
Thank you! My paypal is https://www.paypal.me/javascriptobfuscator

**Comment by sanex3339** [comment]
Thank you for the support!

**Comment by pawelzwronek** [comment]
You are welcome!

śr., 29 sty 2020 o 16:08 Timofey Kachalov <notifications@github.com>
napisał(a):

**Comment by sanex3339** [comment]
Added paypal link
