### ISSUE TITLE
Intermittent restart/crash

### ISSUE THREAD

**Issue by vasist** [javascript-obfuscator/javascript-obfuscator#54]
I had implemented obfuscator in my module - working fine in local but not in live
                        compact: true,
			controlFlowFlattening: false,
			debugProtection: false,
			debugProtectionInterval: false,
			disableConsoleOutput: true,
			rotateStringArray: true,
			selfDefending: true,
			stringArray: true,
			domainLock: ["xxx.com"],
			stringArrayEncoding: false,
			stringArrayThreshold: 0.75,
			unicodeEscapeSequence: false
<img width="734" alt="screen shot 2017-05-24 at 1 40 21 pm" src="https://cloud.githubusercontent.com/assets/7236679/26424591/a0d947f2-4086-11e7-9e87-fd1c4aaa1157.png">

**Comment by sanex3339** [comment]
Hi, can you provide more detailed error description?

**Comment by vasist** [comment]
<img width="1356" alt="screen shot 2017-05-25 at 2 26 30 pm" src="https://cloud.githubusercontent.com/assets/7236679/26471455/a1dbe404-4156-11e7-8134-e99686fa716e.png">
<img width="1367" alt="screen shot 2017-05-25 at 2 28 49 pm" src="https://cloud.githubusercontent.com/assets/7236679/26471453/a1d8f406-4156-11e7-8b47-d8a790ec314d.png">
<img width="1357" alt="screen shot 2017-05-25 at 2 29 00 pm" src="https://cloud.githubusercontent.com/assets/7236679/26471457/a1dc494e-4156-11e7-9901-607a07ab1b11.png">
<img width="1385" alt="screen shot 2017-05-25 at 2 29 10 pm" src="https://cloud.githubusercontent.com/assets/7236679/26471454/a1d9b79c-4156-11e7-8e40-98d85d632708.png">
<img width="1360" alt="screen shot 2017-05-25 at 2 29 18 pm" src="https://cloud.githubusercontent.com/assets/7236679/26471458/a1dd4a38-4156-11e7-94ce-d8eee85e8291.png">
<img width="1338" alt="screen shot 2017-05-25 at 2 29 25 pm" src="https://cloud.githubusercontent.com/assets/7236679/26471456/a1dc3df0-4156-11e7-879e-02e9d9bb3070.png">

this is the heap trace

**Comment by sanex3339** [comment]
You tried to run `javascript-obfuscator` in browser? It designed to run under Node.js

**Comment by vasist** [comment]
yes we are running in both browser as well as node.
how does it relate to the current OOM(out of memory) issue ?

**Comment by sanex3339** [comment]
How many lines of code in project?

**Comment by vasist** [comment]
I cant provide source code.
Can you please take standalone javascript code (around 500-600 lines) and try to execute it

**Comment by sanex3339** [comment]
I tested obfuscator on angular 2 bundle, around 70k loc, without any problems

**Comment by vasist** [comment]
this is server side..

**Comment by sanex3339** [comment]
Closed due to inactivity time, small amount of information and unsupported environment by project.

**Comment by venky352** [comment]
@sanex3339 I have a dynamically generated Javascript (some randomness involved)for each request which needs to be sent to the browser. If we obfuscate the code which needs to be sent over to the browser, over a period of time the server is crashing because of out of memory issue. It looks like the cache here https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/utils/Utils.ts#L14 is piling up over a period of time due to randomness in the javascript code. Is there a way to cleanup the cache or having cache maintained for only one call. Could you please suggest?

**Comment by sanex3339** [comment]
I should clear all static caches after obfuscation.

**Comment by venky352** [comment]
Thanks @sanex3339 for re opening the issue. When can we expect this fix to be published as part of 0.10.0? There is an urgency for this fix and I see my app is getting crashed often.  If this takes longer time, I can take fork from your repo and make temporary fix and use it for sometime till the actual fix made from your side. Thanks for your help.

**Comment by sanex3339** [comment]
I'll release 0.10.0-beta.5 today or in a few next days. 
If you eant to create fork - be aware. 
Most easiest way is to clear this static cache in the `obfuscate` method, but this method will call during obfuscation few times to obfuscate code of custom nodes. This happens two times - before  and after AST tree obfuscation, so static cache will be unexpected cleared before and after transformations. From now it looks like that it wont affect cache of main transformation stage, but be aware. 

In next beta release i will extract this cache and encoding method to separate non-static class, so it wont have any unexpected sideeffects during recursive calls.

**Comment by sanex3339** [comment]
I'm working on it. This fix required much more internal changes than i expected.

**Comment by sanex3339** [comment]
Hi again. @vasist, @venky352 please try new `javascript-obfuscator@0.10.0-beta.5`
Problem should be (i hope) fixed.

**Comment by venky352** [comment]
Thanks @sanex3339 for fixing it. We will check If this fixed our issue and let you know.

**Comment by sanex3339** [comment]
Any news?

**Comment by sanex3339** [comment]
Problem should be fixed. Please reopen issue if not.

**Comment by jhg** [comment]
Maybe this is related:

```
<--- Last few GCs --->

[69633:0x103802800]   227597 ms: Scavenge 2020.0 (2027.2) -> 2019.5 (2037.7) MB, 11.7 / 0.0 ms  (average mu = 0.111, current mu = 0.040) allocation failure 
[69633:0x103802800]   227630 ms: Scavenge 2026.4 (2037.7) -> 2025.1 (2038.7) MB, 22.7 / 0.0 ms  (average mu = 0.111, current mu = 0.040) allocation failure 
[69633:0x103802800]   227653 ms: Scavenge 2027.3 (2038.7) -> 2026.2 (2059.7) MB, 19.6 / 0.0 ms  (average mu = 0.111, current mu = 0.040) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x100930c99]
Security context: 0x21d5bff808a1 <JSObject>
    1: charCodeAt [0x21d5bff8cb29](this=0x21d603ac0111 <Very long string[50070008]>,0x21d569f52911 <HeapNumber 4.49379e+07>)
    2: btoa(aka value) [0x21d570d56369] [/Users/jesus/Repositories/ProtectedJS/node_modules/javascript-obfuscator/dist/index.js:~24] [pc=0xe60560f6f5f](this=0x21d5892a1529 <e map = 0x21d5774286b1>,0x21d58929d741 <Very long st...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10007e9b3 node::Abort() [/usr/local/bin/node]
 2: 0x10007eb37 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x100176337 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1001762d3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1002fa485 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x1002fbb54 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 7: 0x1002f8a27 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x1002f6a0d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 9: 0x1002f58c1 v8::internal::Heap::HandleGCRequest() [/usr/local/bin/node]
10: 0x1002bac3f v8::internal::StackGuard::HandleInterrupts() [/usr/local/bin/node]
11: 0x1005f7b6c v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x100930c99 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
Abort trap: 6
```

I use it with node 12.13.1 all in node side, not browser.

**Comment by zamotkin** [comment]
@jhg try to increase max heap size with node flag `max_old_space_size`.

**Comment by kiliangr** [comment]
@jhg  I don't know if you're still facing this issue. I faced it and tried to increase max heap size without any effect. For me the solution was to disable selfDefending.

**Comment by sanex3339** [comment]
@kiliangr Are you getting this problem during runtime of your obfuscated code?
Self defending completely freezes code if this code is modified in some way.
So, be sure, that you don't touch code after obfuscation.

**Comment by kiliangr** [comment]
This was happening only when running tests with nock on the obfuscated server. I will look into the tests in details but for now I am running the server without self defending.

**Comment by jhg** [comment]
I was thinking to use it with electron, I'm not sure if it's possible that the built app run with that flag always.

Anyway, @kiliangr, also I tested with others how difficult it was to face with obfuscate code and... ok, maybe someone even don't try, but very few time. Less of one hour, a second time even less. Maybe or only minify or if really need obfuscation better try wasm or native modules if it's for node.
