### ISSUE TITLE
Broken After 0.24

### ISSUE THREAD

**Issue by beeing** [javascript-obfuscator/javascript-obfuscator#542]
After updating the lib, there's a chance that the String Array does not work correctly.

I tested below code in obfuscator.io

```js
rows.forEach((row, index) => {
  if (o.val) fn(` CONTENT ${o.val}`)
})
```

- String Array
  - Rotate
  - Shuffle
  - Base64 Encoding
  - Threshold - 0.5
- Split String Chunk: 15
 
The above will generate (result differs for each run):

```js
rows['forEach']((c, d) => {
    if (o[b('0x0')])
        fn('\x20CONTENT\x20' + o['val']);
});
```

```js
rows['forEach']((c, d) => {
    if (o[b('0x1')])
        fn(b('0x0') + o['val']);
});
```

```js
rows['forEach']((c, d) => {
    if (o['val'])
        fn(b('0x1') + o[b('0x0')]);
});
```

I was expecting the code to be below instead.

```js
    if (o[b('0x0')])
        fn(b('0x1') + o[b('0x0')]);
```

**Comment by sanex3339** [comment]
And what is wrong?

**Comment by sanex3339** [comment]
If you worried about different indexes for string array calls, it is ok, because `shuffleStringArray` option is enabled.

**Comment by sanex3339** [comment]
For example, i tested with the following code:
```
const rows = [
    {
        val: 'foo'
    },
    {
        val: 'bar'
    },
    {
        val: 'baz'
    }
];

rows.forEach((row, index) => {
  console.log(`CONTENT ${row.val}`);
})
```

And everything is ok. Order of logs is correct: `'foo', 'bar', 'baz'`

**Comment by beeing** [comment]
Thanks for the quick reply. Actually you need to add the if before the console.log.

It is ok if it does not break anything but for my case, it broke my tests.

There are no errors but the code after the if is not executed.

**Comment by sanex3339** [comment]
Can you show me a standalone small example, that is worked before obfuscation and does not work after?

**Comment by sanex3339** [comment]
The problem looks the same as here:
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/496

Can you try to search a minimum standalone example that will reproduce this error?

**Comment by beeing** [comment]
I've been trying to reproduce a simpler example however not able to reproduce. The source that I have i quite complex which I'm trying to find the pattern that causes it.

Similar to #496 there is no error but produces a wrong result due to the if condition is not met.

My initial suspect was the if condition was wrongly replaced.

**Comment by sanex3339** [comment]
Try to play with options as I said before. We should t find as many hints as possible

**Comment by beeing** [comment]
I've turned off every as below and still having wrong results.

```js
    target: 'node',
    compact: false,
    controlFlowFlattening: false,
    deadCodeInjection: false,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: false,
    identifierNamesGenerator: 'mangled',
    log: false,
    renameGlobals: false,
    rotateStringArray: false,
    selfDefending: false,
    sourceMap: false,
    splitStrings: false,
    splitStringsChunkLength: 15,
    stringArray: false,
    stringArrayEncoding: 'base64',
    stringArrayThreshold: 0.9,
    shuffleStringArray: false,
    transformObjectKeys: false,
    unicodeEscapeSequence: false
```

If you want, I can email you a sample as my code and the result.

**Comment by sanex3339** [comment]
It will be nice! Send it on sanex3339 a t yandex.ru

**Comment by beeing** [comment]
Finally, found the issue here:

```js
function run(aaa, { missing = '' } = {}) {
    let q = `run ${aaa} `;
    if (missing)
        q += ` SOMETHING ${missing}`;
    return q;
}

console.log(run('dummy', { missing: 'IMPORTANT' }))
```

The `{ missing }` is renamed but the outside calling function is still using the same signature.

**Comment by sanex3339** [comment]
Nice!

**Comment by sanex3339** [comment]
PR with the fix https://github.com/javascript-obfuscator/javascript-obfuscator/pull/544

**Comment by sanex3339** [comment]
Please, try 0.24.5 version

**Comment by sanex3339** [comment]
Reopened until approve from your side

**Comment by sanex3339** [comment]
It was fixed there:
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/496

So expect that it was fixed here too

**Comment by sanex3339** [comment]
Comment here if this problem will happen again

**Comment by beeing** [comment]
Yes. Just tested and it looks good so far. Thanks for the quick fixes!

**Comment by sanex3339** [comment]
Nice! Thank you for investigating the problem
