### ISSUE TITLE
The keyword 'interface' is reserved

### ISSUE THREAD

**Issue by zadlo** [javascript-obfuscator/javascript-obfuscator#543]
It seems that after updating my modules I have such error with javascript-obfuscator

`[18:25:25]` Error in plugin "gulp-javascript-obfuscator" 
Message: ERROR in line 10269: The keyword 'interface' is reserved (10269:51)
> ...ace = function(interface) {...
Details:
domainThrown: true`

Any idea how to solve this problem?

**Comment by sanex3339** [comment]
It is the correct error. `interface` is a reserved keyword in javascript.
https://www.w3schools.com/js/js_reserved.asp

So, rename this identifier to other name.
