### ISSUE TITLE
About batch processing

### ISSUE THREAD

**Issue by lonewolfyx** [javascript-obfuscator/javascript-obfuscator#551]
I use https://obfuscator.io/ a lot，but sometimes it takes multiple files to process，so can  you add a bulk processing feature here?

Thank you

**Comment by sanex3339** [comment]
Hi. Currently, i more focused on the obfuscator itself. So right now I haven't time to add so big feature to the web ui.

But PR welcomed!

**Comment by lonewolfyx** [comment]
okay i'll be looking forward to it.
