### ISSUE TITLE
Unicode characters for identifier names

### ISSUE THREAD

**Issue by kittenswolf** [javascript-obfuscator/javascript-obfuscator#553]
The current name generators are a bit lack-luster. I propose a new identifier name generator which basically generates random unicode sequences.

Most unicode is valid for variable names. See:
See: https://mothereff.in/js-variables#%C3%A4%C3%B6%C3%BC%C3%9F%E5%AD%97%E6%BC%A2%E5%AD%97%E5%85%AB

I think this would be a great addition, making code even more unreadable.

**Comment by sanex3339** [comment]
Right now i prefer existing identifier name generators
