### ISSUE TITLE
when i use obfuscator@0.24.5 will cause very strange error.

### ISSUE THREAD

**Issue by bookyo** [javascript-obfuscator/javascript-obfuscator#556]
i have a 4000 lines node code,  i use version 0.18.7 work fine, but use 0.24.5 will cause very strange error.  

like:
const { title, permission, group} = req.body;
sometime will cause group is undefined or some other from req.body be undefined, but i post body is work fine.

i have hundreds const {arg1, arg2, arg3...} = req.body;
but when i submit,  some arg will became undefined.

my config:
compact code: true
identifier Names Generator: hexadecimal
self defending: true
control flow flatteing: true
control flow flattening threshold: 0.8
dead code injection: true
dead code injection threshold: 0.4
string array: true
rotate string array: true
string array encoding: rc4
string array threshold: 0.8
unicode escape sequence: true
disable console output: true
debug protection: true
debug protection interval: true
seed:0
target: node

**Comment by bookyo** [comment]
const vipbuys = await Vipbuy.find().populate('group');
will cause TypeError: Cannot read property 'refPath' of undefined.
this like 'group' be undefined.

**Comment by sanex3339** [comment]
Hmm. Transform object keys is disabled?

**Comment by sanex3339** [comment]
Try to remove all opttions, the error will happen?

**Comment by sanex3339** [comment]
I need an example of the code

**Comment by bookyo** [comment]
like:
```
exports.postadddownload = async (req, res) => {
  const { name, url, type } = req.body;
  await Download.create({
    name,
    url,
    path: './download/' + name + '.mp4',
    status: '等待下载',
    type,
  })
  res.redirect('/admin/download');
}
```
after post, type property will lost.  i dont know what happen, maybe somewhere type is against this 'type'.

**Comment by sanex3339** [comment]
Can you debug:
`const { title, permission, group} = req.body;`
after this line, `group` already `undefined`?

**Comment by bookyo** [comment]
can fix it by obfuscator more times. i think this is because i have more function inclue type property.
like:
```
exports.posteditad = async (req, res) => {
  const id = req.body.id;
  const { title, type } = req.body;
  let types = [];
  types = types.concat(type);
  console.log(types);
  await Ad.updateOne({ _id: id }, { $set: { title, type: types.join(',') } });
  res.redirect('/admin/ad');
};
exports.postaddapp = async (req, res) => {
  const { title, theimg, link, duration, type } = req.body;
  await App.create({ title, img: theimg, link, duration, type });
  res.redirect('/admin/app');
};
```

**Comment by bookyo** [comment]
i cant reappear it. sorry. i already fix it by obfusecate more times.
