### ISSUE TITLE
About property mangling

### ISSUE THREAD

**Issue by edreal** [javascript-obfuscator/javascript-obfuscator#559]
This seems to be the major weakness of all obfuscators.
My idea would be that when the option is enabled, it mangles only objects/classes which are accessed only in safe constant manner with the dot notation like `obj.test = 123`

If obfuscator detects that the "obj" object is accessed somewhere with the bracket notation like:
```
var test = obj[unpredictablePropName];
```
In that case the obfuscator shouldn't mangle any of the "obj" objects property names as that test function might break. However in 99% of the code, I only use the obj.dotNotation.

Could this work or is there some other drawbacks I missed?

**Comment by sanex3339** [comment]
Direct object keys obfuscation is not in the nearest plans. Dublicate of https://github.com/javascript-obfuscator/javascript-obfuscator/issues

**Comment by edreal** [comment]
Okay, why though? I am actually curious would my idea have some drawbacks.

**Comment by sanex3339** [comment]
There is a bunch of more important things to do right now.
Anyway, PR is welcomed.
