### ISSUE TITLE
let {a,b} = obj // dont encode a,b vars

### ISSUE THREAD

**Issue by k7eon** [javascript-obfuscator/javascript-obfuscator#561]
**Is your feature request related to a problem? Please describe.**
i tested on obfuscator.io (with default settings and enabled keys encoding) and my own cli config.
places with 
`let {aaa,bbb} = {aaa:123,bbb:222}` 
become on 
`let {aaa,bbb}=_0x27da44`
i dont found the flag to enable "aaa,bbb" encodes too.

**Describe the solution you'd like**
i would saw on next updates default encoding this or new flag. If not possible simplify it and encode then print warning

**Describe alternatives you've considered**
Code: `let aaa = obj.aaa` ll be encoded fine.

**Comment by sanex3339** [comment]
This is expected behaviour, because both variable names are based on the object property names.

So, i won't changet in the future.
