### ISSUE TITLE
--output behaves totally different on new version 0.25.0

### ISSUE THREAD

**Issue by dusan-dragon** [javascript-obfuscator/javascript-obfuscator#565]
The new version of obfuscator introduced breaking change because it changed behaviour of `--output` parameter.

Command `./node_modules/.bin/javascript-obfuscator ./test.js --output aaa` will behave:
v0.24.2: will create file `aaa`
v0.25.0: will create folder `aaa` and inside it will be file `test.js` 

## Expected Behavior
The library should not introduce breaking change without mentioning it somewhere (release notes) or it should bump major version?

## Current Behavior
The same command produce obfuscated code in different locations

## Steps to Reproduce
1. Run `./node_modules/.bin/javascript-obfuscator ./test.js --output aaa` on v0.24.2
2. Run `./node_modules/.bin/javascript-obfuscator ./test.js --output aaa` on v0.25.0
3. compare location and name of outputs

## Your Environment

* Obfuscator version used: 0.24.2 / 0.25.0
* Node version used: 12.11.1

## Minimal working example that will help to reproduce issue
See steps to reproduce, it does not depend on content of file which is going to be obfuscated

**Comment by sanex3339** [comment]
It isnot a bug. It is a bug fix, because 'aaa' is not a file name, but a directory name.

Also,currwnt version is 0.25.2, which is a lower than 1.0.0, so i can release breaking changes every minor release.

**Comment by sanex3339** [comment]
In your case, you should use 'aaa.js'

**Comment by dusan-dragon** [comment]
🤔 I do not agree with you on this one. Just by seeing some string you cannot tell if it is file or folder.

But still it was breaking change for us and it broke our pipeline. Also note that there is no text mentioning this difference in the readme, nor release notes.

The old behaviour is there for couple months already so the new behaviour could break it for a lot of people.

**Comment by dusan-dragon** [comment]
> Also, current version is 0.25.2, which is a lower than 1.0.0, so i can release breaking changes every minor release.

Hmm good point, thanks for pointing out totally forgot about this aspect of semver :) This is my fault as I set wrong expectation for myself

**Comment by sanex3339** [comment]
I will update changelog to list this change
