### ISSUE TITLE
Using browser-image-compression npm package causes "infinite wait"

### ISSUE THREAD

**Issue by rricamar** [javascript-obfuscator/javascript-obfuscator#566]
Hi, I´m using https://www.npmjs.com/package/browser-image-compression for compress some images on my web app. The fact is that when I obfuscate the code, the library call never returns, resulting in an "infinite wait". I know that is this calls because I put a lot of logs for debug this, but no error is given 😰 

Without obfuscating it, it works.

## Your Environment

* Obfuscator version used: 0.25.2
* Node version used: 10.16.3

# Stack trace

The library doesn't produce any error, it just gets stuck

## Minimal working example that will help to reproduce issue

```typescript
async reduceImages(files: File[]): Promise<File[]> {
    return Promise.all(
      files.map(async (file: File) => {
        try {
          const resizedImage = await this.imageCompression(file, {
            maxWidthOrHeight: 1200, // px
          });
          return resizedImage;
        } catch (error) {
          this.logger.warn('Resize error:', error);
          return file;
        }
      }),
    );
  }
```

I can upload the obfuscated javascript file if needed 👍

**Comment by sanex3339** [comment]
Hi. Show your options

**Comment by sanex3339** [comment]
Yes, also upload your obfuscated script please

**Comment by rricamar** [comment]
- Hi again @sanex3339 , ty a lot for your work as always, this is the script which I use for minificate the script:

```javascript

const fs = require('fs');
const { exec } = require('child_process');

// criteria
const file_prefix = 'main-';
const file_extension = '.js';

// entry point
(async function() {
  await obfuscate();
})();

// helpers
async function obfuscate() {
  const files = fs.readdirSync('./www/');

  for (let i in files) {
    const file = files[i];

    if (shouldObfuscate(file)) {
      try {
        console.debug(`Obfuscating "${file}" ...`);
        await exec_promise(
          `./node_modules/javascript-obfuscator/bin/javascript-obfuscator www/${file} --output www/${file}`,
        );
        console.debug(`Obfuscated "${file}"`);
      } catch (err) {
        process.exit(-1);
      }
    } else {
      console.debug(`File "${file}" doesn't match the criteria, skip it ...`);
    }
  }
}

function shouldObfuscate(file) {
  return file.startsWith(file_prefix) && file.endsWith(file_extension);
}

function exec_promise(command) {
  return new Promise((resolve, reject) => {
    exec(command, (err, stdout, stderr) => {
      if (err) {
        console.error(stderr);
        reject(err);
      }

      resolve(stdout);
    });
  });
}

```

- In the command that you see, I tried also this options: 

`--compact true --controlFlowFlattening false --deadCodeInjection false --debugProtection false --debugProtectionInterval false --disableConsoleOutput true --identifierNamesGenerator hexadecimal --log false --renameGlobals false --rotateStringArray true --selfDefending true --splitStrings false --stringArray true --stringArrayEncoding false --stringArrayThreshold 0.75 --unicodeEscapeSequence false`

- Here is the .zip with the files you asked for, it contains the main-es2015 file and the chunk that is requested when the whole process is called (maybe it can help you).

[minify.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/4265951/minify.zip)

One more time, thank you a lot for your hard work on the library and your quick response 🙏

**Comment by sanex3339** [comment]
Oh. The file is very large, 160k loc.
Can you try to found the problem place and create a standalone small example that won't work?

**Comment by sanex3339** [comment]
To be clear, i need:
- a source file beyond 1000 lines of code that will have this problem
- the options, that I should use to obfuscate this file
- the instructions about how to reproduce this bug

**Comment by rricamar** [comment]
Hi, please take a look to:

https://github.com/rricamar/javascript-obfuscator-566

It's a repo with a minimal working of obfuscation not working.
If I use the non-obfuscated option it works.
Anything please let me know.

**Comment by sanex3339** [comment]
Thank you, will check it

**Comment by sanex3339** [comment]
Hi. At first, please try `0.25.3` version. If it won't help, i'll check it in a few days.

**Comment by sanex3339** [comment]
So.
The problem here:
```
var t = function createWorker(e) {
        return new Worker(URL.createObjectURL(new Blob(["(".concat(e, ")()")])))
    }(function () {
        var e = !1;
        self.addEventListener("message", function (n) {
            return new Promise(function (r, t) {
                var i, a, o, s, c = n.data;
                i = c.file, a = c.id, o = c.imageCompressionLibUrl, s = c.options;
                var u = function $Try_1_Post() {
                    try {
                        return r()
                    } catch (e) {
                        return t(e)
                    }
                }, f = function $Try_1_Catch(e) {
                    try {
                        return self.postMessage({error: e.message + "\n" + e.stack, id: a}), u()
                    } catch (e) {
                        return t(e)
                    }
                };
                try {
                    var m;
                    return e || (importScripts(o), e = !0), imageCompression(i, s).then(function (e) {
                        try {
                            return m = e, self.postMessage({file: m, id: a}), u()
                        } catch (e) {
                            return f(e)
                        }
                    }, f)
                } catch (e) {
                    f(e)
                }
            })
        })
    });
```

You are defined worker body in the same file, where you created the instance of this worker.
Everything inside the worker's body cannot access the outer scope.
But `javascript-obfuscator` cannot know about it and it transformed the worker's body as a usual function, so, the first call to the strings array inside the worker's body is thrown the error.

How to avoid it?
1) Move the body of the worker to a different file
2) Add conditional comments to prevent obfuscation of the worker's body
```
 var t = function createWorker(e) {
        return new Worker(URL.createObjectURL(new Blob(["(".concat(e, ")()")])))
    }(function () {
        //javascript-obfuscator:disable
        var e = !1;
        self.addEventListener("message", function (n) {
            return new Promise(function (r, t) {
                var i, a, o, s, c = n.data;
                i = c.file, a = c.id, o = c.imageCompressionLibUrl, s = c.options;
                var u = function $Try_1_Post() {
                    try {
                        return r()
                    } catch (e) {
                        return t(e)
                    }
                }, f = function $Try_1_Catch(e) {
                    try {
                        return self.postMessage({error: e.message + "\n" + e.stack, id: a}), u()
                    } catch (e) {
                        return t(e)
                    }
                };
                try {
                    var m;
                    return e || (importScripts(o), e = !0), imageCompression(i, s).then(function (e) {
                        try {
                            return m = e, self.postMessage({file: m, id: a}), u()
                        } catch (e) {
                            return f(e)
                        }
                    }, f)
                } catch (e) {
                    f(e)
                }
            })
        })
        //javascript-obfuscator:enable
    });
```

From my side, currently, i won't add the special logic for the inline worker's body, because this is a very special case and `conditional comments` feature was designed specially for this cases

**Comment by sanex3339** [comment]
Ping

**Comment by rricamar** [comment]
Hi @sanex3339 I cannot test 0.25.3 yet since our services were down all week 😢, my bad. But about your solution, it seems that code is of the library isn't it? so no power over there, I couldn't use your disable comments...

Before today's end I´ll let you know if it works, ty!

**Comment by sanex3339** [comment]
Hmm. If it is a library code, this is bad. Need to think.

**Comment by rricamar** [comment]
I was reading the npm docs: https://www.npmjs.com/package/browser-image-compression

Im going to try to disable this param on the call:

`useWebWorker: boolean,      // optional, use multi-thread web worker, fallback to run in main-thread (default: true)`

Because maybe is the source of the problems, so:

1. Try your 0.25.3 version
2. Same as 1) but disabling this params

**Comment by sanex3339** [comment]
Yes, try to disable web worker. And use `0.25.4` version.

**Comment by rricamar** [comment]
Hi @sanex3339 , I can confirm that 0.25.4 works, but I don´t if it was for the new version or that I disabled `useWebWorker` on the library. I´m going to try again with the `useWebWorker:true` (default) and let you know

**Comment by sanex3339** [comment]
It is because you are disabled web workers.

**Comment by rricamar** [comment]
> It is because you are disabled web workers.

Yes, I can confirm that is because of that ... 😱 

Thank you for all your time, I'll go with the `userWebWorker` option to false for now ... 🤦‍♂ 

Ty again and your hard work on this repo and the quick response 👍 

Should I close the issue?

**Comment by sanex3339** [comment]
yes

**Comment by rricamar** [comment]
Perfect, ty! 🙏
