### ISSUE TITLE
Whether it support its work in "Requirejs"

### ISSUE THREAD

**Issue by lonewolfyx** [javascript-obfuscator/javascript-obfuscator#567]
hi

often use this project. can make it work in `RequireJs` ?

**Comment by sanex3339** [comment]
Hi, what it means?

**Comment by lonewolfyx** [comment]
i use this project in `[RequireJs](RequireJs)`，error : JavaScriptObfuscator is not function

so can we use support in RequireJs

**Comment by sanex3339** [comment]
I haven't the plans to add support for it, but PR welcomed

**Comment by sanex3339** [comment]
I will close this issue. If you want, you can create PR with this feature.
