### ISSUE TITLE
Identifier has already been declared with mangled option

### ISSUE THREAD

**Issue by Exocomp** [javascript-obfuscator/javascript-obfuscator#568]
Version: 0.25.2 
Angular: 9

Options:
```compact: true,
identifierNamesGenerator: 'mangled',
stringArray: true,
rotateStringArray: true,
shuffleStringArray: true,
selfDefending: true,
```

Using it with a fairly decent sized angular project that uses multiple bundles I'm running into the following errors when using the "mangled" option:

`Uncaught SyntaxError: Identifier 'a' has already been declared`

I also tried the "dictionary" option with a supplied list of identifiersDictionary while the obfuscate command succeeds it still fails at runtime with a "Identifier 'xxx' has already been declared". However, its intermittent some builds work while other times fails.

Using "hexadecimal" works however it has a pretty big footprint. For example, a 500Kb gz gets to about 950 gz with hexadecimal.

Anyway the "mangled" option generator can be optimized?

**Comment by sanex3339** [comment]
Hi, i need an example of your source code which helps me to reproduce this error.

**Comment by Exocomp** [comment]
I understand I'll have to find some time to reproduce it with a new angular project and then I can make the whole thing available.

**Comment by sanex3339** [comment]
Ok, thank you.

**Comment by sanex3339** [comment]
Also, can you try 0.25.1 version. It will work?

**Comment by Exocomp** [comment]
I tried to reproduce it with a new Angular 9 project but I could not get it to reproduce.

So it may be what you saw that it could some specific syntax that is causing it, I'll try again to reproduce it when I get more time.

By the way, I tried es5 bundles I get a new error, "ERROR TypeError: a8[b(...)] is not a function"

> Also, can you try 0.25.1 version. It will work?

Let me give it a try.

**Comment by sanex3339** [comment]
Can you send me your project (Angular 9) with the problem via email?

**Comment by Exocomp** [comment]
> Also, can you try 0.25.1 version. It will work?

Same thing with 0.25.1

> Can you send me your project (Angular 9) with the problem via email?

Nope. However, if I can get it to reproduce with a new Angular 9 project which I'm hoping to then for sure.

**Comment by sanex3339** [comment]
Ok. 0.25.0 introduced a completely new `mangled` algorithm, so, i really hope that you will found a way to reproduce this bug.

**Comment by Exocomp** [comment]
I tried the CLI and to my surprise that actually worked. While the code method (require('javascript-obfuscator')) fails. Hmm.

Please hold while I do some more testing to determine if I'm doing something in code that is causing the problem.

**Comment by sanex3339** [comment]
This is good. 
Few questions.
Did you use obfuscator before `0.25.*` versions?
If yes, had you this error before?

Probably this is just a conflict between global identifier names between different bundles.
As i understood, you have a few bundles. With `mangled`, each bundle has global identifier names that are started from names like `a`, `b`, `c`.

Because you have a few bundles, these identifier names can conflict with each other.
For this case, here is an option: `identifiersPrefix`. You can use a different prefix for each bundle.
With CLI, this prefix is added automatically.

**Comment by Exocomp** [comment]
Yes this is very good.

> Because you have a few bundles, these identifier names can conflict with each other.
> For this case, here is an option: `identifiersPrefix`. You can use a different prefix for each bundle.
> With CLI, this prefix is added automatically.

That is starting to make sense. Let me give that a shot.

**Comment by Exocomp** [comment]
I'm good to go, that fixed the issue, wohoo.

I'll leave it up to you on how you want to handle this case and close it.

Thanks a lot for your help!

**Comment by Exocomp** [comment]
Ok, another case that causes the same issue.

Using identifiersPrefix with `selfDefending: true` causes the issue.  Any thoughts there?

**Comment by Exocomp** [comment]
Using domainLock also causes the issue.

This works:
```
{
	identifiersPrefix: 'unique identier goes here',
	compact: true,
	identifierNamesGenerator: 'mangled',
	stringArray: true,
	rotateStringArray: true,
	shuffleStringArray: true
}
```

This does not work:
```
{
	identifiersPrefix: 'unique identier goes here',
	compact: true,
	identifierNamesGenerator: 'mangled',
	stringArray: true,
	rotateStringArray: true,
	shuffleStringArray: true,
	domainLock: ['.mydomain.com']
}
```
Or
```
{
	identifiersPrefix: 'unique identier goes here',
	compact: true,
	identifierNamesGenerator: 'mangled',
	stringArray: true,
	rotateStringArray: true,
	shuffleStringArray: true,
	selfDefending: true
}
```

**Comment by sanex3339** [comment]
Will check it

**Comment by jmeinke** [comment]
Hey @sanex3339, what you suggest would be great. We're currently also using the javascript-obfuscator in combination with electron-webpack and `identifierNamesGenerator: 'hexadecimal'`. Upgrading javascript-obfuscator produces the problem `Identifier ... has already been declared`, also with  `identifierNamesGenerator: 'mangled'`. I have tried setting the identifierPrefix in the obfuscator config, but it seems that we need to set an own identifierPrefix for each of the generated bundles?

**Comment by sanex3339** [comment]
Yes. Each bundle should have own prefix. This prefix will affect only global identifiers of this bundle.

**Comment by jmeinke** [comment]
You said earlier, that the CLI will automatically add prefixes for multiple files in a directory correctly. This does not seem to prevent the error that is produced in our case (electron + webpack):
https://sentry.io/share/issue/8f7eb1ac01dc4ea1b44e4349fafb36e7/

We're using the command like this:
```
npx javascript-obfuscator ./dist --config=./obfuscator.config.json --output .
```

The config currently looks like this:
```
{
  "compact": true,
  "controlFlowFlattening": false,
  "deadCodeInjection": true,
  "deadCodeInjectionThreshold": 0.4,
  "debugProtection": false,
  "debugProtectionInterval": false,
  "disableConsoleOutput": true,
  "identifierNamesGenerator": "mangled",
  "log": false,
  "renameGlobals": false,
  "rotateStringArray": true,
  "selfDefending": false,
  "stringArray": true,
  "shuffleStringArray": true,
  "stringArrayEncoding": "base64",
  "stringArrayThreshold": 0.75,
  "unicodeEscapeSequence": false
}
```

Thanks for any hints!

**Comment by sanex3339** [comment]
PR with the fix
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/570

**Comment by sanex3339** [comment]
Released as `0.25.3`

**Comment by jmeinke** [comment]
Thanks for releasing the new version. I've tried it and unfortunately I still get the `identified already declared` problem with the above configs. With version `0.18.8` of javascript-obfuscator the same configs are working well. So for me the problem is not yet solved. Should we provide you with the bundles / dist directory? Oo

**Comment by sanex3339** [comment]
You can send me bunles (with html code that will import this bundles) via email. I will check it.

**Comment by sanex3339** [comment]
Also, i updated `webpack-obfuscator` with auto-generation of identifiers prefixes

**Comment by sanex3339** [comment]
@jmeinke hi. Are you still have this problem on `0.25.4`? If yes, please, create a new issue with details about how are you using obfuscator, and a minimal example if possible.

**Comment by jmeinke** [comment]
Hey @sanex3339, when trying to start the app using the obfuscated code, I get the following error:
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'call' of undefined
    at eQ (/tmp/.mount_...-wIMTCm/resources/app.asar/main.js:1:21716)
    at /tmp/.mount_...-wIMTCm/resources/app.asar/main.js:1:23035
    at Object.<anonymous> (/tmp/.mount_...-wIMTCm/resources/app.asar/main.js:1:23052)
    at Object.<anonymous> (/tmp/.mount_...-wIMTCm/resources/app.asar/main.js:2:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Object.<anonymous> (/tmp/.mount_Idana-wIMTCm/resources/electron.asar/browser/init.js:188:8)
```

What's your email address?

**Comment by sanex3339** [comment]
sanex3339 at yandex.ru
