### ISSUE TITLE
New API - hideString

### ISSUE THREAD

**Issue by yotamshapira** [javascript-obfuscator/javascript-obfuscator#573]
**Is your feature request related to a problem? Please describe.**
In my project, I use "internal" javascript-obfuscator functionality to hide strings:
```typescript
import { ServiceIdentifiers } from "javascript-obfuscator/src/container/ServiceIdentifiers";
import { ICryptUtils } from "javascript-obfuscator/src/interfaces/utils/ICryptUtils";
import { IInversifyContainerFacade } from "javascript-obfuscator/src/interfaces/container/IInversifyContainerFacade";
import { InversifyContainerFacade } from "javascript-obfuscator/src/container/InversifyContainerFacade";

export class SecurityUtils {

  public static hide(str: string, length: number, sourceCode: string, inputOptions: any): [string, string] {
    const inversifyContainerFacade: IInversifyContainerFacade = new InversifyContainerFacade();
    inversifyContainerFacade.load(sourceCode, '', inputOptions);
    return inversifyContainerFacade.get<ICryptUtils>(ServiceIdentifiers.ICryptUtils).hideString(str, length);
  }
}
```
The issue is that I need to know the internal structure of javascript-obfuscator in order to achieve this, compile its code, etc.

**Describe the solution you'd like**
If possible, something similar to this function added to the index.d.ts file:
```typescript
export function hideStr(str: string, length: number, options: ObfuscatorOptions): [string, string]
```

**Describe alternatives you've considered**
As mentioned above, I can compile this by myself, but would rather not do so.

**Additional context**
Even more APIs to be exposed will be very welcome!

**Comment by sanex3339** [comment]
Hi. How are you want to use it? This functionality will be used alongside with the main `obfuscate` method or you just want to use this `hideString` method alone, for your purposes?

**Comment by yotamshapira** [comment]
Hi & thanks for the quick reply!

Its alongside the `obfuscate` method - I "hide" my strings and then `obfuscate`, just to make it a little bit harder to de-obfuscate (i.e. once de-obfuscated, the string will still be hidden, requiring more, less obvious work from the debugging developer).

Thanks.

**Comment by sanex3339** [comment]
By string you meaning each string literal in the code or the whole deobfuscated code as a single string?

**Comment by yotamshapira** [comment]
No - only a set of specific string values that I mean to "hide".
e.g.
```javascript
var hiddenStr = "myValue" // "myValue" should be hidden
var clearStr = "notMyValue" // "notMyValue" should NOT be hidden
```

**Comment by sanex3339** [comment]
Can you provide a standalone simple example with simple source code, `obfuscate` and `hideString` methods, please?
I just want to understand how you plan to use it. If necessary to make it public, or maybe find to a different solution.

**Comment by yotamshapira** [comment]
Sure, I will try to complete it soon

**Comment by yotamshapira** [comment]
Hi,

Please see the example here: https://github.com/yotamshapira/obfuscation-sample
To run it, please run `npm install` and then 'npm run build`

I hope this makes things more clear.

**Comment by sanex3339** [comment]
This API won't be allowed to access outside of the package.
