### ISSUE TITLE
2020 plans

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/javascript-obfuscator#574]
So, after 0.25.* I plan to do the following:
- new mechanism to modify code as a string. Two stages: `before` and `after` `AST` transformations. This will help me to implement https://github.com/javascript-obfuscator/javascript-obfuscator/issues/471 or, for example, the custom mechanism with APP lock (see beyond about it).
- add more code transformations similar to `uglifyjs` or `terser` transformations: convert block scopes to the sequence expressions; convert conditions to ternary conditions; convert simple conditions (and loops) to conditions without block scope
- bug fixes and other feature requests

About APP lock:
The idea is simple. After primary obfuscation, encode all code as a string with `rc4` encoding with a key and append helpers to receive this key via request from the specified URL address and decode this code.

Without concrete dates about each feature, just when i have time

**Comment by userbabu** [comment]
The boss worked hard

**Comment by sanex3339** [comment]
Have started to implement `minify` option with a bunch of `minification` transformers.

**Comment by sanex3339** [comment]
Base `simplify` option has been merged into `master`

**Comment by sanex3339** [comment]
Code transformations and `simplify` option released. Now I will close this issue. App lock feature will be covered in a separate issue.
