### ISSUE TITLE
Copyright & License text added to the top of the JS file should remain at the top after obfuscation

### ISSUE THREAD

**Issue by arnkumar243** [javascript-obfuscator/javascript-obfuscator#575]
![obfuscation](https://user-images.githubusercontent.com/27776238/76284372-1f360480-62c3-11ea-8c17-9c58a3f5d2a3.png)

I added a copyright info to the @license tag. The @license tag is added to the top of the javascript file. But after obfuscation my @license tag is no more at the top. Its moved to second line. I want to have @license tag at the top of the JS file after obfuscation is it possible ?

**Comment by sanex3339** [comment]
Will create a PR with the fix very soon

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/578

**Comment by sanex3339** [comment]
Expect the release today or tomorrow

**Comment by sanex3339** [comment]
Released as `0.25.5`
