### ISSUE TITLE
Issue with two separated obfuscated files on the same page

### ISSUE THREAD

**Issue by slig** [javascript-obfuscator/javascript-obfuscator#58]
Hi,

I think I found an issue. I have two independent javascript files on a page, each one obfuscated by the `webpack-obfuscator` plugin (i.e: different bundles on different `<script>`  tags). Since they both use the same configuration from `webpack.conf.js`, they have the same `seed` config and thus the first variable name that is used on the `stringArray` variable is the same for both obfuscated files. That is an issue as the variable used by `stringArray` is a global and gets replaced by the second script.  
Then somewhere after loading the scripts, any interaction from the first bundle with the `stringArray` function will look at the second bundle `stringArray` variable.

Possible workarounds that I could think: 

1. Have the obfuscator output an immediately invoked function that would scope the variable and not leak them to the global scope.
2. Use the `seed` parameter plus an hash of the source code as the real seed used by the obuscator. This is not fail-proof as it still might generate two variables with the same name and mess things.

Thanks!

**Comment by sanex3339** [comment]
I like second option.

**Comment by sanex3339** [comment]
I'll implement it today or tomorrow.

**Comment by sanex3339** [comment]
Did it, new beta will be ready in 20 mins.

**Comment by sanex3339** [comment]
Hi, check new `javascript-obfuscator@0.10.0-beta.6`

**Comment by slig** [comment]
Thank you very much, will try!

**Comment by sanex3339** [comment]
Any news?

**Comment by slig** [comment]
Sorry for not reporting before. It does work perfectly as expected, thank you very much!

**Comment by sanex3339** [comment]
Nice!
