### ISSUE TITLE
Including a banner to obfuscated output

### ISSUE THREAD

**Issue by kevinpthorne** [javascript-obfuscator/javascript-obfuscator#584]
I cannot seem to find anything on the web about this:

Is there a way currently to add a banner using the BannerPlugin or a preamble like UglifyJS? It seems the Obfuscator currently wipes all comments (expected), including the one put in by the BannerPlugin.

Any help or direction is much appreciated!

**Comment by sanex3339** [comment]
Hi. Add `@preserve`to this comment

**Comment by kevinpthorne** [comment]
Works like a charm. Adding `@preserve` to the comment in the banner plugin like so:

```
new webpack.BannerPlugin({
		banner: '//@preserve My banner, copyright, or whatever',
		raw: true,
		entryOnly: true
})
````

Thank you!
