### ISSUE TITLE
Support for Twig and other templating delimiters

### ISSUE THREAD

**Issue by nickpapoutsis** [javascript-obfuscator/javascript-obfuscator#587]
**Is your feature request related to a problem? Please describe.**
Twig uses {{...}} to insert values into the code at runtime. Usually it's for the HTML parts of the code but they can also be used in JS so `var temp = {{ random_value_coming_from_somewhere_else }}` is perfectly valid code because when you load the page it becomes `var temp = 'some_value'`.

However, if you try to obfuscate such code it throws an error and can't proceed.

**Describe the solution you'd like**
A solution might be custom regexp (for example `/({{).*(}})/gmi` for twig) to ignore certain parts of the code.

**Describe alternatives you've considered**
For now I have moved the declaration of those variables outside the obfuscated code but if I had too many of them it would have been cumbersome.

**Comment by sanex3339** [comment]
Obfuscator works with the valid javascript code.

```
var temp = {{ random_value_coming_from_somewhere_else }}
```

is not the valid javascript code.

**Comment by nickpapoutsis** [comment]
No, it's not valid JS code but it's valid code if you are using Symfony/Twig/etc.
