### ISSUE TITLE
Disabling obfuscation for a module

### ISSUE THREAD

**Issue by Tuszy** [javascript-obfuscator/javascript-obfuscator#589]
Hello,
is there any possibility to disable the obfuscation (name mangling, string array etc.) for a complete module? 
Unfortunately /* javascript-obfuscator:disable */ is not working for me. The functions within the module are still obfuscated when imported from another module. 

Best regards
Dennis

**Comment by 26medias** [comment]
Did you figure it out? I have the same issue.

**Comment by Tuszy** [comment]
No I didn't, sorry...
