### ISSUE TITLE
"use strict" converted to hexa breaks strict mode 

### ISSUE THREAD

**Issue by sp-kilobug** [javascript-obfuscator/javascript-obfuscator#59]
Maybe an "exclude" option could be useful for string to hexa.
Additionally, strings are always converted to hexadecimal code. Since it's not difficult to decrypt hexa,  could you please make this optional ? 
```javascript
function is_strict(){
    'use strict'; // <------- broken
    var is_strict = false;
    try {
        mistypeVariable = 17;  // throws a ReferenceError in strict mode
    } catch(e) {
        is_strict = true;
    }
    return is_strict;
}
alert('strict mode = '+is_strict());

//function is_strict() {
//    '\x75\x73\x65\x20\x73\x74\x72\x69\x63\x74';
//    var _0x2d65e3 = ![];
//    try {
//        mistypeVariable = 0x11;
//    } catch (_0x457d9d) {
//        _0x2d65e3 = !![];
//    }
//    return _0x2d65e3;
//}
//alert('\x73\x74\x72\x69\x63\x74\x20\x6d\x6f\x64\x65\x20\x3d\x20' + is_strict());
    
```

**Comment by sanex3339** [comment]
Hi, check this option
https://github.com/javascript-obfuscator/javascript-obfuscator#unicodeescapesequence

**Comment by sp-kilobug** [comment]
Thank you for your quick reply. Maybe I'm wrong somewhere but here is what I get with gulp-javascript-obfuscator + jso 0.9.4 on windows :

Options :
```
compact: false, 
selfDefending: false,
debugProtection: false,
debugProtectionInterval: false,
disableConsoleOutput: false,
stringArray: false,
stringArrayEncoding: false,
unicodeEscapeSequence: false <----
```
Result :
```javascript
function is_strict() {
    'use\x20strict'; <--- space converted to hexa
    var _0x60e281 = ![];
    try {
        mistypeVariable = 0x11;
    } catch (_0xa0d545) {
        _0x60e281 = !![];
    }
    return _0x60e281;
}
alert('strict\x20mode\x20\x3d\x20' + is_strict()); <--- space and "=" chars converted
```

**Comment by sanex3339** [comment]
And  'use\x20strict'; doesn't working?

On 0.9.x versions all non-latin and non-digit characters will encoded anyway.
On 0.10.0-beta.6 version will encoioded only few symbols selected by this regExp
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/utils/EscapeSequenceEncoder.ts#L26

**Comment by sp-kilobug** [comment]
Looks like the strict mode is very strict ;) with \x20 it's not working in last Chrome or Firefox. But this should  work in 0.10.x. I'm still thinking unicodeEscapeSequence = false should disable all escaping for string literal but I suppose it's necessary for other functionalities. Thank you for your great work.

**Comment by sanex3339** [comment]
> I'm still thinking unicodeEscapeSequence = false should disable all escaping for string literal but I suppose it's necessary for other functionalities.

I can't disable escaping for string literals at all, because runtime errors with strings with linebreaks. This regExp - minimal working filter that work on Angular 2 bundle.

**Comment by sanex3339** [comment]
So, the only one solution for me now - add `'use strict';` to the ignore list

**Comment by sanex3339** [comment]
Hi! Check new `javascript-obfuscator@0.10.0-beta.9`.

I added black list of nodes that shouldn't obfuscated. Currently it contains only one node - 'use strict' operator.

**Comment by sanex3339** [comment]
Use `javascript-obfuscator@0.10.0-beta.10`

`beta.9` has breaking errors.

**Comment by sp-kilobug** [comment]
Thank you very much, it's perfect

**Comment by sanex3339** [comment]
Nice. Please close the issue if your problem was solved.
