### ISSUE TITLE
e.replace is not a function

### ISSUE THREAD

**Issue by skdjfla** [javascript-obfuscator/javascript-obfuscator#590]
/Users/chenbingfeng/freeprojects/openwebmonitor-real/node_modules/javascript-obfuscator/dist/webpack:/JavaScriptObfuscator/src/code-transformers/preparing-transformers/HashbangOperatorTransformer.ts:39
            .replace(/^#!.*$(\r?\n)*/m, (substring) => {
             ^
TypeError: e.replace is not a function

**Comment by sanex3339** [comment]
Need more info. Show your source code

**Comment by sanex3339** [comment]
ping

**Comment by skdjfla** [comment]
`// obfuscate js code
const JavaScriptObfuscator = require('javascript-obfuscator');
const fs = require('fs')
const path = require('path')

const what_to_obfuscate = [
    'super-source', 'super-module', 'main', 'recording', 'index', 'constants', 'browser', 'utils', 'vip_renew', 'winmgr',
    'libopenlog'
]

what_to_obfuscate.forEach(fn=>{
    let full_path =  path.join(__dirname, `${fn}.js`)
    console.log(full_path)
    let raw_data = fs.readFileSync(full_path)
    
    let obfuscationResult = JavaScriptObfuscator.obfuscate(
        raw_data,
        {
            compact: false,
            controlFlowFlattening: true
        }
    );

    fs.writeFileSync(full_path, obfuscationResult.getObfuscatedCode())
})
`

**Comment by skdjfla** [comment]
Read a js file, and obs them, then write back.

**Comment by skdjfla** [comment]
Above error happens when using the lastest version. when changed to old version     "javascript-obfuscator": "~0.19.4"  it disappears.

**Comment by sanex3339** [comment]
Are you sure that `raw_data` for each file is `string` and not `undefined`?

**Comment by skdjfla** [comment]
yes, if file not exist, exception will happen when read. Im sure, that all `raw_data` are a string,

**Comment by skdjfla** [comment]
For be sure, I will check it doubel later

**Comment by sanex3339** [comment]
Check it please. Because this error can happen if source code is not a string.

From my side i should add exception  from the obfuscator side if input source code is not a string

**Comment by sanex3339** [comment]
So, i got this error, when i passed `number` as source code.
```
JavaScriptObfuscator.obfuscate(1).getObfuscatedCode();
```

**Comment by sanex3339** [comment]
Released as `0.27.4`
Now if source code is not a string, it will be normalized to an empty string.
