### ISSUE TITLE
Random error: Unexpected token *

### ISSUE THREAD

**Issue by 1nfility** [javascript-obfuscator/javascript-obfuscator#591]
## Current Behavior
Obfuscating a large file with code, using max settings can sometimes cause the error: ```Unexpected token *```

This error does not happen always, but sometimes. I assume it's an bug under obfuscation where something might be random..?

## Your Environment
I'm using webpack-obfuscator.
* Obfuscator version used: 0.27.2
* Node version used: v12.16.1

**Comment by sanex3339** [comment]
Need more info about how to reproduce this
