### ISSUE TITLE
Support optional chaining and nullish coalescing syntax

### ISSUE THREAD

**Issue by tedgoddard** [javascript-obfuscator/javascript-obfuscator#604]
**Is your feature request related to a problem? Please describe.**
Support optional chaining syntax: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

For example `a?.b`

**Describe the solution you'd like**

Obfuscate code making use of optional chaining.

**Describe alternatives you've considered**

Disable obfuscation for files containing this syntax

**Additional context**

**Comment by sanex3339** [comment]
Hi. We have to wait until this PR will be merged
https://github.com/estools/escodegen/pull/412

But that PR depends on `acorn` PR with this feature. So, expect this not so soon.

**Comment by tedgoddard** [comment]
Relevant Acorn PR: https://github.com/acornjs/acorn/pull/891

**Comment by sanex3339** [comment]
`Acorn` PR has been merged, now waiting for the `escodegen` PR

**Comment by sanex3339** [comment]
This PR estools/escodegen#412 makes me sad

**Comment by sanex3339** [comment]
I think that if I won't get any response during this week, I'll create the fork of `escodegen` (`@javascript-obfuscator/escodegen` package) and `estraverse` (`@javascript-obfuscator/estraverse` package) that will be used until these changes will be merged into the base repo

**Comment by sanex3339** [comment]
Also here is the PR with `nullish coalescing` support
https://github.com/estools/escodegen/pull/417

**Comment by sanex3339** [comment]
Optional chaining has been merged on escodegen side!

**Comment by sanex3339** [comment]
Seems the last step it the PR for `esrecurse` because `eslint-scope` uses it.
https://github.com/estools/esrecurse/pull/22

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/697

**Comment by sanex3339** [comment]
Optional chaining support has been merged. Expect a release later today.

**Comment by sanex3339** [comment]
Optional chaining support still requires estools/esrecurse#22 but right now I avoided it by using `Selective dependency resolutions` feature of `yarn`

**Comment by sanex3339** [comment]
Optional chaining support just has been released as `1.10.0`

**Comment by sanex3339** [comment]
Will be released soon as `2.7.0`
