### ISSUE TITLE
Is there a way to randomize the file names?

### ISSUE THREAD

**Issue by 5haw4** [javascript-obfuscator/javascript-obfuscator#605]
So I'm using this library on my NodeJS project and it works really good, the only problem is that after obfuscation the new files has the same names and I'd really like to not leave the same names for the files, I read the docs few times but couldn't figure out if it's possible to randomize (or uglify) the output file names?
In addition to that, I was interested in knowing if the obfuscation is reversible, meaning if someone gets a hold on the code, can they make it human readable again? (and what if I use a seed, does that mean that you're gonna have to need the seed to un-obfuscate?)

**Comment by sanex3339** [comment]
Hi. Currently, there is no way to randomize file names, and it not in the nearest plans. But PR welcomed.
