### ISSUE TITLE
non reproducible results with "String Array" on "https://obfuscator.io/"

### ISSUE THREAD

**Issue by wothke** [javascript-obfuscator/javascript-obfuscator#606]
3rd party code reviewers are not able to verify that some obfuscated code is indeed equivalent to some original source code since they get a different result when THEY obfuscate the same input source code with the same obfuscation options (even when "shuffle string array" and "rotate string array" options are disabled).

## Expected Behavior
I want to use the "String Array" feature and there should be an option that allows for the exact same obfuscated output every time the same input is used with the exact same obfuscator options (whatever "randomness" is used should be controllable via the UI - but it seems that the "Seed" present in the current UI does not serve this purpose). When I supply both the original and the obfuscated source code to some 3rd party reviewer he should be able to reproduce the exact same obfuscated output from the original source code.

## Current Behavior
It looks as if the order in which the strings appear in the generated array is different each time the same input is processed (from a new browser session) but with the exact same UI settings.

## Steps to Reproduce
open https://obfuscator.io/
click "Reset options"
chose: "Identifier Names Generator=mangled"
disable: "Rotate String Array" & "Shuffle String Array"
set: "String Array Threshold=1"
set: "Seed=1"
set: "Transform Object Keys"
Copy & Paste JavaScript Code => and click "Obfuscate"

=> repeat process and compare the two outputs in some diff tool like WinMerge

## Your Environment
online: https://obfuscator.io/

# Stack trace
na

## Minimal working example that will help to reproduce issue
na

**Comment by sanex3339** [comment]
Hi. Show me the minimal code that will look different between different obfuscations.
With the default code, I got the same results.

**Comment by wothke** [comment]
[diff.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/4661721/diff.zip)
here the output of 2 runs (using the same obfuscator settings - see above; browser closed completely between the 2 runs; I also included beautified versions of the output that might make it easier to see what is going on..)

**Comment by sanex3339** [comment]
Can you show me the original code?

**Comment by sanex3339** [comment]
The obfuscator itself works fine. Looks like something goes wrong with the options on
https://obfuscator.io/

Maybe related with save options to the local storage

**Comment by wothke** [comment]
That's what I thought.. (I meanwhile had an additional issue but I'll open a separate ticket for that..)

**Comment by sanex3339** [comment]
Please try now. All values inside text inputs didn't reset correctly

**Comment by wothke** [comment]
good job, I'd say you fixed it

**Comment by sanex3339** [comment]
Nice!
