### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by ert55** [javascript-obfuscator/javascript-obfuscator#612]
I'm running my app in a low resource environment. After a few calls to JavaScriptObfuscator.obfuscate my nodejs app runs out of memory.
Each obfuscation increases the heap by ~10mb and never gets garbage collected.

var app = require('express')();
var JavaScriptObfuscator = require('javascript-obfuscator');
.....
app.use(async function (req, res, next) {
 if (path.basename(req.url) == 'somefile.js') {
  var file = fs.readFileSync('somefile.js', 'ascii');
  var obfuscationResult = JavaScriptObfuscator.obfuscate(file, {
                    compact: true,
                    controlFlowFlattening: true,
                    controlFlowFlatteningThreshold: 0.75,
                    deadCodeInjection: true,
                    deadCodeInjectionThreshold: 0.4,
                    debugProtection: false,
                    debugProtectionInterval: false,
                    disableConsoleOutput: true,
                    identifierNamesGenerator: 'mangled',
                    log: false,
                    renameGlobals: false,
                    rotateStringArray: true,
                    selfDefending: true,
                    shuffleStringArray: true,
                    splitStrings: true,
                    splitStringsChunkLength: 2,
                    stringArray: true,
                    stringArrayEncoding: 'base64',
                    stringArrayThreshold: 0.75,
                    transformObjectKeys: true,
                    unicodeEscapeSequence: false
                });
   res.end(obfuscationResult.getObfuscatedCode());
}
next();
}

**Comment by sanex3339** [comment]
Hmm. Looks like a memory leak in this option
`identifierNamesGenerator: 'mangled'`

**Comment by sanex3339** [comment]
PR
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/614

Can you try this branch?

**Comment by sanex3339** [comment]
Tested it with 200mb memory limit. Now it works fine!

**Comment by sanex3339** [comment]
Released as `0.28.3`. 
Let me know it it fixed your problem.

**Comment by ert55** [comment]
Looks like it solved the problem. Thanks :)
