### ISSUE TITLE
Question: What's the point of hexadecimal obfuscation?

### ISSUE THREAD

**Issue by madprops** [javascript-obfuscator/javascript-obfuscator#62]
I'm using mangle=true. It seems function and variable names are turned into hexadecimal, instead of using random names. Isn't decoding that as easily as translating the hex? I'm genuinely asking, I don't really know how the obfuscator works, just curious and concerned about the code I'm protecting. Thanks.

**Comment by sanex3339** [comment]
At first, `mangle` option available only in `0.10.0-x` version. Looks like you using `0.9.4` version.

Obfuscation - complex transfrormation of input source code. Just see examples in `README.md`

You can't restore original names of variables from `hex` representation.
`mangle` option - additionally transformation of `hex` variables to one character names like in `UglifyJs`

**Comment by madprops** [comment]
Thanks. I'm confused about how a public function in my js file (exported) is callable by its original name in an html file. It's called init()  , in the file it is obfuscated but I can just call mymodule.init() in the html file? Is this on purpose for public functions/variables?

**Comment by sanex3339** [comment]
Please, play with obfuscation here
https://javascriptobfuscator.herokuapp.com/

Names of globalr functions and variables aren't obfuscated.

`mymodule.init()` - MemberExpression.
`init` name will added to `String Array` in normal or encoded (depends on options) view.
Pseudo code:
```
var _0xabc = ['init'];
var _0xabc123 = function (index) {  
    return _0xabc[index];
}
mymodule[_0xabc123(0)]();
```

**Comment by sanex3339** [comment]
If i answered your questions, please close issue then.
