### ISSUE TITLE
Typo on https://obfuscator.io/ page

### ISSUE THREAD

**Issue by K0nfy** [javascript-obfuscator/javascript-obfuscator#622]
![Screenshot](https://user-images.githubusercontent.com/27099419/83796826-4d509800-a6aa-11ea-8328-9c8fa17a9078.png)
 
## Expected Behavior
"Star" link should lead to this github repository

## Current Behavior
404

**Comment by sanex3339** [comment]
Oh, thank you!

**Comment by sanex3339** [comment]
Fixed
