### ISSUE TITLE
Arrow function in class throws unecpected token

### ISSUE THREAD

**Issue by paaulmv** [javascript-obfuscator/javascript-obfuscator#627]
If you're using an arrow function in a class, it throws an Unexpected token error

## Current Behavior
Throws "Unexpected token" error

## Minimal working example that will help to reproduce issue
```javascript
class test {  
  	test = () => console.log('test')
}
```

**Comment by sanex3339** [comment]
https://github.com/tc39/proposal-class-fields

Hi. Currently this proposal in stage 3, so `acorn` doesn't support it by default.
And `escodegen` too.

So, wait until this proposal reaches stage 4 and `acorn` and `escodegen` implementation.

**Comment by Nashorn** [comment]
Already supported in major browsers, any update?

**Comment by sanex3339** [comment]
As said in the comments above, we have to wait until this proposal reaches stage 4 and `acorn` and `escodegen` implementation.
