### ISSUE TITLE
ERROR : Unexpected token

### ISSUE THREAD

**Issue by Shine753** [javascript-obfuscator/javascript-obfuscator#628]
The obfuscation does not work with :

var aa = "doesn't work"; // doesn't work also with just var aa;
alert(aa); // doesn't work also if this is removed
function(){
            var variable1 = '5' - 3;
            var variable2 = '5' + 3;
            var variable3 = '5' + - '2';
            var variable4 = ['10','10','10','10','10'].map(parseInt);
            var variable5 = 'foo ' + 1 + 1;
            console.log(variable1);
            console.log(variable2);
            console.log(variable3);
            console.log(variable4);
            console.log(variable5);
        }

using any or no option.

Tried personally and on https://obfuscator.io

Errors like :
Error: ERROR at line 3: Unexpected token (3:8) // on https://obfuscator.io
Error: ERROR at line 1: Unexpected token (1:1) // on my tests

**Comment by sanex3339** [comment]
Hi. Your code is invalid because the function doesn't have a name

**Comment by Shine753** [comment]
Well... ok... that's fine to me.
But this is just the README.md function with 2 more lines...
And the obfuscation works fine without the 2 first lines.

**Comment by sanex3339** [comment]
No. In the readme there is the following code:
```
(function(){
            var variable1 = '5' - 3;
            var variable2 = '5' + 3;
            var variable3 = '5' + - '2';
            var variable4 = ['10','10','10','10','10'].map(parseInt);
            var variable5 = 'foo ' + 1 + 1;
            console.log(variable1);
            console.log(variable2);
            console.log(variable3);
            console.log(variable4);
            console.log(variable5);
        })();
```
If uses IIFE function: https://developer.mozilla.org/en-US/docs/Glossary/IIFE
Your code has invalid function declaration without a name and this function is not the IIFE function.

**Comment by Shine753** [comment]
Ok

**Comment by Shine753** [comment]
Same error, so I post here, with working code :

String.prototype.isin = function() {
    for(var i=0; i<arguments.length; i++) {
       if(arguments[i] == this) return true;
	}
    return false;
}

String.prototype.includesany = function() {
    for(var i=0; i<arguments.length; i++) {
       if(this.includes(arguments[i])) return true;
	}
    return false;
}

**Comment by sanex3339** [comment]
This code obfuscated finefor me, without errors

**Comment by Shine753** [comment]
I guess I made something wrong.
I wrote this using available examples around the net for a local usage, that works fine for just one of these 2 methods, but crashes when both are present.
Can you tell me what I did wrong ?

<HTML>
<HEAD>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<script src="javascript-obfuscator-master/dist/index.browser.js"></script>
</HEAD>
<BODY>

<script>
function doit() {
	var data = document.getElementById('Source').value;
	
	var obfuscationResult = JavaScriptObfuscator.obfuscate('('+data+')();',
		{
			compact: true,
			controlFlowFlattening: true,
			controlFlowFlatteningThreshold: 1,
			deadCodeInjection: true,
			deadCodeInjectionThreshold: 1,
			debugProtection: true,
			debugProtectionInterval: true,
			disableConsoleOutput: true,
			log: false,
			mangle: false,
			renameGlobals: true,
			rotateStringArray: true,
			selfDefending: true,
			stringArray: true,
			stringArrayEncoding: 'rc4',
			stringArrayThreshold: 1,
			unicodeEscapeSequence: false
		}
	);
		
	document.getElementById('Dest').value = obfuscationResult.getObfuscatedCode();
}
</SCRIPT>

<textarea id="Source" cols="50" rows="20"></textarea>
<textarea id="Dest" cols="50" rows="20"></textarea>

<input type="button" value="obfuscate" onclick="doit();" />

</BODY>
</HTML>

**Comment by Shine753** [comment]
Oh I thing I got it... I don't have to write '('+data+')();' but just data.
I was confused by the readme.md example that I'm not used with.
Is that it ?

**Comment by sanex3339** [comment]
I don't know what content is exactly in your `data` variable, but looks like it must be like that:
```
JavaScriptObfuscator.obfuscate(data, options);
```
