### ISSUE TITLE
Reserved names and literals not working as expected

### ISSUE THREAD

**Issue by ErinPo** [javascript-obfuscator/javascript-obfuscator#630]
I want to obfuscate code which includes javascript objects with key/value pairs. I would like to exclude some of those key/value pairs from obfuscation as they need to be replaced for customization after obfuscation. However, I found that no matter what I set up as reserved name or literal - the key, the value or the entire object, the whole object always get obfuscated resulting in duplication of all key/value pairs, each of which previously occurred only once.

What am I missing?

**Comment by sanex3339** [comment]
Show me your options.

For me it works fine:

```
const foo = {
	ignoredKey: 'ignoredValue',
  	bar: 'baz'
};
```

options: 
```
reservedNames: 'ignored',
renameProperties,
stringArray: true,
stringArrayThreshold: 1
```

Result:
```
const a = ['baz'];
const b = function (c, d) {
    c = c - 0x0;
    let e = a[c];
    return e;
};
const d = {
    'ignoredKey': 'ignoredValue',
    'c': b('0x0')
};
```

**Comment by ErinPo** [comment]
You're right, that is how it works. The duplications I was seeing came from the dead code injection option. I need to spend more time to learn who obfuscation works. Thank you for your help!

**Comment by sanex3339** [comment]
Can i close this issue?
