### ISSUE TITLE
Recommended way to exclude polyfills

### ISSUE THREAD

**Issue by ErinPo** [javascript-obfuscator/javascript-obfuscator#631]
What is the recommended way to exclude polyfills from obfuscation if I want all javascript to be in a single file? 

I don't see how it could be done using reserved names or literals... maybe there should be some comment that allows certain code portions to be excluded.

**Comment by sanex3339** [comment]
Hi. Check documentation:
https://github.com/javascript-obfuscator/javascript-obfuscator#conditional-comments
