### ISSUE TITLE
https://obfuscator.io/, the option 'Domain lock' can remember what to fill in?

### ISSUE THREAD

**Issue by df257** [javascript-obfuscator/javascript-obfuscator#632]
![image](https://user-images.githubusercontent.com/7835444/85012098-18a60b80-b195-11ea-9883-59a0ab51f2a4.png)

**Comment by df257** [comment]
when I'm refresh the page, this input content will lost

**Comment by sanex3339** [comment]
After you typed something in this field, press `+` button.
