### ISSUE TITLE
When I'm check 'Rename Properties' , the jscode is error

### ISSUE THREAD

**Issue by df257** [javascript-obfuscator/javascript-obfuscator#633]
![image](https://user-images.githubusercontent.com/7835444/85016080-9d942380-b19b-11ea-8dd1-9770289b04ee.png)
![image](https://user-images.githubusercontent.com/7835444/85016166-c2889680-b19b-11ea-8d72-57619576d0f0.png)

**Comment by df257** [comment]
'Domain lock' seem not work

**Comment by sanex3339** [comment]
Check this option description, please
