### ISSUE TITLE
About 'Domain lock' bug, when I run js not use server, just open it in browser, it will not work

### ISSUE THREAD

**Issue by df257** [javascript-obfuscator/javascript-obfuscator#634]
![image](https://user-images.githubusercontent.com/7835444/85095880-4d61a380-b225-11ea-9589-aa510c76b686.png)

**Comment by sanex3339** [comment]
Sorry, i WILL close this issue because it has not any information about your obfuscator version, options and additional details. 
Please, create a new issue and add as many details as possible.
