### ISSUE TITLE
Optional configurable error message for domain lock

### ISSUE THREAD

**Issue by ErinPo** [javascript-obfuscator/javascript-obfuscator#635]
**Describe the solution you'd like**
Sometimes it is preferable to let users know they are doing something unauthorized rather than simulating a functional error.

**Comment by sanex3339** [comment]
I'm not sure that I want to do it right now.

**Comment by slig** [comment]
You can do that by yourself, for instance:

```
// javascript-obfuscator:disable
if (!document.domain !== 'www.example.com') alert('unauthorized domain, the script won't work.');
```

Or during your build process, add the line above directly to the top of your build.
