### ISSUE TITLE
Feature Request: Add support for RSA in encoding, RC4 is broken.

### ISSUE THREAD

**Issue by AhsanE** [javascript-obfuscator/javascript-obfuscator#64]

**Comment by sanex3339** [comment]
What you mean `broken`?

**Comment by sanex3339** [comment]
To be clear, rc4 encoding with random keys -way to make deobfuscation harder (impossible without automation tools on large code size). But keys still presented in obfuscated code and decoding function too.

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
Closed due inactivity and no information. Please create new issue with more details.
