### ISSUE TITLE
Domain lock improvements

### ISSUE THREAD

**Issue by ErinPo** [javascript-obfuscator/javascript-obfuscator#640]
It would be nice if subdomains could be configured to include the root of the domain without having to create two entries (.domain.com and domain.com).

**Comment by sanex3339** [comment]
Need proposal

**Comment by ErinPo** [comment]
I don't know how it can be done, but the way it works now is a bit unexpected. For example, setting a cookie to .domain.com makes it accessible from all subdomains and the root domain, but in obfuscator, it means only subdomains.

**Comment by sanex3339** [comment]
So, under root domain, you mean `domain.com`?

**Comment by sanex3339** [comment]
PR https://github.com/javascript-obfuscator/javascript-obfuscator/pull/682

**Comment by sanex3339** [comment]
@ErinPo ping. If this is what you want, i'll merge this PR

**Comment by ErinPo** [comment]
Sorry, yes, that's what I meant. Would be lovely!

**Comment by sanex3339** [comment]
Ok, i'll merge it

**Comment by sanex3339** [comment]
Merged. Expect a new release in 10 minutes.

**Comment by ErinPo** [comment]
Great, just to be sure:

`domainLock: ['domain.com']`

(without the leading dot) would still only allow usage on domain.com without subdomains, right?

**Comment by sanex3339** [comment]
Yes
