### ISSUE TITLE
obfuscator:disable/enable tags not removed from result

### ISSUE THREAD

**Issue by ErinPo** [javascript-obfuscator/javascript-obfuscator#641]
I noticed that when using tag comments likes /* javascript-obfuscator:disable */ that these remain in the output. They should be removed so as not to brand output with the name of a tool.

**Comment by sanex3339** [comment]
Agreed

**Comment by sanex3339** [comment]
Released as `1.2.0`

**Comment by sanex3339** [comment]
Released `1.2.2` with a performance regression fix
