### ISSUE TITLE
identifiersPrefix: allow a function that returns a string ?

### ISSUE THREAD

**Issue by DRocksCoding** [javascript-obfuscator/javascript-obfuscator#644]
when defining the options object, identifiersPrefix - would it be possible to use a function that returns a string?
For example:     
`identifiersPrefix: function () {return uuidv4();},`

I was trying to use uuidv4 to generate a random prefix but your exception handler throws an error which indicates only a string can be used there.

Let me know if you think that could be useful.
Thanks for the module, I already donated you rock.

**Comment by sanex3339** [comment]
It would be nice but it, not just a function, it is a class with few methods.

**Comment by DRocksCoding** [comment]
cool, thank you for your reply.

Right now I'm also trying another idea in the same direction but using dictionary.
Maybe it would be more appropriate in this way:
```JavaScript
    identifierNamesGenerator: 'dictionary',
    identifiersDictionary: [
        generateDictionaryWord('a'),
        generateDictionaryWord('b'),
        generateDictionaryWord('c'),
    ],
```
```JavaScript
function generateDictionaryWord(letter) {
    //letter param to ensure string never starts with a digit.
    const uniqueStr = `${letter}_${uuidv4()}`;
    return uniqueStr.replace(/\W+/g,''); //a_26f2aa0f666542209d4890f8f2af1fe8
}
```

Would that be a good idea?

**Comment by DRocksCoding** [comment]
Following in this discussion, more directly my last post...

Can you confirm that long and complex dictionary words are more likely to result in unique name generations? You stated that the words are used in a few variants of themselves so if my words are length of 50 compared to length of 3, would the longest words be more collision proof than the short ones?

If you say that this is the case then having a lot of long dictionary words would make it almost impossible to have naked conflicts right?

**Comment by sanex3339** [comment]
If we are talking about `identifierNamesGenerator: 'dictionary'` than - longer words = more variants of this words.

**Comment by DRocksCoding** [comment]
Ok thank you. Then I would be confident for myself that its ok to skip identifiersPrefix safely with a proper dictionary array of long words.
