### ISSUE TITLE
Convert numbers to the expressions

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/javascript-obfuscator#649]
> `1` -> `0x279+8794-0x24d2`
> Just need to think about the algorithm

I have idea, just made the snippet
https://gist.github.com/da411d/0e59f79dcf4603cdabf0024a10eeb6fe

_Originally posted by @da411d in https://github.com/javascript-obfuscator/javascript-obfuscator/issues/420#issuecomment-651408226_

**Comment by sanex3339** [comment]
Implementation
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/664

**Comment by sanex3339** [comment]
Released as `1.6.0`

**Comment by da411d** [comment]
You are awesome!

**Comment by da411d** [comment]
Also that's great that it correctly processes construction like `12345..toString(36)`  and adds brackets 👍

**Comment by da411d** [comment]
But it generates code like `0x1773 + 0xf9 * -0x1 + -0x14d6`, `+ -` looks a bit ugly, but it's not very important. 
I fixed it just replacing as a string, i don't know how it can be fixed.

**Comment by sanex3339** [comment]
> But it generates code like `0x1773 + 0xf9 * -0x1 + -0x14d6`, `+ -` looks a bit ugly, but it's not very important.
> I fixed it just replacing as a string, i don't know how it can be fixed.

Yeah. This is ugly and this is good)

**Comment by da411d** [comment]
It would be great to put some numbers to another place, like it does with functions and strings (like controllFlowFlattening option).

Current code:
```
var _0x5597d6 = (0x31 * -0x1df + -0x19c4 + 0xa5ac)['toString'](-0x1e17 * 0x1 + -0x471 + 0x8ab * 0x4);
console['log'](_0x5597d6);
```


```
var _0x31c141 = {
  'LSxmv': -0x1df,
  'NTxnm': -0x19c4,
  'Bijy': -0x4,
};
var _0x5597d6 = (0x31 * _0x31c141['LSxmv'] + _0x31c141['NTxnm'] + 0xa5ac)['toString'](-0x1e17 * 0x1 + -0x471 + 0x8ab * _0x31c141['Bijy']);
console['log'](_0x5597d6);
```

**Comment by sanex3339** [comment]
Yeah. In the future i'll try it.

**Comment by da411d** [comment]
I think that's simple, just need add one more replacer [here](https://github.com/javascript-obfuscator/javascript-obfuscator/blob/a0761f55fac9261d5263b48b14f8d8945006dae9/src/node-transformers/control-flow-transformers/FunctionControlFlowTransformer.ts#L37), right?

**Comment by da411d** [comment]
One more idea, make same feature for boolean expressions, `true` => `(![] || true) && (!"" || !0)`, with `controlFlowFlattening` it will be powerfull=)

**Comment by da411d** [comment]
Sorry for spamming 😅

**Comment by sanex3339** [comment]
Actually it's already here: 
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/a0761f55fac9261d5263b48b14f8d8945006dae9/src/node-transformers/control-flow-transformers/FunctionControlFlowTransformer.ts#L38

But this transformer runs **AFTER** control flow transformers.
Currently, I'm not sure what I have to do, but looks like I should move this transformation **before** control flow transformations. 

Right now this is `converting` transformer because it converts the number to expression, but right now all `converting` transformers are run after control flow transformers.
Maybe I'll move it to `controlFlow` transformers group (but keep under `numberToExpression` option).

**Comment by sanex3339** [comment]
Updated https://obfuscator.io/ with this option

**Comment by sanex3339** [comment]
Feel free to report any runtime bugs with this option
