### ISSUE TITLE
eval() breaks Chrome Extensions

### ISSUE THREAD

**Issue by HerrimanCoder** [javascript-obfuscator/javascript-obfuscator#65]
I just tried out the obfuscator online here:
https://javascriptobfuscator.herokuapp.com/

...which I believe is based on this TS obfuscator. But after obfuscating the js files in my Chrome Extension, my extension breaks hard because eval() is illegal in some contexts of Chrome Extensions. This is a show-stopper for me, so I was wondering if there's some way to instruct the obfuscator to not ever use eval() in the obfuscation. It would be especially nice if you could tell me which setting(s) to avoid at javascriptobfuscator.herokuapp.com so I can retry there first. And then, how would I do the same thing in the downloaded TS app? 

Thanks so much in advance, this seems like an awesome free tool.

**Comment by sanex3339** [comment]
Hi. `Eval` using in code of the custom nodes. You can try to disable `selfDefending`, `debugProtection`, and `donainLock`. But i will think how i can remove eval from code of this custom nodes.

**Comment by HerrimanCoder** [comment]
I disabled those 3 settings, but there are still eval() calls in there, breaking the extension. I would suggest an additional setting specific to eval, and when that is unchecked, no evals would ever be used in the obfuscated code. Thank you.

**Comment by sanex3339** [comment]
This is high priority for me now.

**Comment by sanex3339** [comment]
Oh, i was wrong. Right now you should set to `false` following options that using `Function(...)` in their code:
`disableConsoleOutput`
`domainLock`
`stringArrayEncoding`

**Comment by HerrimanCoder** [comment]
Thank you, sanex. With your latest instructions I disabled those few settings and was able to obfuscate all my code so that it doesn't break in the extension. BUT when I de-obfuscate the obfuscated code at http://jsnice.org/, it successfully re-constructs the code in a mostly-understandable fashion. Some things are still nicely opaque, but many things are now understandable. When I enable those other obfuscation settings, jsnice can't touch it, and things remain very obfuscated, but as it stands, it's too easy. Is there any way you can make the obfuscation more hard-core without resorting to eval()? And perhaps have a separate checkbox just for "use eval()" or etc? That would be super awesome.

**Comment by HerrimanCoder** [comment]
One other note: https://javascriptobfuscator.com/ (the paid tool) can do quite impressive obfuscation without using eval and thus without breaking chrome extensions. So I know this is possible. Thanks in advance for anything you can do. I love that yours is free.

**Comment by sanex3339** [comment]
If you will use `controlFlowFlattening` option alongside with new `deadCodeInjection` (this option available only in `0.10.0-beta.x` versions - transformations of code will very hardcode =))

Also new `0.10.0-beta.8` version with fix https://github.com/javascript-obfuscator/javascript-obfuscator/commit/2114064665c16e5db573f03ceffa96286f4854e3 will be available later today.

**Comment by HerrimanCoder** [comment]
Thanks! Here are the settings I used: http://www.zerogravpro.com/temp/obf_settings.png

**Comment by sanex3339** [comment]
`stringArray` option veruy important

**Comment by sanex3339** [comment]
In 10 mins i will publish new beta release

**Comment by sanex3339** [comment]
Please try new `javascript-obfuscator@0.10.0-beta.8`
`eval` and `Function(...)` are no more using in code of custom nodes.

But be aware. Version on https://javascriptobfuscator.herokuapp.com/ will be changed only with stable release (currently panned in next one-two weeks).

**Comment by HerrimanCoder** [comment]
String Array does make the obfuscation MUCH stronger...but it uses eval() and thus breaks my Chrome Extension. I am using the website version.

**Comment by sanex3339** [comment]
> String Array does make the obfuscation MUCH stronger...but it uses eval() and thus breaks my Chrome Extension. I am using the website version.

No. `eval` was used with `stringArrayEncoding`, you can disable it.

**Comment by HerrimanCoder** [comment]
I am trying it right now, thanks very much.

**Comment by sanex3339** [comment]
Nice! Ifhere no problem anymore, please, close the issue and be prepared for sable release of 0.10.0 in next two weeks.

**Comment by tomgallagher** [comment]
Hello

Great package!

Is there a date on the version on https://javascriptobfuscator.herokuapp.com/ without eval?

**Comment by sanex3339** [comment]
Version without eval already on https://javascriptobfuscator.herokuapp.com/
