### ISSUE TITLE
How to change js object values after obfuscation with string array encoding?

### ISSUE THREAD

**Issue by ErinPo** [javascript-obfuscator/javascript-obfuscator#650]
`var setting = { param1 : 'param1', param2: 'param2' }`

I can recognize the base64-encoded versions of 'param1' and 'param2' which I need to modify but inserting equally base64-encoded versions of the values I need breaks the script with the error:

>  Cannot read property 'replace' of undefined

I already have self-defending turned off as I read it is problematic when changes need to be made after obfuscation.

**Comment by sanex3339** [comment]
Why arr you trying to do this?

**Comment by ErinPo** [comment]
Because I don't know and doubt that I can install node on this server and all the other dependencies required by your script so I would prefer to handle obfuscation beforehand, just that some adaptations are needed.

**Comment by sanex3339** [comment]
You shouldn't change your code after obfuscation.
