### ISSUE TITLE
Are mangled identifier names possibly repeated when using disabling and enabling obfuscation

### ISSUE THREAD

**Issue by ErinPo** [javascript-obfuscator/javascript-obfuscator#651]
I got many errors in ESlint concerning variable redeclarations which are not present in the original source. Could it be that J-O does not keep track of which names were already used when the code is divided up into portions with and without obfuscation using /* javascript-obfuscator:disable/enable */ ?

When I switched to hexadecimal identifier naming, those errors disappeared, but it might just be that they are less likely to happen with hexadecimal naming. ..

**Comment by sanex3339** [comment]
The logic of mangled identifier names generator is trying to use same identifier names for the different block scopes. So yes, identifier names between sibling functions can be the same

**Comment by sanex3339** [comment]
Why are you trying to lint obfuscated code with eslint?

**Comment by ErinPo** [comment]
I linted to get ideas for why the script no longer works. It's not easy for me to debug scrambled code. Based on what you're saying, it is breaking from something other than enabling and disabling obfuscation.

**Comment by sanex3339** [comment]
Obfuscation may break your code, but it should not do it.
So right now I don't know why your code is not working after obfuscation. I need the example and more info
