### ISSUE TITLE
[Feature] Force obfuscate string list

### ISSUE THREAD

**Issue by da411d** [javascript-obfuscator/javascript-obfuscator#657]
Opposite feature to [reservedStrings](https://github.com/javascript-obfuscator/javascript-obfuscator#reservedstrings) - if string matches regex or string - it will be obfuscated even if by random it shouldn't.

Useful for hiding some important keys or tokens.

**Comment by da411d** [comment]
Also in string array present many strings with equal length. Likely there are keys for objects in helper objects for controlFlowFlattening.
<kbd>
![image](https://user-images.githubusercontent.com/12462454/86961033-2d106f00-c169-11ea-9728-3325ab38ae65.png)
</kbd>

My idea is to mask force-obfuscated-string by splitting it and masking between many short strings.

**Comment by sanex3339** [comment]
`splitStrings` option already exist

**Comment by da411d** [comment]
> `splitStrings` option already exist

Okay, here i agree with you.
I meant to add this feature to force-obfuscate-string, but now i understand that this is bad idea to mix them

**Comment by sanex3339** [comment]
`forceTranformStrings` option WILL have a priority over `reservedStrings` option. But right now it's a hard task to make a priority over `conditional comments`, because of the way how it works.

**Comment by sanex3339** [comment]
PR was merged

**Comment by sanex3339** [comment]
Will release it later today.

**Comment by sanex3339** [comment]
Released as 2.4.0
