### ISSUE TITLE
disableConsoleOutput not working

### ISSUE THREAD

**Issue by bikb** [javascript-obfuscator/javascript-obfuscator#67]
Hello,

I am using your tool for the first time today. Thank You very much for coding. 
When using this:
"C:\Users\Admin\AppData\Roaming\npm\javascript-obfuscator" in.js -o out.js --compact true --controlFlowFlattening false --deadCodeInjection false --debugProtection false --debugProtectionInterval false --disableConsoleOutput true --mangle true --rotateStringArray true --selfDefending true --stringArray true --stringArrayEncoding 'base64' --stringArrayThreshold 0.75 --unicodeEscapeSequence false --domainLock 'www.xyz.de' --seed 1
The console output is still activated. Why?

TIA
Best regards
bikb

**Comment by sanex3339** [comment]
Code that disables console output inserts not directly in the top of the obfuscated code, but in the one of the deepest function from first 10% functions during code execution.

So, if here about 100 functions in the code, code can be inserted in first 10 functions. If in will inserted in 10th function, it won't affect first nine functions.

Please try to use console log somewhere else in the your program.

**Comment by sanex3339** [comment]
So, for example

```
function foo () {

}

function bar () {
    function inner1 () {

    }

    function inner2 () {
        var inner3 = function () {

        };

        inner3();
    }

    inner2();
    inner1();
}

function baz () {

}

baz();
foo();
bar();
```

In the code abow, `disableConsoleOutput` code will appended to the `baz` function body.

**Comment by sanex3339** [comment]
Also you can see test fixtures here:
https://github.com/javascript-obfuscator/javascript-obfuscator/tree/master/test/unit-tests/node/node-appender/fixtures/append-node-to-optimal-block-scope

Fixtures with `-expected` postfix shows expexted behaviour.

**Comment by sanex3339** [comment]
Also look at this example
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/test/unit-tests/node/node-appender/fixtures/append-node-to-optimal-block-scope/variant-2-expected.js

This example shows how deep `disableConsoleOutput` code can be inserted in the input code.

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
So, i should disable this option by default to prevent misunderstanding.

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/commit/da7d71d855885194bb54721c5254fcefaa3ee4ca
