### ISSUE TITLE
Can someone post "index.browser.js" not compiled version?

### ISSUE THREAD

**Issue by HohohoCode** [javascript-obfuscator/javascript-obfuscator#675]
Can someone post "index.browser.js" not compiled version?
I'm trying to communnicate  with this JS file, but it's compiled... I can't see the code to change the options...
{
    compact: true,
    controlFlowFlattening: false,
    controlFlowFlatteningThreshold: 0.75,
    deadCodeInjection: false,
    deadCodeInjectionThreshold: 0.4,
    debugProtection: false,
    debugProtectionInterval: false,
    disableConsoleOutput: false,
    domainLock: [],
    identifierNamesGenerator: 'hexadecimal',
    identifiersDictionary: [],
    identifiersPrefix: '',
    inputFileName: '',
    log: false,
    numbersToExpressions: false,
    renameGlobals: false,
    renameProperties: false,
    reservedNames: [],
    reservedStrings: [],
    rotateStringArray: true,
    seed: 0,
    selfDefending: false,
    shuffleStringArray: true,
    simplify: true,
    sourceMap: false,
    sourceMapBaseUrl: '',
    sourceMapFileName: '',
    sourceMapMode: 'separate',
    splitStrings: false,
    splitStringsChunkLength: 10,
    stringArray: true,
    stringArrayEncoding: false,
    stringArrayThreshold: 0.75,
    target: 'browser',
    transformObjectKeys: false,
    unicodeEscapeSequence: false
}

**Comment by sanex3339** [comment]
Hi. All sources here:
https://github.com/javascript-obfuscator/javascript-obfuscator/tree/master/src

It's `.ts` files. There no source files with `.js` extension because of this project written in typescript.
So, you can clone these sources and edit them manually and then compile them.
