### ISSUE TITLE
Can we have an option of embedding either certificate or a set of encryption decryption keys?

### ISSUE THREAD

**Issue by gaurav-cointab** [javascript-obfuscator/javascript-obfuscator#678]
I am a fan of your library and I am using it to obfuscate our prod build before shipping them to the clients. We obfuscate using your library and then we package your obfuscated code using the "pkg" library into a build. If you have some other suggestion of packaging the obfuscated code into one build, then I would like to hear them. In any case this is not regarding the packaging issue that I want to discuss.

In our code we have to embed certain certificates, and certain encryption decryption string (this is a business requirement). So currently by using your string related settings I am able to obfuscate the strings perfectly, But I was wondering that could there be a mechanism of splitting above mentioned strings into multiple files, spread out in the code. or something.

Is something like this helpful in preventing reverse engineering those pieces of code? What are your thoughts.

We have to package your obfuscated code, and then ship the builds to the clients on-premise deployment. So what mechanism could be introduced to prevent the reverse engineering of such strings, certificates, etc.

Or could be have a mechanism of keeping a list of file hashes somewhere (either in a seperate file, or in the same file) and we can check the first time a file is required somewhere... and we allow that file to get required only if the file hash matches the saved file hashes. In this way we can prevent the tampering of the code.

**Comment by sanex3339** [comment]
Right now you can use the combination of options:
- `stringArrayEncoding: 'rc4'`
- `splitStrings: true`
- `splitStringsChunkLenght: 4`
- `shuffleStringArray: true`

**Comment by sanex3339** [comment]
Closed. Use a combination of the following options:
```
stringArrayEncoding: 'rc4'
splitStrings: true
splitStringsChunkLenght: 4
shuffleStringArray: true,
controlFlowFlattening: true
```
