### ISSUE TITLE
simple example not work

### ISSUE THREAD

**Issue by dacrhu** [javascript-obfuscator/javascript-obfuscator#68]
Hi, I tried this:

[dacr@berci temp]$ cat index.js 
console.log('hello');

[dacr@berci temp]$ node index.js 
hello

[dacr@berci temp]$ javascript-obfuscator index.js --output release.js
[dacr@berci temp]$ cat release.js 
var _0xe838=['\x77\x61\x72\x6e','\x64\x65\x62\x75\x67','\x69\x6e\x66\x6f','\x65\x72\x72\x6f\x72','\x65\x78\x63\x65\x70\x74\x69\x6f\x6e','\x74\x72\x61\x63\x65','\x6c\x6f\x67','\x68\x65\x6c\x6c\x6f','\x61\x70\x70\x6c\x79','\x72\x65\x74\x75\x72\x6e\x20\x28\x66\x75\x6e\x63\x74\x69\x6f\x6e\x28\x29\x20','\x63\x6f\x6e\x73\x6f\x6c\x65'];(function(_0x9b53c2,_0x2376bf){var _0x113bfc=function(_0x82c740){while(--_0x82c740){_0x9b53c2['\x70\x75\x73\x68'](_0x9b53c2['\x73\x68\x69\x66\x74']());}};_0x113bfc(++_0x2376bf);}(_0xe838,0x1ec));var _0x8e83=function(_0x2cbc10,_0xab0d0b){_0x2cbc10=_0x2cbc10-0x0;var _0x1302cf=_0xe838[_0x2cbc10];return _0x1302cf;};var _0x379db5=function(){var _0x2fbfaa=!![];return function(_0x121ab6,_0x5b06df){var _0x4485fb=_0x2fbfaa?function(){if(_0x5b06df){var _0x1f1f61=_0x5b06df[_0x8e83('0x0')](_0x121ab6,arguments);_0x5b06df=null;return _0x1f1f61;}}:function(){};_0x2fbfaa=![];return _0x4485fb;};}();var _0x1b8219=_0x379db5(this,function(){var _0x4ccb01=Function(_0x8e83('0x1')+'\x7b\x7d\x2e\x63\x6f\x6e\x73\x74\x72\x75\x63\x74\x6f\x72\x28\x22\x72\x65\x74\x75\x72\x6e\x20\x74\x68\x69\x73\x22\x29\x28\x20\x29'+'\x29\x3b');var _0x3daec1=function(){};var _0x149d9a=_0x4ccb01();if(!_0x149d9a[_0x8e83('0x2')]){_0x149d9a['\x63\x6f\x6e\x73\x6f\x6c\x65']=function(_0x2d223b){var _0x41a76f={};_0x41a76f['\x6c\x6f\x67']=_0x2d223b;_0x41a76f[_0x8e83('0x3')]=_0x2d223b;_0x41a76f[_0x8e83('0x4')]=_0x2d223b;_0x41a76f[_0x8e83('0x5')]=_0x2d223b;_0x41a76f[_0x8e83('0x6')]=_0x2d223b;_0x41a76f[_0x8e83('0x7')]=_0x2d223b;_0x41a76f[_0x8e83('0x8')]=_0x2d223b;return _0x41a76f;}(_0x3daec1);}else{_0x149d9a[_0x8e83('0x2')][_0x8e83('0x9')]=_0x3daec1;_0x149d9a[_0x8e83('0x2')][_0x8e83('0x3')]=_0x3daec1;_0x149d9a[_0x8e83('0x2')][_0x8e83('0x4')]=_0x3daec1;_0x149d9a[_0x8e83('0x2')][_0x8e83('0x5')]=_0x3daec1;_0x149d9a['\x63\x6f\x6e\x73\x6f\x6c\x65'][_0x8e83('0x6')]=_0x3daec1;_0x149d9a['\x63\x6f\x6e\x73\x6f\x6c\x65'][_0x8e83('0x7')]=_0x3daec1;_0x149d9a[_0x8e83('0x2')][_0x8e83('0x8')]=_0x3daec1;}});_0x1b8219();console['\x6c\x6f\x67'](_0x8e83('0xa'));

[dacr@berci temp]$ node release.js 
[dacr@berci temp]$ 

Result is blank :(

Thank you,
David

**Comment by sanex3339** [comment]
Hi. Please check this option.

Console output disabled by default.

https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/README.md#disableconsoleoutput

**Comment by dacrhu** [comment]
Thank you sanex!
