### ISSUE TITLE
Does obfuscating my code twice make it more protected ?

### ISSUE THREAD

**Issue by cameronbraid** [javascript-obfuscator/javascript-obfuscator#680]
It sure makes it harder to read !

```
// Paste your JavaScript code here
function hi() {
  console.log("Hello World!");
}
hi();
```

using default values at https://www.obfuscator.io/ turns into 

```
var _0x3e54=['log'];(function(_0x4772a7,_0x3e5496){var _0x4436ea=function(_0x1a120c){while(--_0x1a120c){_0x4772a7['push'](_0x4772a7['shift']());}};_0x4436ea(++_0x3e5496);}(_0x3e54,0x190));var _0x4436=function(_0x4772a7,_0x3e5496){_0x4772a7=_0x4772a7-0x0;var _0x4436ea=_0x3e54[_0x4772a7];return _0x4436ea;};function hi(){console[_0x4436('0x0')]('Hello\x20World!');}hi();
```

And then you run it through https://www.obfuscator.io/  again, but this time with `High obfuscation, low performance ` options from https://github.com/javascript-obfuscator/javascript-obfuscator 

ends up with 5626k .js and 2342k .js.gz

**Comment by sanex3339** [comment]
Yes, it does. But the performance and size costs are very huge

**Comment by da411d** [comment]
Yes, but if you obfuscate code with  `Self Defending` option, it will break the code. So be sure that you enable `Self Defending` only at last iteration of obfuscation.
