### ISSUE TITLE
Errors while running the code obfuscated with some specific options

### ISSUE THREAD

**Issue by TUHIN-DAS** [javascript-obfuscator/javascript-obfuscator#685]
I have an angular application which I build and get javascript files. Now I am applying obfuscation on one of the javascript files and running it with the following options :

            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 0.9,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 0.5,
            unicodeEscapeSequence: true 

## Expected Behavior
The application should run with obfuscated file.

## Current Behavior
The code when run is throwing the following error : 

main-es2015.d03d74f003314263cfea.js:1 Uncaught SyntaxError: Identifier 'aK' has already been declared

## Steps to Reproduce (for bugs)
1. Build any sample angular application with production mode enabled. 
2. Use the attached grunt file to obfuscate.
3. Host the dist folder of the angular build on a server.
4. Open the application on browser.
5. It will throw the error on console.

## Your Environment
* Obfuscator version used: 6.0.0
* Node version used: v12.13.1
* Grunt version used:0.4.5
* Angular version used:8.2.14

# Stack trace
main-es2015.d03d74f003314263cfea.js:1 Uncaught SyntaxError: Identifier 'aK' has already been declared

## Grunt Script
module.exports = function(grunt) {

    const DIR_PATH = "dist/tdi-web";
    let mainFiles = grunt.file.expand({filter: "isFile", cwd: DIR_PATH},
                                      ["main-es2015*.js"]);
    let files = {};
    for(let i = 0; i < mainFiles.length; i++) {
        let fileWithPath = DIR_PATH + "/" + mainFiles[i];
        files[fileWithPath] = [fileWithPath];
    }

    grunt.initConfig({
    obfuscator: {
        options: {
            
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 0.9,
            deadCodeInjection: true,
            deadCodeInjectionThreshold: 0.5,
            unicodeEscapeSequence: true
        },
        task1: {
            files
        }
    }
  })
  grunt.loadNpmTasks('grunt-contrib-obfuscator');
};

**Comment by sanex3339** [comment]
`'grunt-contrib-obfuscator'` has old `javascript-obfuscator` version as dependency.
https://github.com/javascript-obfuscator/grunt-contrib-obfuscator/blob/master/package.json#L31

Current `javascript-obfuscator` version is `1.8.0`

**Comment by sanex3339** [comment]
I created the issue https://github.com/javascript-obfuscator/grunt-contrib-obfuscator/issues/22

**Comment by sanex3339** [comment]
Try to update to `grunt-contrib-obfuscator` `7.0.0`
In the new version `javascript-obfuscator` described as `peerDependency`, so you have to set in your `package.json` file:
```
'javascript-obfuscator': '^1.8.0'
```

**Comment by gaurav-singh-dev** [comment]
Thanks Timofey for your help :)
