### ISSUE TITLE
deadCodeInjection and stringArray cause error "Cannot find module" in Electron

### ISSUE THREAD

**Issue by NullScope** [javascript-obfuscator/javascript-obfuscator#687]
## Expected Behavior
Electron should be able to find modules called by import with `deadCodeInjection` and `stringArray` set to `true`, for example, on my case it fails to import the `path` module.

## Current Behavior
Errors out with "Cannot find module 'X'" on execution if either `deadCodeInjection` or `stringArray` are set to `true`, no other option set to either `true` or `false` matters.

## Steps to Reproduce

1. `npx create-electron-app my-new-app --template=typescript-webpack`
2. `npm install webpack-obfuscator`
3. Insert the content shown below into `webpack.rules.js`
4. `npm start`
5. As soon as webpack finishes a window will popup with the same errors as shown in the stack trace (`Cannot find module electron`)
6. Set `deadCodeInjection` **AND** `stringArray` to `false`
7. `npm start`
8. As soon as webpack finishes, electron will start normally

## Your Environment

* Obfuscator version used: 1.8.1
* Node version used: LTS
* Electron built with Electron Forge's Typescript Webpack Template
Using webpack-obfuscator loader with the following rules (dump of the whole `webpack.rules.js` file)

```
const path = require('path');
const WebpackObfuscator = require('webpack-obfuscator');

module.exports = [
  // Add support for native node modules
  {
    test: /\.node$/,
    use: 'node-loader',
  },
  {
    test: /\.(m?js|node)$/,
    parser: { amd: false },
    use: {
      loader: '@marshallofsound/webpack-asset-relocator-loader',
      options: {
        outputAssetBase: 'native_modules',
      },
    },
  },
  {
    test: /\.tsx?$/,
    exclude: /(node_modules|\.webpack)/,
    use: {
      loader: 'ts-loader',
      options: {
        transpileOnly: true
      }
    }
  },
  {
    test: /\.(tsx?|jsx?)$/i,
    exclude: /(node_modules|\.webpack)/,
    include: path.resolve(__dirname, 'src'),
    enforce: 'post',
    use: [
      {
        loader: WebpackObfuscator.loader,
        options: {
          compact: true,
          controlFlowFlattening: false,
          controlFlowFlatteningThreshold: 0.75,
          deadCodeInjection: true,
          deadCodeInjectionThreshold: 1,
          debugProtection: true,
          debugProtectionInterval: true,
          disableConsoleOutput: true,
          domainLock: [],
          identifierNamesGenerator: 'hexadecimal',
          identifiersDictionary: [],
          identifiersPrefix: '',
          inputFileName: '',
          log: false,
          numbersToExpressions: true,
          renameGlobals: false,
          renameProperties: false,
          reservedNames: [],
          reservedStrings: [],
          rotateStringArray: true,
          seed: new Date().getTime(),
          selfDefending: false,
          shuffleStringArray: true,
          simplify: true,
          sourceMap: false,
          sourceMapBaseUrl: '',
          sourceMapFileName: '',
          sourceMapMode: 'separate',
          splitStrings: true,
          splitStringsChunkLength: 10,
          stringArray: true,
          stringArrayEncoding: 'rc4',
          stringArrayThreshold: 1,
          target: 'node',
          transformObjectKeys: true,
          unicodeEscapeSequence: true,
        },
      },
    ],
  }
];
```

# Stack trace
![image](https://user-images.githubusercontent.com/4614486/88716072-66a81a80-d116-11ea-904f-413d8f6a49a2.png)

## Minimal working example that will help to reproduce issue
An example repo can be found [here](https://github.com/NullScope/javascript-obfuscator-electron-bug)

**Comment by sanex3339** [comment]
Related to new loader inside `webpack-obfuscator`. Found a bug.

**Comment by sanex3339** [comment]
Try `webpack-obfuscator@1.8.3`

**Comment by NullScope** [comment]
@sanex3339 It's working perfectly fine in both the example and my actual project, thank you!

**Comment by sanex3339** [comment]
Nice!
