### ISSUE TITLE
SyntaxError: Unexpected token: name (ChargingStationClient)

### ISSUE THREAD

**Issue by LucasBrazi06** [javascript-obfuscator/javascript-obfuscator#69]
Hi,

I just built a project in order to reproduce this error.

Once unpacked, simply do: 
- npm install
- grunt build:prod

Cheers,
Serge.

**Comment by LucasBrazi06** [comment]
[project_to_reproduce.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/1162764/project_to_reproduce.zip)

**Comment by sanex3339** [comment]
Hi again!. I will look into this.

**Comment by sanex3339** [comment]
This grunt task doesn't run JavaScript obfuscator.

It runs only uglification task.

```
grunt.registerTask("build:prod", ["clean", "uglify"]);
```

**Comment by LucasBrazi06** [comment]
Thanks!

Then in other words, I have to open an issue to UglifyJS :-(

**Comment by LucasBrazi06** [comment]
Even with creating an obfuscator task and replacing uglify I get the same error:
```
    obfuscator: {
        files: ["src/**/*.js"],
	    options: {
		    compact: true,
		    controlFlowFlattening: false,
		    controlFlowFlatteningThreshold: 0.75,
		    deadCodeInjection: false,
		    deadCodeInjectionThreshold: 0.4,
		    debugProtection: false,
		    debugProtectionInterval: false,
		    disableConsoleOutput: true,
		    mangle: false,
		    reservedNames: [],
		    rotateStringArray: true,
		    seed: 0,
		    selfDefending: false,
		    sourceMap: false,
		    sourceMapBaseUrl: '',
		    sourceMapFileName: '',
		    sourceMapMode: 'separate',
		    stringArray: true,
		    stringArrayEncoding: false,
		    stringArrayThreshold: 0.75,
		    unicodeEscapeSequence: false		    }
		},

```

**Comment by LucasBrazi06** [comment]
I updated the grunt file and ran the obfuscator's task:

[GruntFile.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/1163872/GruntFile.zip)

It worked and produced an 'output.js' in the dist directory but when I want to start it with node it outputs the following error:

```
SyntaxError: Identifier 'ChargingStationClient' has already been declared
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

```
What did I do wrong again :-( ?

Thanks in advance for your help!

**Comment by sanex3339** [comment]
Hi. Looks like problem in `grunt-contrib-obfuscator`. This plugin just obfuscate all files and then concatenate it into single file. 

This is wrong behaviour, because it doesn't wrap modules in wrapper functions like Webpack, so after concatenation class and variable declaration with same name are conflicted because they in the same scope.

Please create this issue here:
https://github.com/javascript-obfuscator/grunt-contrib-obfuscator

**Comment by LucasBrazi06** [comment]
Thanks for your support !

Do you know a grunt/gulp plugin that would do the trick with your javascript-obfuscator and encrypt my nodejs project correctly ?

I'm running out of patience :-(

**Comment by sanex3339** [comment]
You can use `webpack` (standalone or as `gulp` plugin) with https://github.com/javascript-obfuscator/webpack-obfuscator

`webpack` will bundle all your JS code into single file, and then `webpack-obfuscator` will properly obfuscate this bundle.

**Comment by LucasBrazi06** [comment]
Ok, I'll try

**Comment by slig** [comment]
The `grunt-contrib-obfuscator` mimics the behaviour of the grunt uglify task (i.e: receives a bunch of file names and outputs one file with the result). Maybe you can use a babel grunt plugin that will bundle the files into one and then use the obfuscator plugin on that file, but I don't recommend doing that. The best and modern way to do is to use webpack as @sanex3339 recommended.
