### ISSUE TITLE
Detection PhantomJS and Chrome Headless

### ISSUE THREAD

**Issue by wufeifei** [javascript-obfuscator/javascript-obfuscator#70]

**Comment by sanex3339** [comment]
Please, provide more info or issue will closed.

**Comment by wufeifei** [comment]
It is recommended to add the PhantomJS protection option to the Chrome Headless protection option.

PhantomJS and Chrome Headless are often used to simulate requests, and protection options should be provided so that confusing javascript code can not run in these simulators.

--phantomProtection <boolean>
--chromeHeadlessProtection <boolean>

## Detection Implementation Method Reference
[Detecting PhantomJS Based Visitors](http://engineering.shapesecurity.com/2015/01/detecting-phantomjs-based-visitors.html)
[Can a website detect when you are using selenium with chromedriver?](http://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver)
[Is there a way to detect that I'm in a Selenium Webdriver page from Javascript？](http://stackoverflow.com/questions/3614472/is-there-a-way-to-detect-that-im-in-a-selenium-webdriver-page-from-javascript)
[Reliably detecting PhantomJS-based spam bots](http://stackoverflow.com/questions/20862728/reliably-detecting-phantomjs-based-spam-bots)
[Method and system for detection of headless browser bots](http://www.freepatentsonline.com/y2016/0359904.html)
[Headless browsers in web forum spam](http://vamsoft.com/downloads/articles/vamsoft-headless-browsers-in-forum-spam.pdf)

**Comment by sanex3339** [comment]
Interesting. I'll think about it.

**Comment by sanex3339** [comment]
Closed. Right now i think we don't need so specific feature.
