### ISSUE TITLE
global.console.log.bind is not a function with disableConsoleOutput 

### ISSUE THREAD

**Issue by NullScope** [javascript-obfuscator/javascript-obfuscator#702]
Using xstate and javascript obfuscator on an electron app causes error `global.console.log.bind is not a function` with the option `disableConsoleOutput` even by providing an empty function logger option of the interpreter of xstate

## Expected Behavior
App should run as expected with no errors

## Current Behavior
App crashes with  `global.console.log.bind is not a function` error 

## Steps to Reproduce

1. npx create-electron-app my-new-app --template=typescript-webpack
2. npm install webpack-obfuscator xstate https://github.com/javascript-obfuscator/javascript-obfuscator.git
3. set a webpack rule for webpack-obfuscator with the loader on `webpack.rules.js` with `disableConsoleOutput` turned on
4. add the quick start example of xstate from [here](https://xstate.js.org/docs/) to `index.ts` 
5. npm start

## Your Environment

* Obfuscator version used: master branch
* Node version used: LTS

**Comment by sanex3339** [comment]
PR with the fix:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/705

**Comment by NullScope** [comment]
Nice, thank you, it is working!

**Comment by sanex3339** [comment]
Released as `1.10.0`
