### ISSUE TITLE
problem with eval function

### ISSUE THREAD

**Issue by huynv86** [javascript-obfuscator/javascript-obfuscator#703]
input:
```
function resolveAfter2Seconds() {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve('resolved');
    }, 2000);
  });
}

async function asyncCall() {
  console.log('calling');
  const result = await eval('resolveAfter2Seconds')();
  console.log(result);
  // expected output: "resolved"
}

asyncCall();
```

output:
`const _0xd761=['log','resolved'];(function(_0x1cf9e9,_0xd76171){const _0x4c969b=function(_0x26f174){while(--_0x26f174){_0x1cf9e9['push'](_0x1cf9e9['shift']());}};_0x4c969b(++_0xd76171);}(_0xd761,0xdd));const _0x4c96=function(_0x1cf9e9,_0xd76171){_0x1cf9e9=_0x1cf9e9-0x0;let _0x4c969b=_0xd761[_0x1cf9e9];return _0x4c969b;};function resolveAfter2Seconds(){return new Promise(_0x302403=>{setTimeout(()=>{_0x302403(_0x4c96('0x0'));},0x7d0);});}async function asyncCall(){console[_0x4c96('0x1')]('calling');const _0x3f7fdb=await eval('resolveAfter2Seconds;')();console['log'](_0x3f7fdb);}asyncCall();`

it works well
![image](https://user-images.githubusercontent.com/747614/90039875-6fd9df80-dcf1-11ea-8dab-b9fe28d884b5.png)
but doesn't work in on https://repl.it/languages/javascript
![image](https://user-images.githubusercontent.com/747614/90040041-a6175f00-dcf1-11ea-92f1-f9de1542add1.png)

please give me an advise. thank you so muck

**Comment by sanex3339** [comment]
It doesn't work without obfuscation too on this REPL:
![image](https://user-images.githubusercontent.com/9210534/90045339-912dd200-dcd7-11ea-85f7-1a65bbdd4c87.png)
