### ISSUE TITLE
[Bug] DeadCodeInjection puts unobfuscated code

### ISSUE THREAD

**Issue by da411d** [javascript-obfuscator/javascript-obfuscator#708]
I think it is too obviously if all code is obfuscated but some part don't.

![image](https://user-images.githubusercontent.com/12462454/90267807-bac53580-de5e-11ea-95db-1d2a0c2fd302.png)

I think this bug is because obfuscator doesn't obfuscate variables and function that weren't declared in current scope. DeadCodeInjector just steals a part of code, but declaration of variable is in outer scope.

So my solution is to run deadCodeInjection after renaming variables.

**Comment by sanex3339** [comment]
Yes, i know about this and will try to fix it in the future. This is because some identifiers HAS NOT declarations and these identifiers keep without obfuscation.

**Comment by sanex3339** [comment]
Issue for `export * as` exports
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/710

**Comment by sanex3339** [comment]
So. I'll close this issue. Tomorrow i'll release a new version with literals fix

**Comment by da411d** [comment]
How do you think about just taking random variables from upper scope?
That will be pretty messy😏

**Comment by sanex3339** [comment]
No. I have added additional transformer for dead code injection that renames ALL `through` identifiers (identifiers without declaration. It will rename some global identifiers too like `console` and others, but it should affect runtime, because dead code isn't evaluated during runtime.

**Comment by sanex3339** [comment]
PR: https://github.com/javascript-obfuscator/javascript-obfuscator/pull/715
