### ISSUE TITLE
controlFlowFlattening seems to ignore continue in while or for loop

### ISSUE THREAD

**Issue by jpodpro** [javascript-obfuscator/javascript-obfuscator#71]
i've got a while loop with a condition that calls continue. when controlFlowFlattening is enabled (threshold is at 0.75) the condition is reached but continue does not appear to be called. the lines of code after are called instead of the loop restarting. I have also discovered this happening in a for loop elsewhere in my code.

    while (link_it.next())
    {
          var pkt = link_it.value.getPacketFrom();
          if (!pkt)
          {
                pkt = link_it.value.getPacketTo();
          }
          if (!pkt)
          {
                console.log('there is no packet');
                continue;
          }

          console.log('packet is', pkt);
          var src = pkt.src;
          var dst = pkt.dst;
    }

the console shows:
> there is no packet
> packet is null

here are my obfuscation options:

        --compact true
        --controlFlowFlattening true
        --controlFlowFlatteningThreshold 0.75
        --deadCodeInjection true
        --deadCodeInjectionThreshold 0.4
        --debugProtection false
        --debugProtectionInterval false
        --disableConsoleOutput false
        --mangle false
        --rotateStringArray true
        --selfDefending true
        --stringArray true
        --stringArrayEncoding 'base64'
        --stringArrayThreshold 0.75
        --unicodeEscapeSequence false

**Comment by sanex3339** [comment]
Thank you for bug report. I will see into this tomorrow.

**Comment by jpodpro** [comment]
as expected, with a lower threshold sometimes it happens and sometimes not. when threshold is set to 1 it always happens.

**Comment by sanex3339** [comment]
I know why this happens. When obfuscator using one of type of control flow flattening - he skipped all statements with `continue` or `break`. And i forgot to add `WhileStatement` node.

**Comment by sanex3339** [comment]
Previous comment was wrong, problem was in other place, but looks like i fixed it.
Expect new beta version tomorrow, and if in this version won't contain bugs - i release stable version.

**Comment by sanex3339** [comment]
Hi. Check new beta `javascript-obfuscator@0.10.0-beta.12`.

I'll release stable version later today.

**Comment by jpodpro** [comment]
thanks!

**Comment by sanex3339** [comment]
0.10.0 is out!
