### ISSUE TITLE
Remark about 'Debug Protection' option

### ISSUE THREAD

**Issue by Feavy** [javascript-obfuscator/javascript-obfuscator#713]
Hello,

On your website it is written that Debug Protection '_makes it almost impossible to use the Console tab of the Developer Tools (both on Google Chrome and Mozilla Firefox)._' but there is a very simple way to bypass this protection both on Google Chrome and Firefox. Just open the dev tools and check this option, then all breakpoints will be ignored:

![image](https://user-images.githubusercontent.com/34109688/90335628-82486780-dfd6-11ea-8435-518fe72b8aaa.png)

Nevertheless I think this option can still prevent users from setting their own breakpoints to debug the code, maybe it would be better to precise that on the website.

**Comment by sanex3339** [comment]
Good point

**Comment by sanex3339** [comment]
Will update the site in few minutes and `README.md` in a next release
