### ISSUE TITLE
obfuscator breaks code string.split(" ") not working.

### ISSUE THREAD

**Issue by tamis-laan** [javascript-obfuscator/javascript-obfuscator#722]
I'm receiving a JWT token I need to verify, which I split to get the token and remove the word bearer:
```javascript
    const bearerHeader = req.headers['authorization'];
    const bearer = bearerHeader.split(" ")
```
With obfuscation on I get:
```javascript
[
  'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTgyNjU5NjksImlhdCI6MTU5ODI2NTM2OX0.gYp5wThUw8E7F-I0yhOvMuCwWkCNd8v1XomsWKnm2ss'
]
```
With obfuscation off I get:
```javascript
[
  'Bearer',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTgyNjU5NjksImlhdCI6MTU5ODI2NTM2OX0.gYp5wThUw8E7F-I0yhOvMuCwWkCNd8v1XomsWKnm2ss'
]
```
Looks like white spaces are replaced with some other character that breaks the `split(" ")` code. I also noticed a bunch of \x20 in my console output instead of spaces. What gives? How can I fix this?

**Comment by sanex3339** [comment]
Hi. Yes, obfuscator encodes some characters (including spaces) with unicode escape sequences. But it shouldn't break the code.

For example:
```
console.log('a b'.split('\x20')); // ['a', 'b']
console.log('a\x20b'.split('\x20')); // ['a', 'b']
console.log('a\x20b'.split(' ')); // ['a', 'b']
```

**Comment by sanex3339** [comment]
May you create a simple standalone example that will produce the wrong array with 'split' here:
https://obfuscator.io/

**Comment by tamis-laan** [comment]
Well it doesn't break my front end, but I'm using it also for my backend (nodejs). I have found a work around by using the option `preserveWhiteSpace:true`. This allows for the code to run correctly. The code example above is from my backend.

**Comment by sanex3339** [comment]
`preserveWhiteSpace` - where did you get this option?

**Comment by tamis-laan** [comment]
Oef can't trace back where I found it. It was on a github issue page related to vue.js which was not working. Someone proposed the option as a fix.

**Comment by sanex3339** [comment]
Obfuscator does not have `preserveWhiteSpace` option

**Comment by tamis-laan** [comment]
That's strange! I basicaly changed the webpack command from:
```javascript
const obfuscator = require('webpack-obfuscator');
new obfuscator({rotateStringArray: true},[])
```
to
```javascript
const obfuscator = require('webpack-obfuscator');
new obfuscator({rotateStringArray: true,preserveWhitespace: true})
```
And now things work correctly

**Comment by sanex3339** [comment]
What `webpack-obfuscator` version are you using?

**Comment by sanex3339** [comment]
Obfuscator never supports `preserveWhitespace` option. So please check that it produces obfuscated code with `preserveWhitespace` option.

**Comment by tamis-laan** [comment]
I used version: 1.11.0 and it does produce obfuscated code using the preserveWhitespace option. Not sure whats going on, maybe it's because I changed:
```javascript
new obfuscator({rotateStringArray: true},[])
```
to 
```javascript
new obfuscator({rotateStringArray: true})
```

**Comment by sanex3339** [comment]
May you create a small standalone repo with this bug and when this option helps. I want  to investigate this bug and how this unexisting option affects it

**Comment by sanex3339** [comment]
Any news?

**Comment by tamis-laan** [comment]
I can't send over the code and replicating the bug will take some time. Time and don't have atm.

**Comment by sanex3339** [comment]
Any news?

**Comment by sanex3339** [comment]
Closed. Feel free to reopen this issue if the problem happens again

**Comment by tamis-laan** [comment]
I will, sorry I was unable to replicate the problem for you.
