### ISSUE TITLE
Command line argument improvements: --preset preset_name

### ISSUE THREAD

**Issue by isohelio** [javascript-obfuscator/javascript-obfuscator#723]
Could you add a new command line argument --preset low|medium|high that implements the option sets described in the documentation?

Apologies if I have missed it.

**Comment by sanex3339** [comment]
It will be easy to implement

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/725

**Comment by sanex3339** [comment]
Released as `1.12.0`. `optionsPreset` option. With CLI `--options-preset`. Available values here:
https://github.com/javascript-obfuscator/javascript-obfuscator#optionspreset

**Comment by sanex3339** [comment]
Will update http://obfuscator.io/ later today.

**Comment by isohelio** [comment]
Thanks, very useful.
