### ISSUE TITLE
[BUG] Webpack String Array Encoding Didn't Support a Few Types

### ISSUE THREAD

**Issue by BlackYuzia** [javascript-obfuscator/javascript-obfuscator#732]
I'm too lazy for all so I just explain all in a few words. SRY :3 

If I try setup `stringArrayEncoding: ['rc4', "none", "base64"]` in webpack, 
I get error what `stringArrayEncoding` would be string => `"rc4"` OR `"none"` OR `"base64"`

I read docs about `javascript-obfuscator` and `stringArrayEncoding` allow array with encoding types. This allow encode strings with more like one type.

Ikd, but maybe webpack didn't support this?

**Comment by BlackYuzia** [comment]
uh, wait.
Repo with webpack is different? :D 
I ... broke.

**Comment by sanex3339** [comment]
Yes. The readme in the main repo is already describes 2.0.0 version that will be released soon, and this version has a breaking change with this option: now this option accepts array of available encodings.

This repo is for webpack plugin and will be updated to the 2.0.0 version  shortly after obfuscator 2.0.0 release.
