### ISSUE TITLE
Performance problem after obfuscation

### ISSUE THREAD

**Issue by isohelio** [javascript-obfuscator/javascript-obfuscator#734]
Hi, I'm working on a method that generates 3d surfaces by marching cubes. 

The underlying data is generated by various 3d distance measurements which are accumulated into a javascript array.

Calculation times in firefox on i7 are shown below for various levels of obfuscation (and some use of :enable :disable comments in code)

|Method|Time (s)|
|-------|------|
|Unobfuscated|0.66
|Default|7.75|
|High| 7.80|
|Enable/Disable|4.0|

So I'm seeing a > 10x decrease in performance which I can't really live with.

Inspection of generated code shows that code in the critical sections like this

`    grid[pos] = d;`

becomes something like

`    this[a15_0x16af('0x0')][_0x941b7f] =  _0x5d67a9;`

I could not see any options that would simplify the obfuscation of the grid array lookup. 

Is there any way to change the obfuscation settings that would help improve performance here?

Thanks

**Comment by sanex3339** [comment]
Hi. Use conditional comments to exclude parts of your code from obfuscation
https://github.com/javascript-obfuscator/javascript-obfuscator#conditional-comments

**Comment by sanex3339** [comment]
Did it help?

**Comment by isohelio** [comment]
I used conditional comments in some places and see some improvements but still leaves it nearly 10x slower, and its not practical to catch all the places I need.

I would like obfuscation to provide the software as part of a software evaluation without fully exposing the code.
I was hoping for a simpler but obviously less effective method, such as just variable mangling without the function and dictionary lookup steps.

I will check the reservedStrings suggestion.

Thanks

**Comment by sanex3339** [comment]
Disable all options like: `stringArray`

**Comment by isohelio** [comment]
OK, I added a couple of variables to the reservedNames list (e.g. `gr` in the example above) and got most of the performance back.

Unobfuscated 0.66s now 1.1s, which is still usable.

Thanks for your help and great software!

**Comment by sanex3339** [comment]
Nice!
