### ISSUE TITLE
It doesn't uglify the function names.

### ISSUE THREAD

**Issue by msg768** [javascript-obfuscator/javascript-obfuscator#74]
I tried the default example and the function hi(); remains hi();
It doesn't uglify it. Is there anything I need to do or is it a bug?

**Comment by sanex3339** [comment]
Hi. Obfuscator skipped all function and variable names in global scope.

**Comment by sanex3339** [comment]
Because they automatically added to global object (window or

**Comment by msg768** [comment]
Thanks for the quick reply. I kind of need global variables and function so I can't do that. I wonder why you skip global variables and/or functions?

**Comment by sanex3339** [comment]
Because they can be accessed anywhere else in your JS code in other `.js`. files.

For example you declare global variable `$` (`jquery`) and this variable should be accessed as `$` or `window.$` from any other `.js` file.

Currently here no way to statically detect global variable that will used only in current `.js`. file.

**Comment by msg768** [comment]
Fair enough. Mine are only being used in one .js file. I wish you had an option to uglify global variables and functions at the discretion of your users, so they would only choose that option if their global variables were being used in the same .js file! Thanks anyway...

**Comment by msg768** [comment]
Awesome man. Thanks in advance :P

**Comment by sanex3339** [comment]
I'll try to enable obfuscation of global names with declarations if specific option is enabled

**Comment by slig** [comment]
Meanwhile you can workaround this by using `immediately invoked functions`:

	(function () {
	
		// your original code with public variables goes here
	
		var foo = 42; // will be obfuscated
	
		// now this function name will be obfuscated as well
		function hi() {
			alert('hi!');
		}
	
		// but can be also called externally, for instance in
		// <button onclick="hi()">say hi</button>
		// if you "export" it by doing this:
		window.hi = hi;

	})();

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/commit/a59fda5d7c4bdaaec0a277a90cc46d332a3a4b4b

**Comment by sanex3339** [comment]
Hi. Check new `javascript-obfuscator@0.11.0-beta.1`

I added new `renameGlobals` option.

PS: Also i added new `log` option that enable simple logging to the console.

**Comment by sanex3339** [comment]
Expect 0.11.0 release this weekend.

**Comment by sanex3339** [comment]
`javascript-obfuscator@0.11.0` is out!
