### ISSUE TITLE
Javascript-Obfuscator build errors

### ISSUE THREAD

**Issue by invisiblepatriot** [javascript-obfuscator/javascript-obfuscator#743]
Hi,

We are trying to implement javascript-obfuscator (@2.1.0) for webpack build. However, when running the webpack build we've come across these build errors:

ERROR in [at-loader] ./node_modules/javascript-obfuscator/src/interfaces/IInitializable.ts:7:17
    TS2370: A rest parameter must be of an array type.

ERROR in [at-loader] ./node_modules/javascript-obfuscator/src/interfaces/IInitializable.ts:1:44
    TS2304: Cannot find name 'unknown'.

ERROR in [at-loader] ./node_modules/javascript-obfuscator/src/types/TDictionary.ts:3:30
    TS2304: Cannot find name 'unknown'.

## Expected Behavior
The application will be obfuscated

## Your Environment

* Obfuscator version used: 2.1.0
* Node version used: 12.15.0

"dependencies": {
    "@angular-devkit/core": "^7.3.10",
    "@angular-devkit/schematics": "^7.3.10",
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@fortawesome/fontawesome-pro": "^5.9.0",
    "@schematics/angular": "^8.3.29",
    "ajv": "^6.9.1",
    "bootstrap": "^4.5.2",
    "clean-webpack-plugin": "^3.0.0",
    "core-js": "^2.5.4",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "popper.js": "^1.16.1",
    "rxjs": "~6.2.0",
    "to-string-loader": "^1.1.6",
    "uglifyjs-3-webpack-plugin": "^1.2.4",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "webpack-cli": "^3.3.6",
    "webpack-obfuscator": "^2.1.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "~6.2.2",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/node": "~8.9.4",
    "angular-router-loader": "^0.8.5",
    "angular2-template-loader": "^0.6.2",
    "awesome-typescript-loader": "^5.2.1",
    "codelyzer": "~4.3.0",
    "copy-webpack-plugin": "^6.1.0",
    "css-loader": "^3.2.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^4.2.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "style-loader": "^1.0.0",
    "terser-webpack-plugin": "^4.1.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "^2.9.2",
    "webpack": "^4.39.1",
    "webpack-dev-server": "^3.8.0",
    "webpack-merge": "^4.2.1"
  }

The issues only seem to occur when we import the plugin -> var WebpackObfuscator = require('webpack-obfuscator');
Any help would be hugely appreciated

**Comment by sanex3339** [comment]
Hi. Use the latest typescript version.
