### ISSUE TITLE
Error after obfuscating angualrjs code vs 1.8.1

### ISSUE THREAD

**Issue by Woean** [javascript-obfuscator/javascript-obfuscator#749]
## Expected Behavior
i obfuscated my whole projects js code folder with the cli javascript-obfuscator ./dist --output ./dist/obfuscated

## Current Behavior
without obfuscating everything works fine.

the code was obfuscated correctly, but when I try to run the obfuscated code the console throws error:

Error: [$injector:unpr] http://errors.angularjs.org/1.8.1-build.1809+sha.e7ae36158/$…eProvider%20%3C-%20_0x76253e%20%3C-%20documentClickDirective

## Steps to Reproduce

not possible because of legal issues

## Your Environment

* Obfuscator version used: 2.2.1_2020-09-15T13:49:20.295Z
* Node version used: v12.16.0
*AngularJS used: 1.8.1

# Stack trace

**Comment by sanex3339** [comment]
AngularJS is using dependency injection based on identifier names.
Check this https://docs.angularjs.org/guide/di and use $inject Property Annotation
