### ISSUE TITLE
Uncaught SyntaxError: Identifier '_0x4482' has already been declared

### ISSUE THREAD

**Issue by rangam1004** [javascript-obfuscator/javascript-obfuscator#751]
Hi, 
we are getting Uncaught SyntaxError: Identifier '_0x4482' has already been declared error in console. 

## Expected Behavior
In console it should not show following error.
Uncaught SyntaxError: Identifier '_0x4482' has already been declared

## Current Behavior
Getting error:
Uncaught SyntaxError: Identifier '_0x4482' has already been declared

## Steps to Reproduce
Please try to obfuscate following sample function and obfuscated code use it in application.

function testCall(empList){
  empList.forEach(function(object){
    let smalest=findSmallPoints(object.points);
  });
}

## Your Environment

* Obfuscator version used: 2.3.0
* Node version used: v12.18.4

**Comment by sanex3339** [comment]
Cannot reproduce.
Show me your options and an example that WILL show this error.
For me the following code works fine:
```
function findSmallPoints(points) {
   console.log(points);
}

function testCall(empList){
  empList.forEach(function(object){
  	let smalest=findSmallPoints(object.points);
  });
}

testCall([{points: 'foo'}]);

// foo
```

**Comment by rangam1004** [comment]
@sanex3339 Thank you for reply.

Above mentioned obfuscated code working fine separately. But in our application we have many other obfuscated functions, with that if we include this obfuscated code we are getting error. Unfortunately I will not able to provide other obfuscated code.

Please note this issue we are facing with obfuscated code which is starting with const type. Our application other obfuscated  codes are starting with var. Is this possible can we get obfuscated output starting with var type?

**Comment by sanex3339** [comment]
Please show me your obfuscation options

**Comment by rangam1004** [comment]
https://obfuscator.io/

Default obfuscation options with above link. I tried with online also.

**Comment by sanex3339** [comment]
This identifier _0x4482 most likely is the string array identifier. It shouldn't be declared twice. So looks like you did something wrong. If possible send me your source code that you obfuscated via obfuscator.io. I can sign the NDA if you want.

**Comment by sanex3339** [comment]
Or send me the obfuscated code. Or try to find the problematic place by removing parts of the code.

**Comment by sanex3339** [comment]
Maybe you used same seed option for a two separate files that then were concatenated together. So with the same seed the names of the string array identifiers will be the same

**Comment by sanex3339** [comment]
This error happens every time after obfuscation or it appears randomly?

The name of the identifier in the error is always the same or it's the different?

**Comment by sanex3339** [comment]
Without all this info i cannot help

**Comment by sanex3339** [comment]
So, you mentioned that a single file works fine but a few files together are broken. So probably you used the same seed for each file.

Try to use a different seed for these files OR use the identifiersPrefix option to set the identifiers prefix for each file:
https://github.com/javascript-obfuscator/javascript-obfuscator#identifiersprefix

**Comment by rangam1004** [comment]
This is application issue, obfuscated code is working fine alone. Not able to find exact root cause. So temporarily unchecked string array in obfuscate option and obfuscated code does not contain constant type, this is resolved the issue temporarily. Thank you @sanex3339 for the support. 🙂

**Comment by sanex3339** [comment]
As i said before, try to use a different seed for each obfuscated file of use identifiersPrefix option

**Comment by rangam1004** [comment]
> As i said before, try to use a different seed for each obfuscated file of use identifiersPrefix option

Yes we tried same, still facing same issue.

**Comment by sanex3339** [comment]
Show me the error with identifierPrefix option enabled.

**Comment by zengfanfan** [comment]
need no example code nor reproduce steps, just think about this case:
1. a resuable js file is obfuscated with global `const/let` declarations
2. this file is run for more than once
3. then it absolutely(and inevitablely) will suffer an `already been declared` error

why don't we use `var` instead? the obfuscated code should not be modified so variables dont have to be 'readonly'
