### ISSUE TITLE
[BUG] SelfDefender Does Not Work Correctly

### ISSUE THREAD

**Issue by BlackYuzia** [javascript-obfuscator/javascript-obfuscator#754]
#### Description 

@sanex3339 Idk how he work exact but when I try obfuscate this code:
```
console.log("Kruzya is not a pidor"); // This is a Lie!
```
with `self defender` I get this:

```
var _0x2a17dc = function () {
        var _0x1e4686 = !![];
        return function (_0x5bc252, _0x3968f2) {
            var _0x5333b7 = _0x1e4686 ? function () {
                if (_0x3968f2) {
                    var _0x23343b = _0x3968f2['apply'](_0x5bc252, arguments);
                    return _0x3968f2 = null, _0x23343b;
                }
            } : function () {};
            return _0x1e4686 = ![], _0x5333b7;
        };
    }(),
    _0x1402d9 = _0x2a17dc(this, function () {
        var _0xf1702c = function () {
            var _0x11f380 = _0xf1702c['constructor']('return /\" + this + \"/')()['constructor']('^([^ ]+( +[^ ]+)+)+[^ ]}');
            return !_0x11f380['test'](_0x1402d9);
        };
        return _0xf1702c();
    });
_0x1402d9(), console['log']('Kruzya is not a pidor');
```

but when I just edit this ... all is work :eyes: 

#### Settings

![image](https://user-images.githubusercontent.com/25010528/93687838-b7f6d980-fac9-11ea-9732-de73284e0eb4.png)

#### Example of work after edit

![image](https://user-images.githubusercontent.com/25010528/93687849-da88f280-fac9-11ea-9b8f-c7ecca80a798.png)

**Comment by BlackYuzia** [comment]
Yea, this code is too short... but...

**Comment by sanex3339** [comment]
Selfdefending works in some other way. Try to beautify this code and see the result.

**Comment by BlackYuzia** [comment]
> Selfdefending works in some other way. Try to beautify this code and see the result.

yea, I now that. but what if I just beatify code, edit code, return oneline code again?
