### ISSUE TITLE
type error html parameters? 

### ISSUE THREAD

**Issue by Woean** [javascript-obfuscator/javascript-obfuscator#756]
i get a type error when i try to obfuscate my code, i think the problem are the parameters between html and js, because the js code is obfuscated and then i got the error : ... is undefined. 
do you know how to solve this problem? 
thanks a lot

**Comment by sanex3339** [comment]
Show me the example on source code

**Comment by sanex3339** [comment]
ping

**Comment by sanex3339** [comment]
I will close this issue. Create a new issue with additional details.
