### ISSUE TITLE
--config option does not work

### ISSUE THREAD

**Issue by psabharwal123** [javascript-obfuscator/javascript-obfuscator#76]
Webpack seems to convert 'require(configFileLocation)' in file JavaScriptObfuscatorCLI to !function(){var e=new Error('Cannot find module "."');throw e.code="MODULE_NOT_FOUND",e}().

**Comment by psabharwal123** [comment]
solution is to use __non_webpack_require__ instead; however, i cant figure out a way to use that without typescript compliaing. Please see if you can figure out a way.

**Comment by sanex3339** [comment]
Interesting. With `__non_webpack_require__` unit tests will break.

**Comment by sanex3339** [comment]
Expect 0.10.1 version later today.

**Comment by sanex3339** [comment]
Fixed in `javascript-obfuscator@0.10.1`

**Comment by psabharwal123** [comment]
thanks! feel free to remove `exprContextCritical: false,` :)

**Comment by sanex3339** [comment]
Oh >_<. I'll remove it in next release when it will be done.

**Comment by sanex3339** [comment]
`exprContextCritical: false` still needed to hide this message.
