### ISSUE TITLE
error - console.groupCollapsed >log

### ISSUE THREAD

**Issue by lonewolfyx** [javascript-obfuscator/javascript-obfuscator#761]
use online Obfuscator and make OptionsPreset to medium. The result turned out to be unable to run.

Obfuscator code:
console.groupCollapsed(' first group');
    console.groupCollapsed('second group');
        console.log('Hello Word');
    console.groupEnd();  
console.groupEnd();

**Comment by sanex3339** [comment]
It works for me

**Comment by sanex3339** [comment]
Closed as inactive. Feel free to reopen this issue if you have additional details about this error.
