### ISSUE TITLE
Shouldn't libraries avoid using debugProtectionInterval?

### ISSUE THREAD

**Issue by DidierLoiseau** [javascript-obfuscator/javascript-obfuscator#763]
We are (indirectly) using a proprietary library that appears to be using the obfuscator with `debugProtectionInterval`. This makes debugging globally unusable as soon as the library is loaded.

Shouldn't libraries avoid enabling it since it has impact outside of the library scope? If yes, it would be nice to make it a recommendation in the documentation.

**Comment by sanex3339** [comment]
Obfuscator is just a tool. Anyone who is using it should understand all benefits and problems of it. So it's better to write to the author of the 3rd party library and to ask him about the possibility of disabling `debugProtectionInterval`.
