### ISSUE TITLE
Domain Lock Pattern *.edu

### ISSUE THREAD

**Issue by anywhichway** [javascript-obfuscator/javascript-obfuscator#764]
Typically domain lock wild cards are applied at tertiary levels. Will your lock work at a secondary level, e.g. allow anything from .edu with *.edu?

**Comment by da411d** [comment]
Just tested, yes, it should work.
**But,** as stated in [doc](https://github.com/javascript-obfuscator/javascript-obfuscator#domainlock), you need to set not "*.edu" but ".edu".

I just tested it with simple hello world in browser console and it seems to work.

**Comment by sanex3339** [comment]
Feel fre to reopen this issue if you will have additional questions
