### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by madprops** [javascript-obfuscator/javascript-obfuscator#77]
Is there a preset I can use to minify the file to the lowest file size possible?

**Comment by sanex3339** [comment]
Obfuscation - not a minification.
You should chose - small file size or protection.

For small file size check this:
https://github.com/mishoo/UglifyJS
http://www.iteral.com/jscrush/ - very nice mification, but be aware, anyone can restore original code in one minute, so this don't protect your code.
