### ISSUE TITLE
Debug protection only inside obfuscated code.

### ISSUE THREAD

**Issue by downrunner-help** [javascript-obfuscator/javascript-obfuscator#771]
**Is your feature request related to a problem? Please describe.**

When debug protection is turned on it prevents debugging of all JavaScript code. This can be quite annoying if the bugs are not in the code being obfuscated.

**Describe the solution you'd like**

Have a flag that turns debug protection on and off only while inside the target obfuscated code.

**Describe alternatives you've considered**

None

**Additional context**

This might be implemented by modifications to the global interval handler than currently does debug protection by simply setting a global variable whenever an obfuscated function is entered and exited.

Have not thought a lot about the internals, my idead may simply not be possible.

**Comment by sanex3339** [comment]
Use obfuscation only in `production`. If you need to debug code - don't enable the `debugProtectionInterval` option.

**Comment by downrunner-help** [comment]
@sanex3339 The challenge is that a website may depend on a bunch of other libraries and sometimes bugs in these make their way in unknown. Additionally if someone else is using my library (which I know ... or hope to be bug free) which is obfuscated and protected, they can't debug their own code.

**Comment by sanex3339** [comment]
Disable this option, then

**Comment by downrunner-help** [comment]
@sanex3339 I guess I am not making my use case clear, so I will drop this. Continued thanks for the great library and online tool though!
