### ISSUE TITLE
Laravel Usage?

### ISSUE THREAD

**Issue by igquiz** [javascript-obfuscator/javascript-obfuscator#786]
Is there any possibility to use this as laravel package?
I am zipping javascript files before users can download them - I have to obfuscator them on your website everytime. I am asking myself if there is a way to obfuscate them before they get zipped?

Kind regards

**Comment by sanex3339** [comment]
Hi. Javascript obfuscator has: 
- API https://www.npmjs.com/package/javascript-obfuscator#obfuscatesourcecode-options
- webpack plugin and loader https://www.npmjs.com/package/webpack-obfuscator
