### ISSUE TITLE
Some errors when compiling javascript-obfuscator

### ISSUE THREAD

**Issue by wyw900807** [javascript-obfuscator/javascript-obfuscator#787]
Dear sir,
             I try to compile javascript-obfuscator by myself, but after inputting "tsc", there are some errors as follows, could you tell me how to compile this project?  Thank you very much!

src/node-transformers/string-array-transformers/StringArrayScopeCallsWrapperTransformer.ts:185:13 - error TS1005: ',' expected.

185     ): [name: string, index: number] {
                ~

src/node-transformers/string-array-transformers/StringArrayScopeCallsWrapperTransformer.ts:185:28 - error TS1005: ',' expected.

185     ): [name: string, index: number] {
                               ~

src/node-transformers/string-array-transformers/StringArrayScopeCallsWrapperTransformer.ts:203:13 - error TS1005: ',' expected.

203     ): [name: string, index: number] {
                ~

src/node-transformers/string-array-transformers/StringArrayScopeCallsWrapperTransformer.ts:203:28 - error TS1005: ',' expected.

203     ): [name: string, index: number] {
                               ~

src/node-transformers/string-array-transformers/StringArrayTransformer.ts:233:13 - error TS1005: ',' expected.

233     ): [name:string, index:number] {
                ~

src/node-transformers/string-array-transformers/StringArrayTransformer.ts:233:27 - error TS1005: ',' expected.

233     ): [name:string, index:number] {
                              ~

src/node-transformers/string-array-transformers/StringArrayTransformer.ts:245:13 - error TS1005: ',' expected.

245     ): [name:string, index:number] {
                ~

src/node-transformers/string-array-transformers/StringArrayTransformer.ts:245:27 - error TS1005: ',' expected.

245     ): [name:string, index:number] {
                              ~

src/node-transformers/string-array-transformers/StringArrayTransformer.ts:262:13 - error TS1005: ',' expected.

262     ): [name:string, index:number] {
                ~

src/node-transformers/string-array-transformers/StringArrayTransformer.ts:262:27 - error TS1005: ',' expected.

262     ): [name:string, index:number] {
                              ~

src/types/utils/TTransformersRelationEdge.ts:2:21 - error TS1005: ',' expected.

2     transformerNameA: TTransformerName,
                      ~

src/types/utils/TTransformersRelationEdge.ts:3:21 - error TS1005: ',' expected.

3     transformerNameB: TTransformerName | null

**Comment by sanex3339** [comment]
After you cloned this project, install all dependencies.
This project will compile only under the latest typescript@4.1-beta.

After `npm i` run `npm run watch`

**Comment by wyw900807** [comment]
Thank you!
