### ISSUE TITLE
Is  javascript obufusactor (2.6.1) fails with mixpanel ?

### ISSUE THREAD

**Issue by ravicce** [javascript-obfuscator/javascript-obfuscator#793]
We used  JavaScript obfuscator version 0.28.2. It was working fine even with mix panel.
After updating to  javascript obfuscator 2.6.1, mix-panel events are failing. We use mix-panel for analytics.
Other functionality is working fine with latest version of JavaScript obfuscator except for mix panel events. It gives the following error. 
VM10 polyfills-es2015.c752f970d38c0e068e53.js:1 GET https://api-js.mixpanel.com/decide/? 400

It would be helpful if i can debug the obfuscated code with source maps.

**Comment by sanex3339** [comment]
This error gives no info for me.

**Comment by sanex3339** [comment]
Any info?

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
Closed. Create a new issue with more details.
