### ISSUE TITLE
Domain lock not working!

### ISSUE THREAD

**Issue by abraham891** [javascript-obfuscator/javascript-obfuscator#794]
I have 2 blogs on Blogger. I added domain lock for first blog, but when i tried to run it 2nd blog it still runs. Is that because URL of Blogger blogs have ".blogspot" in it?

**Comment by sanex3339** [comment]
Please provide more details.

**Comment by sanex3339** [comment]
Any info?

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
Closed. Create a new issue with more details.
