### ISSUE TITLE
Obfuscate code contains variable declared without var/let may cause name conflict

### ISSUE THREAD

**Issue by wyzzoo** [javascript-obfuscator/javascript-obfuscator#796]
Obfuscate code contains variable declared without var/let may cause name conflict.

## Steps to Reproduce
obfuscate following code 

```
z = {};
z.v = function() {
  console.log(0);
}

function f1() {
  let x = 1;
  let y = 2;

  z.v();
}

f1();
```

with config

```
{
    ...
    "indetifierNamesGenerator": "dictionary",
    "indetifierDictionary": ["z", "a", "b", "c", "d", "e", "f", "g"]
    ...
}
```
not 100% so I write a bash script to repeat obfuscate the script util error occured
```
set -e
while true
do
  node javascript-obfuscator 4.js --config options.json
  node 4-obfuscated.js
done
```

## Your Environment

* Obfuscator version used: latest code in master branch
* Node version used: v10.21.0

**Comment by sanex3339** [comment]
Why did you initialized `z` object without `var`, `let` or `const`?
This error won't happen if you write:
```
var z = {};
```
