### ISSUE TITLE
Logic error when using spread operator

### ISSUE THREAD

**Issue by spoonysnail** [javascript-obfuscator/javascript-obfuscator#797]
## Minimal working example that will help to reproduce issue

```
const demo = { active: true, name: 'demo' }
console.log({
      active: false,
      ...demo
})
```
## Expected Behavior

Output: { active: true, name: 'demo' }
## Current Behavior

Output: { active: false, name: 'demo' }
## Your Environment

* Obfuscator version used: 2.6.3
* Node version used: v12.13.1

## 
Code After Obfuscation:
```
const _0x41674a={..._0x5b345c};
_0x41674a[_0x22a0ec('0x17')]=![], console['log'](_0x41674a);}
```
Clearly, the order of assignment is wrong.

**Comment by sanex3339** [comment]
Hi. What options did you used?

**Comment by sanex3339** [comment]
This bug reproduced with `transformObjectKeys` option is enabled.

**Comment by sanex3339** [comment]
Seems i fixed it. PR will be ready in 30 minutes.
After fix all object members previous to `spread element` will be ignored.

**Comment by sanex3339** [comment]
That's sad that this bug has existed for so long.

**Comment by sanex3339** [comment]
Will be released later today

**Comment by sanex3339** [comment]
Released
