### ISSUE TITLE
ReferenceError when using mangle

### ISSUE THREAD

**Issue by madprops** [javascript-obfuscator/javascript-obfuscator#80]
The code without obfuscation works. 
The code obfuscated without mangle works.
But when I activated mangle I got this: 

https://pastebin.com/z3dzrn3z
http://i.imgur.com/eI0HpoV.jpg

Maybe it could help.

**Comment by sanex3339** [comment]
Mangle option use `esmangle`, so most likely it related to `esmangle` package.
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/JavaScriptObfuscatorInternal.ts#L126

**Comment by sanex3339** [comment]
Cannot reproduce.

My code:
```
let vars = {
    foo: {
        edges: [
            'foo',
            'bar'
        ]
    },
    bar: {
        edges: [
            'foo',
            'bar'
        ]
    }
};
let keys = [
    'foo',
    'bar'
];

for (var i = 0; i < keys.length; i++) {
    console.log(1);
    var edges = vars[keys[i]].edges;
    console.log(2);

    var found = false;
    console.log(22);

    for (var el of edges) {
        console.log(3);
        if (vars[el] !== undefined) {
            found = true;
            break;
        }
    }

    if (!found) {
        console.log(4);
        acyclic = true;
        delete variables[keys[i]];
        sorted.push(keys[i]);
    }
    console.log(5);
}
```

Options: 
```
    {
            stringArray: true,
            stringArrayThreshold: 1,
            controlFlowFlattening: true,
            controlFlowFlatteningThreshold: 1,
            mangle: true
        }
```

**Comment by madprops** [comment]
Only option I used is mangle:true, using 0.10.1

**Comment by sanex3339** [comment]
As i said before - cannot reproduce. Can you attach your full source code?

**Comment by madprops** [comment]
I can't sorry :( However I can give you the obfuscated code https://pastebin.com/YAexyEG3  and the where it failed http://i.imgur.com/fjmHaZc.jpg

**Comment by sanex3339** [comment]
I got error `math is not defined`.

Also, try to use other js minification tool like `UglifyJs`. If with `UglifyJs` obfuscated code wont throw error - problem in `esmangle`

**Comment by madprops** [comment]
It's no problem, I just don't use the mangle option and it works fine.

Also yeah I doubt that code will work, it's just for reference purposes.

**Comment by crazyyi** [comment]
I use `mangle: true` and I get `RangeError: Maximum call stack size exceeded.` when I run my app. Don't have this problem it is set to false.
