### ISSUE TITLE
Error after obfuscate

### ISSUE THREAD

**Issue by DowsingUK** [javascript-obfuscator/javascript-obfuscator#807]
Angular9
Node12

ERROR TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.
    at S.p.<computed>.r.<computed>.p.<computed>.<computed> [as readAsDataURL]

Everything works as expected until apply obfuscation

**Comment by sanex3339** [comment]
Please provide more info, obfuscator version and reproducible example.

**Comment by DowsingUK** [comment]
javascript-obfuscator@2.8.1

html
<input type="file" (change)="fileChangeEvent($event)" class="fileInputProfile">

ts
fileChangeEvent(fileInput: any) {
        this.imageError = null;
        if (fileInput.target.files && fileInput.target.files[0]) {
            // Size Filter Bytes
            const max_size = 20971520;
            const allowed_types = ['image/png', 'image/jpeg'];
            const max_height = 15200;
            const max_width = 25600;

            if (fileInput.target.files[0].size > max_size) {
                this.imageError =
                    'Maximum size allowed is ' + max_size / 1000 + 'Mb';

                return false;
            }

            if (!_.includes(allowed_types, fileInput.target.files[0].type)) {
                this.imageError = 'Only Images are allowed ( JPG | PNG )';
                return false;
            }
            const reader = new FileReader();
            reader.onload = (e: any) => {
                const image = new Image();
                image.src = e.target.result;
                image.onload = rs => {
                    const img_height = rs.currentTarget['height'];
                    const img_width = rs.currentTarget['width'];

                    console.log(img_height, img_width);


                    if (img_height > max_height && img_width > max_width) {
                        this.imageError =
                            'Maximum dimentions allowed ' +
                            max_height +
                            '*' +
                            max_width +
                            'px';
                        return false;
                    } else {
                        const imgBase64Path = e.target.result;
                        this.cardImageBase64 = imgBase64Path;
                        this.isImageSaved = true;
                        // this.previewImagePath = imgBase64Path;
                    }
                };
            };

            reader.readAsDataURL(fileInput.target.files[0]);
        }
    }

**Comment by sanex3339** [comment]
Cannot reproduce with this example. I corrected it slightly to work without angular, and `readAsDataURL` works fine for me with `optionsPreset: 'high-obfuscation'`

**Comment by DowsingUK** [comment]
Yes you are right I did try using it without Angular and I had to problem but my entire project it's based on Angular so I guess I can't use this obfuscator thank you anyways
