### ISSUE TITLE
Obfuscator not working with any javascript code.

### ISSUE THREAD

**Issue by Hadatko** [javascript-obfuscator/javascript-obfuscator#808]
I am running latest obfuscator on several js code files and it looks like obfuscator ends always in the middle of obfuscating. Didn't get any error.

## Expected Behavior
obfuscate whole files

## Current Behavior
it looks obfuscating is broken during process.

## Steps to Reproduce
1. javascript-obfuscator <folder with js code> --output dist/win-unpacked/out --compact false --self-defending false

## Your Environment

* Obfuscator version used: 2.8.1
* Node version used:v14.15.0

## Minimal working example that will help to reproduce issue
[js.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/5537467/js.zip)

**Comment by sanex3339** [comment]
what file from `js.zip` archive i should obfuscate?

**Comment by Hadatko** [comment]
All of them. But it looks like the issue is not in obfuscator but in electron app i am using. It looks like it is able only show part of obfuscated code. I looked into obfuscated code directly and i don't see reason why it is failing.
