### ISSUE TITLE
Run specific code on self defend

### ISSUE THREAD

**Issue by klokwert** [javascript-obfuscator/javascript-obfuscator#809]
**Is your feature request related to a problem?**
I was searching for a good js obfuscator and i found this one, it's perfect exept for one thing...
it has much features but you can't customize actions taken when something triggers like self defending or domain lock

**Describe the solution you'd like**
I would really like to be able to put in my own javascript that runs when it self defends or if it runs on the wrong domain

**Additional context**
I would really like to be able to use this amazing feature (if it gets added)

**Comment by sanex3339** [comment]
Hi. I can't add any code when self-defending triggers because of the way how the self-defending is working.

**Comment by klokwert** [comment]
isn't it possible to rewrite the self-defending so it is possible?

**Comment by sanex3339** [comment]
No.

**Comment by klokwert** [comment]
ohh, ok, unfortunately

**Comment by klokwert** [comment]
and how about the custom code for domain lock

**Comment by sanex3339** [comment]
Right now i can add custom code for domain lock. But probably in the future, I will change the way how it works the same as `selfDefending`

**Comment by sanex3339** [comment]
To be clear, as soon as self defending mechanism triggers, all code evaluation is stopping
