### ISSUE TITLE
Exponent operator ** break IE11

### ISSUE THREAD

**Issue by kedare** [javascript-obfuscator/javascript-obfuscator#814]
## Expected Behavior
There should have no impact on the good working of the code after running obfuscation

## Current Behavior
On IE11 the code is failing because there are "**" operators inserted in the code (not present in the original code) that is not supported in IE11 :

## Steps to Reproduce
1. I could not reproduce with test code, unfortunately I am not authorized to provide the code that create this issue (internal only), but it's not using React or any large framework, just plain javascript with websockets, webworkers and JWT library
2. Compile the code (tested via webpack)

## Your Environment

* Obfuscator version used: 2.8.1 (webpack plugin 3.1.0)
* Node version used: v14.15

# Stack trace
Syntax Error
The code block in question contains the following part (the issue point at the "**" that are not supported in IE11)

``` javascript
f.prototype.readUint32BE=f.prototype.readUInt32BE=function(t,e){return t>>>=0,e||x(t,4,this.length),16777216*this[t]+(this[t+1]<<16|this[t+2]<<8|this[t+3])},f.prototype.readBigUInt64LE=G((function(t){N(t>>>=0,"offset");const e=this[t],r=this[t+7];(void 0===e||void 0===r)&&D(t,this.length-8);const i=e+256*this[++t]+65536*this[++t]+this[++t]*2**24,n=this[++t]+256*this[++t]+65536*this[++t]+r*2**24;return BigInt(i)+(BigInt(n)<<BigInt(32))})),f.prototype.readBigUInt64BE=G((function(t){N(t>>>=0,"offset");const e=this[t],r=this[t+7];(void 0===e||void 0===r)&&D(t,this.length-8);const i=e*2**24+65536*this[++t]+256*this[++t]+this[++t],n=this[++t]*2**24+65536*this[++t]+256*this[++t]+r;return(BigInt(i)<<BigInt(32))+BigInt(n)})),f.prototype.readIntLE=function(t,e,r){t>>>=0,e>>>=0,r||x(t,e,this.length);let i=this[t],n=1,o=0;for(;++o<e&&(n*=256);)i+=this[t+o]*n;return n*=128,i>=n&&(i-=Math.pow(2,8*e)),i},f.prototype.readIntBE=function(t,e,r){t>>>=0,e>>>=0,r||x(t,e,this.length);let i=e,n=1,o=this[t+--i];for(;i>0&&(n*=256);)o+=this[t+--i]*n;return n*=128,o>=n&&(o-=Math.pow(2,8*e)),o},
```

## Minimal working example that will help to reproduce issue

Unknown, could not reproduce on sample code

**Comment by sanex3339** [comment]
Obfuscator does not add `**` symbols

**Comment by kedare** [comment]
I will take a look why it's working when not obfuscated, maybe it's somewhere in the bundle but not executed when not obfuscated (but should not event this cause a syntax error?)

**Comment by kedare** [comment]
I suspect this may be coming from this dependency : https://github.com/feross/buffer/blob/74899b7fbd0e3247931fa3cfb9fc27e96a995d21/index.js

After a lookup with the method name, I will check tomorrow as I don't have access to the code or the dependency list right now

**Comment by BlackYuzia** [comment]
Anybody use IE? No srly. 
I want to hear real numbers what a total % use IE. :thinking:

**Comment by kedare** [comment]
@BlackYuzia I wish I could skip IE support but I'm not the one deciding that on this project unfortunately 😅 
At least I don't need to support IE 6...
