### ISSUE TITLE
The output file name will be 'xjs' rather than 'x.js' when I input a directory

### ISSUE THREAD

**Issue by jianweiqin** [javascript-obfuscator/javascript-obfuscator#816]
The output file name will be 'xjs' rather than 'x.js' when I input a directory:
>javascript-obfuscator ./src

Is this a bug?

version:2.9.1
node:14.8

**Comment by sanex3339** [comment]
Cannot reproduce. 
Steps:
- created the directory called `abc` with file in it `x.js`
- called `javascript-obfuscator ./abc`
- result obfuscated file name is `x-obfuscated.js`

**Comment by jianweiqin** [comment]
> Cannot reproduce.
> Steps:
> 
> * created the directory called `abc` with file in it `x.js`
> * called `javascript-obfuscator ./abc`
> * result obfuscated file name was `x-obfuscated.js`

@sanex3339 
When I call:
>javascript-obfuscator ./abc --output ./dist
I found a file named 'xjs'. I need it to be 'x.js'

**Comment by jianweiqin** [comment]
> Cannot reproduce.
> Steps:
> 
> * created the directory called `abc` with file in it `x.js`
> * called `javascript-obfuscator ./abc`
> * result obfuscated file name was `x-obfuscated.js`

When I call:

>javascript-obfuscator ./abc --output ./dist

I found a file named 'xjs'. I need it to be 'x.js'

**Comment by jianweiqin** [comment]
> Cannot reproduce.
> Steps:
> 
> * created the directory called `abc` with file in it `x.js`
> * called `javascript-obfuscator ./abc`
> * result obfuscated file name was `x-obfuscated.js`

@sanex3339 
When I called:

>javascript-obfuscator ./abc --output ./dist

I found a file named 'xjs'. I need it to be 'x.js'

**Comment by sanex3339** [comment]
Still can't reproduce. For me it creates a correct output directory with a correct file name.
![image](https://user-images.githubusercontent.com/9210534/99767564-47455b00-2b14-11eb-8768-d53bced0b0f7.png)

**Comment by sanex3339** [comment]
Are you under unix or windows environment?

**Comment by jianweiqin** [comment]
windows
@sanex3339

**Comment by sanex3339** [comment]
I have a test for this behaviour and it runs fine under `windows` environment.

**Comment by sanex3339** [comment]
Does it happen with any filename, not only `x.js`?

**Comment by jianweiqin** [comment]
All the files are that style.
![22222](https://user-images.githubusercontent.com/26958373/99768526-e03d9b80-2b3f-11eb-98d4-75c2bf48acd5.png)

**Comment by jianweiqin** [comment]
I found it! When I input a '.' for current directory, it happens:
>javascript-obfuscator . --output "./dist/obfuscated"

**Comment by sanex3339** [comment]
Nice, now i can reproduce it.

**Comment by sanex3339** [comment]
Found the problem, will create the PR soon

**Comment by sanex3339** [comment]
PR: 
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/819

**Comment by sanex3339** [comment]
Released as `2.9.3`
