### ISSUE TITLE
Mangling option may produce buggy code in IE8-.

### ISSUE THREAD

**Issue by Wain-PC** [javascript-obfuscator/javascript-obfuscator#82]
Hello!
Consider this example:
```
var name = 'test',
	func = function () {
		try {
			console.log(name);
		} catch (e) {
		}
	};

func();
```
Obviously, this should output `'test'`, however, it outputs `undefined` in IE8 and older when running the obfuscator with `mangle:true` (yes, I know we're in 2017 =( ). This is related to the infamous [IE8 catch scope leak issue](http://linterrors.com/js/value-of-a-may-be-overwritten-in-ie8). The issue may occur in random parts of the code that use ``` var smth; try { ... } catch(e){ ... }``` pattern as the variable of the outer scope may be named the same as the `catch` argument, thus shadowing it.

Would you please take a look?
Thanks in advance!

**Comment by sanex3339** [comment]
PR welcomed) Or more detailed explanation how i can fix this.

**Comment by sanex3339** [comment]
But really fine solution - replace esmangle with uglifyjs 3. But after that obfuscation will slightly longer, because esmangle takes parsed ast tree, but for uglifyjs 3 i should takeobfuscated source code, because uglifyjs doesn't support esprima ast tree.

**Comment by Wain-PC** [comment]
Thanks for the attention. I've taken a look on `esmangle` and it seems it's pretty much abandoned. Moving to `uglifyjs` should definitely solve the issue, as it has been addressed before (can't find the exact pull request now, but I've surely seen it).
Also, what if I manually use `uglifyjs` on top of the obfuscated code for now (with `selfDefending: false`, of course)? Would it produce the same code?

**Comment by sanex3339** [comment]
It should produce same code (but i don't sure)

**Comment by sanex3339** [comment]
It's hard to replace `uglifyjs` instead of `esmangle` because `uglifyjs` transforming strings encoded as `unicode escape sequence` and numbers in hexadecimal format to normal view.

**Comment by Wain-PC** [comment]
Okay then, I've managed to minify the obfuscated code as a separate build step and it seems to work correctly, so I don't need `mangle` option for now. Thanks for helping!

**Comment by sanex3339** [comment]
Closed
