### ISSUE TITLE
[Feature Request] Interpretation Code

### ISSUE THREAD

**Issue by BlackYuzia** [javascript-obfuscator/javascript-obfuscator#821]
**Describe the solution you'd like**
Maybe you saw sometimes [yoptascript](https://yopta.space/).
On this site you can replace all words (default js methods and etc) to russian words (or phrases) (this is verry funny. **lol**)

![image](https://user-images.githubusercontent.com/25010528/99852813-6d0d4700-2b8a-11eb-869d-cc2651e7ff9b.png)

So, I have question or feature request to create auto renamer a code to anything useless like "abc abc abc".
How I know yopta script just innerpt yoptascript back to javascript :eyes:

> If we don't make that feature - kruzya stay a gay. **Save kruzya.**

**Code Example**

#### First way (obfuscate)
```
// before obfuscate
const value = "some string";

// after obfuscate
Gay gay equalToGay  Gay1some stringGay2GayClose
// const => Gay
// value => gay
// = => equalToGay
// " => Gay1
// " => Gay2
// some string => some string
// ; => GayClose // nvm
```

#### Second way (obfuscate + hide code)
```
// Before
const myKruzya = new (class Kruzya{isGay: true});

// After
a b c d ( f k {l: s}); // yep. "a b c d ( f k {l: s});" === const myKruzya = new (class Kruzya{isGay: true}); 
```

PS: IDK why but I like this idea :eyes:. Actualy, idk how that exactly can be released and complete inside code etc
PSS: I think we can inject some js file what "interpretate" our "bool shit" code to "normal js" code. And this js file should generate specialy for every obfuscated code ... etc?
PSSS: Kruzya is **obfuscated** gay! (idk why... he should be.)

**Comment by sanex3339** [comment]
Sorry, no)

**Comment by BlackYuzia** [comment]
> If we don't make that feature - kruzya stay a gay. Save kruzya.

@CrazyHackGUT F Bro.
