### ISSUE TITLE
Conflicts of identifier names between different files

### ISSUE THREAD

**Issue by drveresh** [javascript-obfuscator/javascript-obfuscator#824]
## Summary
The `identifiersPrefix` option is not working.  Duplicate `const` variables are defined in multiple javascript files and conflict with each other. 

For example, if I have two files File1 and File2, with each same variable/code declaration, with two different `identifiersPrefix` as "V1", and "V2" in the config, for both it is generating the same obfuscated code containing "`const h = xyz`".

## Expected Behavior
With `identifiersPrefix` defined separately for each file, all variable in those files must be unique with its prefix.

## Current Behavior
Currently, multiple files containing the same "const" variables and conflicting with each other.

**Comment by sanex3339** [comment]
Hi. Show all options that you used and also please show the part of the code with these identifiers.
Probably because these identifiers are global, you need to use `renameGlobals` option

**Comment by drveresh** [comment]
Please find attached two sample JS files, with the same code, except two extra const variables defined in each file, and below is my config:

**Config: build-obfuscate-config.json**
```
{
  "compact": true,
  "identifierNamesGenerator": "mangled",
  "stringArray": true,
  "renameGlobals": true
}
```

**Run Commands:**
```
javascript-obfuscator '../public/jsx/test2.js' --output '../public/jsl/test2.js' --config='../build/build-obfuscate-config.json' --identifiers-prefix "B2"
    javascript-obfuscator '../public/jsx/test1.js' --output '../public/jsl/test1.js' --config='../build/build-obfuscate-config.json' --identifiers-prefix "B1"
```

As expected, I still see several duplicate `const` variables, without prefixing the given `--identifiers-prefix`, as `"B1" and "B2"` to each file.
[test-js-code.zip](https://github.com/javascript-obfuscator/javascript-obfuscator/files/5580879/test-js-code.zip)

![image](https://user-images.githubusercontent.com/3812468/99925036-7ea94700-2d62-11eb-858b-8c618b76ffdb.png)

I am using this lib in build scripts of 5+ production applications and getting numerous bugs due to these issues.  I appreciate your help.  Ideally, every variable should be prefixed with given "`--identifiers-prefix`"

**Comment by drveresh** [comment]
@sanex3339 .  There, the const "test" is common in both files, but the other two const "test1" and "test2" are separately defined in each file.  So, no matter where and how they are defined every should be should have its prefix defined.

**Comment by sanex3339** [comment]
Can you send this two files without obfuscation?

**Comment by drveresh** [comment]
Here are the plain JS files.
[Uploading test-js-files.zip…]()

**Comment by sanex3339** [comment]
Please, recheck your link. It's broken.

**Comment by drveresh** [comment]
I have attached them again here, please check and let me know.
[test1.js.txt](https://github.com/javascript-obfuscator/javascript-obfuscator/files/5595491/test1.js.txt)
[test2.js.txt](https://github.com/javascript-obfuscator/javascript-obfuscator/files/5595492/test2.js.txt)

**Comment by sanex3339** [comment]
Cannot reproduce. What obfuscator version did you use?
For me identifiers with names `test` and `test1` was obfuscated fine.

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
Closed as inactive. Feel free to create a new issue with more info
