### ISSUE TITLE
sourceMapMode:"inline" option doesn't seems to be working.

### ISSUE THREAD

**Issue by whoami-shubham** [javascript-obfuscator/javascript-obfuscator#826]
Hi 👋, Thanks for this powerful library.
I had a doubt regarding option `sourceMapMode:"inline"`, it doesn't seem to be working because it doesn't generate source map file, is `inline` mode only works for CLI? I was wondering if the source map would have been generated where it would have been located?
I have used the following options
```js
{
    compact: true,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 1,
    numbersToExpressions: true,
    sourceMap:true,
    sourceMapMode:"inline",
    simplify: true,
    shuffleStringArray: true,
    splitStrings: true,
    stringArrayThreshold: 1,
  }
```
I am using node version `v12.18.2`

**Comment by sanex3339** [comment]
`inline` adds source map into the `.js` file.
If you want a separate `.js.map` file you have to use `sourceMapMode: 'separate'`

**Comment by whoami-shubham** [comment]
@sanex3339 Thanks for the quick reply, do you mean `inline` adds source map at the end of each ` .js` files?

**Comment by sanex3339** [comment]
Yes

**Comment by whoami-shubham** [comment]
then this line should be changed 
* `inline` - emit a single file with source maps instead of having a separate file;
to 
* `inline` -inline add source map at the end of each .js files;
in the readme?

**Comment by sanex3339** [comment]
Agree

**Comment by whoami-shubham** [comment]
shall I send a PR for this?

**Comment by sanex3339** [comment]
Yes, it would be nice
