### ISSUE TITLE
How to run it with php?

### ISSUE THREAD

**Issue by framgrab** [javascript-obfuscator/javascript-obfuscator#83]
Hello, this project is literally amazing, I really admire. Is there any way for running this system on php? Thank you.

**Comment by sanex3339** [comment]
No way(

**Comment by sanex3339** [comment]
But you can up obfuscator service alongside with php and send to it message from php

**Comment by Yellow79** [comment]
I think it will help you
https://stackoverflow.com/questions/17180656/run-server-side-js-from-php-through-exec/17182368#17182368

**Comment by sanex3339** [comment]
Closed due inactivity. Please create new issue or write here and i'll reopen this issue.
