### ISSUE TITLE
Domainlock does not lock to domain

### ISSUE THREAD

**Issue by tomatopuree** [javascript-obfuscator/javascript-obfuscator#835]
This is how I run the command
`javascript-obfuscator unobfuscated.js -o obfuscated.js --string-array-encoding "base64" --domain-lock ["https://www.domainA.com/"]`

And then obfuscated.js is included in the head of domainB.com/page.html

When I go on the page, and trigger the script with the click of a button event (the script is one single function), the script runs.

Interestingly at console.log I see:
"Uncaught ReferenceError: data is not defined" 

## Current Behavior

The current behavior is that although console.log says "data is not defined" the function is successfully run on a domain that is not the domain the code should be locked to.

Obfuscator version used: 2.8.1_2020-11-09T22:05:23.007Z
Node version used: v14.15.0

I tried empty cache and hard reload incase some caching with a nonlocked was going on.

**Comment by da411d** [comment]
That is [function hoisting](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting#Learn_more). 
As **temporary solution** you can wrap your code in [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE) and then "export" only that function that should be outside:
```
(function(){
  function foo(){
    console.log(1257);
  }
  window.foo = foo;
})();
```

**Comment by sanex3339** [comment]
After `2.15.1` the `domainLock` option now redirects to the `domainLockRedirectUrl` address.
