### ISSUE TITLE
disableConsoleOutput is applied outside of scope

### ISSUE THREAD

**Issue by kioan000** [javascript-obfuscator/javascript-obfuscator#836]
In my webpack stack i have several entrypoints. One of them is importing some js that are obfuscated with a bunch of rules and disableConsoleOutput flag enabled. Obfuscation is desired only on these specific files so is applied by file name.

## Expected Behavior

Obfuscation should be applied only on the targeted files. 

## Current Behavior

Only target files are obfuscated BUT console.logs are omitted on other entrypoints and related files that are completely out of scope and not matching text regex. Only some files are affected (randomly)

## Steps to Reproduce
I can't understand the bug so I can't reproduce. Affected files are always the same but I can't understand why it happens on those (related files aren't importing obfuscated files)

## Your Environment

* Obfuscator version used: 3.1
* Node version used: webpack 4.44
- My obfuscator loader configuration says:
```js
test: /(a|b|c).js$/,
          enforce: 'post',
          use: {
            loader: WebpackObfuscator.loader,
            options: {
            ...
               disableConsoleOutput: true
            }   
```
- One of the obuscated files is a javascript worker loaded with worker-loader.
- We have some async chunks with dynamic imports

# Stack trace
- no errors are emitted and transpiled code looks the same

**Comment by sanex3339** [comment]
Hi. This is not a bug, bot how `disableConsoleOutput` works.
