### ISSUE TITLE
Fails on arrow functions expressions in ES6 classes

### ISSUE THREAD

**Issue by Nashorn** [javascript-obfuscator/javascript-obfuscator#840]
Input:
```
class Test {
	onUpdate =()=> {
    
    }
}
```

Error on Obfuscator:
------------------------------------------------
Error: ERROR at line 2: Unexpected token (2:10)
> ...onUpdate =()=> {...

**Comment by sanex3339** [comment]
Same as https://github.com/javascript-obfuscator/javascript-obfuscator/issues/510
