### ISSUE TITLE
__webpack_modules__ properties renamed => breaks code

### ISSUE THREAD

**Issue by gregbenz** [javascript-obfuscator/javascript-obfuscator#846]
Using code output from webpack, the obfuscator is making a breaking change if options.renameProperties = true;

The output throws an error on the output line of the form:
```return __webpack_modules__[moduleId](module, module[_0x41d9dc(0x43e)], __webpack_require__), module['exports'];```

Adding some logging to the obfuscated output, I see that the moduleId property strings have been renamed from the original name ('../src/events.ts' or '../src/menus.ts' affected) to something like _0x90d7c8. I have other similar filenames that aren't being renamed (such as '../src/paths.ts' or '../src/tools.ts') and don't see obvious differences in use or module imports, so I am unclear why these two changing where others are left alone.

this results in an error being thrown: **Uncaught TypeError: __webpack_modules__[moduleId] is not a function**

Replacing that line with the code below shows that the problem is that the property in the modules has been renamed, but the array used to loop over it has not.

- The moduleId array still lists the original name before obfuscation. (Test 1)
- However, the actual property in __webpack_modules__ has been renamed (Test 0)

```
try {
    console.warn('\n\n\nNow testing: ' + moduleId);
    if (typeof __webpack_modules__[moduleId] !== 'function') {
        for (const props in __webpack_modules__) console.warn(`WEBPACK TEST 0: __webpack_modules__${props} = `, props); _//reviewing console shows one affected module listed as _0x90d7c8 for example_
    }
return __webpack_modules__[moduleId](module, module['exports'], __webpack_require__), module[__0x2e4d00(0x1f3)_];
} catch (e) {
    if (typeof __webpack_modules__[moduleId] !== 'function') console.warn('WEBPACK TEST 1: ', moduleId); _//lists original name for all_
    console.warn('WEBPACK TEST 2: ', __webpack_modules__[moduleId]); //undefined for renamed module
    console.error('WEBPACK TEST 3: ', e);
    return function () {};
}
```

I do not see a clear pattern as to which names get mangled.

## Workaround:
Using the following prevents the issue (all my modules end in .ts since I'm using TypeScript)
```options.reservedNames.push('.*.ts')```

## Your Environment

* Obfuscator version used: v2.9.5
* Node version used: v12.16.1

**Comment by sanex3339** [comment]
Hi. If this option breaks your code - disable it.
https://github.com/javascript-obfuscator/javascript-obfuscator#i-enabled-renameproperties-option-and-my-code-broke-what-to-do

**Comment by gregbenz** [comment]
Obfuscating method names is probably the best and most useful feature of this software, and a conflict with webpack is likely to prevent a lot of developers from being able to use it. Chances are it probably affects other scenarios, as the issue is that the object keys are being obfuscated in one context and not another. Any chance of leaving this open?

**Comment by sanex3339** [comment]
Property names cannot be done in the same way as identifier names. So the logic is the following:
- traverse through all property names
- for each property name rename this name and put it in the cache
- if the visited property name is the same as already renamed - put the name for this property from the cache

So, it respects only string literal property names. If a property name is computed in some way - this option WILL break your code.

**Comment by gregbenz** [comment]
@sanex3339 I appreciate you taking the time to provide that info. That makes sense and I would expect computed keys would break things. In this case, these are calls to retrieve object methods based on string literals. 

Would it be possible to update the rename properties feature so that you can prevent it from renaming properties when they are created using string literals for the keys? Disabling these string property replacements would protect webpack, while allowing obfuscation of most of the actual application code. I'd use a Regex, but the other bug about the call stack seems to prevent broad use of Regex to protect certain patterns.


Below are snippets of the code before obfuscation with more detail on the nature of the problem:

========
**From Webpack part #1**: module assigned as a variable. Webpack provides a string to pull an object method later. Obfuscator leaves these as is, which creates a conflict later with part 4

`/* harmony import */ var _src_menus__WEBPACK_IMPORTED_MODULE_12__ = __webpack_require__(/*! ./src/menus */ "../LIBRARY/src/menus.ts");`


========
**Webpack part #2**: Webpack uses a generic function to return modules from an object containing them as methods (nothing important affected here):

```
function __webpack_require__(moduleId) {
    ...
    /******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
    ...
    }
```


========
**Webpack part #3**: The object methods (obfuscation occurs here and creates problems because the string literal argument above is not obfuscated). The bug occurs when the obfuscator converts from string "../LIBRARY/src/menus.ts" to _0x475d46. Unclear why this string property is converted while most on this same object are not.

```
/******/ 	var __webpack_modules__ = ({
    ...
/***/ "../LIBRARY/EXPORTS.ts":
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {
    "use strict";
    __webpack_require__.r(__webpack_exports__);
    /* harmony export */ __webpack_require__.d(__webpack_exports__, {
    ...

    /***/ "../LIBRARY/src/menus.ts": 
    /*!***********************************!*\
    !*** ../LIBRARY/src/menus.ts ***!
    \***********************************/
    /***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {...
```

**Comment by sanex3339** [comment]
I think the best way is to use `reservedNames` option. I don't want to make exceptions based on the current implementation of some libraries.
Right now webpack uses this approach. Later it may use a different approach.

**Comment by gregbenz** [comment]
Ok, I appreciate you reviewing it.
