### ISSUE TITLE
does the CLI support directory compilation?

### ISSUE THREAD

**Issue by viane** [javascript-obfuscator/javascript-obfuscator#85]
So far I'm using 1 command per file, is the native support for directory obfuscation available? Or I will pull and try to implement this option is that okay?

**Comment by sanex3339** [comment]
PR welcomed! Right way - implement ability to obfuscate array of strings through API (and keep ability to obfuscate single string to prevent breaking change) and directory through CLI-interface.

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/commit/905132d3e340fdb10270f0d073661e22a1a6c652

**Comment by sanex3339** [comment]
Hi. Check new `javascript-obfuscator@0.12.0`!

https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/CHANGELOG.md#v0120
