### ISSUE TITLE
Can `debugProtectionInterval` freeze the browser if i don't open the developer tools?

### ISSUE THREAD

**Issue by allanassis** [javascript-obfuscator/javascript-obfuscator#858]
It is not explicit in the documentation of the `debugProtectionInterval` if it can freeze the browser if i don't open de developer tools as it is clear for the `debugProtection`.

<img width="1125" alt="Captura de Tela 2021-01-13 às 10 28 31" src="https://user-images.githubusercontent.com/23871115/104458398-17518b80-558a-11eb-9a4e-205101576255.png">

**Comment by sanex3339** [comment]
It should freeze the browser only if the developer tools window is opened.
If for some reason it freezes the browser in other cases - please provide a reproducible example.

**Comment by allanassis** [comment]
Thanks!!

**Comment by allanassis** [comment]
Hi @sanex3339, today we were testing one app and we see that when enabling `debugProtection`  and `debugProtectionInterval` the app was freezing in mobile. 

When we disabled these flags, the app starts to work normally on mobile.

Should i open another issue with bug label?

**Comment by sanex3339** [comment]
Can you create a repo with a reproducible example?

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
Closed as inactive. Feel free to create a new issue with more info. Or write here, I'll reopen this issue.
