### ISSUE TITLE
Last update broke smth for csgo cheat javascripting

### ISSUE THREAD

**Issue by l0ccy** [javascript-obfuscator/javascript-obfuscator#859]
This code stuff causes errors now and cant be loaded anymore in csgo onetap cheat

```
function degree_to_radian(degree) {
    return (degree / 180) * Math.PI;
}

function angle_vectors(angle) {
    const sp = Math.sin(degree_to_radian(angle[0]));
    const cp = Math.cos(degree_to_radian(angle[0]));
    const sy = Math.sin(degree_to_radian(angle[1]));
    const cy = Math.cos(degree_to_radian(angle[1]));

    return [cp * cy, cp * sy, -sp];
}
```

**Comment by sanex3339** [comment]
Hi. Please provide a reproducible example

**Comment by l0ccy** [comment]
the obfuscatored code get some "let" in it but the cheat js api cant use it it can only use var its still 5.0 not 5.1 on that api shit they use

**Comment by sanex3339** [comment]
Please provide more info. Obfuscator options and reproducible example

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
Closed as inactive. Feel free to create a new issue with more info. Or write here, I'll reopen this issue.
