### ISSUE TITLE
Maximum call stack size exceeded Error on Android 

### ISSUE THREAD

**Issue by srkgupta** [javascript-obfuscator/javascript-obfuscator#86]
I am trying to integrate this with a cordova application. The app works totally fine when obfuscated and rendered via Chrome on my desktop. However, when I compile and install it on my Android phone, I see this error. It doesn't shows anything else. 

Uncaught RangeError: Maximum call stack size exceeded. 

I believe either this is either not supported on a Hybrid App on Android (or) there is some other issue. 

Any help is appreciated.

**Comment by sanex3339** [comment]
What options you are using?

**Comment by srkgupta** [comment]
I am using the default options:
selfDefending: true, 
disableConsoleOutput: true, 
debugProtection: false, 
log: false, 
mangle: false, 
renameGlobals: false, 
sourceMap: false, 
rotateStringArray: true, 
stringArray: true, 
stringArrayEncoding: false, 
compact: true, 
stringArrayThreshold: 0.75, 
unicodeEscapeSequence: false

I also tried with just this:
selfDefending: true

But still ended up with the same issue.

**Comment by sanex3339** [comment]
try to disable `selfDefending`
