### ISSUE TITLE
What's the tested most stable set of configurations?

### ISSUE THREAD

**Issue by m4heshd** [javascript-obfuscator/javascript-obfuscator#862]
I'll be using this with an Electron project and more specifically on the main process. I'm extremely impressed by this tool and kinda overwhelmed with the configuration. 

I'm finding reported bugs here and there with different combinations of configs. What would be the safest set of configurations to use if I plan to split my main process into multiple files? Which means I need to be able to import and call functions + access variables from those files.

**Comment by sanex3339** [comment]
Use option presets as a start point:
https://github.com/javascript-obfuscator/javascript-obfuscator#optionspreset

**Comment by m4heshd** [comment]
Thank you for the instant response. Just noticed that. Will the `simplify` setting in default preset cause me any issues as mentioned in #860?
Also will the function names between files be an issue?

**Comment by sanex3339** [comment]
#860 should be a rare issue, so try to use it

**Comment by m4heshd** [comment]
Will do. Thank you. Closing the issue.
