### ISSUE TITLE
[CLI] "Reserved Names" are Ignored When "Rename Globals" is Enabled

### ISSUE THREAD

**Issue by iceman2894** [javascript-obfuscator/javascript-obfuscator#868]
Related to the closed javascript-obfuscator/javascript-obfuscator-ui#27 - Still happening for me **@2.10.1**

**CLI**
`test.js --output test.min.js --reserved-names 'a' --rename-globals true --log true`

**test.js**
`var a;`

**test.min.js**
`var a0_0x2ffb6f;`

**CLI Output**

> [javascript-obfuscator-cli] Obfuscating file: test.js... 
 [javascript-obfuscator] Version: 2.10.1_2021-01-01T13:47:46.265Z
[javascript-obfuscator] Obfuscation started... 
[javascript-obfuscator] Random generator seed: 583819106...
[javascript-obfuscator] Code transformation stage: PreparingTransformers...
[javascript-obfuscator] AST transformation stage: Initializing...
[javascript-obfuscator] AST transformation stage: Preparing...
[javascript-obfuscator] AST transformation stage: Converting...
[javascript-obfuscator] AST transformation stage: RenameIdentifiers...
[javascript-obfuscator] AST transformation stage: StringArray...
[javascript-obfuscator] AST transformation stage: Simplifying...
[javascript-obfuscator] AST transformation stage: Finalizing...
[javascript-obfuscator] Code transformation stage: FinalizingTransformers...
[javascript-obfuscator] Obfuscation completed. Total time: 0.035 sec.

**NPM**
`$ npm list -g | grep javascript`
`-- javascript-obfuscator@2.10.1
  +-- @javascript-obfuscator/escodegen@2.1.1
`

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
Closed as inactive. Feel free to create a new issue with more info. Or write here, I'll reopen this issue.

**Comment by iceman2894** [comment]
Still having the same issue up till now, Using CLI with PHP Storm

Screenshot attached with the console and the files


![image](https://user-images.githubusercontent.com/15612446/112875801-f0a0ec80-90c4-11eb-903f-132c57e858ce.png)

**Comment by iceman2894** [comment]
@sanex3339  ping

**Comment by sanex3339** [comment]
Can you provide more info? Reproducible example and other stuff?

**Comment by iceman2894** [comment]
Thanks for re-opening,

I had already attached an example in my reply above, 
bottom part is the command I had used,
top left is the original file
top right is the resulting file

**Comment by sanex3339** [comment]
I can't reproduce.
With your command and source code I got the following output:
```
var a;
```

**Comment by iceman2894** [comment]
Running the command from git bash works correctly

Changing `'a'` to `"a"` in phpStorm fixed the issue

![image](https://user-images.githubusercontent.com/15612446/115137439-6cd48300-a026-11eb-9fdc-714cf878a2a3.png)


Thanks for following up.
