### ISSUE TITLE
Keep process.env.* intact 

### ISSUE THREAD

**Issue by ppoliani** [javascript-obfuscator/javascript-obfuscator#869]
Is there any way that the obfuscator simply ignore all `process.env.*`.

I'm trying the following in the online playground  (https://obfuscator.io/)

`process.env.NODE_ENV`

As a result a get something like this:

`process[_0x3ab67a(0x74)][_0x3ab67a(0x6b)]);`

I used the reservedNames as well but to no avail.

Is there a way to let the obfuscator know that this should stay as it is

**Comment by sanex3339** [comment]
Hi. Why did you want to ignore `process.env`?

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
Closed as old

**Comment by BlackYuzia** [comment]
@sanex3339 maybe he mean what `process[_0x3ab67a(0x74)][_0x3ab67a(0x6b)]);` return undefined?

**Comment by TrejGun** [comment]
@sanex3339

we have the same problem with the process.env and webpack. Webpack replaces process.env.VAR with value and can't do that properly when it obfuscate to `process[_0x3ab67a(0x74)][_0x3ab67a(0x6b)]);`
