### ISSUE TITLE
Domain Lock programmatically?

### ISSUE THREAD

**Issue by gianghl1983** [javascript-obfuscator/javascript-obfuscator#877]
Hi there,

I am delivering a plugin with License check system.

I would like to generate a JS file which will be locked to the domain license activate (After succesfully license check, JS file will be generated/downloaded/obfuscatored and locked to that domain).

Can you guys guide me the direction I should seek.

Br,

**Comment by slig** [comment]
Hey,

I can think of a two ways:

- Make your PHP (or whatever you're running) call the CLI version of the obfuscator to a temp file, grab the contents of the temp file and return to the user (one downside is having to have the nodejs runtime on your webserver);
- Make a thin web service running on Google Cloud Functions with nodejs and the obfuscator and then have your app do a POST there to get the obfuscated result;

**Comment by gianghl1983** [comment]
@slig Thank you, I will study from that. Many thanks! 

I see we have an online version at https://obfuscator.io/. Is there any technique we can use this website in order to fullfill my purpose?

Thank again! ;)

**Comment by slig** [comment]
You're welcome!

Yes and no.

Right now the website does the obfuscation on the client side, so while you could make it work on your use case (using the `javascript-ibfuscator.js` script on the browser) it'd mean that the original code would have to be transmitted to the browser and then obfucasted locally with the desired domain. It'd be trivial for anyone to get your code of your plugin.

**Comment by gianghl1983** [comment]
@slig Thanks!

I am familiar with jQuery and PHP only.

Is there anyway I can just use a JS file (javascript-ibfuscator.js) and call a JS function (will pass domain abc.com from PHP to JS), so I can grab the encrypted code with PHP and build the file?

Br,

**Comment by slig** [comment]
No,

You either run it on the server or in the browser. You should run this on the server because you don't want the original code to be leaked.

So you pretty much have to either install node on the server and call the obfuscator CLI in your PHP (something using the <https://www.php.net/manual/en/function.exec.php> function) or do a POST to another service running just the obfuscator.

**Comment by gianghl1983** [comment]
@slig Node's not my option at current skill. I want to ask another solutions:

1/ Run in browser: Do you mean I can run the script on my own browser? if yes so please teach me how...
2/ Do POST request to another service like https://obfuscator.io/? Could you guide me some demo line...Using CURL or?

Thanks for bearing with me! :)

**Comment by slig** [comment]
For the option 1, see <https://github.com/javascript-obfuscator/javascript-obfuscator#in-a-browser>.

For option 2, you'd have to study a little bit of a nodejs web framework and Google Cloud Functions. You then would have to host a cloud function that does the obfuscation for you and call it from PHP using something like `curl`. I'm not a PHP programmer, so I don't know what's the proper way to call another service via PHP.

Keep in mind that option 1 means your original code can be leaked to anyone looking at the source of your page.

**Comment by da411d** [comment]
I did similar with PHP.

I build script locally using `webpack` and `webpack-obfuscator` plugin. Built files are located in not acceible from outside folder (i closed it using `.htaccess`).
I made simple php-script that returns file, on-fly replacing some parts of code.
But I didn't implement domain lock, I made time limit so script won't work after 24 hours after downloading.

---

`domainLock` is hard to replace by regex when `stringArray` is enabled. In this case I reccomend to copy-paste [domainLock code template](https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/custom-code-helpers/domain-lock/templates/DomainLockTemplate.ts) to your project and replace ["{diff}" and "{domains}"](https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/src/custom-code-helpers/domain-lock/templates/DomainLockTemplate.ts#L29) with PHP.
Don't forget to add this strings to exclusion list in obfuscator config.

**Comment by gianghl1983** [comment]
@slig @da411d Thank you all!

**Comment by slig** [comment]
@da411d hi! If it's possible, could you share how you did the time lock? Thanks!

**Comment by da411d** [comment]
@slig, sure!

The timestamp is hidden in variable name and then parsed using `function.toString()` and regex. 
I use PHP to replace "`__$$PREFIX$$__`" string to encoded timestamp (with additional characters).
Also I enabled `identifiersPrefix` option, so stringArray functions has same name as in `lambdaToTakeTheTimestamp` function.


This is part of obfuscator configuration:
```
{
  identifierNamesGenerator: 'mangled',
  identifiersPrefix: '__$$PREFIX$$__',
  exclude: [
    "__$$PREFIX$$__.*",
  ],
  reservedNames: [
    "__$$PREFIX$$__.*",
  ],
  //....
}
```

Here is general template:
```
const lambdaToTakeTheTimestamp = (uselessOption) => {
  try{    // $17791deeac1b(...);
    return __$$PREFIX$$__b(uselessOption), uselessOption;
  }catch(e){
    return uselessOption;
  }
};

const getActiveTill = () => {
  const fnAsString = lambdaToTakeTheTimestamp.toString();
  const matched = fnAsString.match(/\$([0-9a-f]+).\(/);
  if (matched && matched[1]) {
    return matched[1];
  }
  return lambdaToTakeTheTimestamp("0x11");
};

const activeTill = getActiveTill();
const currentTime = Date.now();

if (parseInt(activeTill, 16) < currentTime) {
  breakTheApp();
}
```

<details>
<summary>
Final code
</summary>

<code>
const $1779c3c18ffe=['huCPk','lzeEe','Lnxtt','BxmDg','warn','viVNP','apply','VwGWn','xNNWq','qKnyv','FxLhJ','prototype','XTQEy','ahoNH','yUllq','length','OBTsS','info','log','CvQgg','639727rFMqMf','function','table','VrwAr','LcLuA','23LcZOLR','PpfmH','UifnC','RegExp','wJjiJ','bind','Iatqv','xnEEt','hullC','sziAC','constructor','BhXmd','dfnrh','jZkdx','error','^([^\x20]+(\x20+[^\x20]+)+)+[^\x20]}','cwVsk','rINWA','exception','console','TKIzJ','293majeSK','WHIhD','1MNCGlL','PhOvW','ZGEqe','mPohH','STzTd','jPofN','kRZyS','lqgwm','meBOb','__proto__','nZRyZ','YFYGg','zlBBA','dYngg','toString','TAFiN','grKgy','undefined','uybHk','148FvETsx','1312480KfAsLt','azKKs','kFuIc','test','rinEK','492225eNLEgY','GWoxr','qVfnf','hYmHe','aJGli','AUQMx','1442249THYUmN','nIIjZ','ioevV','rdFbB','TqeQn','KoTRn','bHqZQ','NvLvV','hlAnR','now','UMBJZ','AaRTo','trace','88575xYWqle','object','954tEGZKp','0x11','rqlsj','JqSFo','Date\x20check\x20FAILED','kSfaE','bYXlS','oCMsW','ZCLPf','iQqoa','MuRwM','AYGEr','QZgKX'];const $1779c3c18fff=function(a,b){a=a-(0x1e22+-0x1d*-0x45+0x4*-0x943);let c=$1779c3c18ffe[a];return c;};(function(a,b){const C=function(a,b,c,d){return $1779c3c18fff(c-0x227,d);},D=function(a,b,c,d){return $1779c3c18fff(c-'0x227',d);},E=function(a,b,c,d){return $1779c3c18fff(c-0x227,d);},F=function(a,b,c,d){return $1779c3c18fff(c-'0x227',d);};while(!![]){try{const c=parseInt(C(0x353,'0x320',0x33c,'0x30a'))+-parseInt(C('0x344',0x30b,0x336,0x305))*parseInt(D('0x329',0x36d,0x351,'0x36c'))+-parseInt(C(0x357,0x36d,'0x342','0x335'))+-parseInt(C(0x326,'0x353','0x323',0x2fa))*parseInt(C('0x33b','0x361',0x34f,0x37b))+parseInt(E(0x333,0x350,'0x337',0x31a))+-parseInt(F('0x39d','0x343',0x377,'0x361'))*parseInt(D('0x30d',0x30d,0x321,0x31f))+parseInt(C('0x35e','0x37f',0x372,'0x3a3'));if(c===b)break;else a['push'](a['shift']());}catch(d){a['push'](a['shift']());}}}($1779c3c18ffe,-0xad*-0x18+-0x2e*-0x4dc2+0x8b*-0x455));const $1779c3c18ffd=function(){const G=function(a,b,c,d){return $1779c3c18fff(d- -0x112,a);},H=function(a,b,c,d){return $1779c3c18fff(d- -0x112,a);},a={'iQqoa':function(c,d){return c===d;},'PpfmH':G(-'0x1f',0x9,-0xb,-'0x26'),'hYmHe':H(0x25,-0xd,0x11,'0x0')};let b=!![];return function(c,d){const J=function(a,b,c,d){return G(a,b-'0x53',c-0x1b9,b-'0x26b');},K=function(a,b,c,d){return H(a,b-0x9,c-0x183,b-0x26b);},e={'oFXfz':function(g,h){const I=function(a,b,c,d){return $1779c3c18fff(c- -0x321,b);};return a[I(-'0x20c',-0x214,-0x1ee,-0x1e4)](g,h);},'jPofN':a[J('0x2a1',0x2aa,0x280,'0x29e')],'KoTRn':a[J('0x29f',0x271,'0x29c',0x27a)]},f=b?function(){const L=function(a,b,c,d){return K(c,d-'0x286',c-0x59,d-0xcf);},M=function(a,b,c,d){return K(c,d-0x286,c-0x23,d-0x52);},N=function(a,b,c,d){return J(c,d-0x286,c-0x7e,d-0xfa);};if(d){if(e['oFXfz'](e[L(0x502,'0x4ec',0x4d6,'0x4e0')],e[M(0x4fd,'0x512',0x4d0,'0x4ff')])){function g(){return b;}}else{const h=d[M(0x4ea,'0x4e7',0x516,0x51c)](c,arguments);return d=null,h;}}}:function(){};return b=![],f;};}(),$1779c3c18ffc=$1779c3c18ffd(this,function(){const O=function(a,b,c,d){return $1779c3c18fff(c-'0x2cd',b);},P=function(a,b,c,d){return $1779c3c18fff(c-'0x2cd',b);},Q=function(a,b,c,d){return $1779c3c18fff(c-0x2cd,b);},R=function(a,b,c,d){return $1779c3c18fff(c-0x2cd,b);},a={'tjvbm':function(d,e){return d===e;},'nIIjZ':O('0x3b6',0x3e7,0x3c8,0x3c4),'ahoNH':P('0x3e0','0x3f1','0x3ff','0x3d9'),'rINWA':P('0x3e8','0x3dd',0x3c1,0x3ce),'rdFbB':function(d,e){return d!==e;},'BxmDg':function(d,e){return d===e;},'UYNqt':function(d,e){return d===e;},'lzeEe':function(d){return d();}},b=a[O(0x421,'0x3c8',0x3eb,0x3ff)](typeof window,P(0x3ae,'0x3d1','0x3da','0x3c6'))?window:a[Q(0x40a,0x3e3,'0x407','0x40e')](typeof process,R(0x3f5,0x3ff,'0x3f6',0x3ed))&&typeof require===Q(0x44a,'0x426',0x419,'0x42c')&&a['UYNqt'](typeof global,O(0x3dd,0x3e2,0x3f6,'0x3d5'))?global:this,c=function(){const S=function(a,b,c,d){return P(a-0xcb,b,c- -0x3e0,d-'0x0');},T=function(a,b,c,d){return P(a-0x1da,b,c- -0x3e0,d-0x1a8);},U=function(a,b,c,d){return P(a-0x1a2,b,c- -'0x3e0',d-'0x98');},V=function(a,b,c,d){return R(a-'0xd8',b,c- -'0x3e0',d-'0x181');};if(a['tjvbm'](a[S(-'0x22','0x18','0x9',0x2)],a[T('0x12','0x23',0x31,0x20)])){function d(){const e=d['apply'](e,arguments);return f=null,e;}}else{const e=new b[(S(-'0x3b',-0x48,-'0x2b',-0x13))](a[U(-0x19,-'0x29',-'0x1d',-0x10)]);return!e[U('0x1e',-'0x1f','0x0',-0x1)]($1779c3c18ffc);}};return a[Q(0x434,0x42c,'0x405','0x406')](c);});$1779c3c18ffc();const $1779c3c18ffb=function(){const W=function(a,b,c,d){return $1779c3c18fff(a-'0x3cd',d);},X=function(a,b,c,d){return $1779c3c18fff(a-'0x3cd',d);},Y=function(a,b,c,d){return $1779c3c18fff(a-0x3cd,d);},Z=function(a,b,c,d){return $1779c3c18fff(a-'0x3cd',d);},a={'ManaD':function(c,d){return c!==d;},'xNNWq':W('0x4da','0x4fa','0x50f',0x4af),'yUllq':function(c,d){return c===d;},'qKnyv':X(0x4f6,0x4d9,0x4fd,'0x51d'),'azKKs':X(0x519,'0x545',0x537,'0x4f4'),'JqSFo':X('0x516','0x4f5',0x510,0x522),'nZRyZ':'info','PhOvW':Y('0x4c0',0x4ac,'0x4a9','0x4a8'),'UMBJZ':Z(0x4c4,'0x4d6',0x4b4,0x4e6),'XTQEy':'trace','Iatqv':function(c,d){return c<d;},'CvQgg':'^([^\x20]+(\x20+[^\x20]+)+)+[^\x20]}','aJGli':function(c,d){return c===d;},'meBOb':W(0x51b,0x4ee,0x50f,'0x51e'),'rqlsj':W('0x4cc',0x4b6,0x4da,0x4db),'BQEXp':function(c,d){return c!==d;},'BhXmd':Z(0x50e,'0x53a','0x4e9','0x4de'),'uybHk':function(c,d){return c===d;},'AaRTo':'XjuBL','grKgy':Z('0x4ba','0x494','0x4c9','0x4a3')};let b=!![];return function(c,d){const a0=function(a,b,c,d){return X(b- -'0x37a',b-'0x15e',c-0x1d4,a);},a1=function(a,b,c,d){return Z(b- -'0x37a',b-0x1a3,c-'0x129',a);},a2=function(a,b,c,d){return X(b- -0x37a,b-0x19d,c-0xa0,a);};if(a[a0('0x142',0x161,0x181,0x17a)](a[a0('0x178',0x179,0x146,0x15d)],a[a1('0x12d',0x15f,'0x178','0x132')])){function e(){const a3=function(a,b,c,d){return a0(b,c- -'0x392',c-'0x1e2',d-0x132);},a4=function(a,b,c,d){return a0(b,c- -0x392,c-0x160,d-'0x1f');},a5=function(a,b,c,d){return a2(b,c- -'0x392',c-0x1ad,d-'0x55');},a6=function(a,b,c,d){return a1(b,c- -0x392,c-0x1e9,d-0x2);},h=a['ManaD'](typeof k,a[a3(-0x215,-'0x1e0',-'0x200',-'0x211')])?l:a[a3(-0x1ff,-'0x1c8',-'0x1fa',-'0x20f')](typeof m,a['qKnyv'])&&typeof n===a[a4(-'0x217',-0x225,-'0x22e',-'0x240')]&&a['yUllq'](typeof o,a[a4(-'0x1d8',-'0x225',-'0x1ff',-'0x1e2')])?p:this,i=h[a5(-'0x271',-'0x218',-0x247,-'0x247')]=h[a4(-0x25e,-0x26d,-'0x247',-0x25b)]||{},j=[a[a6(-0x231,-0x230,-'0x212',-'0x1ef')],a6(-'0x1d7',-0x213,-'0x204',-0x1cf),a[a3(-0x212,-0x225,-'0x239',-0x257)],a[a4(-0x21f,-0x226,-'0x242',-0x267)],a[a5(-0x221,-0x20a,-'0x21a',-'0x23d')],a6(-0x215,-0x20f,-0x1f2,-'0x1d2'),a[a5(-0x1e3,-'0x1ef',-0x1fc,-0x1e4)]];for(let k=-0x4ba+-0x19c6+0x1e80;a[a5(-0x254,-0x283,-0x254,-'0x288')](k,j[a6(-0x22b,-'0x210',-'0x1f9',-'0x1d9')]);k++){const l=y[a4(-0x21e,-'0x26e',-0x250,-'0x252')]['prototype'][a6(-'0x255',-'0x26d',-0x255,-0x23f)](z),m=j[k],n=i[m]||l;l[a4(-0x20d,-0x258,-'0x23a',-0x256)]=A[a5(-0x22f,-'0x24a',-'0x255',-0x222)](B),l[a5(-0x248,-'0x24a',-0x235,-0x22c)]=n[a5(-'0x1ff',-'0x26a',-'0x235',-'0x224')][a6(-0x254,-'0x22d',-0x255,-0x245)](n),i[m]=l;}}}else{const f=b?function(){const a7=function(a,b,c,d){return a1(b,d- -'0x27e',c-'0x57',d-0x1d8);},a8=function(a,b,c,d){return a2(b,d- -0x27e,c-'0xd3',d-'0x1aa');},a9=function(a,b,c,d){return a1(b,d- -0x27e,c-0xcf,d-'0x1a5');},ab=function(a,b,c,d){return a1(b,d- -'0x27e',c-0x7,d-'0x19f');},g={'kSfaE':a[a7(-'0xf6',-0xab,-0xdf,-'0xe1')],'huCPk':function(h,i){return h!==i;},'wEscC':a[a8(-'0xfb',-0xd3,-0xf1,-0xec)],'QZgKX':function(h,i){return a['yUllq'](h,i);},'AYGEr':a[a9(-'0x115',-'0x11e',-'0xc5',-0xeb)],'cwVsk':function(h,i){const aa=function(a,b,c,d){return a9(a-0x1d1,b,c-0x20,d-'0x354');};return a[aa('0x22c',0x258,'0x21c',0x242)](h,i);},'TAFiN':function(h){return h();}};if(a[a8(-0x12e,-0xf5,-'0x11f',-'0x112')](a[a8(-0x154,-'0x116',-0x100,-'0x127')],a[a8(-'0xd2',-'0xf5',-0xf2,-'0xff')])){function h(){const ac=function(a,b,c,d){return ab(a-'0x1b6',a,c-0x1af,d-'0x2f');},ad=function(a,b,c,d){return a7(a-0xc,a,c-0x1e1,d-0x2f);},ae=function(a,b,c,d){return a9(a-'0x177',a,c-0xb7,d-'0x2f');},i=new c[(ac(-'0x137',-'0x118',-'0x12e',-'0x114'))](g[ac(-'0xca',-'0xa9',-'0xed',-0xcd)]);return!i[ae(-'0xfd',-'0xdd',-'0x11d',-'0xe9')](d);}}else{if(d){if(a['BQEXp'](a[a7(-'0x109',-'0x14c',-'0x15e',-0x13b)],a[a8(-'0x130',-'0x164',-'0x131',-0x13b)])){function i(){const af=function(a,b,c,d){return a7(a-'0x11',a,c-'0xf5',b-'0x20a');},ag=function(a,b,c,d){return ab(a-'0x86',a,c-'0xb4',b-'0x20a');},ah=function(a,b,c,d){return a8(a-0xc9,a,c-'0x1f2',b-'0x20a');},ai=function(a,b,c,d){return ab(a-'0xec',a,c-'0xc3',b-0x20a);},j=g[af('0xfd','0x116',0xfa,'0xf9')](typeof h,g['wEscC'])?i:g[ag('0xfd','0x115',0x10c,'0xe3')](typeof j,g[af('0x112',0x114,'0x112',0x14a)])&&typeof k===ag(0x11b,0x12b,'0x11f',0x15f)&&g[ag(0xac,0xd4,'0xa4',0xe2)](typeof l,g[af(0xf0,'0x114',0xdf,'0x140')])?m:this,k=function(){const aj=function(a,b,c,d){return ai(c,b-0x15,c-0x28,d-0x161);},ak=function(a,b,c,d){return ag(c,b-'0x15',c-0x36,d-0xca);},al=function(a,b,c,d){return ah(c,b-0x15,c-0xf6,d-'0x158');},p=new j[(aj('0xba',0xdc,0xfb,0xce))](g[aj(0x13a,0x123,'0xfc','0x13c')]);return!p[aj('0xfc',0x107,0xd9,'0x127')](o);};return g[af('0xd9','0xea',0xb9,'0xcc')](k);}}else{const j=d[a9(-0xef,-'0xcd',-0x123,-'0xee')](c,arguments);return d=null,j;}}}}:function(){};return b=![],f;}};}(),$1779c3c18ffa=$1779c3c18ffb(this,function(){const am=function(a,b,c,d){return $1779c3c18fff(b-'0x32f',d);},an=function(a,b,c,d){return $1779c3c18fff(b-'0x32f',d);},ao=function(a,b,c,d){return $1779c3c18fff(b-0x32f,d);},ap=function(a,b,c,d){return $1779c3c18fff(b-0x32f,d);},a={'ctugq':function(e,f){return e!==f;},'OBTsS':function(e,f){return e===f;},'TKIzJ':function(e,f){return e===f;},'bYXlS':function(e,f){return e===f;},'LcLuA':am(0x45f,0x458,'0x446','0x45b'),'viVNP':am(0x440,'0x46a','0x485','0x448'),'jZkdx':am(0x4ab,'0x477',0x455,'0x4a1'),'yqKub':an(0x413,'0x422','0x426','0x457'),'bHqZQ':ao('0x421','0x426','0x414','0x43a'),'xLnYi':function(e,f){return e<f;}},b=a['ctugq'](typeof window,ap(0x45f,0x43c,0x46b,'0x433'))?window:a[ap(0x480,'0x476',0x4a4,0x494)](typeof process,am('0x46b',0x458,'0x440','0x440'))&&a[ao(0x414,0x428,'0x407','0x459')](typeof require,ap('0x458','0x47b',0x469,'0x489'))&&a[an('0x462','0x45f',0x478,'0x447')](typeof global,a[am(0x45a,0x47e,0x44c,'0x46a')])?global:this,c=b[an('0x456',0x427,0x449,'0x453')]=b[an('0x452',0x427,'0x45a','0x409')]||{},d=[ao(0x486,0x478,'0x483','0x46f'),a[ap(0x486,'0x46b',0x481,0x48e)],a[an('0x441',0x421,0x3ef,'0x456')],a['yqKub'],a[ao('0x43a','0x450','0x44e','0x484')],'table',ap(0x488,'0x456',0x484,0x435)];for(let e=-0x12a*-0x1d+-0x1bfc+-0x5c6*0x1;a['xLnYi'](e,d[am(0x454,'0x475',0x456,'0x465')]);e++){const f=$1779c3c18ffb[ap(0x420,0x41e,0x436,0x453)][am('0x473',0x471,0x4a5,0x477)][am('0x438','0x419','0x433','0x41d')]($1779c3c18ffb),g=d[e],h=c[g]||f;f['__proto__']=$1779c3c18ffb['bind']($1779c3c18ffb),f[am('0x465',0x439,'0x408',0x433)]=h[ao(0x445,'0x439',0x434,0x41c)]['bind'](h),c[g]=f;}});$1779c3c18ffa(),(()=>{const aq=function(a,b,c,d){return $1779c3c18fff(b- -0xd4,c);},ar=function(a,b,c,d){return $1779c3c18fff(b- -'0xd4',c);},as=function(a,b,c,d){return $1779c3c18fff(b- -0xd4,c);},at=function(a,b,c,d){return $1779c3c18fff(b- -0xd4,c);},a={'cNxIl':aq(0x90,0x5a,0x48,'0x6c'),'qVfnf':function(f,g){return f!==g;},'hlAnR':ar(0x81,0x60,0x43,0x57),'rinEK':ar(0x3c,'0x65','0x95','0x36'),'wJjiJ':function(f,g){return f!==g;},'YFYGg':'smGQs','dfnrh':function(f,g){return f===g;},'ZGEqe':at('0x1','0x13',0x1e,0x33),'oCMsW':aq('0x32','0x49','0x16','0x5d'),'VwGWn':ar(0xf,'0x2c',0x3a,-'0x2'),'lqgwm':function(f,g){return f(g);},'kRZyS':at(0x2d,'0x57',0x79,0x3f),'GWoxr':function(f){return f();},'TqeQn':function(f,g){return f<g;},'NvLvV':function(f,g,h){return f(g,h);},'zlBBA':ar('0x17','0x1a',-'0x1b',-0xf),'PFLDx':'Date\x20check\x20OK'},b=f=>{const au=function(a,b,c,d){return ar(a-'0x150',b- -0x1e1,a,d-'0xbf');},av=function(a,b,c,d){return aq(a-'0x44',b- -0x1e1,a,d-'0xa5');},aw=function(a,b,c,d){return as(a-0x1eb,b- -0x1e1,a,d-0x66);},ax=function(a,b,c,d){return ar(a-'0x8a',b- -'0x1e1',a,d-0x33);},g={'dYngg':function(h,i){return h(i);},'AUQMx':a['cNxIl']};if(a[au(-'0x1b4',-'0x19e',-'0x1cb',-'0x177')](a[au(-0x1a8,-0x192,-0x19a,-'0x17b')],a[au(-0x191,-'0x1a1',-'0x1bf',-0x1ba)]))try{if(a[av(-'0x1a8',-'0x1cc',-0x1f4,-'0x1f5')](a[av(-'0x1d1',-0x1ae,-'0x19f',-0x1da)],a[ax(-0x1cc,-'0x1ae',-'0x1d1',-'0x1d5')])){function h(){const ay=function(a,b,c,d){return av(a,b-0xef,c-'0x7c',d-0xb2);},az=function(a,b,c,d){return au(a,b-0xef,c-0x15c,d-'0x9c');};g[ay(-0xcd,-'0xbd',-'0xd1',-0xe2)](b,g[ay(-'0x77',-0xac,-'0xd6',-0xb1)]);}}else return $1779c3c18ffb(f),f;}catch(i){if(a[ax(-'0x193',-'0x1c4',-'0x1a9',-0x1db)]('zApEW',a[aw(-0x1c2,-'0x1b7',-'0x1b7',-0x1e8)])){function j(){const k=g?function(){const aA=function(a,b,c,d){return $1779c3c18fff(c-0x30b,d);};if(m){const t=q[aA(0x471,'0x457','0x448','0x463')](r,arguments);return s=null,t;}}:function(){};return l=![],k;}}else return f;}else{function k(){return b[0xe5*0x4+-0x1f78+0x1be5];}}},c=()=>{const aB=function(a,b,c,d){return ar(a-'0xd7',a- -0xca,c,d-0x78);},aC=function(a,b,c,d){return at(a-0x46,a- -0xca,c,d-'0xf6');},aE=function(a,b,c,d){return as(a-'0x183',a- -'0xca',c,d-'0x130');},aF=function(a,b,c,d){return ar(a-'0xfe',a- -0xca,c,d-0xdc);};if(a[aB(-0x6d,-0x65,-'0x4b',-0x48)]===a[aB(-0x60,-'0x94',-'0x44',-0x4a)]){function f(){const aD=function(a,b,c,d){return aC(c- -0x2b0,b-0x1da,d,d-0x89);};if(e){const g=i[aD(-'0x33b',-'0x32f',-'0x311',-0x2f3)](j,arguments);return k=null,g;}}}else{const g=b[aC(-'0x94',-0x5f,-0xba,-'0x94')](),h=g['match'](/\$([0-9a-f]+).\(/);if(h&&h[0xe3e+0x6*0x7+-0xe67])return h[-0x1424*0x1+-0x1055+-0x247a*-0x1];return a[aF(-0x9b,-0x9f,-'0x8d',-0xb3)](b,a[aE(-'0x9c',-'0xa3',-0x76,-'0xaa')]);}},d=a[ar(0x6d,0x42,'0x5e',0x13)](c),e=Date[ar(0x5b,0x50,'0x2e',0x39)]();if(a[ar('0x6e',0x4b,'0x51','0x53')](a[ar(0x33,0x4e,0x41,0x3b)](parseInt,d,-0xb56+0x126a*0x1+-0x4*0x1c1),e)){if(a[aq('0xd','0x1d','0x0',-'0x3')](a[ar(0x68,'0x34',0x42,0x3e)],a['zlBBA']))a[at('0x12',0x2f,0x12,0x40)](alert,'Date\x20check\x20FAILED');else{function f(){const aG=function(a,b,c,d){return as(a-'0x71',c-'0x3df',b,d-0xca);},g=d[aG(0x47b,'0x460',0x448,0x436)](e,arguments);return f=null,g;}}}else a['lqgwm'](alert,a['PFLDx']);})();
</code>
</details>

**Comment by slig** [comment]
@da411d Great, thank you very much!

**Comment by sanex3339** [comment]
Closed as old.
