### ISSUE TITLE
Is there a way to exclude a function from obfuscation?  

### ISSUE THREAD

**Issue by Kukunin** [javascript-obfuscator/javascript-obfuscator#88]
In one of my project we have `WorkerFn` function that executes within WebWorker environment. 
We create it in this way:

```js
function WorkerFn(root) {
  //here is worker code
}

url = URL.createObjectURL(
  new Blob([ '(' + WorkerFn.toString() + ')(this)' ], { type: 'text/javascript' })
);

ww = new Worker(url);
```

This is only place that breaks after obfuscation, because this function executes in clean environment (WebWorker) and doesn't have global function to resolve names. 

I know the workaround to add every name into `reservedNames` array, but it has serious downsides:

* it prevents names from obfuscations in other places of script
* it is tedious process and breaks every time source code is changed

Is there good solution to avoid obfuscation of this chunk?

**Comment by sanex3339** [comment]
Please, check `reservedNames` option.

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator#reservednames

**Comment by Kukunin** [comment]
It seems I don't understand this option well. 

I've added `reservedNames: ['WorkerFn']`, but function's content is still obfuscated. 
The only difference that now I can find the function definition without obfuscated function name.

**Comment by sanex3339** [comment]
If you want to exclude whole function content from obfuscation - add all identifiers inside this function to `reservedNames` array.

**Comment by sanex3339** [comment]
But i should add feature to ignore code between contextual comments from obfuscation.

Like
```
/* javascript-obfuscator:disable */ - Disable obfuscation for the rest of the file
/* javascript-obfuscator:enable */ - Enable obfuscation for the rest of the file

**Comment by sanex3339** [comment]
Base functional already in `dev` branch, will be out with `0.12.0` release.

```
/* javascript-obfuscator:disable */ - Disable obfuscation for the rest of the file
/* javascript-obfuscator:enable */ - Enable obfuscation for the rest of the file
```

With this feature i had 2 ways: 
* analyze source code as string and don't obfuscate parts between conditional comments 
* analyze AST-tree and ignore nodes betwen conditional comments

First way easier to implement but contains many problems like:

```
// source code
var foo = 1;
/* javascript-obfuscator:disable */ 
var bar = 2;
console.log(foo);
/* javascript-obfuscator:enable */ 


// obfuscated code 
var _0xabc123 = 1;
var bar= 2;
console.log(foo); // this line completely ignored from obfuscation, so it will throw error
```

Second way was harder to implement but it will ignore nodes in AST-tree from obfuscation only for direct transformations. All side effect will applied to nodes:

```
// source code
var foo = 1;
/* javascript-obfuscator:disable */ 
var bar = 2;
console.log(foo);
/* javascript-obfuscator:enable */ 


// obfuscated code 
var _0xabc123 = 1;
var bar= 2;
console.log(_0xabc123); // this line completely ignored from obfuscation, but it will correctly obfuscated because this is side-effect transformation of variable declared above conditional comment.
```

**Comment by sanex3339** [comment]
Hi. Check new `javascript-obfuscator@0.12.0`!

https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/CHANGELOG.md#v0120

**Comment by Kukunin** [comment]
Amazing, thanks. You do great job!

**Comment by apetrock** [comment]
I'm running into this issue as well.  Instead of excluding obfuscation, could you perhaps create a localized obfuscations for situations where the scope is local, such as worker environments, is this possible?

/* javascript-obfuscator:local_start */ - Disable obfuscation for the rest of the file
/* javascript-obfuscator:local_end */ - Enable obfuscation for the rest of the file

Thanks!

**Comment by AlenToma** [comment]
using `/* javascript-obfuscator:disable */` not working for me.

I have some expression function where I extract the fieldName from them eg `Column(x=> x.name)` those are rewritten for which I do not want them to be as I am after the field `name`
tried to add `/* javascript-obfuscator:disable */` on top of the file but its not working.

**Comment by 583** [comment]
Did you finally solve this problem? I am also a web worker. I used /* javascript-obfuscator:disable */ but it was invalid.
