### ISSUE TITLE
Why do you mention its impossible to recover the source code back?

### ISSUE THREAD

**Issue by oddmario** [javascript-obfuscator/javascript-obfuscator#883]
Hello,

I have read it multiple times on the online version (obfuscator.io), you keep mentioning that its impossible to recover the source code again.

Is it really impossible?
Also since this project is open-source, doesn't this make it easier to reverse engineer a code protected with this?

Kind regards.

**Comment by sanex3339** [comment]
Hi. It's possible to partially deobfuscate obfuscated code, especially - place all strings back to their original places.
Currently, deobfuscators (that I know) can't deobfuscate a code obfuscated with the latest `javascript-obfuscator` version.
But things may change in the future.
