### ISSUE TITLE
Support for Webpack's topLevelAwait experiment?

### ISSUE THREAD

**Issue by Slapbox** [javascript-obfuscator/javascript-obfuscator#884]
Unfortunately the obfuscator implodes when it reaches a [top level await](https://webpack.js.org/configuration/experiments/#experiments), when using the obfuscator-loader.

If I transpile the code and then obfuscate with javascript-obfuscator (not the Webpack version) it works fine.

Any thoughts?

**Comment by sanex3339** [comment]
Transferred to the main repo

**Comment by sanex3339** [comment]
Will release it in 1 hour

**Comment by sanex3339** [comment]
Released as `javascript-obfuscator@2.10.6`

**Comment by Slapbox** [comment]
Wow that was so fast! Thanks @sanex3339!
