### ISSUE TITLE
Error with node-mysql + webpack

### ISSUE THREAD

**Issue by stefanoriva-xs** [javascript-obfuscator/javascript-obfuscator#886]
If i bundle my node app, the only error i keep reciving is this from the mysql module

Error: Received packet in the wrong sequence.
code : 'PROTOCOL_INCORRECT_PACKET_SEQUENCE'

I've looked around but nobody seems to have this issue, which is strange but whatever.
If i bundle my app with just Webpack with mangle : false on TeaserPlugin, it works fine, as soon as i add the webpack-ofuscator plugin i start getting errors only on this specific module.

Is there anything i can do about this?

**Comment by sanex3339** [comment]
Hi. Please provide more details like obfuscator options and others.
If possible - try to create a repo with a reproducible example.

**Comment by stefanoriva-xs** [comment]
I will create an example repo of which issue i'm facing asap

**Comment by sanex3339** [comment]
Hi. Any new info?

**Comment by sanex3339** [comment]
Closed as old
