### ISSUE TITLE
[Feature Request] Rename Properties Auto Rewriter

### ISSUE THREAD

**Issue by BlackYuzia** [javascript-obfuscator/javascript-obfuscator#892]
This issue is a "fix suggestion" for #891 

How I describe in issue #891 I have bug with exported/imported data/modules (objects/classes etc) what have any props (keys) .

My suggestion is something like:

Original code
```js
const object = require("class.js") // return class with {active: true} prop.
object.active // true
```
Obfuscated code
```js
const object = require("class.js") // return class with {active: true} prop.
// This, how I write, should execute in runtime, maybe we can run this in handlerFunction or on pre/post obfuscation start?
for (const key of object) {
 const value = object[key];
 object.0xfff = value; // set new keyname for value
 delete object[key];   // delete old key
}
object.0xfff // true
```

Actualy, this is only prototype. I think we can fail with private properties, methods and etc.

**Comment by sanex3339** [comment]
https://github.com/javascript-obfuscator/javascript-obfuscator/issues/629
