### ISSUE TITLE
[Question] Main & Modules Sync

### ISSUE THREAD

**Issue by BlackYuzia** [javascript-obfuscator/javascript-obfuscator#893]
One more question about #891 

If we have next code:
```js
// index.js
const module = require('module.js') // return object => {active: true}
console.log(module) // return {active: true}

// module.js
module.exports = {active: true} 
```
then I obfuscated this but I get next:
```js
const _0x1= require('module.js') // return object => {active: true}
console.log(_0x1) // return {active: true}, this object didn't obfuscate!
```

what if we try obfuscate module.js?
```js
// index.js
const _0x1= require('module.obfuscated.js') // return object => { _0x1: true}
console.log(_0x1) // return {0x01: true}, this object is obfuscate!
// But we have bug:
_0x1.active // undefined
```

if we obfuscate module.js and index.js?
```js
// index.obfuscated.js
const _0x1= require('module.obfuscated.js') // return object => { _0x1: true}
console.log(_0x1) // return {0x01: true}, this object is obfuscate!
// But we have bug:
_0x1._0xf // undefined

// Here we go ...
// We suck because index.js obfuscator ... сцук, инглиш я забыл потому допишу дальше на русском. Что я имел ввиду, в этот моменте в index.js мы не можем получить значение пропа active из module.obfuscated.js по причине того, что мы не знаем первоначальное название пропа (до его обфускации). Следовательно, мы всегда будем получать undefined в кач-ве ответа. СЛЕДОВАТЕЛЬНО. Нам нужно запускать обфускацию как index.js так и всех модулей которые вызываются вместе с ним (в данном случае module.js) после чего сохранять старый и новый ключ и пихать везде где был старый (active) новый (_0x999 например) ключ. После чего мы сможем обфусцировать все. 
```
Сорян, я забыл английский. Позовите учителя с B1 по инглишy пусть переведет.
Ну и тут главный вопрос, как это все реализовать? Как не поломать модули которые будут вызываться внутри index.js из за обфускации их кода? Ну и + сюда еще можно плюсануть информацию и функционал из #892 

That all. My mind is too heavy. I activate my lazy mode. 

PS: Моя мечта иметь обфускацию которая не ломает код даже если все функции включены :eyes:
PSS: Писал все по частям, потому местами мог потерять нить...

![image](https://user-images.githubusercontent.com/25010528/109669364-b05c5600-7b7a-11eb-8160-02edcf87ad11.png)

**Comment by da411d** [comment]
Тебя в гугл транслейте забанили?😂

**Comment by BlackYuzia** [comment]
Да я подумал и так ясно будет че я написал. А пихать это в гуглтранслейт себе дороже. Потом иди еще вспомни что ты там хотел написать. :eyes:

**Comment by da411d** [comment]
Блин, изза тебя я разленился писать на английском.

Кароч, у меня идея как это пофиксить. Я бы сделал общий кеш `originalName => obfuscatedName`. Минус этого подхода - повсюду названия будут одинаковыми. То есть даже в других местах кода для если было где-то поле `.value`, то оно будет `._0xfa` повсюду. Это упростит деобфускацию, но и сделает код стабильнее, думаю.

**Comment by BlackYuzia** [comment]
Ну, а вариантов там не много так-то.
Это же ссылка на объект по сути всегда. 
Что значит мы или делаем везде одинаковые пропы (аля` ._0xfa`) или сосем шлен в виде `undefined`.
Вариантов не много.

**Comment by sanex3339** [comment]
@BlackYuzia please use english language here. 
Next time I'll remove all your issues with russian language.

**Comment by sanex3339** [comment]
Seems this issue is a duplicate of https://github.com/javascript-obfuscator/javascript-obfuscator/issues/629
