### ISSUE TITLE
obfuscate() not a Function

### ISSUE THREAD

**Issue by wwderw** [javascript-obfuscator/javascript-obfuscator#895]
I don't know if it's because I'm trying to use Deno instead of Node that this is coming up.

I grabbed the project through the skypack cdn and when I go to do the obfuscate() portion, it tells me that it isn't a function.  Is this due to the fact that I'm using Deno instead of Node or is there another way I should be going about this if trying to use Deno?

**Comment by sanex3339** [comment]
Obfuscator has never tested with `deno` so i can't even suggest what is the problem here.
