### ISSUE TITLE
Obfuscator doesn't work with JS classes

### ISSUE THREAD

**Issue by Pryanishnik** [javascript-obfuscator/javascript-obfuscator#896]
Obfuscator doesn't work with JS classes

## Expected Behavior
Get obfuscated js file for JS class

## Current Behavior
If we have a class with fields, js obfuscator crashes on the line with the first field
with the following exception
```
node_modules\javascript-obfuscator\dist\webpack:\javascript-obfuscator\src\ASTParserFacade.ts:67
        throw new Error(`ERROR at line ${position.line}: ${errorMessage}\n${formattedPointer} ${formattedCodeSlice}`);
              ^
Error: ERROR at line 6: Unexpected token (6:8)
> ...data;...
```

## Steps to Reproduce
1. Create a basic class with a field
2.Try to compile with js-obfuscator  with no additional options

## Your Environment

* Obfuscator version used: The last one

**Comment by BlackYuzia** [comment]
You sure?
I try obfuscate code:

```js
class Kruzya { // work
 constructor() {this.isGay = true;this.gayLevel = Infinity}
	toString() {return `Kruzya-${this.gayLevel}`}
}

const kruzya = new Kruzya();

console.log(kruzya); // return "Kruzya-Infinity
```
Yep. That true.

```js
class Kruzya {
  isGay = true;
  // Error: ERROR at line 2: Unexpected token (2:8)
  // > ...isGay = true;...
}

const kruzya = new Kruzya();

console.log(kruzya)
```

**Comment by sanex3339** [comment]
This is because of class properties that are currently on `stage 3` of ECMA proposal and does not support by `acorn` and `escodegen`
