### ISSUE TITLE
Use in php file 

### ISSUE THREAD

**Issue by Dazzler1985** [javascript-obfuscator/javascript-obfuscator#897]
i have php files with a part of javascript code in it . within that code there is also a <?php echo if i use obfuscator it does not work.

Is it possible to encrypt it in place thru php ?

**Comment by da411d** [comment]
I had similar problem.
I moved all PHP-code to separate php file, and then replaced js using `str_replace`. 
Also I started to use Webpack, divided code to modules.

Example:
**config.js**
```
module.exports = __$$CONFIG$$__ || {};
```

**someModule.js**
```
const isDev = __$$IS_DEV$$__;
if(!isDev){
  // ...
}
// ...
```

**controller.php**
```
<?php
$content = file_get_contents("path/to/main.js");
$content = str_replace('__$$CONFIG$$__', $configJson, $content);
$content = str_replace('__$$IS_DEV$$__', $isDev ? '!0' : '!1', $content);
// ...
echo $content;
```

**Comment by sanex3339** [comment]
Hi. Javascript obfuscator works only with `js` code so if you want to obfuscate `js` code in you PHP files, you have to make some additional steps to extract your `js` code into separate files, obfuscate these `js` files and move obfuscated code back to the `php` files.

Also, the best thing (in terms of development) is to keep your `js` code separate from your `php` code.
