### ISSUE TITLE
How to use it to vite project?

### ISSUE THREAD

**Issue by allran** [javascript-obfuscator/javascript-obfuscator#898]
Is there have some plugins or any codes to obfuscator vite project code ?

**Comment by sanex3339** [comment]
Seems there no plugin yet.

**Comment by petermekhaeil** [comment]
Vite plugins are an extension of Rollup's plugin interface. Try these:
https://github.com/getkey/rollup-plugin-obfuscator
https://github.com/javascript-obfuscator/rollup-plugin-javascript-obfuscator
