### ISSUE TITLE
Consider using a hash-based domain matching scheme

### ISSUE THREAD

**Issue by TJKoury** [javascript-obfuscator/javascript-obfuscator#901]
Code generated often has decipherable bits of the domains the code is locked to, and if one has the patience it can be substituted for another domain.

Consider running the domain through something like [xxhash](https://github.com/pierrec/js-xxhash).  Of course this will add bulk to the output, but it could be a configurable option.

**Comment by da411d** [comment]
I will not be mistaken if I say that PR is welcomed🙃

**Comment by TJKoury** [comment]
I'll get to it at some point, but the whole TypeScript / IOC framework going on here will take some time to figure out.

**Comment by sanex3339** [comment]
Hi. Try to use `stringArrayEncoding` option. It will add additional encoding over a base domain encoding

**Comment by sanex3339** [comment]
Closed as old
