### ISSUE TITLE
Is there a way to exclude an Unicode Hexadecimal or ASCII Hexadecimal string from obfuscation?

### ISSUE THREAD

**Issue by lorrandavid** [javascript-obfuscator/javascript-obfuscator#903]
Hello,

I am trying to obfuscate a javascript file but I would like to exclude a particular string (a few) from obfuscation.

Here the smallest example of what I would like to achieve:

`// Paste your JavaScript code here
function hi() {
  console.log("\xbb\xf0");
}
hi();`

Outputs:

`... console[_0x518641(0x110)]('»ð');}hi();`

I wish it would mantain those characters as:

`... console[_0x518641(0x110)]('\xbb\xf0');}hi();`

Is it possible? I tried using a few regexes but it doesn't seem to work at all

* Reason being I'm trying to obfuscate an Angular main.js file and there are several strings like that but whenever a obfuscate my file it shows up incorrectly on my browser.

**Comment by BlackYuzia** [comment]
did you try use `reserveStrings` param / option of obfuscator?

**Comment by sanex3339** [comment]
Hi! As said @BlackYuzia you can use `reservedStrings` option with some regexp, for example the regexp that @BlackYuzia mentioned.

Input (`reservedStrings: ['(\\x\w*){1,}']`):
```
console.log("foo");
console.log("\xbb\xf0");
console.log("bar");
```

Output:
```
var a = [
    'log',
    'foo',
    'bar'
];
var b = function (c, d) {
    c = c - (0x1fcb + 0x180b + -0x374d);
    var e = a[c];
    return e;
};
console[b(0x89)](b(0x8a)), console[b(0x89)]('»ð'), console[b(0x89)](b(0x8b));
```

With `unicodeEscapeSequence: true` option the output will be like:
```
var a = [
    '\x6c\x6f\x67',
    '\x66\x6f\x6f',
    '\x62\x61\x72'
];
var b = function (c, d) {
    c = c - (-0x1b03 + -0xae8 + 0x275c);
    var e = a[c];
    return e;
};
console[b(0x171)](b(0x172)), console[b(0x171)]('\u00bb\u00f0'), console[b(0x171)](b(0x173));
```

**Comment by lorrandavid** [comment]
Thanks guys, I decided to just wait for a server migration to update my nginx configuration, I don't think it will be necessary anymore. 

If anyone else needs it I tried it out and it works when I set `unicodeEscapeSequence` to **true**, but it doesn't work when it's **false** for some reason I don't really get it.
