### ISSUE TITLE
what the principle of Self - Defending is?

### ISSUE THREAD

**Issue by supatato** [javascript-obfuscator/javascript-obfuscator#91]
Hi, I look at the source code but I don't know what the principle of Self - Defending is.I want to combine the Dead Code Injection or Control Flow Flattening to make the formatting of his Code go wrong.
                              
    thanks!

**Comment by sanex3339** [comment]
Sorry, but i don't understand your second sentence =(

**Comment by sanex3339** [comment]
Closed due inactivity
