### ISSUE TITLE
Avoid using eval(), setTimeout(), setInterval() or Function()

### ISSUE THREAD

**Issue by bibicron** [javascript-obfuscator/javascript-obfuscator#92]
Thank you for the obfuscator. It is the best free one I could find,

The new Firefox add-ons cannot use eval(), setTimeout(), setInterval() or Function().
If I obfuscate an add-on using https://javascriptobfuscator.herokuapp.com, some of these 4 functions will appear in the code if I enable any of:
- String Array Encoding
- Disable Console Output
- Debug Protection
So in order to pass the review for the add-on, I cannot enable any of these 3 options. In my case I am mostly interested in String Array Encoding(Base64).

Even without these 3 options, this project is useful for me.

**Comment by sanex3339** [comment]
Hmm.

`Function()` is using in the additional helper code which generated when one of options above are enabled. 
This code needed to get global object.

```
            try { 
                var getGlobal = Function('return (function() ' + '{}.constructor("return this")( )' + ');');
                
                that = getGlobal(); 
            } catch (e) { 
                that = window; 
            }
```

In Chrome extensions `eval` and other functions not working too. I avoided it by wrapping code in `try-catch` statement. If code throws error - this is browser environment and global object is `window`.

So i need cross platform way to detect global object.

**Comment by sanex3339** [comment]
I think i should add new option `avoidEvals` and code like this when it enabled.
```
var global = typeof global !== 'undefined' ? 
             global : 
             typeof self !== 'undefined' ? 
               self : 
               typeof window !== 'undefined' ?
               window :
               {};
```

**Comment by bibicron** [comment]
The avoidEvals option would be great.
If I enable all the options on https://javascriptobfuscator.herokuapp.com, I can run fine the obfuscated add-on on my test computer. Probably because of the try-catch. But addons.mozilla.org will not accept to make it public because it sees Function() inside the code.

**Comment by Elite** [comment]
I would also vouch for a `avoidEvals` option which is considered a security nightmare by platforms.

**Comment by sanex3339** [comment]
Start working on it right now

**Comment by sanex3339** [comment]
Base implementation here and i'll very happy if someone test it.
https://github.com/javascript-obfuscator/javascript-obfuscator/commit/2fa1c95f5a828648ea98ebe43d0a9aa6e6212bb2

New option: `target`

Allows to set target environment for obfuscated code.

Available values: 
* `browser`;
* `extension`;
* `node`.

Currently output code for `browser` and `node` targets is identical.
Output code for `extension` target is not using `eval`.

So, for your case - you should set `target: 'extension'`

**Comment by sanex3339** [comment]
Hi. Check new `javascript-obfuscator@0.12.0`!

https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/CHANGELOG.md#v0120
