### ISSUE TITLE
Fails to obfuscate with 'static' keyword

### ISSUE THREAD

**Issue by datdinhquoc** [javascript-obfuscator/javascript-obfuscator#939]
## Expected Behavior
The CLI command and online obfuscator should work well with 'static' keyword in code.

## Current Behavior
ES6 has the new 'static' keyword for static properties of class. Command `javascript-obfuscator` fails with error: 
`Error: RangeError: Maximum call stack size exceeded`

## Steps to Reproduce
1. Create a .js file with an ES6 class inside
2. Add a static property with 'static' keyword
3. Run the obfuscator on the file
4. Error is shown "Error: RangeError: Maximum call stack size exceeded"

## Your Environment
WSL

# Stack trace
No

## Minimal working example that will help to reproduce issue

```
class MyClass {

    // Static properties
    static myProp = {
        name: "foobar"
    };
}
```

**Comment by sanex3339** [comment]
Duplicate of https://github.com/javascript-obfuscator/javascript-obfuscator/issues/909
Wait until this PR will be merged:
https://github.com/javascript-obfuscator/javascript-obfuscator/pull/916
