### ISSUE TITLE
Obfuscated js throws error: "Uncaught SyntaxError: Illegal return statement"

### ISSUE THREAD

**Issue by HerrimanCoder** [javascript-obfuscator/javascript-obfuscator#94]
I am using _javascript-obfuscator 0.10.0-beta.8_, and I have been obfuscating my js from the command line, with good success, for a few months now. But as of the past week or so, many of my resultant obfuscations error out inside my Chrome extension. I haven't touched javascript-obfuscator, haven't updated it, nothing. Also I haven't changed the way I'm calling it from cmd-line, nor changed any params.

Here is the error I have been getting: `Uncaught SyntaxError: Illegal return statement`. And here is the obfuscated block of code that triggers it:

```
if (_0x4423('0x7') === 'mJc') {
     zingLog(_0x4423('0x8'));
} else {
      return !![];
}
```

The `return !![];` seems to be throwing the error. Both Chrome and JSNice point at the same line. When I encountered this 3-4 days ago, I had no idea what to do about it. I ended up re-obfuscating my files 2 or 3 more times, and after that -- PRESTO -- the error was gone. I wish I had taken a diff so I could know what changed. But that was another puzzling thing: how can I get different obfuscated results after changing nothing, no cmd-line params, no source code, etc? It seems as though the obfuscator generates different results each time it runs??

Here is how I'm calling the obfuscator:

`node "C:\javascript-obfuscator.js" "myfile.js" --output "C:\obfuscated.js" --compact true --controlFlowFlattening true --controlFlowFlatteningThreshold 0.75 --deadCodeInjection true --deadCodeInjectionThreshold 0.4 --mangle false --rotateStringArray true --selfDefending true --stringArray true --stringArrayThreshold 0.75 --stringArrayEncoding false --unicodeEscapeSequence false`

That always executes with no errors, and as mentioned, in the past the resulting obfuscations work great, and ran fine in Chrome. I am currently using Chrome Version 61.0.3163.79 (Official Build) (64-bit). That's the latest update as of 9/12/2017, but the previous version I was on (60.xxx - before today) threw the same error.

Is this a bug in the obfuscator? A bug in the browser? Can changing a cmd-line option solve this? My entire obfuscated file is over 1500 lines so it seems ill-advised to post all of it here, but I can if necessary. Please help.

Thanks in advance.

**Comment by sanex3339** [comment]
At first - can you update to 0.11.0 version?

**Comment by HerrimanCoder** [comment]
I apologize, but how do I update from cmd-line? It took me awhile to figure out how to just get it installed and working, but I never updated before.

**Comment by sanex3339** [comment]
Did you install obfuscator globally? If so - `npm i -g javascript-obfuscator`

**Comment by HerrimanCoder** [comment]
I ran that, and it seemed to work. But I can't tell if it really upgraded because:
(1) After re-obfuscating and running my extension in Chrome, I still get the same error.
(2) The version inside .\javascript-obfuscator\package.json is still 0.10.0-beta.8, as before. (How can I determine the installed version?)

**Comment by sanex3339** [comment]
`.\javascript-obfuscator\package.json`

show me full path

**Comment by sanex3339** [comment]
Anyway i reproduced error.

**Comment by sanex3339** [comment]
Fixed in https://github.com/javascript-obfuscator/javascript-obfuscator/commit/d9612d1bf4032bcb868a2a3771aea5de03dbdcb3

Will be out with first `0.12.0` beta release in next few weeks.

**Comment by HerrimanCoder** [comment]
I'm not sure I understand. Am I able to get the fixed files somehow? I clicked the link, but don't know how to get that fix. Thanks! (I can't wait a few weeks because it's fairly urgent.)

**Comment by sanex3339** [comment]
I'll release first beta version of 0.12.0 in next few weeks.

**Comment by sanex3339** [comment]
And i should release 0.11.1 bugfix version on thos week.

**Comment by sanex3339** [comment]
Hi again. Check new `javascript-obfuscator@0.11.1` version with this fix.

**Comment by HerrimanCoder** [comment]
That works great now. Thanks so much!
