### ISSUE TITLE
How to obfuscator without call to global variable from callback function?

### ISSUE THREAD

**Issue by zenlykoi** [javascript-obfuscator/javascript-obfuscator#943]
My english is not good, but i will try to explain my problem.

I want to obfuscator my script (chrome extension). In my script have some callback function does not execute in this context. It will be send to another context to execute (background send a function from string to content and execute it).

When i obfuscator my script in [https://obfuscator.io/](obfuscator.io) with option of **Identifier Names Generator** is _Hexadecimal_ , my script call to a variable in global! 

How can i obfuscator my script with _Hexadecimal_ and without this change in my callback function?

![image](https://user-images.githubusercontent.com/42612129/123502151-2cbbfd00-d674-11eb-922d-fe03e28f6d3c.png)
![image](https://user-images.githubusercontent.com/42612129/123502162-4cebbc00-d674-11eb-9996-2f496052d880.png)

**Comment by sanex3339** [comment]
Hi. As i understood, `executeScript` function runs code in a different context, as BLOB inline WebWorker does?
Try to wrap it into conditional comments (https://github.com/javascript-obfuscator/javascript-obfuscator#conditional-comments):
```
function executeScript(fn) {}

// javascript-obfuscator:disable
executeScript(function () {
    var a = 5;
    console.log(a);
});
// javascript-obfuscator:enable
```

**Comment by zenlykoi** [comment]
> Hi. As i understood, `executeScript` function runs code in a different context, as BLOB inline WebWorker does?
> Try to wrap it into conditional comments (https://github.com/javascript-obfuscator/javascript-obfuscator#conditional-comments):
> 
> ```
> function executeScript(fn) {}
> 
> // javascript-obfuscator:disable
> executeScript(function () {
>     var a = 5;
>     console.log(a);
> });
> // javascript-obfuscator:enable
> ```
