### ISSUE TITLE
Installation error on windows "opencollective postinstall"

### ISSUE THREAD

**Issue by d3v0e** [javascript-obfuscator/javascript-obfuscator#944]
When installing via npm there is an error

```
npm ERR! code 1
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c opencollective postinstall

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2021-06-30T12_42_07_984Z-debug.log
```

## Your Environment
* Obfuscator version used: 2.15.5
* Node version used: v15.14.0

**Comment by d3v0e** [comment]
Log from npm
https://pastebin.com/54RFgmWX

**Comment by sanex3339** [comment]
How did you solve it?

**Comment by d3v0e** [comment]
I uninstalled package.json, and reinstalled all the dependencies. This was the only thing that helped.
