### ISSUE TITLE
Delete original file after obfuscation

### ISSUE THREAD

**Issue by jmechevarria** [javascript-obfuscator/javascript-obfuscator#945]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A new CLI argument to delete original file(s) after obfuscation.

**Describe alternatives you've considered**
None

**Additional context**
None

Thank you

**Comment by sanex3339** [comment]
No. I won't add this feature. This is unsafe. You can easily do this with the custom command after obfuscation
