### ISSUE TITLE
Include/copy over the rest of the files in a folder when obfuscating said folder's JS files

### ISSUE THREAD

**Issue by jmechevarria** [javascript-obfuscator/javascript-obfuscator#946]
**Is your feature request related to a problem? Please describe.**
Trying to obfuscate a folder with many JS and non-JS files.

**Describe the solution you'd like**

Is there or could there be an option (CLI arg) to include the rest of the files in a folder when obfuscating said folder's JS files?

If a have files **src/js/a.js**, **src/js/b.js** and **src/css/a.css**, I'd like to be able to do something like

`javascript-obfuscator src --output src-o --copy-rest`

so I end up with an obfuscated version of my JS files, alongside my non-JS files.

This would be very handy when dealing with lots of files.

**Describe alternatives you've considered**
None

**Additional context**
None

Thank you

**Comment by sanex3339** [comment]
Sorry but no. You can easily do this with a custom command/script after the obfuscation
