### ISSUE TITLE
Anonymous functions and parenthesized

### ISSUE THREAD

**Issue by guowei1003** [javascript-obfuscator/javascript-obfuscator#947]
I try this function：
`const a = (function(){return 1})();`
get:
`const a = function () {
    return 0x1;
}();`
An exception occurs because some editors check that anonymous function execution must be parenthesized.
Error:

> Wrap an immediate function invocation in parens to assist the reader in understanding that the expression is the result of a function, and not the function itself. (W062)

Through the following parser that acron does not recognize the bracketed code in the code.
[https://astexplorer.net/#/gist/f31ddd911a58f8b588a140e8ea11dd88/396eaf8d1b328b05c4fe5dceb78c723c2a6e194e](url)
Use the bebal parser to identify code with parentheses.
[https://lihautan.com/babel-ast-explorer/#?eyJiYWJlbFNldHRpbmdzIjp7InZlcnNpb24iOiI3LjYuMCJ9LCJ0cmVlU2V0dGluZ3MiOnsiaGlkZUVtcHR5Ijp0cnVlLCJoaWRlTG9jYXRpb24iOnRydWUsImhpZGVUeXBlIjp0cnVlLCJoaWRlQ29tbWVudHMiOnRydWV9LCJjb2RlIjoiY29uc3QgYSA9IChmdW5jdGlvbigpe3JldHVybiAxfSkoKTtcblxuY29uc3QgYiA9IGZ1bmN0aW9uKCl7cmV0dXJuIDJ9KCk7In0=](url)

How do I solve it ？

**Comment by sanex3339** [comment]
Don't think that this is a problem. Obfuscated code is not about easy `reading`. And i can't change parser.
