### ISSUE TITLE
A typescipt error was detected during the build.

### ISSUE THREAD

**Issue by arakawayasuaki** [javascript-obfuscator/javascript-obfuscator#964]
I detected the following typescipt error during the build.

\node_modules\javascript-obfuscator\src\utils\Utils.ts(24,53)

      **TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.**

## Expected Behavior

Be able to build

## Current Behavior

An error has occurred.

## Steps to Reproduce

1.　Using webpack-obfuscator in webpack

## Your Environment

* Obfuscator version used:
The version I'm using is as follows

 webpack-obfuscator@3.4.0
  └── javascript-obfuscator@2.18.1

* Node version used:
 node -v
v14.17.0

## Minimal working example that will help to reproduce issue

I have modified the source as follows to avoid the error.

```
public static buildVersionMessage(version?: string, buildTimestamp?: string): string {
        const isUnknownVersion = !version || !buildTimestamp;

        if (isUnknownVersion || buildTimestamp === undefined) {
            return 'unknown';
        }

        const buildDate: string = new Date(parseInt(buildTimestamp, 10)).toISOString();

        return `${version}_${buildDate}`;
    }

```

**Comment by sanex3339** [comment]
Hi. Please update your dependencies. Current `master` version uses `typescript@4.4.0-beta` and compiles it without errors.
