### ISSUE TITLE
How to locate the problem with the error stack?

### ISSUE THREAD

**Issue by kefeibuhuifei** [javascript-obfuscator/javascript-obfuscator#969]
I am using the obfuscated file now, and there is an error, but the reported stack information is after obfuscation, how can I find the location information in my original file? I found that have sourceMap, how can I achieve my needs, how can I use it, I read the document, but I am still very confused, can you give an example? Thank you very much！！

**Comment by sanex3339** [comment]
Hi. As a start point describe how you're using obfuscator (CLI, node js API, webpack plugin)

**Comment by kefeibuhuifei** [comment]
i use javascript-obfuscator source.js --output out.js --config obfuscator.json，And then out.js use on my website. but i use window.onerror accept the error message，but the reported stack information is after obfuscation how can I find the location information in my original file?

**Comment by sanex3339** [comment]
Using a source map on production anyone can get the original source code from this source map. 
So basically, you just may add `--source-map true --source-map-mode separate` and the file with the source map will be generated. But as I mentioned before when you will serve this source map file, keep it unreachable (with help of server configuration) for all external users.

**Comment by kefeibuhuifei** [comment]
Maybe this is not what I want. I want to capture the user’s error message (using the onerror function to listen for Javascript errors), so I can’t restrict external users. Then I want to use this error message to know what is wrong with my code, but The current error message is after confusion

**Comment by sanex3339** [comment]
There are ways to map the error stack trace using the source map to its original positions, on NodeJS side, for example. But this is a different topic not related to obfuscator.

**Comment by sanex3339** [comment]
I will close this issue. If you have other questions feel free to create a new issue.

**Comment by kefeibuhuifei** [comment]
ok thanks!!!to find
