### ISSUE TITLE
Desobfuscate

### ISSUE THREAD

**Issue by oracle63** [javascript-obfuscator/javascript-obfuscator#97]
Hi everybody !

I would like to know how to desobfuscate Javascript password with this API. Thanks. Moreover, can we use js-obfuscator without node.js ?

**Comment by sanex3339** [comment]
Hi! You can use obfuscator without node on this service https://javascriptobfuscator.herokuapp.com/

You cannot deobfuscate things with `javascript-obfuscator`

**Comment by sanex3339** [comment]
Closed due inactivity
