### ISSUE TITLE
Object initializer with computed property names does not work

### ISSUE THREAD

**Issue by oogFranz** [javascript-obfuscator/javascript-obfuscator#98]
Hi, everyone.
I found that this obfuscator breaks the following code.
 
in.js: 
```JS
const key = 'bar';
const obj = {
    [key]: 1
};
console.log(obj);
```

```
$ node in.js
{ bar: 1 }
$
$ javascript-obfuscator in.js --output out.js
$ node out.js
{ key: 1 }
```

Could you fix it?

ref. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015

**Comment by sanex3339** [comment]
Will be fixed in 0.11.2 later today

**Comment by sanex3339** [comment]
Fixed in `javascript-obfuscator@0.11.2`

**Comment by oogFranz** [comment]
@sanex3339 
Great! Thank you very much! :octocat:

**Comment by sanex3339** [comment]
Ok, i'll close issue.
