### ISSUE TITLE
Output List of All Renamed Public Properties In A File

### ISSUE THREAD

**Issue by nkosi23** [javascript-obfuscator/javascript-obfuscator#989]
**Is your feature request related to a problem? Please describe.**
We do not people to be aware of certain features of our application, so keeping public properties and methods intact shares too much information.  

The problem is when using a data binding library such as KnockoutJS defining bindings to public properties in data-bind attributes of HTML files,  it is not possible to rename public properties and methods in javascript without breaking the application (since the HTML file still has the old name).

**Describe the solution you'd like**
It would be great if obfuscator.io could output an intermediate file containing a mapping of all the properties it has renamed. That way we would be able to add a simple "Find and Replace" step to the build process of our applications, and benefit from very robust confidentiality. 

**Describe alternatives you've considered**
Can't think of a suitable alternative.

**Comment by nkosi23** [comment]
Okay, so it looks like what I am after is the identifierNamesCache option and it is already there. For some reason I didn't see it before posting (despite scratching my head on this for quite some time).

**Comment by da411d** [comment]
So maybe close the issue?
