### ISSUE TITLE
Apply different ciphers to string literal encryption.

### ISSUE THREAD

**Issue by leogatesx9r** [javascript-obfuscator/javascript-obfuscator#99]
A great update would be support for difference ciphers rather than the weak RC4 algorithm currently implemented. Such ciphers may be aes, camellia, tripledes, seed, idea etc. 
I'd also suggest caching decrypted strings -- possibly in Base64 for faster retrieval -- to avoid lagging the program.

At the very least, you really should implement this:
https://github.com/ricmoo/aes-js

Great job thus far btw. This truly is an amazing tool!

**Comment by sanex3339** [comment]
Main goal of string encoding - you need automatization to decode it. All strings will replaced on call to decode function with two parameters - decoded string and key.

Rc4 cipher very good for this task. Key length can be any size, so i use 3 or 4 chars keys.
I'll lok at aes cipher, if decode function faster than rc4 and it supports keys 3-4 chars length - i'll add it

**Comment by sanex3339** [comment]
Right now i don't see any reason to add more complex encoding, but i'll look at encoding with keys of any length with more faster decoding algorithm than in `rc4`.

**Comment by sanex3339** [comment]
closes
