### ISSUE TITLE
Can't make the EXCLUDE parameter works

### ISSUE THREAD

**Issue by fernandocfbf** [javascript-obfuscator/javascript-obfuscator#998]
I'm trying to obfuscate my code, but I want to exclude some folder inside the src from the obfuscation. But I tried different nomenclatures on the exclude parameters and I can still see all my files being obfuscated.

I tried all the following:
`
"./src/someFolder"
"src/someFolder"
"**/src/someFolder/**"
"**/src/someFolder/**/**"
`

No-one  worked, could someone help me here? 
Thank you in advance!!

**Comment by da411d** [comment]
Try take a look on [obfuscator-loader](https://github.com/javascript-obfuscator/obfuscator-loader)

**Comment by sanex3339** [comment]
For the plugin, `exclude` parameter accepts the name of the bundle. If you want to exclude by a path, use `obfuscator-loader` as @da411d suggested

**Comment by fernandocfbf** [comment]
I would like to make it work by using glob strings, but I can't do it at all.
I just want to obfuscate one file called api.js (src/services/api.js). I tried using:

/**/!(api).js
**/!(api).*

But it didn't worked. Could someone help me here?

**Comment by christian-demel-horsch** [comment]
Has someone an answer, how to get the exclude parameter to work in an cli?

**Comment by nhanpdnguyen** [comment]
Finally figured this out, the glob pattern for excluding a folder should be: `someFolder/**/*`

However this will miss the case where the directory or file name starts with "." character. See [wiki](https://en.wikipedia.org/wiki/Glob_(programming))
> Traditionally, globs do not match hidden files in the form of Unix [dotfiles](https://en.wikipedia.org/wiki/Dotfiles); to match them the pattern must explicitly start with .. For example, * matches all visible files while .* matches all hidden files.

So eventually, we'll need to configure our glob pattern to:
```
someFolder/{.**,**}/{.*,*}
```
which will be expaned to `someFolder/.**/.*` `someFolder/.**/*` `someFolder/**/.*` `someFolder/**/*`
